#+TITLE: 如何使用 @lisp
#+AUTHOR: VitalGG

* 安装
  下载 (@).fas 或 @lisp.zelx 后，把这个文件拖入CAD绘图区，等待下载必需文件，和安装完成即可。

  安装完成后会出现 @lisp(A) 菜单。

* @lisp 基本命令和菜单
  @lisp 基本功能菜单都在 @lisp -> 配置 菜单下。
  以下 标题中 | 前面是在命令行输入的命令 ， | 后面是菜单项。
** @ | 重新加载
   重新加载 @lisp , 如果 @lisp 不完整，多次运行可自行修补完整 。
** @@ 
   显示 *@lisp* 命令面板。面板功能按钮与菜单是一一对应的，操作更快捷一点。
** @H | 关于@lisp
   显示CAD命令及用法。

** @P | 应用管理
   图形界面的应用包管理器，用于管理 '应用包'的安装、加载、卸载。

   当 *勾选* 了某个或某些应用后，@lisp 系统会在加载 *@lisp* 时，同时加载这些应用。

   如果本地没有这个应用的副本， *@lisp* 会从网站下载一个副本到你的硬盘。 

   如果本地的副本版本较低， *@lisp* 会从网站下载一个新版本的副本到你的硬盘，也就是升级。

** @I 
   命令行方式安装应用包。输入 @I 并回车或空格，然后输入应用包名(英文名).就可以完成这个应用包的安装。

** @S | 配置管理
   设置系统变量的值。

** @L
   在命令行显示已安装的应用包列表。

** @M | 重建菜单
   重新生成菜单。如果 @lisp 菜单与现有的环境不匹配，可运行此命令。

** @R
   remove,命令行工具 移除应用包。在应用管理器中，取消 ‘勾选’ 后的功能相同。

** @U | 升级系统
   update，手动更新 @lisp 系统及已安装的包。
** @W
   www，访问 @lisp 网站。查询 @lisp 新动态及新增应用包。

** 菜单 @lisp主目录

   打开本地@lisp的主目录，所有@lisp应用都存放在这个目录下。

** 菜单 自毁@lisp
   删除@lisp主文件和菜单文件。再次打开CAD后，就不加载@lisp了。

   @lisp目录一其它文件可保留，以便于以后再次安装时使用原来的配置。

   如果不需要，可以手动删除@lisp目录及以下的所有文件。




