#+prefix: FAQ
* 修复单色显示,单色显示修复
点击CAD菜单 文件/页面设置管理器，打开页面设置管理器后，点击修改，去掉显示打印样式前的 对勾 即可。

* 如何使用自带的编译器
对于autocad 2021 及以后的版本，默认 vscode 作为 visual lisp 编辑器及调试器。
如果想使用旧的 vlide ， 可以将变量 lispsys 设为 0。然后重启 CAD ,即可。
* not found visualisp env
有些精简版的CAD或CAD LT版本，删除了 visuallisp环境。这些版本不支持@lisp的安装和运行。

如果想要使用 @lisp，请安装支持vl的CAD版本。
* 乱码,汉字乱码
对于低于2021版本或 lispsys=0的 CAD， 记事本中 保存时 改为 GB2312 或 ANSI 编码。

2021版本以上的，可以用vscode编辑lsp源码，源码可采用 utf8 编码。

建议 lispsys 设为 2，这样编译的fas文件可以用在低版本的CAD中。
* 双击不能编辑文字
1 两个变量会影响双击文字的编辑。
  - =DBLCLKEDIT=
  - =pickfirst=
2 鼠标双击反应器影响。执行下面的代码查看有没有 :VLR-beginDoubleClick字样。
#+begin_src lisp
(foreach reaction (vlr-reactors)(princ (vlr-reactions  (cadr reaction))))
#+end_src

* 移除双击反应器
#+begin_src lisp
  (foreach
   reactor (vlr-reactors)
   (if (and (eq :vlr-mouse-reactor(car reactor))
            (assoc :VLR-beginDoubleClick (vlr-reactions (cadr reactor))))
       (vlr-remove (cadr reactor))))
#+end_src
* 改变CAD背景色,CAD底色怎么将黑色变更白色
命令 op，或菜单工具-选项，打开选项对话框。
点击 ‘显示’ 栏，然后点击颜色。
上下文：二维模型空间，界面元素：统一背景。颜色选白色或你希望的颜色。
最后点确定。

* 未知命令Txx_xxx
当不是以 天正平台选择 方式启动CAD时，如双击dwg,或双击autocad的图标打开的CAD应用程序，CAD的当前配置是天正时。
可能会出现天正的侧边栏菜单，但是天正的相关文件没有加载。

正确的方式是先用桌面上的天正图标打开CAD，然后再打开dwg文件。

* 双击dwg不在当前CAD打开,双击dwg打开新的CAD
DWG文件的打开方式应该设为AutoCAD DWG Launcher。
这样双击dwg时会在最后打开的CAD应用程序窗口打开。
如果dwg的打开方式是acad.exe 之类的，双击dwg会打开新的CAD应用程序。
