* MAXACTVP
设置布局中可同时激活的视口的最大数目。
* qaflags
是个未公布的变量，用来控制LISP中使用EXPLODE炸开一个选择集的时候的表现。
如果QAFLAGS＝0，那么用LISP执行(command ""explode"" ss """")的时候仅仅能炸开选择集的第一个实体，其他实体炸不了.如果QAFLAGS＝1，可以炸开选择集所有实体。"
* *_TOOLPALETTEPATH
控制用于“工具选项板”窗口的路径。
* _PKSER
返回产品序列号。
* _VERNUM
返回产品的内部版本号。
* 3DCONVERSIONMODE
用于将材质和光源定义转换为当前产品版本。
* 3DDWFPREC
控制三维 DWF 或三维 DWFx 发布的精度
* 3DOSMODE
设置执行三维对象捕捉。
* 3DSELECTIONMODE
控制使用三维视觉样式时视觉上和实际上重叠的对象的选择优先级。
* ACADLSPASDOC
控制是将 acad.lsp 文件加载到每个图形中，还是仅加载到任务中打开的第一个图形中。
类型:	整数
保存位置:	注册表
初始值:	0

值 说明
0 仅将 acad.lsp 加载到任务中打开的第一个图形中
1 将 acad.lsp 加载到每一个打开的图形中
* ACADPREFIX
列出“文件”选项卡的“选项”对话框中指定的“支持文件搜索”路径。
（只读）
类型:	字符串
保存位置:	未保存
初始值:	不确定
将“支持文件搜索”路径存储在 ACAD 操作系统环境变量中。除“选项”对话框之外，您还可以使用 AutoLISP 函数、getenv 和 setenv 来访问这些搜索路径。例如，通过 AutoLISP 例程或命令提示，您可以使用 (getenv "ACAD") 列出“支持文件搜索”路径。
* ACADVER
返回产品的版本号。
（只读）
类型:	字符串
保存位置:	未保存
初始值:	不确定
此变量与 DXF 文件表头变量 $ACADVER 不同，$ACADVER 包含图形数据库的级别号。

值 | 说明
24.1s (LMS Tech) | AutoCAD 2022
24.0s (LMS Tech) | AutoCAD 2021
23.1s (LMS Tech) | AutoCAD 2020
23.0s (LMS Tech) | AutoCAD 2019
22.0s (LMS Tech) | AutoCAD 2018
21.0s (LMS Tech) | AutoCAD 2017
20.1s (LMS Tech) | AutoCAD 2016
20.0s (LMS Tech) | AutoCAD 2015
19.1s (LMS Tech) | AutoCAD 2014
19.0s (LMS Tech) | AutoCAD 2013
18.2s (LMS Tech) | AutoCAD 2012
18.1s (LMS Tech) | AutoCAD 2011
18.0s (LMS Tech) | AutoCAD 2010
17.2s (LMS Tech) | AutoCAD 2009
17.1s (LMS Tech) | AutoCAD 2008
17.0s (LMS Tech) | AutoCAD 2007
16.2s (LMS Tech) | AutoCAD 2006
16.1s (LMS Tech) | AutoCAD 2005
16.0 | AutoCAD 2004
15.06 | AutoCAD 2002
15.05 | AutoCAD 2000i
15.0 | AutoCAD 2000
14.0 | AutoCAD R14
* ACTPATH
指定可从其中加载用于回放的动作宏的其他路径。
类型:	字符串
保存位置:	注册表
初始值:	""
通过使用分号分隔可以指定多个路径。
* ACTRECORDERSTATE
指定动作录制器的当前状态。
（只读）
类型:	整数
保存位置:	未保存
初始值:	0
值 | 说明
0 | 动作录制器处于空闲状态
1 | 动作录制器处于活动状态；当前正在录制动作宏
2 | 动作录制器处于活动状态；当前正在回放动作宏

* ACTRECPATH
指定用于存储新动作宏的路径。
类型:	字符串
保存位置:	注册表
初始值:	不确定
* ACTUI
控制录制和回放宏时“动作录制器”面板的行为。
类型:	位码
保存位置:	注册表
初始值:	6
值 | 说明
0 | 录制或回放动作宏时，“动作录制器”面板不会发生变化
1 | 回放期间会展开“动作录制器”面板
2 | 录制期间会展开“动作录制器”面板
4 | 录制完成后，提示输入动作宏的名称和说明
* ADCSTATE
指示“设计中心”窗口处于打开还是关闭状态。
（只读）
类型:	整数
保存位置:	未保存
初始值:	不确定
用于需要通过 AutoLISP 来确定状态的开发人员。

值 | 说明
0 | 关闭
1 | 打开

* AFLAGS
设置属性选项。
类型:	整数
保存位置:	未保存
初始值:	16
该值是下列位码值之和：

值 | 说明
0 | 无选定的属性模式
1 | 不可见
2 | 固定
4 | 验证
8 | 预设
16 | 锁定块中的位置
32 | 多行
* ANGBASE
将相对于当前 UCS 的基准角设定为 0（零）。
类型:	实数
保存位置:	图形
初始值:	0.0000
* ANGDIR
设置正角度的方向。
类型:	整数
保存位置:	图形
初始值:	0
从相对于当前 UCS 方向的 0 角度测量角度值。

值 | 说明
0 | 逆时针
1 | 顺时针
* ANNOALLVISIBLE
隐藏或显示不支持当前注释比例的注释性对象
类型:	整数
保存位置:	图形
初始值:	1
值| 说明
0 | 仅显示支持当前注释比例的注释性对象
1 | 显示所有注释性对象
* ANNOAUTOSCALE
更改注释比例时，将更新注释性对象以支持注释比例。

类型:	整数
保存位置:	注册表
初始值:	-4
该值为负时，将关闭自动缩放功能，但仍保留设置：

值 | 说明
0 | 新设置的注释比例未添加到注释性对象。
1 | 将新设置的注释比例添加到支持当前比例（关闭、冻结、锁定或设定为“视口”>“冻结”图层上的比例除外）的注释性对象。
2 | 将新设置的注释比例添加到支持当前比例（关闭、冻结或设定为“视口”>“冻结”图层上的比例除外）的注释性对象。
3 | 将新设置的注释比例添加到支持当前比例的注释性对象（已锁定图层上的注释性对象除外）。
4 | 将新设置的注释比例添加到支持当前比例的所有注释性对象。
* ANNOMONITOR
打开或关闭注释监视器。当注释监视器打开时，所有非关联标注和引线上会显示黄色警告标记。
类型:	整数
保存位置:	图形
初始值:	-2
值 | 说明
0 | 注释监视器处于关闭状态。
1, -1 | 注释监视器处于打开状态 (1) 和关闭状态 (-1)。状态栏按钮 (+ ) 在 1 和 -1 之间切换。
2, -2 | 也会打开 (2) 或关闭 (-2) 注释监视器，但有一个重要例外。如果设置为 -2，则任何“模型文档”编辑和更新事件会自动将设置更改为 2。状态栏按钮 (+) 在 2 和 -2 之间切换。
* ANNOTATIVEDWG
指定图形插入其他图形是否表现为注释性块。
类型:	整数
保存位置:	图形
初始值:	0
值 | 说明
0 | 非注释性
1 | 注释性

注意: 如果图形包含注释性对象，则 ANNOTATIVEDWG 系统变量将成为只读系统变量。
* APBOX
打开或关闭自动捕捉靶框的显示。
类型:	整数
保存位置:	注册表
初始值:	0
当捕捉对象时，靶框显示在十字光标的中心。

值 | 说明
0 | 关闭
1 | 打开
* 变量APERTURE
控制对象目标框的大小。
类型:	整数
保存位置:	注册表
初始值:	10
该系统变量的名称与命令相同。使用 SETVAR 命令可访问此系统变量。

输入一个值 (1-50)。数值越高，靶框越大。

也可以在“选项”对话框的“草图”选项卡上更改此设置。

APERTURE 控制对象捕捉靶框，而不是“选择对象”提示下显示的拾取框。对象选择拾取框还受 PICKBOX 系统变量控制。
* APPAUTOLOAD
控制何时加载插件应用程序。
类型:	位码
保存位置:	用户设置
初始值:	14
值 | 说明
0 | 在任何时间都不加载插件应用程序
1 | 加载插件应用程序时显示所有消息
2 | 启动时加载插件应用程序
4 | 打开新图形时加载插件应用程序
8 | 插件应用程序出现在插件文件夹时加载插件应用程序

* APPLYGLOBALOPACITIES
将透明度设置应用到所有选项板。

类型:	整数
保存位置:	注册表
初始值:	0
值 | 说明
0 | 透明度设置关闭
1 | 透明度设置打开
* APSTATE
指示块编辑器中的“块编写选项板”窗口处于打开还是关闭状态。
（只读）
类型:	整数
保存位置:	未保存
初始值:	0
值 | 说明
0 | 关闭
1 | 打开
* 变量AREA
存储由 AREA 命令计算出的上一个面积。
（只读）
类型:	实数
保存位置:	未保存
初始值:	0.0000
该系统变量的名称与命令相同。要启动此系统变量，请使用以下方法之一：

在基于 AutoCAD 的产品中：使用 SETVAR 命令。
在 AutoCAD LT 中：使用 GETVAR 命令。
* ARRAYASSOCIATIVITY
设置要成为关联或非关联的新阵列的默认行为。
类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 非关联
1 | 关联

关联阵列被视为单个阵列对象，当您希望修改间距、角度或替换或修改源对象时，这将很有用。

如果阵列是非关联的，每个复制的项目都将被视为一个单独的对象。编辑一个项目不会影响其他项目。
* ARRAYEDITSTATE
指示图形是否处于阵列编辑状态，该状态在编辑关联阵列的源对象时激活。
（只读）
类型:	参数
保存位置:	未保存
初始值:	0
值 | 说明
0 | 关闭
1 | 打开
* ARRAYTYPE
指定默认的阵列类型。

类型:	整数
保存位置:	注册表
初始值:	0
值 | 说明
0 | 矩形阵列
1 | 路径阵列
2 | 环形阵列
* ATTDIA
控制 INSERT 命令是否使用对话框来输入属性值。

类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 发出命令提示
1 | 使用对话框
* ATTIPE
控制修改多行属性时随在位编辑器一起显示的文字格式工具栏。
类型:	整数
保存位置:	注册表
初始值:	0

值 | 说明
0 | 使用在位编辑器显示缩写的文字格式工具栏
1 | 使用在位编辑器显示全写的文字格式工具栏

当修改多行属性以与 2008 之前的产品版本实现最佳兼容时，使用在位编辑器显示缩写的文字格式工具栏。
* ATTMODE
控制属性的显示。

类型:	整数
保存位置:	图形
初始值:	1
值 | 说明
0 | 关闭：使所有属性都不可见
1 | 常规：保持每个属性的当前可见性；显示可见属性，不显示不可见属性
2 | 打开：使所有属性都可见
* ATTMULTI
控制是否可创建多行文字属性。
类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 关闭创建多行文字属性的所有访问方法。仍然可对其进行查看和编辑。
1 | 打开创建多行文字属性的所有访问方法。
* ATTREQ
在插入块过程中控制 INSERT 是否使用默认属性设置。

类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 所有属性均采用各自的默认值
1 | 按照 ATTDIA 系统变量选择的设置，打开命令提示或使用对话框获取属性值

* AUDITCTL
控制 AUDIT 命令是否创建核查报告 (ADT) 文件。

类型:	整数
保存位置:	注册表
初始值:	0
值 | 说明
0 | 禁止写 ADT 文件
1 | 写 ADT 文件
* AUNITS
设定角度单位。
类型:	整数
保存位置:	图形
初始值:	0
值 | 说明
0 | 十进制度数
1 | 度/分/秒
2 | 百分度
3 | 弧度
4 | 勘测单位
* AUPREC
设定角度单位和坐标的显示精度。

类型:	整数
保存位置:	图形
初始值:	0

但是，无论显示精度如何设置，始终保留角度值和坐标的内部精度。AUPREC 并不影响标注文字的显示精度（请参见 DIMSTYLE）。
有效值为 0 到 8 之间的整数。
* AUTODWFPUBLISH
控制保存或关闭图形(DWG) 文件时是否自动创建 DWF（Web 图形格式）文件。
类型:	整数
保存位置:	注册表
初始值:	0
值 | 说明
0 | 关闭当保存或关闭图形时自动发布为 DWF 文件
1 | 打开当保存或关闭图形时自动发布为 DWF 文件

AUTOPUBLISH 命令用于控制其他选项。
注意:此系统变量可能会在将来的版本中删除。

* AUTOMATICPUB
控制保存或关闭图形(DWG) 文件时是否自动创建电子文件 (DWF/PDF)。

类型:	整数
保存位置:	用户设置
初始值:	0
值 | 说明
0 | 关闭当保存或关闭图形时自动发布为 DWF/PDF 文件
1 | 打开当保存或关闭图形时自动发布为 DWF/PDF 文件

AUTOPUBLISH 命令用于控制其他选项。
* AUTOSNAP
控制自动捕捉标记、工具提示和磁吸的显示。
类型:	整数
保存位置:	注册表
初始值:	63
也可以打开极轴追踪和对象捕捉追踪，并控制极轴追踪、对象捕捉追踪和正交模式工具提示的显示。系统将使用下列位码值之和将该设置存储为一个位码：

值 | 说明
0 | 关闭自动捕捉标记、工具提示和磁吸。同时，关闭极轴追踪、对象捕捉追踪以及极轴追踪、对象捕捉追踪和正交模式的工具提示
1 | 打开自动捕捉标记
2 | 打开自动捕捉工具提示
4 | 打开自动捕捉磁吸
8 | 打开极轴追踪
16 | 打开对象捕捉追踪
32 | 打开极轴追踪、对象捕捉追踪和正交模式的工具提示
* BACKGROUNDPLOT
控制为打印和发布打开还是关闭后台打印。
类型:	整数
保存位置:	注册表
初始值:	2
默认情况下，关闭后台打印，打开后台发布。

值 | PLOT | PUBLISH
0 | 前景 | 前景
1 | 背景 | 前景
2 | 前景 | 背景
3 | 背景 | 背景

如果脚本（SCR 文件）中使用了 -PLOT、PLOT、-PUBLISH 和 PUBLISH，则 BACKGROUNDPLOT 系统变量的值将被忽略，并将在前景中处理 -PLOT、PLOT、-PUBLISH 和 PUBLISH。
* BACKZ
以图形单位存储当前视口后向剪裁平面到目标平面的偏移值。

（只读）
类型:	实数
保存位置:	图形
初始值:	0.0000
仅当在 CAMERA、DVIEW 或 3DCLIP 中指定剪裁时才有意义。如果存在若干相机，则该值为用户置为当前的最后一个后向剪裁平面。后向剪裁平面到相机点之间的距离可以通过相机到目标的距离减去 BACKZ 的值得到。
* BACTIONBARMODE
指示块编辑器中是否显示动作栏或传统动作对象。

类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 块编辑器中将显示传统动作对象
1 | 块编辑器中将显示动作栏

注意:BACTIONBARMODE 系统变量设定为 1 时，将禁用 BACTIONSET、BASSOCIATE 和 BLOOKUPTABLE 命令。
* BACTIONCOLOR
设置块编辑器中动作的文字颜色。

类型:	字符串
保存位置:	注册表
初始值:	7
有效值包括“BYLAYER”、“BYBLOCK”以及 1 到 255 之间的整数。

真彩色的有效值是一个前面带有 RGB 的整数字符串，每个整数（1 到 255）之间用逗号分隔。真彩色设置的输入如下：

RGB:000,000,000
* BCONSTATUSMODE
打开或关闭约束显示状态，基于约束级别控制对象着色。

类型:	整数
保存位置:	未保存
初始值:	0

显示状态为打开时，将根据对象是局部受约束、完全受约束、受过度约束还是不受约束来对其进行着色。

值 | 说明
0 | 关闭约束显示状态
1 | 打开约束显示状态

可以在“块编辑器设置”对话框中修改与约束状态相对应的颜色。进入块编辑器时，值始终设定为 0。

* BDEPENDENCYHIGHLIGHT
控制在块编辑器中选定参数、动作或夹点时是否亮显相应依赖对象。
类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 指定不亮显依赖对象
1 | 指定亮显依赖对象

依赖亮显显示带有光晕效果的对象。
* BGCOREPUBLISH
控制后台发布是使用单核还是多核。

类型:	整数
保存位置:	注册表
初始值:	1

默认情况下，后台发布会利用处理器的多个核心来提高输出到以下内容的性能：

- 单页 DWF/DWFx 或 PDF 文件
- 多页 PDF 文件（如果发布选项“包含超链接”处于未选中状态）
- 这允许并行并同时输出多个图纸。

注意:BACKGROUNDPLOT 系统变量必须设置为值 2 或 3，才能利用多个单核。
值 | 说明
0 | 关闭 - 单核用于后台发布；基于 AutoCAD 2021 的产品及更早版本的行为
1 | 打开 - 多个核心用于后台发布

此设置不会提高以下操作的性能：
- 后台发布到硬拷贝设备或多页 DWF/DWFx 文件
- 前台发布
- 后台或前台打印
* BGRIPOBJCOLOR
设置块编辑器中夹点的颜色。
类型:	字符串
保存位置:	注册表
初始值:	141
有效值包括“BYLAYER”、“BYBLOCK”以及 1 到 255 之间的整数。

真彩色的有效值是一个前面带有 RGB 的整数字符串，每个整数（1 到 255）之间用逗号分隔。真彩色设置的输入如下：

RGB:000,000,000
* BGRIPOBJSIZE
设置块编辑器中相对于屏幕显示的自定义夹点的显示尺寸。

类型:	整数
保存位置:	注册表
初始值:	8
有效值为 1 到 255 之间的整数。
* BINDTYPE
控制对外部参照执行绑定操作或在位编辑操作后，如何将名称指定给该外部参照中的“命名对象”。
类型:	整数
保存位置:	未保存
初始值:	0
命名对象包括图层、标注和文字样式、块、视图等。

例如，假设将图形文件命名为“Floorplan”，其中包含一个名为“Electrical”的图层。如果该图形作为外部参照附着到当前图形中，则该图层名称将显示为“drawingname | layername”，或在本例中，为“Floorplan|Electrical”。 此命名样式旨在避免与当前图形中的现有图层名称发生冲突。

当 BINDTYPE 设置为 0（零）时（标准行为），如果对外部参照执行了绑定操作，则图层名称将变为“drawingname$0$layername”，或在本例中为“Floorplan$0$Electrical”。如果由于之前的绑定操作，图层“Floorplan$0$Electrical”已经存在，新的图层名称将为“Floorplan$1$Electrical”等等。

当 BINDTYPE 设置为 1 时（合并行为），如果对外部参照执行了绑定操作，则图层名称将保持原样，在本例中为“Electrical”。这会将外部参照中的图层与当前图形中的图层合并，这类似于拆离和插入参照图形。

值 | 说明
0 | 标准行为
1 | 合并行为

以下是命令及其如何受此系统变量影响：

-REFEDIT - 控制参照中的图层和其他命名对象是否具有唯一名称。这相当于“参照编辑”对话框（REFEDIT 命令）“设置”选项卡上的“创建唯一图层、样式和块名”选项。
-XREF - 控制使用“绑定”选项时要使用的绑定类型。这相当于“绑定外部参照/DGN 参考底图”对话框（EXTERNALREFERNCES 和 XREF 命令）中的“绑定”和“插入”选项。
EXTERNALREFERENCES 或 XREF - 指定要在“绑定外部参照/DGN 参考底图”对话框中使用的默认绑定类型，该对话框通过从“外部参照”选项板上的上下文菜单中选择“绑定”显示。
注意:XBIND 和 REFEDIT 命令不受此系统变量影响。

* BLOCKCREATEMODE
在使用 BLOCK 和 -BLOCK 命令创建块后，设置选定对象的行为。对象将被删除、保留或替换为块的实例。

类型:	整数
保存位置:	用户设置
初始值:	0
值 | 说明
0 | 在使用 BLOCK 或 -BLOCK 命令创建块后，将选定对象转换为图形中的块实例。
1 | 在使用 BLOCK 或 -BLOCK 命令创建块后，将选定对象保留为图形中的不同对象。
2 | 在使用 BLOCK 或 -BLOCK 命令创建块后，从图形中删除选定对象。
* BLOCKEDITLOCK
禁止打开块编辑器以及编辑动态块定义。
类型:	整数
保存位置:	注册表
初始值:	0
BLOCKEDITLOCK 设定为 1 时，双击图形中的动态块可以打开“特性”选项板。如果动态块包含属性，则双击块参照将打开增强属性编辑器。双击可以使用“创建双击动作”自定义的动作。

值 | 说明
0 | 指定可以打开块编辑器
1 | 指定不可以打开块编辑器

* BLOCKEDITOR
指示块编辑器是否处于打开状态。
（只读）
类型:	整数
保存位置:	未保存
初始值:	0
值 | 说明
0 | 指示块编辑器未打开
1 | 指示块编辑器已打开
* BLOCKMRULIST
控制在“块”选项板的“最近使用”选项卡中显示的最近使用块的数量。

类型:	整数
保存位置:	注册表
初始值:	50
有效值为 0 到 100 之间的整数。

提示将此系统变量设置为 0，可清除“最近使用”选项卡中显示的块。
* BLOCKNAVIGATE
控制在“块”选项板的“其他图形”选项卡中显示的文件和块。

类型:	字符串
保存位置:	注册表
初始值:	无
有效值为：文件夹路径；包括现有文件的路径、文件名和扩展名的完整文件名；或“.”表示“无”。如果设置为“无”，则将保留上次使用的文件或文件夹，并在下一次选项板打开时在会话中保持不变。
* BLOCKREDEFINEMODE
控制在从“块”选项板插入名称与现有块定义相同的块时是否显示对话框。

类型:	整数
保存位置:	注册表
初始值:	1
当尝试插入名称相同的其他块时，将显示一个对话框或一个命令行提示，以便可以选择将现有块重新定义为要插入的块。

值	说明
0	始终使用现有块定义，而不是要插入的新块定义
1	显示一个对话框，可以重新定义现有块定义
2	显示命令行提示，以允许用户重新定义现有块定义
* BLOCKSRECENTFOLDER
设置存储最近插入或创建的块的路径。

类型:	字符串
保存位置:	注册表
初始值:	不确定
登录到您的 Autodesk 帐户，并在 BLOCKSRECENTFOLDER 系统变量中指定云存储位置，以从任何设备访问最近使用的块和块库。
* BLOCKSTATE
报告“块”选项板处于打开状态还是关闭状态。
（只读）
类型:	整数
保存位置:	未保存
初始值:	0
值 | 说明
0 | 关闭
1 | 打开
* BLOCKTESTWINDOW
指示某个测试块窗口是否为当前窗口。
（只读）
类型:	整数
保存位置:	未保存
初始值:	0
BLOCKTESTWINDOW 系统变量可控制测试块窗口为当前窗口时出现的上下文面板的显示。测试块窗口为当前窗口时，此系统变量设定为 1，否则设定为 0。
* BPARAMETERCOLOR
设置块编辑器中参数的颜色。

类型:	字符串
保存位置:	注册表
初始值:	170
有效值包括“BYLAYER”、“BYBLOCK”以及 1 到 255 之间的整数。

真彩色的有效值是一个前面带有 RGB 的整数字符串，每个整数（1 到 255）之间用逗号分隔。真彩色设置的输入如下：

RGB:000,000,000
* BPARAMETERFONT
设置块编辑器中的参数和动作所用的字体。

类型:	字符串
保存位置:	注册表
初始值:	Simplex.shx
可以指定 True Type 字体或 SHX 字体（例如，Verdana 或 Verdana.ttf）。必须添加 .shx 扩展名以指定 AutoCAD SHX 字体。

指定亚洲大字体时，使用以下命名惯例：SHX 文件后跟随一个逗号 (,)，再跟随一个大字体文件名（例如，Simplex.shx,Bigfont.shx）。
* BPARAMETERSIZE
设置块编辑器中相对于屏幕显示的参数文字和部件的显示尺寸。

类型:	整数
保存位置:	注册表
初始值:	12
有效值为一个 1 到 255 之间的整数。
* BPTEXTHORIZONTAL
强制使块编辑器中为动作参数和约束参数显示的文字以水平方式显示。

类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 将文字与参数的尺寸线对齐
1 |在块编辑器中水平显示动作参数和约束参数的文字

BPTEXTHORIZONTAL 系统变量适用于动作参数和块约束参数。
* BTMARKDISPLAY
控制是否为动态块参照显示数值集标记。
类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 指定不显示数值集标记
1 | 指定显示数值集标记

* BVMODE
控制当前可见性状态下可见的对象在块编辑器中的显示方式。
类型:	整数
保存位置:	未保存
初始值:	0

值 | 说明
0 | 指定隐藏对象不可见
1 | 指定隐藏对象可见但暗显

* CACHEMAXFILES
设置为产品保存的图形缓存文件的最大数量。

类型:	整数
保存位置:	注册表
初始值:	256
有效范围为从 0 到 65535 个文件。

达到上限时，将自动删除图形缓存中最旧的文件条目。将此变量设置为 0（零）可完全禁用缓存，并删除任何当前不在打开的图形文件中使用的图形缓存文件夹中的文件。

注意:图形缓存中图形文件条目数的当前上限为 32,767。在将来的版本中，上限可能会增加。

* CACHEMAXTOTALSIZE
设置为产品保存的所有图形缓存文件的总大小的最大值。
类型:	整数
保存位置:	注册表
初始值:	1024
有效范围为从 0 到 65535 MB。

达到上限时，将自动删除图形缓存中最旧的文件条目。将此变量设置为 0（零）可完全禁用缓存，并删除任何当前不在打开的图形文件中使用的图形缓存文件夹中的文件。

注意:当前图形缓存大小的上限为 32,767 兆字节。在将来的版本中，上限可能会增加。
* CALCINPUT
控制是否计算文字中以及窗口和对话框的数字输入框中的数学表达式和全局常量。

类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 不计算表达式
1 | 按 Alt+Enter 组合键后计算表达式

* CAMERADISPLAY
打开或关闭相机对象的显示。

类型:	整数
保存位置:	图形
初始值:	0
使用 CAMERA 命令时，值将更改为 1（可显示相机）。

值 | 说明
0 | 不显示相机轮廓
1 | 显示相机轮廓
* CAMERAHEIGHT
为新相机对象指定默认高度。
类型:	实数
保存位置:	图形
初始值:	0.0000
高度以当前图形单位表示。
* CANNOSCALE
为当前空间设置当前注释比例的名称。
类型:	字符串
保存位置:	图形
初始值:	1:1
仅可输入图形的命名比例列表中存在的命名比例。
* CANNOSCALEVALUE
显示当前注释比例的值。
（只读）
类型:	实数
保存位置:	图形
初始值:	1.0000
* CAPTURETHUMBNAILS
指定是否及何时为回放工具捕捉缩略图。
类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 如果视图更改发生在 SteeringWheels 之外，则不会生成预览缩略图
1 | 将括号置于空框上方时，根据需要为回放工具生成预览缩略图
2 | 每次更改视图后，均自动生成预览缩略图
* CBARTRANSPARENCY
控制约束栏的透明度。
类型:	整数
保存位置:	注册表
初始值:	50
CBARTRANSPARENCY 系统变量的有效值从 10 到 90。值越大，约束栏越不透明。
* CCONSTRAINTFORM
控制是将注释性约束还是将动态约束应用于对象。

类型:	整数
保存位置:	注册表
初始值:	0
值 | 说明
0 | 动态
1 | 注释性

如果将此系统变量设置为 0（零），使用 DIMCONSTRAINT 命令时会默认创建动态约束。

* CDATE
以编码的小数格式存储当前的日期和时间。
（只读）
类型:	实数
保存位置:	未保存
初始值:	不确定
日期和时间以小数格式显示（以年、月和日开头）。在小数点后，CDATE 使用 24 小时制显示时间。例如，2006 年 2 月 9 日下午 3:05 显示为 20060209.15050000。

注意:从基于 AutoCAD 2017 的产品开始，CDATE 系统变量中存储的当前系统日期和时间将精确到当前秒；但在以前的版本中，当前系统时间还包括毫秒。如果要使用 CDATE 系统变量来追踪开始时间和结束时间之间的变化，请注意除非经过一秒，否则将看不到时间变化，即使已经过 0 至 999 毫秒也是如此。在需要计算小于一秒的时间差时，请考虑使用 MILLISECS 系统变量返回的值。

* CECOLOR
在创建新对象时设置它们的颜色。

类型:	字符串
保存位置:	图形
初始值:	BYLAYER
有效值包括：

BYLAYER 或 BYBLOCK
AutoCAD 颜色索引 (ACI)：介于 1 和 255 之间的整数值，或前七种颜色中的一种颜色名称
真彩色：介于 000 和 255 之间的 RGB 或 HSL 值，格式为“RGB:130,200,240”
配色系统：标准 PANTONE 或自定义配色系统、DIC 颜色手册或 RAL 颜色集中的文字，例如“DIC COLOR GUIDE(R)$DIC 43”
注意:图形中的对象可以具有不同的颜色特性，并且可以随时更改对象的颜色。
* CELTSCALE
设置当前对象的线型比例缩放因子。

类型:	实数
保存位置:	图形
初始值:	1.0000
相对于 LTSCALE 命令设置为新对象设置线型比例。在 CELTSCALE = 2 的图形中绘制的直线，如果将 LTSCALE 设置为 0.5，其效果与在 CELTSCALE = 1 的图形中绘制的直线 LTSCALE = 1 时的效果相同。
* CELTYPE
设置新对象的线型。
类型:	字符串
保存位置:	图形
初始值:	BYLAYER
* CELWEIGHT
设置新对象的线宽。
类型:	整数
保存位置:	图形
初始值:	-1
值 | 说明
-1 | 将线宽设定为“BYLAYER”。
-2 | 将线宽设定为“BYBLOCK”。
-3 | 将线宽设定为“DEFAULT”。“DEFAULT”由 LWDEFAULT 系统变量控制。

其他以百分之一毫米为单位输入的有效值包括 0、5、9、13、15、18、20、25、30、35、40、50、53、60、70、80、90、100、106、120、140、158、200 和 211。

所有的值都必须以毫米的百分之一为单位输入。（乘上 2540 可以将值的单位从英寸转换为毫米的百分之一。）

* CENTERCROSSGAP
确定中心标记与其中心线之前的间隙。
类型:	字符串
保存位置:	图形
初始值:	“0.05x”
CENTERCROSSGAP 系统变量仅适用于使用 CENTERMARK 命令创建的中心标记。中心标记的默认相对大小和间隙分别为 0.1x 和 0.05x。

注意:CENTERCROSSSIZE 和 CENTERCROSSGAP 系统变量设置彼此相关。建议这两个系统变量都使用相同的值类型（绝对值、相对值或 ByLineType）。
如果圆的半径小于中心标记大小与间距之和的一半，将忽略 CENTERCROSSGAP 系统变量设置。可以通过为 CENTERCROSSSIZE 和 CENTERCROSSGAP 系统变量指定相对值来避免出现该问题。

值 | 说明
绝对值（任何正实数） | 使用单位指定中心标记的线段与其中心线之间的距离。

相对值（指定为比例因子的任何正实数）| 指定圆或圆弧的直径相对值。输入后跟 x 的正实数。例如，0.1x 表示圆直径的 1/10。

“ByLineType” | 中心标记与其中心线之间的间距源自指定给它的线型。注意:当中心标记的线型仅具有划线和间隙时，最后一个划线的尺寸和图案间隙可用作中心标记的尺寸和间隙。如果中心标记的线型图案具有其他类型的元素，则使用默认设置。
* CENTERCROSSSIZE
确定关联中心标记的尺寸。
类型:	字符串
保存位置:	图形
初始值:	“0.1x”
CENTERCROSSSIZE 系统变量仅适用于使用 CENTERMARK 命令创建的中心标记。中心标记的默认相对大小和间隙分别为 0.1x 和 0.05x。

注意:CENTERCROSSSIZE 和 CENTERCROSSGAP 系统变量设置彼此相关。建议这两个系统变量都使用相同的值类型（绝对值、相对值或 ByLineType）。
值 | 明
绝对值（任何正实数） | 使用单位指定中心标记的线段长度。
相对值（指定为比例因子的任何正实数） | 指定圆或圆弧的直径相对值。输入后跟 x 的正实数。例如，0.1x 表示圆直径的 1/10。
“ByLineType” | 中心标记的尺寸源自指定给它的线型。注意:当中心标记的线型仅具有划线和间隙时，最后一个划线的尺寸和图案间隙可用作中心标记的尺寸和间隙。如果中心标记的线型图案具有其他类型的元素，则使用默认设置。
* CENTEREXE
控制中心线延伸的长度。
类型:	实数
保存位置:	图形
初始值:	0.1200（英制）或 3.5000（公制）
CENTEREXE 系统变量仅适用于使用 CENTERMARK 命令和 CENTERLINE 命令创建的中心线延伸的长度。此系统变量仅接受正实数。

* CENTERLAYER
为新中心标记或中心线指定默认图层。
类型:	字符串
保存位置:	图形
初始值:	“使用当前值”
CENTERLAYER 系统变量仅适用于使用 CENTERMARK 和 CENTERLINE 命令创建的中心标记和中心线。

除“.”以外的值（使用当前）值替代当前图层值（CLAYER 系统变量）。
* CENTERLTSCALE
设置中心标记和中心线所使用的线型比例。

类型:	实数
保存位置:	图形
初始值:	1.0000
CENTERLTSCALE 系统变量仅适用于使用 CENTERMARK 命令和 CENTERLINE 命令创建的中心标记和中心线。此系统变量接受除零以外的任何实数。
* CENTERLTYPE
指定中心标记和中心线所使用的线型。

类型:	字符串
保存位置:	图形
初始值:	“CENTER2”
CENTERLTYPE 系统变量仅适用于在使用 CENTERMARK 和 CENTERLINE 命令创建的中心标记和中心线上使用的线型。此系统变量接受以下值：“.”（使用当前值）、ByLayer 或任何有效线型。
* CENTERLTYPEFILE
指定用于创建中心标记和中心线的已加载的线型库文件。

类型:	字符串
保存位置:	图形
初始值:	“acad.lin”
CENTERLTYPEFILE 系统变量仅适用于使用 CENTERMARK 命令和 CENTERLINE 命令创建的中心标记和中心线。此系统变量决定 CENTERMARK 命令和 CENTERLINE 命令所使用的 CENTERLTYPE 设置的 .lin 文件。
* CENTERMARKEXE
确定中心线是否会自动从新的中心标记延伸。

类型:	参数
保存位置:	图形
初始值:	1
CENTERMARKEXE 系统变量仅适用于使用 CENTERMARK 命令创建的中心标记。

值 | 说明
0 | 隐藏从中心标记延伸的中心线
1 | 显示从中心标记延伸的中心线

* CENTERMT
控制通过夹点拉伸多行水平居中的文字的方式。

类型:	整数
保存位置:	注册表
初始值:	0
CENTERMT 不能应用于通过使用在位文字编辑器中的标尺来拉伸多行文字。

值 | 说明
0 | 在居中的多行文字中移动角点夹点时，中心夹点在同方向上移动，而对边上的夹点保持在原位置
1 | 在居中的多行文字中移动角点夹点时，中心夹点保持在原位置，而两边的夹点在拉伸的方向上移动

* CETRANSPARENCY
设定新对象的透明度级别。

类型:	整数
保存位置:	图形
初始值:	-1
值 | 说明
-1（ByLayer） | 由图层确定的透明度值
-2（ByBlock） | 由块确定的透明度值
0 | 完全不透明（不透明）
1-90 | 定义为百分比的透明度值
 
若要更改现有对象的透明度，请使用“特性”选项板或“图层特性管理器”。

注意:将透明度值限制为 90%，以避免与关闭或冻结的图层混淆。
新图案填充对象的透明度级别由 HPTRANSPARENCY 系统变量控制。
* CGEOCS
存储指定给图形文件的 GIS 坐标系的名称。
类型:	字符串
保存位置:	图形
初始值:	无
* CHAMFERA
当 CHAMMODE 设定为 0 时设置第一个倒角距离。
类型:	实数
保存位置:	图形
初始值:	0.0000
* CHAMFERB
当 CHAMMODE 设定为 0 时设置第二个倒角距离。
类型:	实数
保存位置:	图形
初始值:	0.0000
* CHAMFERC
当 CHAMMODE 设定为 1 时设置倒角长度。
类型:	实数
保存位置:	图形
初始值:	0.0000
* CHAMFERD
当 CHAMMODE 设定为 1 时设置倒角角度。
类型:	实数
保存位置:	图形
初始值:	0.0000
* CHAMMODE
设置 CHAMFER 的输入方法。

类型:	整数
保存位置:	未保存
初始值:	0
值 | 说明
0 | 需要两个倒角距离
1 | 需要一个倒角长度和一个角度

* CIRCLERAD
设置默认的圆半径。

类型:	实数
保存位置:	未保存
初始值:	0.0000
零表示无默认半径。
* CLAYER
设置当前图层。

类型:	字符串
保存位置:	图形
初始值:	0
* CLAYOUT
设置当前布局。

类型:	字符串
保存位置:	图形
初始值:	不确定
CLAYOUT 的值由两部分组成：布局名称和句柄。例如

输入 CLAYOUT 的新值 <"Model*22">:

在此案例中，Model 是布局的名称，22 是句柄（* 是分隔符）。您可以通过输入 Model 或 *22 切换到此选项卡。将显示此句柄，以为开发人员提供方便。

注意:在内部，AutoCAD 将“模型”选项卡视为特殊的布局选项卡。
* CLEANSCREENSTATE
指示全屏显示状态是处于打开还是处于关闭状态。
（只读）
类型:	整数
保存位置:	未保存
初始值:	0
值 | 说明
0 | 关闭
1 | 打开
* CLIPROMPTLINES
当浮动命令窗口设置为仅显示提示行时，设置将显示的临时提示行的数量。
类型:	整数
保存位置:	注册表
初始值:	3
默认情况下，命令窗口显示单个提示行。当命令正在运行时，在命令窗口上方会显示临时提示历史记录。输入 0 到 50 之间的值，以指定在单个命令的提示历史记录中显示的最大行数。
* CLIPROMPTUPDATE
控制命令行是否显示在执行 AutoLISP 或脚本文件时生成的消息和提示。
类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 命令或 AutoLISP 例程运行时，命令行不显示消息。
1 | 命令行显示命令或 AutoLISP 例程的进度。
* CLISTATE
指示命令行处于打开还是关闭状态。
（只读）
类型:	整数
保存位置:	未保存
初始值:	1
值 | 说明
0 | 关闭
1 | 打开
* CLOUDCOLLABMODIFIEDOPTION
控制文档（DWG 和 DWT 文件）在 AutoCAD 中关闭后何时在 BIM 360 中解锁。

类型:	整数
保存位置:	注册表
初始值:	0
文档在关闭后不会立即解锁。对文档进行编辑、保存并关闭文档后，在所做更改全部上传到 BIM 360 后，图形将会解锁。这样一来，在最新更改上传完毕之前，其他用户将无法打开文档。

在您关闭文档后，Autodesk Desktop Connector 的“待定操作”窗口中将会显示“解锁文件”操作，即使未对文档进行任何更改也是如此。

在大多数情况下，文档在关闭后会立即解锁（文档有未保存的更改时除外），这样可以提供更好的性能。当文档在关闭后立即解锁时，Autodesk Desktop Connector 的“待定操作”窗口中不会显示“解锁文件”操作。

重要信息:当 CLOUDCOLLABMODIFIEDOPTION 系统变量设置为 1 时，经过编辑和保存的文档在关闭后会立即解锁。根据保存图形后关闭文档的时间，在所做更改全部上传到 BIM 360 之前，图形可能会在 BIM 360 中解锁。要确保所做更改上传完毕之前文档在 BIM 360 中一直保持锁定状态，可以将 CLOUDCOLLABMODIFIEDOPTION 系统变量的值更改为 0。
注意:更改此系统变量的值后，必须重新启动 AutoCAD。
* CMATERIAL
设置新对象的材质。

类型:	字符串
保存位置:	图形
初始值:	BYLAYER
有效值为“BYLAYER”、“BYBLOCK”和图形中材质的名称。
* CMDACTIVE
指示处于激活状态的是普通命令、透明命令、脚本还是对话框。
（只读）
类型:	整数
保存位置:	未保存
初始值:	不确定
系统将使用下列位码值之和将该设置存储为一个位码：

值 | 说明
0 | 不激活任何命令
1 | 激活普通命令
2 | 激活透明命令
4 | 激活脚本
8 | 激活对话框
16 | 激活动态数据交换 (DDE)
32 | 激活 AutoLISP（仅对 ObjectARX 定义的命令可见）
64 | 激活 ObjectARX 命令
* CMDDIA
控制执行 DIMEDIT 和 QLEADER 命令时在位文字编辑器的显示，以及基于 AutoCAD 的产品中的某些对话框的显示。
控制执行 DIMEDIT 和 QLEADER 命令时在位文字编辑器的显示，以及基于 AutoCAD 的产品中的某些对话框的显示。

类型:	整数
保存位置:	注册表
初始值:	1
在脚本中，某些命令会自动隐藏某些对话框或在位文字编辑器。在其他情况下，将 CMDDIA 设置为 0（零），或者在命令的命令行版本（以短划线开头）可用时使用它。

值 | 说明
0	禁止显示在位文字编辑器和某些对话框。
1	显示在位文字编辑器和某些对话框。
注意: FILEDIA 系统变量控制文件对话框的显示，例如 SAVEAS 和 OPEN。

下列 AutoCAD 命令的对话框以 CMDDIA 为准。

DBCDEFINELT
DBCDEFINELLT
DBCDELETEELT
DBCDELETEELLT
DBCDELETEQRY
DBCDISCONNECT
DBCEDITQRY
DBCEDITTABLE
DBCEXECUTEQRY
DBCEXPORTLINKS
DBCNEWQRYTABLE
DBCONFIGURE
DBCRELOADLABELS
DBCVIEWLINKEDTABLE
DBCVIEWTABLE
LAYOUTMERGE (Express Tool)
LEADER
PLOT
REDIR (Express Tool)
SOLIDEDIT
SYSVARMONITOR
TCASE (Express Tool)
TEXT
XATTACH
-XREF
此外，某些特定于基于 AutoCAD 的产品的命令也以 CMDDIA 为准。
* CMDECHO
控制在 AutoLISP 命令函数运行时是否回显提示和输入。

类型:	整数
保存位置:	未保存
初始值:	1
值 | 说明
0 | 关闭回显
1 | 打开回显
* CMDINPUTHISTORYMAX
设定存储在命令提示中的先前输入值的最大数量。
类型:	整数
保存位置:	注册表
初始值:	20
用户输入值历史记录的显示由 INPUTHISTORYMODE 系统变量所控制。
* CMDNAMES
显示活动命令和透明命令的名称。
（只读）
类型:	字符串
保存位置:	未保存
初始值:	""
例如，LINE'ZOOM 表示 ZOOM 命令将在执行 LINE 命令期间被透明使用。

此变量用于编程接口，例如 AutoLISP 和 ActiveX Automation（在 AutoCAD LT 中不可用）以及 DIESEL。

下例演示了如何使用 DIESEL 在状态行中显示当前命令。

命令：modemacro

输入 MODEMACRO 的新值，或输入 . 表示无值 <"">: $(getvar, cmdnames)
* CMFADECOLOR
控制所有附着的协调模型上混合的黑色量。

类型:	整数
保存位置:	注册表
初始值:	60
有效值从 0 到 90。

值 | 说明
0 | 协调模型不与黑色混合。
>0 | 控制混合百分比，最高为 90%。

结合使用 CMFADECOLOR 与 CMFADEOPACITY 以使更其易于区分图形几何图形和附着的协调模型。

* CMFADEOPACITY
通过透明度控制所有附着的协调模型的暗显程度。

类型:	整数
保存位置:	注册表
初始值:	40
有效值从 0 到 90。

值 | 说明
0 | 协调模型不会暗显。
>0 | 控制暗显百分比，最高为 90%。

结合使用 CMFADEOPACITY 和 CMFADECOLOR，以使更其易于区分图形几何图形和附着的协调模型。

* CMLEADERSTYLE
设置当前多重引线样式的名称。
类型:	字符串
保存位置:	图形
初始值:	标准
* CMLJUST
指定多行对正。
类型:	整数
保存位置:	图形
初始值:	0
值 | 说明
0 | 上
1 | 零（中）
2 | 下
* CMLSCALE
控制多行的全局宽度。
类型:	实数
保存位置:	图形
初始值:	1.0000（英制）或 20.0000（公制）
如果比例因子为 2.0，多线宽度将是样式定义宽度的两倍。比例因子为 0 将把多线重叠到单一直线。比例因子为负将颠倒偏移直线的次序，即当多线从左向右绘制时，最小（即绝对值最大）的负值被放置在顶部。

* CMLSTYLE
设置用于控制多行外观的多行样式。

类型:	字符串
保存位置:	图形
初始值:	标准
* CMOSNAP
决定是否为附着至图形的协调模型中的几何图形激活对象捕捉。

类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 为附着至图形的所有协调模型中的几何图形禁用对象捕捉。
1 | 为附着至图形的所有协调模型中的几何图形启用对象捕捉。
* COLORTHEME
将功能区、选项板和若干其他界面元素的颜色主题设置为深色或浅色。

类型:	整数
保存位置:	注册表
初始值:	0
值 | 说明
0	显示深色主题。
1	显示浅色主题。
* COMMANDPREVIEW
控制是否显示命令的可能结果的预览。
类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0	关闭
1	打开
预览主要影响更改对象部分的命令，例如 TRIM、EXTEND、BREAK 和 LENGTHEN。它还会影响 ERASE。

注意:如果 COMMANDPREVIEW 处于打开状态，将忽略 SELECTIONPREVIEW 系统变量的值。
* COMPARECOLOR1
设置比较图形文件中仅在第一个图形中存在的对象的颜色。
类型:	整数
保存位置:	注册表
初始值:	82
有效值包括：

AutoCAD 颜色索引 (ACI)：介于 1 和 255 之间的整数值，或前七种颜色中的一种颜色名称
真彩色：介于 000 到 255 之间的 RGB 或 HSL 值，格式为“RGB:41,165,0”
配色系统：标准 PANTONE 或自定义配色系统、DIC 颜色手册或 RAL 颜色集中的文字
* COMPARECOLOR2
设置比较结果图形文件中仅在第二个图形中存在的对象的颜色。
类型:	整数
保存位置:	注册表
初始值:	1
有效值包括：

AutoCAD 颜色索引 (ACI)：介于 1 和 255 之间的整数值，或前七种颜色中的一种颜色名称
真彩色：介于 000 到 255 之间的 RGB 或 HSL 值，格式为“RGB:255,0,0”
配色系统：标准 PANTONE 或自定义配色系统、DIC 颜色手册或 RAL 颜色集中的文字
* COMPARECOLORCOMMON
设置进行比较的两个图形中相同对象的颜色。

类型:	整数
保存位置:	注册表
初始值:	253
* COMPAREFRONT
控制比较图形中重叠对象的默认显示次序。

类型:	整数
保存位置:	图形
初始值:	1
值 | 描述
1 | 将第一个图形中新的或更改的对象设置在第二个图形中新的或更改的对象的前方
2 | 将第二个图形中新的或更改的对象设置在第一个图形中新的或更改的对象的前方

* COMPAREHATCH
控制是否在图形比较中包含图案填充对象。

类型:	整数
保存位置:	图形
初始值:	0
值 | 说明
0 | 从图形比较中排除图案填充对象
1 | 在图形比较中包含图案填充对象

* COMPAREPROPS
控制是否将对象特性中的更改标识为两个图形版本之间的更改。

类型:	位码
保存位置:	注册表
初始值:	0
根据系统变量的值，相应的对象特性更改都包含在图形比较中，如下表中所述：

值 | 说明
0 | 对象特性更改未包含在图形比较中
1 | 颜色
2 | 图层
4 | 线型
8 | 线型比例
16 | 线宽
32 | 透明度
64 | 厚度

要指定想要在比较中包含的多个特性，请输入各值之和。
* COMPARERCMARGIN
指定比较图形中更改集边界与矩形/多边形修订云线之间的偏移距离。
类型:	整数
保存位置:	图形
初始值:	5
请输入有效值（1 至 25）。边距值越高，包含差异的边界越大，从而导致出现更大的修订云线。

* COMPARERCSHAPE
控制比较图形中单个差异是否合并为单个较大更改集或一系列较小更改集。

类型:	整数
保存位置:	图形
初始值:	0
值 | 说明
0 | 使用一个矩形修订云线标记差异
1 | 使用几个较小的矩形修订云线标记差异

* COMPARESHOW1
显示仅在第一个图形中存在的对象。
类型:	整数
保存位置:	图形
初始值:	1
值 | 说明
0 | 不显示第一个图形中的对象
1 | 显示第一个图形中的对象
* COMPARESHOW2
显示仅在第二个图形中存在的对象。
类型:	整数
保存位置:	图形
初始值:	1
值 | 说明
0 | 不显示第二个图形中的对象
1 | 显示第二个图形中的对象
* COMPARESHOWCOMMON
显示进行比较的两个图形中相同的对象。

类型:	整数
保存位置:	图形
初始值:	1
值 | 说明
0 | 在比较图形中不显示正在比较的两个图形中的相同对象
1 | 在比较图形中显示正在比较的两个图形中的相同对象

* COMPARESHOWRC
控制比较图形中差异（更改集）周围修订云线的显示。

类型:	整数
保存位置:	图形
初始值:	1
值 | 说明
0 | 修订云线显示已关闭。
1 | 修订云线显示已打开。

* COMPARETEXT
控制是否在图形比较中包含文字对象。
类型:	整数
保存位置:	图形
初始值:	1
值 | 说明
0 | 从图形比较中排除文字对象
1 | 在图形比较中包含文字对象

* COMPARETOLERANCE
指定比较两个图形文件/对象时所使用的公差 - 如果它们低于或等于指定的小数点值，则认为它们是相同的。

类型:	整数
保存位置:	图形
初始值:	6
有效值为 0 到 14。
* COMPASS
控制三维指南针在当前视口中打开还是关闭。
类型:	整数
保存位置:	未保存
初始值:	0
值 | 说明
0 | 关闭三维指南针
1 | 打开三维指南针
* COMPLEXLTPREVIEW
控制是否在交互式操作期间显示复杂线型的预览。

类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 关闭
1 | 打开
* CONSTRAINTBARDISPLAY
为随后应用的几何约束控制约束栏的显示并为选定的对象控制隐藏约束的显示。
类型:	位码
保存位置:	注册表
初始值:	3
系统将使用下列位码值之和将该设置存储为一个位码：

值 | 说明
0 | 在应用几何约束之后将自动隐藏约束栏。注意: 当 CONSTRAINTBAR = Showall 时，即使将 CONSTRAINTBARDISPLAY 系统变量的值设定为 0，也将始终显示约束栏。
1 | 当几何约束对象时，将显示约束栏。
2 | 几何约束和标注约束都可显示任何隐藏的约束，但仅在选定受约束的对象之后。

* CONSTRAINTBARMODE
控制约束栏上几何约束的显示。
类型:	位码
保存位置:	注册表
初始值:	4095
值 | 说明
1 |  水平
2 |  垂直
4 | 垂足
8 | 平行
16 | 切点
32 | 平滑
64 | 重合
128 | 同心
256 | 共线
512 | 对称
1024 | 相等
2048 | 修复

例如，将 CONSTRAINTBARMODE 设定为 12 (8+4) 可在约束栏上显示平行约束和垂直约束。

将 CONSTRAINTBARMODE 设为 4095 可为所有约束类型显示约束栏。
* CONSTRAINTINFER
控制在绘制和编辑几何图形时是否推断几何约束。
类型:	整数
保存位置:	注册表
初始值:	0
值 | 说明
0 | 关闭
1 | 推断几何约束
* CONSTRAINTNAMEFORMAT
控制标注约束的文字格式。
类型:	整数
保存位置:	注册表
初始值:	2
值 | 说明
0 | 名称（例如宽度）
1 | 值（例如 4.0000）
2 | 表达式（例如 宽度 = 4.0000）

注意:CONSTRAINTNAMEFORMAT 系统变量同样适用于块编辑器中的块约束参数（BCPARAMETER命令）。（在 AutoCAD LT 中不可用。）
* CONSTRAINTSOLVEMODE
控制应用或编辑约束时的约束行为。
类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 应用或修改约束时不保持几何图形的大小
1 | 应用或修改约束时保持几何图形的大小

注意:CONSTRAINTSOLVEMODE 设定为 0 时，调整约束几何图形的大小可能会产生不可预测的结果。

* COORDS
控制状态栏上的光标位置是连续进行更新还是仅在特定时间更新。它也控制坐标的显示格式。

类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 显示绝对坐标；坐标显示仅在指定指定某个点后更新。
1 | 显示绝对坐标；坐标显示将实时持续更新。
2 | 当命令处于活动状态并指定点、距离或角度时，显示相对极坐标；坐标显示将实时持续更新。当命令未处于活动状态时，显示绝对坐标值。注意:Z 值始终为绝对坐标。
3 | 显示地理（纬度和经度）坐标；坐标显示将实时持续更新。坐标格式受 GEOLATLONGFORMAT 系统变量控制。注意:当图形文件包含地理位置信息时，不显示 Z 值。

注意:默认情况下，“坐标显示”不显示在状态栏上。若要在状态栏中显示坐标，请单击状态栏中最右端的“自定义”(  查找) 按钮，然后选择“坐标”。
* COPYMODE
控制是否自动重复 COPY 命令。
类型:	整数
保存位置:	注册表
初始值:	0
值 | 说明
0 | 设置自动重复的 COPY 命令
1 | 设置创建单个副本的 COPY 命令
* COUNTCHECK
控制要检入计数的错误类型。
类型:	位码
保存位置:	注册表
初始值:	2
系统将使用下列位码值之和将该设置存储为一个位码：

值	说明
1	检查彼此重叠的重复对象
2	检查彼此重叠、重命名或分解块的重复对象

* COUNTCOLOR
设置计数中对象的亮显颜色。

类型:	整数
保存位置:	注册表
初始值:	3
有效值为从 1 到 255（AutoCAD 颜色索引 (ACI) 颜色）。

注意:当前视口设置为三维视觉样式时，COUNTCOLOR 不起作用。
* COUNTERRORCOLOR
对在计数中可能造成潜在错误的对象设置亮显颜色。

类型:	整数
保存位置:	注册表
初始值:	1
有效值为从 1 到 255（AutoCAD 颜色索引 (ACI) 颜色）。

注意:当前视口设置为三维视觉样式时，COUNTERRORCOLOR 不起作用。
* COUNTERRORNUM
显示当前计数中的错误数量。
（只读）
类型:	整数
保存位置:	未保存
初始值:	0
* COUNTNUMBER
显示当前计数的数量。
（只读）
类型:	整数
保存位置:	未保存
初始值:	0
* COUNTPALETTESTATE
报告“计数”选项板处于打开状态还是关闭状态。
（只读）
类型:	参数
保存位置:	未保存
初始值:	不确定
值	说明
关	关闭
开	打开

* COUNTSERVICE
控制计数的后台索引。

* CPLOTSTYLE
控制新对象的当前打印样式。
类型:	整数
保存位置:	注册表
初始值:	1
值	说明
0	后台索引关闭。
1	后台索引打开。

* CPROFILE
显示当前配置的名称。
（只读）
类型:	字符串
保存位置:	注册表
初始值:	<<未命名配置>>
* CROSSINGAREACOLOR
控制窗交选择时选择区域的颜色。

类型:	整数
保存位置:	注册表
初始值:	100
有效取值范围为 1 到 255。SELECTIONAREA 系统变量必须设置为开。
* CTAB
确定绘图区域显示“模型”选项卡还是指定的布局选项卡。
类型:	字符串
保存位置:	图形
初始值:	模型
CTAB 通常用于自定义程序。
* CTABLESTYLE
设置当前表格样式的名称。
类型:	字符串
保存位置:	图形
初始值:	标准
* CULLINGOBJ
控制是否可以亮显或选择从视图中隐藏的三维子对象。
类型:	整数
保存位置:	注册表
初始值:	1
无子对象剔除
将鼠标悬停于三维对象上时，会亮显所有三维子对象（包括隐藏的子对象）。
通过拖动选择三维对象会选择所有三维子对象（包括隐藏的子对象）。

应用子对象剔除

将鼠标悬停于三维对象上时，仅会亮显在当前视图中垂直的子对象。
通过拖动选择三维对象将仅选择在当前视图中垂直的子对象。
* CULLINGOBJSELECTION
控制是否可以亮显或选择从视图中隐藏的三维对象。
类型:	整数
保存位置:	注册表
初始值:	0
无对象剔除
将鼠标悬停于三维对象上时，会亮显所有三维对象（包括隐藏的对象）。
通过拖动选择三维对象会选择所有三维对象（包括隐藏的对象）。
应用对象剔除
将鼠标悬停于三维对象上时，仅会亮显在当前视图中垂直的对象。
通过拖动选择三维对象将仅选择在当前视图中垂直的对象。
* CURSORBADGE
确定某些光标标记是否显示在绘图区域中。

类型:	整数
保存位置:	注册表
初始值:	2
值 | 说明
1 | 禁用以下命令中使用的光标标记：AREA、COPY、DIST、ERASE、ID、LIST、MASSPROP、MEASUREGEOM、MOVE、ROTATE、SCALE、TRIM 和 ZOOM。
2 | 启用所有光标标记。
* CURSORSIZE
按屏幕大小的百分比确定十字光标的大小。

类型:	整数
保存位置:	注册表
初始值:	5
有效设置的范围为 1% 到 100% 。当设定为 100% 时，十字光标为全屏显示且看不到十字光标的末端。当设置值小于 100% 时，光标移到屏幕边缘时，可以看到十字光标的末端。
* CURSORTYPE
确定定点设备显示的光标。

类型:	参数
保存位置:	注册表
初始值:	0
值 | 说明
0 | AutoCAD 十字光标
1 | Microsoft Windows® 鼠标指针

注意:建议您保持此系统变量的默认值以获得最佳体验。

* CVIEWDETAILSTYLE
设置当前局部视图样式的名称。当前局部视图样式控制所创建的所有新模型文档局部视图、详图边界和引线的外观。

类型:	字符串
保存位置:	图形
初始值:	Imperial24（英制）或 Metric50（公制）
* CVIEWSECTIONSTYLE
设置当前截面视图样式的名称。当前截面视图样式控制所创建的所有新模型文档截面视图和剖切线的外观。
类型:	字符串
保存位置:	图形
初始值:	Imperial24（英制）或 Metric50（公制）
* CVPORT
显示当前视口的标识码。
类型:	整数
保存位置:	图形
初始值:	2
可以更改本系统变量的值从而更改当前视口，但必须满足下列条件：

指定的标识码是一个活动视口的标识码。
执行中的命令没有锁定光标以阻止它移向此视口。
数字化仪模式为关闭。
* DATALINKNOTIFY
控制关于已更新数据链接或缺少数据链接的通知。

类型:	整数
保存位置:	注册表
初始值:	2
值 | 说明
0 | 禁用数据链接更新通知。
1 | 启用数据链接通知。通过在应用程序窗口的右下角（状态栏托盘的通知区域）显示数据链接图标，通知用户外部数据已链接至当前图形。将不显示气泡式消息通知。
2 | 启用数据链接通知和气泡式消息通知。通知用户外部数据已链接至当前图形（如以上 1 中所述）。同时在数据链接需要更新的图形区域中显示数据链接文件更改通知。
* DATE
以约简儒略日期格式存储当前的日期和时间。
（只读）
类型:	实数
保存位置:	未保存
初始值:	不确定
“修改的 Julian 日期”(MJD) 格式为 Julian 天数后跟一天的小数部分：

<Julian day number>.<Decimal fraction of a day>
“修改的 Julian 日期”（通常称为 UT1）是一个全世界的科学性标准，用以指定自公元前 4713 年 1 月 1 日 12:00 a.m. (B.C.E.) 起的天数。按照此系统，1997 年 7 月 4 日 2:29:58 p.m. 表示为 2450634.60387736，而 1998 年 1 月 1 日正午 12:00 则相应地表示为 2450815.50000000。

因为系统时钟会提供当前日期和时间，所以仅当系统时钟被设定为 UTC/Zulu（格林尼治标准时间）时，DATE 系统变量才返回真正的 Julian 日期。系统变量 TDCREATE 和 TDUPDATE 与 DATE 格式相同，但这两个变量的值分别表示当前图形的创建时间和最后更新的时间。

通过用 DATE 返回的数字相减可计算出日期和时间的差别。 通过用 86400 秒乘以 DATE 的小数部分，可以计算出自午夜起的秒数。

注意:从基于 AutoCAD 2017 的产品开始，DATE 系统变量中存储的当前系统日期和时间将精确到当前秒；但在以前的版本中，当前系统时间还包括毫秒。如果要使用 DATE 系统变量来追踪开始时间和结束时间之间的变化，请注意除非经过一秒，否则将看不到时间变化，即使已经过 0 至 999 毫秒也是如此。在需要计算小于一秒的时间差时，请考虑使用 MILLISECS 系统变量返回的值。
在基于 AutoCAD 的产品（非 AutoCAD LT）中，AutoLISP 可用于基于 DATE 返回的值计算自午夜起的秒数。

(setq s (getvar "DATE"))
(setq seconds (* 86400.0 (- s (fix s))))
注意:如果使用的是基于 AutoCAD 的产品而非 AutoCAD LT，可以使用 DATE Express Tool 以及 DATE 系统变量。DATE Express Tool 的功能与命令相似，并使用字符串格式（如 MON 2012/5/7 10:29:10.563）。要查看基于 AutoCAD 的产品中 DATE 系统变量的当前值，请输入 SETVAR，然后在提示下输入 DATE。
* DBCSTATE
指示数据库连接管理器处于打开还是关闭状态。
（只读）
类型:	整数
保存位置:	未保存
初始值:	0
值 | 说明
0 | 关闭
1 | 打开
* DBLCLKEDIT
控制绘图区域中的双击编辑操作。
类型:	整数
保存位置:	注册表
初始值:	1
可以使用自定义用户界面 (CUI) 编辑器自定义双击动作。

系统变量可以接受值“打开”和“关闭”以代替 1 和 0。

值 | 说明
0 | 禁用
1 | 启用
* DBMOD
指示图形的修改状态。
（只读）
类型:	整数
保存位置:	未保存
初始值:	0
系统将使用下列位码值之和将该设置存储为一个位码：

值 | 说明
1 | 对象数据库被修改
4 | 数据库变量被修改
8 | 窗口被修改
16 | 视图被修改
32 | 字段被修改

保存图形时，DBMOD 的值被重置为 0。
* DCTCUST
显示当前的自定义拼写词典的路径和文件名。
类型:	字符串
保存位置:	注册表
初始值:	不确定
* DCTMAIN
显示当前主拼写词典的三字母关键字。
类型:	字符串
保存位置:	注册表
初始值:	因国家/地区而异
可以使用 SETVAR 命令指定默认的主拼写词典。提示为 DCTMAIN 指定新值时，可以输入下表中的关键字之一：根据程序的语言版本，有些词典可能会不可用。
值 | 说明
enu | 美国英语
eng | 英国英语 (ise)
enc | 加拿大英语
cat | 加泰罗尼亚语
csy | 捷克语
dan | 丹麦语
nld | 荷兰语（主要）
fin | 芬兰语
fra | 法语（大写字母标重音）
frc | 法语（大写字母不标重音）
deu | 德语（后现代）
deo | 德语（前现代）
ita | 意大利语
nor | 挪威语（博克马尔）
ptb | 葡萄牙语（巴西）
ptg | 葡萄牙语（伊比利亚半岛地区）
rus | 俄语
esp | 西班牙语
sve | 瑞典语
* DEFAULTGIZMO
选择子对象过程中将三维移动小控件、三维旋转小控件或三维缩放小控件设定为默认小控件。
类型:	整数
保存位置:	未保存
初始值:	0
值 | 说明
0 | 默认情况下，在三维视觉样式中选定某个对象后，将显示三维移动小控件。
1 | 默认情况下，在三维视觉样式中选定某个对象后，将显示三维旋转小控件。
2 | 默认情况下，在三维视觉样式中选定某个对象后，将显示三维缩放小控件。
3 | 默认情况下，在三维视觉样式中选择某个对象后，不显示任何小控件。

默认情况下，将此变量设定为显示最常用的小控件。
* DEFAULTLIGHTING
打开或关闭代替其他光源的默认光源。
类型:	整数
保存位置:	图形
初始值:	1

默认光源由沿观察方向的一组平行光提供。打开默认光源时，阳光和其他光源将不投射光源（即使已打开这些光源）。该系统变量的设置是特定于视口的。

值 | 说明
0 | 当打开点光源、聚光灯、平行光或阳光时，默认光源将自动关闭
1 | 仅打开默认光源
* DEFAULTLIGHTINGTYPE
指定默认光源的类型（原有类型或新的类型）。

类型:	整数
保存位置:	图形
初始值:	1
基于 AutoCAD 2006 以及更早版本的产品中提供的默认光源使用的是一组平行光。新的默认光源使用两组平行光从而可以照亮更多模型并同时调节环境光。该系统变量的设置是特定于视口的。

值 | 说明
0 | 原有默认光源类型
1 | 新的默认光源类型
* DEFLPLSTYLE
指定在打开 AutoCAD 2000 之前的版本中创建的图形时，图形中所有图层的默认打印样式；或指定在不使用图形模板从头创建新图形时，图层 0 的默认打印样式。
类型:	字符串
保存位置:	注册表
初始值:	普通
图形打开且 PSTYLEPOLICY 设定为 1（颜色相关打印样式模式）时，DEFLPLSTYLE 是只读的，且值为“BYCOLOR”。如果图形打开时 PSTYLEPOLICY 设定为 0（零）（命名打印样式模式），则 DEFLPLSTYLE 是可写的，且默认值为“NORMAL”。

要将当前图形转换为使用命名打印样式或颜色相关打印样式，请使用 CONVERTPSTYLES 命令。
* DEFPLSTYLE
指定在打开 AutoCAD 2000 之前的版本中创建的图形或不使用图形模板从头创建新图形时，图形中新对象的默认打印样式。
类型:	字符串
保存位置:	注册表
初始值:	BYLAYER
图形打开且 PSTYLEPOLICY 设定为 1（颜色相关打印样式模式）时，DEFLPLSTYLE 是只读的，且值为“BYCOLOR”。如果 PSTYLEPOLICY 设定为 0（零）（命名打印样式模式），则 DEFPLSTYLE 是可写的，且默认值为“BYLAYER”。

要将当前图形转换为使用命名打印样式或颜色相关打印样式，请使用 CONVERTPSTYLES 命令。

* DELOBJ
控制保留还是删除用于创建其他对象的几何图形。
类型:	整数
保存位置:	注册表
初始值:	3
该系统变量的功能会有所不同，具体取决于产品。

基于 AutoCAD 的产品
如果您使用的产品支持创建基于现有几何图形的三维模型，请使用此系统变量控制是保留还是删除原始几何图形。

如果 SURFACEASSOCIATIVITY 系统变量设定为 1，将忽略 DELOBJ 设置。

值 | 说明
0 | 保留所有定义几何图形。此设置包括为所有阵列命令保留源对象。
1 | 删除轮廓曲线（包括使用 EXTRUDE、SWEEP、REVOLVE 和 LOFT 命令的轮廓曲线）。删除 CONVTOSOLID、CONVTOSURFACE、CONVTONURBS 和 CONVTOMESH 命令的所有定义几何图形。还将删除使用 LOFT 命令的横截面。
2 | 删除所有定义几何图形（包括与 SWEEP 和 LOFT 命令配合使用的路径曲线和导向曲线）。
3 | 如果动作产生实体对象，将删除所有定义几何图形（包括与 SWEEP 和 LOFT 命令配合使用的路径曲线和导向曲线）。删除 CONVTOSOLID、CONVTOSURFACE、CONVTONURBS 和 CONVTOMESH 命令的所有定义几何图形。该设置也应用于命令（例如 PEDIT 和 SPLINE）中的选项，以用于在样条曲线和样条拟合多段线之间转换。非零值范围用于保持 AutoCAD 的兼容性。
-1 | 显示删除轮廓曲线（包括与 EXTRUDE、SWEEP、REVOLVE 和 LOFT 命令配合使用的轮廓曲线）的提示。提示删除与 LOFT 命令配合使用的横截面。CONVTOSOLID、CONVTOSURFACE 和 CONVTOMESH 命令的原始几何图形将在无提示情况下被删除。
-2 | 显示删除所有定义几何图形（包括与 SWEEP 和 LOFT 命令配合使用的路径曲线和导向曲线）的提示。CONVTOSOLID、CONVTOSURFACE 和 CONTOMESH 命令的原始几何图形将在无提示情况下被删除。
-3 | 显示结果图元是任何类型的曲面时删除所有定义几何图形的提示。删除生成实体图元的所有原始几何图形，CONVTOSOLID、CONVTOSURFACE、CONVTONURBS 和 CONVTOMESH 命令的原始几何图形将在无提示的情况下被删除。

AutoCAD LT
如果使用 AutoCAD LT 在样条拟合多段线和样条曲线之间转换，请使用此系统变量控制是显示还是删除原始几何图形。

值 | 说明
0 | 保留所有定义几何图形。
从 -3 到 3 的非零整数值
在某些命令（例如 SPLINE 和 PEDIT）中，删除用于创建其他对象的对象。
非零值范围用于保持 AutoCAD 的兼容性。
* DEMANDLOAD
指定是否以及何时按需加载某些应用程序。
类型:	整数
保存位置:	注册表
初始值:	3
如果将此系统变量设定为 0，则第三方应用程序和某些 AutoCAD 命令无法运行。

值 | 说明
0 | 关闭按需加载。
1 | 在打开包含自定义对象的图形时按需加载源应用程序。在调用该应用程序的某个命令时，此设置并不按需加载该应用程序。
2 | 在调用应用程序的某个命令时，按需加载源应用程序。在打开包含自定义对象的图形时，此设置并不按需加载该应用程序。
3 | 在打开包含自定义对象的图形或调用应用程序的某个命令时，按需加载源应用程序。

* DGNFRAME
确定 DGN 参考底图边框在当前图形中是否可见或是否打印。

类型:	整数
保存位置:	图形
初始值:	0
FRAME 系统变量替代 DGNFRAME 设置。在 FRAME 系统变量后使用 DGNFRAME 系统变量以重置 DGN 边框设置。

值 | 说明
0 | 不显示也不打印 DGN 参考底图边框。在选择集预览或对象选择期间，将暂时重新显示该边框。
1 | 显示并打印 DGN 参考底图边框。
2 | 显示但不打印 DGN 参考底图边框。
* DGNIMPORTMAX
设置输入 DGN 文件时转换的元素的最大数目。
类型:	整数
保存位置:	注册表
初始值:	10000000
此限制可防止程序在输入大型的 DGN 文件时用尽内存及挂起。

值 | 说明
0 | 关闭限制。
>0 | 设置对元素数量的限制。
* DGNIMPORTMODE
控制 DGNIMPORT 命令的默认行为。
类型:	整数
保存位置:	用户设置
初始值:	0
值 | 说明
0 | 在新图形文件中输入 DGN 文件。
1 | 将 DGN 文件输入到当前打开的图形并忽略重复的命名对象。
2 | 将 DNG 文件输入到当前打开的图形，并为所有具有 DGN 文件名的命名对象添加前缀。

* DGNMAPPINGPATH
指定用于存储 DGN 映射设置的 dgnsetups.ini 文件的位置。
（只读）
类型:	字符串
保存位置:	注册表
初始值:	不确定
注意:用户可以在“文件”选项卡（“选项”对话框）中设置 dgnsetups.ini 文件的位置。
* DGNOSNAP
决定是否为附着在图形中的 DGN 参考底图中的几何图形激活对象捕捉。

类型:	整数
保存位置:	注册表
初始值:	1
UOSNAP 系统变量将替代 DGNOSNAP 设置。

值 | 说明
0 | 关闭附着在图形中的所有 DGN 参考底图中的几何图形的对象捕捉
1 | 打开附着在图形中的所有 DGN 参考底图中的几何图形的对象捕捉

* DIASTAT
存储最近使用的对话框的退出方式。
（只读）
类型:	整数
保存位置:	未保存
初始值:	0
值 | 说明
0 | 取消
1 | 确定

注意:DIASTAT 系统变量不会应用于标准文件选择对话框（例如“选择文件”和“图形另存为”对话框）。

* DIGITIZER
标识连接到系统的数字化仪。
（只读）
类型:	整数
保存位置:	注册表
初始值:	0
值 | 说明
1 | 集成触摸
2 | 外部触摸
4 | 集成笔
8 | 外部笔
16 | 多种输入
128 | 输入设备就绪
* DIMADEC
控制角度标注中显示的精度小数位数。
类型:	整数
保存位置:	图形
初始值:	0
值 | 说明
-1 | 角度标注显示 DIMDEC 指定的小数位数
0-8 | 指定角度标注中显示的小数位数（与 DIMDEC 无关）

* DIMALT
控制标注中换算单位的显示。
* DIMALTD
控制换算单位中的小数位数。
* DIMALTF
控制换算单位的乘数。
* DIMALTRND
舍入换算标注单位。
* DIMALTTD
设置换算标注单位中的公差值的小数位数。
* DIMALTTZ
控制对公差值的消零处理。
* DIMALTU
为所有标注子样式（角度标注除外）的换算单位设定单位格式。
* DIMALTZ
控制对换算单位标注值的消零处理。
* DIMANNO
指示当前标注样式是否为注释性样式。
* DIMAPOST
指定用于所有标注类型（角度标注除外）的换算标注测量值的文字前缀或后缀（或两者都指定）。
* DIMARCSYM
控制弧长标注中圆弧符号的显示。
* DIMASSOC
控制标注对象的关联性以及是否分解标注。
* DIMASZ
控制尺寸线和引线箭头的大小。并控制基线的大小。
* DIMATFIT
尺寸界线内的空间不足以同时放下标注文字和箭头时，此系统变量将确定这两者的排列方式。
* DIMAUNIT
为角度标注设定单位格式。
* DIMAZIN
针对角度标注进行消零处理。
* DIMBLK
设置尺寸线末端显示的箭头块。
* DIMBLK1
为尺寸线的第一个端点设置箭头（当 DIMSAH 处于打开状态时）。
* DIMBLK2
为尺寸线的第二个端点设置箭头（当 DIMSAH 处于打开状态时）。
* DIMCEN
通过 DIMCENTER、DIMDIAMETER 和 DIMRADIUS 命令控制圆或圆弧圆心标记以及中心线的绘制。
* DIMCLRD
为尺寸线、箭头和标注引线指定颜色。
* DIMCLRE
为尺寸界线、圆心标记和中心线指定颜色。
* DIMCLRT
为标注文字指定颜色。
* DIMCONSTRAINTICON
控制标注约束的锁定图标的显示。
* DIMCONTINUEMODE
确定连续标注或基线标注的标注样式和图层是否继承自正在连续使用的标注。
* DIMDEC
设置标注主单位中显示的小数位数。
* DIMDLE
当使用小斜线代替箭头进行标注时，设置尺寸线超出尺寸界线的距离。
* DIMDLI
控制基线标注中尺寸线的间距。
* DIMDSEP
指定创建单位格式为小数的标注时要使用的单字符小数分隔符。
* DIMEXE
指定尺寸界线超出尺寸线的距离。
* DIMEXO
指定尺寸界线偏离原点的距离。
* DIMFRAC
设置分数格式（当 DIMLUNIT 设定为 4 [建筑] 或 5 [分数] 时）。
* DIMFXL
设置起始于尺寸线，直至标注原点的尺寸界线总长度。
* DIMFXLON
控制是否将尺寸界线设定为固定长度。
* DIMGAP
设置当打断尺寸线以符合标注文字时，标注文字周围的距离。
* DIMJOGANG
决定折弯半径标注中，尺寸线的横向线段的角度。
* DIMJUST
控制标注文字的水平位置。
* DIMLAYER
为新的标注指定默认图层。
* DIMLDRBLK
指定引线箭头的类型。
* DIMLFAC
为线性标注测量值设置比例因子。
* DIMLIM
生成标注界限作为默认文字。
* DIMLTEX1
设置第一条尺寸界线的线型。
* DIMLTEX2
设置第二条尺寸界线的线型。
* DIMLTYPE
设置尺寸线的线型。
* DIMLUNIT
为所有标注类型（角度标注除外）设置单位。
* DIMLWD
为尺寸线指定线宽。
* DIMLWE
为尺寸界线指定线宽。
* DIMPICKBOX
在 DIM 命令中设置对象选择目标高度（以像素为单位）。
* DIMPOST
为标注测量值指定文字前缀或后缀（或两者）。
* DIMRND
将所有标注距离舍入为指定值。
* DIMSAH
控制尺寸线箭头块的显示。
* DIMSCALE
设置应用于标注变量（用于指定尺寸、距离或偏移量）的全局比例因子。
* DIMSD1
控制是否隐去第一条尺寸线和箭头。
* DIMSD2
控制是否隐去第二条尺寸线和箭头。
* DIMSE1
控制是否隐去第一条尺寸界线。
* DIMSE2
控制是否隐去第二条尺寸界线。
* DIMSOXD
如果尺寸界线内没有足够的空间，则隐去箭头。
* DIMSTYLE
显示图形中的标注使用的单位类型（英制/标准或 iso-25/公制）。
* DIMTAD
控制文字相对于尺寸线的垂直位置。
* DIMTDEC
设置标注主单位的公差值中显示的小数位数。
* DIMTFAC
与通过 DIMTXT 系统变量设置一样，指定分数和公差值的文字高度相对于标注文字高度的比例因子。
* DIMTFILL
控制标注文字的背景。
* DIMTFILLCLR
为标注中的文字背景设置颜色。
* DIMTIH
控制所有标注类型（坐标标注除外）的标注文字在尺寸界线内的位置。
* DIMTIX
在尺寸界线之间绘制文字。
* DIMTM
为标注文字设置最小（即最低）公差限制（当 DIMTOL 或 DIMLIM 设定为开时）。
* DIMTMOVE
设置标注文字的移动规则。
* DIMTOFL
控制是否在尺寸界线之间绘制尺寸线（即使标注文字被放置在尺寸界线之外）。
* DIMTOH
控制标注文字在尺寸界线外的位置。
* DIMTOL
将公差附在标注文字中。
* DIMTOLJ
设置公差值相对于表面标注文字的垂直对正方式。
* DIMTP
为标注文字设置最大（即最高）公差限制（当 DIMTOL 或 DIMLIM 设定为开时）。
* DIMTSZ
指定线性标注、半径标注以及直径标注中绘制的代替箭头的小斜线的尺寸。
* DIMTVP
控制标注文字在尺寸线上方或下方的垂直位置。
* DIMTXSTY
指定标注的文字样式。
* DIMTXT
指定标注文字的高度（除非当前文字样式具有固定的高度）。
* DIMTXTDIRECTION
指定标注文字的阅读方向。
* DIMTXTRULER
在编辑标注文字时，控制标尺的显示。
* DIMTZIN
控制对公差值的消零处理。
* DIMUPT
控制用户定位文字的选项。
* DIMZIN
控制针对主单位值的消零处理。
* DISPSILH
控制三维实体对象和曲面对象轮廓边在线框或二维线框视觉样式中的显示。
* DISTANCE
存储 DIST 命令计算出的距离。
* DIVMESHBOXHEIGHT
为网格长方体沿 Z 轴的高度设置细分数目。
* DIVMESHBOXLENGTH
为网格长方体沿 X 轴的长度设置细分数目。
* DIVMESHBOXWIDTH
为网格长方体沿 Y 轴的宽度设置细分数目。
* DIVMESHCONEAXIS
设置绕网格圆锥体底面周长的细分数目。
* DIVMESHCONEBASE
设置网格圆锥体底面周长与圆心之间的细分数目。
* DIVMESHCONEHEIGHT
设置网格圆锥体底面与顶点之间的细分数目。
* DIVMESHCYLAXIS
设置绕网格圆柱体底面周长的细分数目。
* DIVMESHCYLBASE
设置从网格圆柱体底面圆心到其周长的半径细分数目。
* DIVMESHCYLHEIGHT
设置网格圆柱体的底面与顶面之间的细分数目。
* DIVMESHPYRBASE
设置网格棱锥体底面圆心与其周长之间的半径细分数目。
* DIVMESHPYRHEIGHT
设置网格棱锥体的底面与顶面之间的细分数目。
* DIVMESHSPHEREAXIS
设置绕网格球体轴端点的半径细分数目。
* DIVMESHSPHEREHEIGHT
设置网格球体两个轴端点之间的细分数目。
* DIVMESHTORUSPATH
设置由网格圆环体轮廓扫掠的路径的细分数目。
* DIVMESHTORUSSECTION
设置扫掠网格圆环体路径的轮廓中的细分数目。
* DIVMESHWEDGEBASE
设置网格楔体的周长中点与三角形标注之间的细分数目。
* DIVMESHWEDGEHEIGHT
为网格楔体沿 Z 轴的高度设置细分数目。
* DIVMESHWEDGELENGTH
设置网格楔体沿 X 轴的长度细分数目。
* DIVMESHWEDGESLOPE
设置从楔体顶点到底面的边之间斜度的细分数目。
* DIVMESHWEDGEWIDTH
设置网格楔体沿 Y 轴的宽度细分数目。
* DONUTID
设置圆环的默认内径。
类型:	实数
保存位置:	未保存
初始值:	0.5000
* DONUTOD
设置圆环的默认外径。
类型:	实数
保存位置:	未保存
初始值:	1.0000
此值不能为零。如果 DONUTID 系统变量的值大于 DONUTOD，则运行下一个命令时两者的值将互换。

* DRAGMODE
控制进行拖动的对象的显示方式。

类型:	整数
保存位置:	注册表
初始值:	2
该系统变量的名称与命令相同。使用 SETVAR 命令可访问此系统变量。

如果启用该命令，将对象拖动到另一位置时，将会显示该对象的图像。对于配置较低的计算机，拖动可能会很费时。使用 DRAGMODE 可禁止拖动。

值 | 说明
0 | 在拖动时不显示对象的轮廓
1 | 在选定要拖动的对象后，仅当在命令提示下输入 drag 后，才会在拖动时显示对象的轮廓
2 | 自动；在拖动时总是显示对象的轮廓
* DRAGP1
当使用硬件加速时，控制在系统从鼠标检查新输入样例之前，当用户拖动二维视口中的对象时，系统将绘制多少矢量。

类型:	整数
保存位置:	注册表
初始值:	5000
较大的数字会在拖动对象时导致显示更多的图形矢量。为了获得最佳性能，建议使用硬件加速而非软件加速。当在三维视口中拖动对象时，DRAGP1 没有效果。
* DRAGP2
当使用软件加速时，控制在系统从鼠标检查新输入样例之前，当用户拖动二维视口中的对象时，系统将绘制多少矢量。
类型:	整数
保存位置:	注册表
初始值:	10
较大的数字会在拖动对象时导致显示更多的图形矢量。为了获得最佳性能，建议使用硬件加速而非软件加速。当在三维视口中拖动对象时，DRAGP2 没有效果。
* DRAGVS
设置在创建三维实体、网格图元以及拉伸实体、曲面和网格时显示的视觉样式。
类型:	字符串
保存位置:	图形
初始值:	""
用户可以输入句点 (.) 以指定当前视觉样式。DRAGVS 只能设定为保存在图形中的视觉样式。

当前视口的视觉样式设定为“二维线框”时 DRAGVS 无效。

无法通过 PURGE 命令删除为 DRAGVS 指定的视觉样式。
* DRAWORDERCTL
控制创建或编辑重叠对象时这些对象的默认显示行为。

类型:	整数
保存位置:	图形
初始值:	3
关闭重叠对象的默认绘图次序：对象经过编辑后，无论其绘图次序如何，均显示在最前端，直到重生成图形 (REGEN) 或重新打开图形。此设置还会关闭绘图次序继承：对于使用下列命令从另一对象创建的新对象，不会将原对象的绘图次序指定给它们。使用此设置可以提高大型图形中的编辑操作的速度。受继承影响的命令有 BREAK、FILLET、HATCH、HATCHEDIT、EXPLODE、TRIM、JOIN、PEDIT 和 OFFSET。
打开对象的默认绘图次序：编辑对象之后，它们将自动按照正确的绘图次序显示。
打开绘图次序继承：对于使用以上列出的命令从另一对象创建的新对象，将原对象的绘图次序指定给它们。

提供完全绘图次序显示。打开对象的正确绘图次序，并打开绘图次序继承。

注意:完全绘图次序显示可能会降低一些编辑操作的速度。
* DRSTATE
指示“图形修复管理器”窗口处于打开还是关闭状态。
（只读）
类型:	整数
保存位置:	未保存
初始值:	不确定
值 | 说明
0 | 关闭
1 | 打开
* DTEXTED
指定编辑单行文字时显示的用户界面。
类型:	整数
保存位置:	注册表
初始值:	2
已弃用的系统变量。被 TEXTED 系统变量替换。
* DWFFRAME
决定 DWF 或 DWFx 参考底图边框在当前图形中是否可见或是否打印。

类型:	整数
保存位置:	图形
初始值:	2
FRAME 系统变量将替代 DWFFRAME 设置。在 FRAME 系统变量后使用 DWFFRAME 系统变量以重置 DWF 边框设置。

值 | 说明
0 | DWF 或 DWFx 参考底图边框不可见且不打印。在选择集预览或对象选择期间，将暂时重新显示该边框。
1 | 显示和打印 DWF 或 DWFx 参考底图边框。
2 | 显示但不打印 DWF 或 DWFx 参考底图边框。
* DWFOSNAP
决定是否为附加到图形的 DWF 或 DWFx 参考底图中的几何图形激活对象捕捉。
类型:	整数
保存位置:	注册表
初始值:	1

UOSNAP 系统变量将替代 DWFOSNAP 设置。

值 | 说明
0 | 禁用所有 DWF 或 DWFx 参考底图附件中几何图形的对象捕捉
1 | 启用所有 DWF 或 DWFx 参考底图附件中几何图形的对象捕捉

* DWGCHECK
打开图形时检查图形中是否存在潜在问题。
类型:	整数
保存位置:	注册表
初始值:	1
不会为由 Autodesk 发布的应用程序或基于 RealDWG 的应用程序以外的应用程序保存的图形文件显示警告。如果图形受到损坏，将显示“错误通知”对话框。
将为由 Autodesk 发布的应用程序或基于 RealDWG 的应用程序以外的应用程序保存的图形文件显示一个警告对话框和命令行警告。如果图形受到损坏，将显示“错误通知”对话框。
将在命令行中仅为由 Autodesk 发布的应用程序或基于 RealDWG 的应用程序以外的应用程序保存的图形文件显示警告信息。如果图形受到损坏，将忽略错误并打开该图形（如果可能）。
将为由 Autodesk 发布的应用程序或基于 RealDWG 的应用程序以外的应用程序保存的图形文件显示一个警告对话框和命令行警告。如果图形受到损坏，将忽略错误并打开该图形（如果可能）。
将在命令行中仅为由 Autodesk 发布的应用程序或基于 RealDWG 的应用程序以外的应用程序保存的图形文件显示警告信息。如果图形受到损坏，将显示“错误通知”对话框。
将为由 Autodesk 发布的应用程序或基于 RealDWG 的应用程序以外的应用程序保存的图形文件显示一个警告对话框和命令行警告。如果图形受到损坏，将显示“错误通知”对话框。
将在命令行中仅为由 Autodesk 发布的应用程序或基于 RealDWG 的应用程序以外的应用程序保存的图形文件显示警告信息。如果图形受到损坏，将中止打开图形的尝试。
将为由 Autodesk 发布的应用程序或基于 RealDWG 的应用程序以外的应用程序保存的图形文件显示一个警告对话框和命令行警告。如果图形受到损坏，将中止打开图形的尝试。
* DWGCODEPAGE
与 SYSCODEPAGE 系统变量存储相同的值（由于兼容性原因）。
（只读）
类型:	字符串
保存位置:	未保存
初始值:	不确定
* DWGNAME
存储当前图形的名称。
（只读）
类型:	字符串
保存位置:	未保存
初始值:	Drawing1.dwg
如果新图形尚未保存，DWGNAME 将默认为“Drawing1.dwg”。其他新图形命名为“Drawing2.dwg”、“Drawing3.dwg”等。

已保存的图形文件的驱动器和文件夹路径存储在 DWGPREFIX 中。
* DWGPREFIX
存储当前图形的驱动器和文件夹路径。
（只读）
类型:	字符串
保存位置:	未保存
初始值:	不确定
* DWGTITLED
指示当前图形是否已命名。
（只读）
类型:	整数
保存位置:	未保存
初始值:	0
值 | 说明
0 | 图形未命名
1 | 图形已命名
* DXEVAL
控制数据提取处理表何时与数据源相比较，如果数据不是当前数据，则显示更新通知。
类型:	整数
保存位置:	图形
初始值:	12
系统将使用以下值之和将该设置存储为一个整数：

值 | 说明
0 | 没有通知
1 | 打开
2 | 保存
4 | 打印
8 | 发布
16 | 电子传递/存档
32 | 保存时自动更新
64 | 打印时自动更新
128 | 发布时自动更新
256 | 电子传递/存档时自动更新
* DYNCONSTRAINTMODE
选定受约束的对象时显示隐藏的标注约束。
类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 选定对象时使约束保持隐藏状态
1 | 选中受标注约束的对象时显示隐藏的约束

注意:动态约束隐藏时，此系统变量生效（请参见 DCDISPLAY 命令）。
* DYNDIGRIP
控制在夹点拉伸编辑期间显示哪些动态标注。

类型:	位码
保存位置:	注册表
初始值:	31
必须将 DYNDIVIS 系统变量设置为 2，这将显示所有的动态标注。

系统将使用下列位码值之和将该设置存储为一个位码：

值 | 说明
0 | 无
1 | 结果尺寸
2 | 长度更改标注
4 | 绝对角度标注
8 | 角度修改标注
16 | 圆弧半径标注

DYNMODE 系统变量用于打开或关闭动态输入功能。
* DYNDIVIS
控制在夹点拉伸编辑期间显示的动态标注数量。
类型:	整数
保存位置:	注册表
初始值:	1
DYNDIGRIP 控制在夹点拉伸编辑期间显示哪些动态标注。

值 | 说明
0 | 仅显示循环次序中的第一个动态标注
1 | 仅显示循环次序中的前两个动态标注
2 | 显示由 DYNDIGRIP 系统变量控制的所有动态标注

DYNMODE 系统变量用于打开或关闭动态输入功能。
* DYNINFOTIPS
控制在使用夹点进行编辑时是否显示使用 Shift 键和 Ctrl 键的提示。

类型:	整数
保存位置:	注册表
初始值:	1
启用动态输入并且选择一个夹点时，光标处的提示将列出可用的夹点选项，可以使用 Shift 键或 Ctrl 键循环浏览这些选项。

值 | 说明
0 | 隐藏 Shift 和 Ctrl 提示
1 | 显示 Shift 和 Ctrl 提示

该设置位于“绘图设置”对话框的“动态输入”选项卡上。
* DYNMODE
打开或关闭动态输入功能。
类型:	整数
保存位置:	注册表
初始值:	3
全部功能都打开时，上下文将控制所显示的内容。

如果 DYNMODE 设定为负值，则动态输入功能将不会打开，但将会存储其设置。

值 | 说明
0 | 关闭所有动态输入功能（包括动态提示）
1 | 打开指针输入
2 | 打开标注输入
3 | 同时打开指针和标注输入

如果动态提示处于打开状态（DYNPROMPT 设置为 1），则 DYNMODE 设置为 1、2 或 3 时将显示动态提示。

如果标注输入处于打开状态（DYNMODE = 2 或 3），当输入逗号、角度括号 (<) 或选择多个夹点时程序将切换到指针输入。

如果 DYNMODE 设定为 1、2 或 3，则可以通过按下临时替代值键 F12 来临时关闭所有功能。

设置位于“草图设置”对话框的“动态输入”选项卡上。
* DYNPICOORDS
控制指针输入是使用相对坐标格式，还是使用绝对坐标格式。

类型:	整数
保存位置:	注册表
初始值:	0
值 | 说明
0 | 相对坐标
1 | 绝对

DYNMODE 系统变量用于打开或关闭动态输入功能。
* DYNPIFORMAT
控制指针输入是使用极轴坐标格式，还是使用笛卡尔坐标格式。
类型:	整数
保存位置:	注册表
初始值:	0
此设置仅适用于第二点或下一点。

值 | 说明
0 | 极轴
1 | 笛卡尔

DYNMODE 系统变量用于打开或关闭动态输入功能。
* DYNPIVIS
控制何时显示指针输入。

类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 仅当提示输入点后进行输入时显示
1 | 提示输入点时自动显示
2 | 始终显示

DYNMODE 系统变量用于打开或关闭动态输入功能。
* DYNPROMPT
控制“动态输入”工具提示中提示的显示。
类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 关闭
1 | 打开

DYNMODE 系统变量用于打开或关闭动态输入功能。当 DYNMODE 设置为 0（关闭）时，无论 DYNPROMPT 如何设置，都不再显示提示。
* DYNTOOLTIPS
控制受工具提示外观设置影响的工具提示。

类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 仅动态输入值字段
1 | 所有绘图工具提示
* EDGEMODE
控制 TRIM 和 EXTEND 命令确定边界的边和剪切边的方式。
类型:	整数
保存位置:	注册表
初始值:	0
值 | 说明
0 | 使用不带延伸线的选定边
1 | 将选定的对象延伸或修剪到剪切边或边界的假想尺寸界线

直线、圆弧、椭圆弧、射线和多段线都是可以自然延伸的对象。直线和射线的自然延伸都是无限长线（构造线）。圆弧的自然延伸是一个圆，而椭圆弧的自然延伸是一个椭圆。多段线可以拆分成直线和圆弧部件，这些部件都可以延伸到其自然边界。

* ELEVATION
存储新对象相对于当前 UCS 的当前标高。
类型:	实数
保存位置:	图形
初始值:	0.0000
控制从 BIM 360 打开图纸集 (DST) 文件后是否自动锁定该文件。

类型:	整数
保存位置:	注册表
初始值:	0
值 | 说明
0 | DST 文件不自动锁定；默认
1 | 从 BIM 360 打开时 DST 文件将自动锁定，关闭时将解除锁定

* ENTERPRISEMENU
存储企业自定义文件名（如果已定义），其中包括文件名的路径。
（只读）
类型:	字符串
保存位置:	注册表
初始值:	"."
* ERHIGHLIGHT
控制在“外部参照”选项板或图形窗口中选择参照的对应内容时，是亮显参照名还是参照对象。
类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 不亮显参照对象。
1 | 亮显参照对象。
* ERRNO
AutoLISP 函数调用导致 AutoCAD 检测到错误时，显示相应的错误代码的编号。
（只读）
类型:	整数
保存位置:	未保存
初始值:	0
AutoLISP 应用程序可用 (getvar "errno") 来检验 ERRNO 的当前值。

ERRNO 系统变量并不总是被清为零。除非在 AutoLISP 函数发现错误之后立即检查该变量，否则代码值所指示的错误可能会引起误解。在启动或打开一个图形时，该变量被清为零。
* ERSTATE
指示“外部参照”选项板处于打开还是关闭状态。
（只读）
类型:	整数
保存位置:	未保存
初始值:	不确定
值 | 说明
0 | 关闭
1 | 打开
* EXPERT
控制是否显示某些特定提示。
类型:	整数
保存位置:	未保存
初始值:	0
值 | 说明
0 | 正常地显示所有提示。
1 | 禁止显示“准备重生成，是否继续？”和“是否确实希望关闭当前图层？”(-LAYER)
2 | 禁止显示上述提示和“已定义块。是否重新定义？”(-BLOCK) 和“具有此名称的图形已存在。是否替换？”（SAVE 或 WBLOCK）。
3 | 不显示上述提示，以及尝试加载已加载的线型或尝试在已定义线型的文件中创建新线型时由 LINETYPE 命令提示 (-LINETYPE) 发出的提示。
4 | 不显示上述提示，以及输入的名称已存在时 UCS 命令的“保存”选项和 VPORTS 命令的“保存”选项所给出的提示。
5 | 禁止显示提示“该名称已在使用，是否重新定义？”由 -DIMSTYLE 的“保存”选项发出的“该名称已在使用。是否重新定义？”提示。不显示 -SCALELISTEDIT 系统变量“添加”选项发放的相同提示。

当提示被 EXPERT 禁止时，将执行正在处理的操作，而认为用户在提示时输入了 y。


注意:设置 EXPERT 可以影响脚本、菜单宏、AutoLISP 及命令函数。（不适用于 AutoCAD LT。）

* EXPLMODE
控制 EXPLODE 命令是否支持按非统一比例缩放(NUS) 的块。
类型:	整数
保存位置:	未保存
初始值:	1
值 | 说明 
0 | 不分解 NUS 块
1 | 分解 NUS 块
* EXPORTMODELSPACE
指定要将图形中的哪些内容从模型空间中输出为 DWF、DWFx 或 PDF 文件
类型:	整数
保存位置:	图形
初始值:	0
值 | 说明
0 | 当前布局
1 | 所有布局
* EXPORTPAGESETUP
指定是否按照当前页面设置输出为 DWF、DWFx 或 PDF 文件。
类型:	整数
保存位置:	图形
初始值:	0
值 | 说明
0 | 当前 - 使用 DWG 的当前页面设置来输出文件。此变量设定为 0（零）时，功能区“输出”选项卡的“输出为 DWF/PDF”面板中的“页面设置”组合框将显示“当前”。
1 | 替代 - 输出文件并允许用户替代 DWG 的当前页面设置。此变量设定为 1 时，功能区“输出”选项卡的“输出为 DWF/PDF”面板中的“页面设置”组合框将显示“替代”。用户可以在“页面设置替代”对话框中替代打印选项，例如页面大小和方向。

* EXPORTPAPERSPACE
指定要将图形中的哪些内容从图纸空间中输出为 DWF、DWFx 或 PDF 文件。

类型:	整数
保存位置:	图形
初始值:	0
值 | 说明
0 | 当前布局
1 | 所有布局
* EXPVALUE
指定渲染期间要应用的曝光值。

类型:	实数
保存位置:	图形
初始值:	8.8000
曝光值控制应用到渲染图像的光源量。

减小该值可使渲染的图像变亮，增加该值可使渲染的图像变暗。有效值范围为 -6 到 21。
* EXPWHITEBALANCE
指定渲染期间要应用的开尔文颜色温度（白平衡）。
类型:	实数
保存位置:	图形
初始值:	6500.0000
开尔文颜色温度值可控制渲染图像的整体色调。

减小该值可以使渲染图像中的光源变冷，增加该值可以使渲染图像中的光源变暖。冷温度值会产生蓝色光，而暖温度值会产生黄色或红色光。

有效值范围为 1000.0000 到 20000.0000。
* EXTMAX
存储图形范围右上角点的值。

类型:	三维点
保存位置:	图形
初始值:	不确定
如果有新的对象绘制到界限之外，则仅当使用 ZOOM 命令的“全部”或“范围”选项时，对象才会收缩至新范围内。本系统变量的值表示为当前空间中的世界坐标值。
* EXTMIN
存储图形范围左下角点的值。
（只读）
类型:	三维点
保存位置:	图形
初始值:	不确定
如果有新的对象绘制到界限之外，则仅当使用 ZOOM 命令的“全部”或“范围”选项时，对象才会收缩至新范围内。本系统变量的值表示为当前空间中的世界坐标值。
* EXTNAMES
控制圖塊、標註型式、圖層以及其他具名物件的名稱所接受的字元。

类型:	整数
保存位置:	图形
初始值:	1
值 | 说明 
0 | 使用版本 14 的参数，参数名称最多包含 31 个字符。其中可以包括字母 A 到 Z、数字 0 到 9 以及特殊字符，例如，美元符号 ($)、下划线 (_) 和连字符 (-)。
1 | 使用版本 2000（或更高版本）的参数。名称最长可达 255 个字符，其中可以包括字母 A 到 Z、数字 0 到 9、空格以及操作系统和该产品未用于其他目的的任何特殊字符。

* FACETERDEVNORMAL
设置曲面法线与相邻网格面之间的最大角度。
类型:	实数
保存位置:	用户设置
初始值:	40
此设置会影响使用 MESHSMOOTH 命令从另一个对象转换的网格。此值还可以在“网格镶嵌选项”对话框中进行设置。

使用此设置可在形状相同、但大小不同的网格对象之间保持视觉一致性。可以输入从 0（零）到 180 的任意非负数。减少该值会增大高曲率区域中的密度，同时降低曲率较低区域中的密度。

减少该值可能会增大图形文件的大小，应为具有高 FACETERDEVSURFACE 设置的较大型对象进行存储。避免为带有小细节（例如孔或圆角）的对象减小该值。

注意: 此系统变量的值反映平滑度为零的对象的值。
* FACETERDEVSURFACE
设置经转换的网格对象与实体或曲面的原始形状的相近程度。

类型:	实数
保存位置:	用户设置
初始值:	0.0010
此设置会影响使用 MESHSMOOTH 命令从另一个对象转换的网格。此值还可以在“网格镶嵌选项”对话框中进行设置。

可以输入任意非负数，包括 0（零）。值越小，面数越大，对象曲面中偏差较低的网格精确度越高，而性能越低。将此值设定为 0 可关闭此选项。

注意: 此系统变量的值反映平滑度为零的对象的值。
* FACETERGRIDRATIO
为转换为网格的实体和曲面而创建的网格细分设置最大宽高比。

类型:	实数
保存位置:	用户设置
初始值:	0.0000
此设置会影响使用 MESHSMOOTH 命令从另一个对象转换的网格。此值还可以在“网格镶嵌选项”对话框中进行设置。

允许值的范围从 0 到 100 之间，并设置面的高度/宽度比。使用此变量可防止出现长而薄的面，这些面可能由柱面对象转换而来。值越小，面越多，构造越精细，但是可能会影响性能。将此值设定为 0 可将其关闭。

如果输入的值小于 1，则比例计算基于 1/n。例如，如果输入 0.2，则变量值为 1/0.2 = 5。

注意: 此系统变量的值反映平滑度为零的对象的值。
* FACETERMAXEDGELENGTH
为通过从实体和曲面转换创建的网格对象设置边的最大长度。
类型:	实数
保存位置:	用户设置
初始值:	0.0000
可以使用任意非负数，包括 0（零）。

此设置会影响使用 MESHSMOOTH 命令从另一个对象转换的网格。此值还可以在“网格镶嵌选项”对话框中进行设置。

注意: 此系统变量的值反映平滑度为零的对象的值。
* FACETERMAXGRID
设置内部参数，它会在使用 MESHSMOOTH 命令将对象转换为网格对象时，影响 U 和 V 栅格线的最大数量。
类型:	整数
保存位置:	用户设置
初始值:	4096
值的范围为从 0 到 4096。

注意: 此系统变量的值反映平滑度为零的对象的值。

* FACETERMESHTYPE
设置要创建的网格类型。

类型:	整数
保存位置:	用户设置
初始值:	0
值 | 说明
0 | 对象将转换为具有较少面的优化网格对象类型
1 | 面大多为四边形
2 | 面大多为三角形

此设置会影响使用 MESHSMOOTH 命令从另一个对象转换的网格。此值还可以在“网格镶嵌选项”对话框中进行设置。

* FACETERMINUGRID
设置内部参数，它会在使用 MESHSMOOTH 命令将对象转换为网格对象时，影响 U 栅格线的最小数量。

类型:	整数
保存位置:	用户设置
初始值:	0
值的范围介于 0 到 1023 之间或更少，具体取决于其他设置。设置为 0（零）可关闭该设置。此系统变量的值不能超过 FACETERMAXGRID 的值。

注意: 此系统变量的值反映平滑度为零的对象的值。
* FACETERMINVGRID
设置内部参数，它会在使用 MESHSMOOTH 命令将对象转换为网格对象时，影响 V 栅格线的最小数量。

类型:	整数
保存位置:	用户设置
初始值:	0
值的范围介于 0 到 1023 之间或更少，具体取决于其他设置。设置为 0（零）可关闭该设置。此系统变量的值不能超过 FACETERMAXGRID 的值。

注意: 此系统变量的值反映平滑度为零的对象的值。
* FACETERPRIMITIVEMODE
指定转换为网格的对象的平滑度设置是来自“网格镶嵌选项”对话框还是来自“网格图元选项”对话框。
类型:	整数
保存位置:	用户设置
初始值:	1
值 | 说明
0 | 将“网格镶嵌选项”对话框中的设置应用于转换的对象。
1 | 将“网格图元选项”对话框中的设置应用于转换的对象。

此设置会影响使用 MESHSMOOTH 命令从三维实体对象图元（例如长方体或圆锥体）转换的网格。还可以在“网格镶嵌选项”对话框中进行设置。
* FACETERSMOOTHLEV
设置转换为网格的对象的默认平滑度。
类型:	整数
保存位置:	用户设置
初始值:	1
值 | 说明
-N | 转换后请勿对对象进行平滑处理
0 | 转换后请勿对对象进行平滑处理
1 | 转换后应用平滑度 1
2 | 转换后应用平滑度 2
3 | 转换后应用平滑度 3
4 | 转换后应用平滑度 4

此变量可设置平滑度，该平滑度将应用于由于使用 MESHSMOOTH 命令从另一个对象转换而创建的网格。

该值不能大于 SMOOTHMESHMAXLEV 的值。

在以下情况下创建的网格对象在创建时平滑度始终为零，且不受此系统变量影响：

使用 REVSURF、TABSURF、RULESURF 或 EDGESURF 创建的网格
将网格类型设定为四边形或三角形时使用 MESHSMOOTH 创建的网格 (FACETERMESHTYPE)
此变量还可以在“网格镶嵌选项”对话框中进行设置。
* FACETRATIO
控制圆柱和圆锥实体镶嵌面的宽高比。

类型:	整数
保存位置:	未保存
初始值:	0
值 | 说明
0 | 为圆柱和圆锥实体创建 N x 1 网格
1 | 为圆柱和圆锥实体创建 N x M 网格

设置为 1 将增加网格密度以改善渲染模型和着色模型的质量。

镶嵌面仅在二维线框视觉样式中可见。
* FACETRES
调整着色和渲染对象、渲染阴影以及删除了隐藏线的对象的平滑度。
类型:	实数
保存位置:	图形
初始值:	0.5000
有效值为 0.01 到 10.0。

注意:
3DDWFPREC 在控制发布的三维 DWF 文件精度方面可以替代 FACETRES。
使用 3DPRINT 命令时，FACTRES 系统变量将设定为 10。
在 AutoCAD LT 中提供此系统变量，仅用于辅助在诸如 AutoCAD 等其他产品中创建的三维对象的显示。

* FIELDDISPLAY
控制字段显示时是否带有灰色背景。

类型:	整数
保存位置:	注册表
初始值:	1
不打印背景。

值 | 说明
0 | 显示的字段不带背景
1 | 显示的字段带有灰色背景

* FIELDEVAL
控制字段的更新方式。

类型:	整数
保存位置:	图形
初始值:	31
系统将使用下列位码值之和将该设置存储为一个位码：

值 | 说明
0 | 不更新
1 | 打开时更新
2 | 保存时更新
4 | 打印时更新
8 | 使用 ETRANSMIT 时更新
16 | 重生成时更新

注意:“日期”字段由 UPDATEFIELD 更新，但是不会基于 FIELDEVAL 系统变量的设置自动进行更新。

* FILEDIA
不显示文件导航对话框。
类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 不显示对话框。用户仍然可以通过在响应命令提示时输入波浪号 (~) 来申请显示文件对话框。
1 | 显示对话框。但是，如果正在执行一个脚本，将会显示通常状况下的提示。如果 AutoLISP 或 ObjectARX™ 程序处于活动状态，也将显示提示。（不适用于 AutoCAD LT。）

注意:脚本的执行可能会暂时隐藏“文件导航”对话框。
* FILETABPREVIEW
控制将光标悬停在图形文件选项卡上方时的预览类型。

类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 显示包含模型和所有布局名称的列表。
1 | 显示一组缩略图。
* FILETABSTATE
指示位于绘图区域顶部的文件选项卡的显示状态。
（只读）
类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 隐藏文件选项卡。
1 | 显示文件选项卡。

当文件选项卡处于隐藏状态时，请使用 Ctrl+TAB 组合键浏览文件选项卡。
* FILETABTHUMBHOVER
指定当您将光标悬停在文件选项卡缩略图上时，是否在图形窗口中加载相应的模型或布局。
类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
1 | 当您将光标悬停在文件选项卡缩略图上时，在图形窗口中加载模型或布局。
0 | 当您将光标悬停在文件选项卡缩略图上时，在图形窗口中不加载模型或布局。

* FILLETPOLYARC
确定多段线（包括当前圆弧或旧圆弧）的圆角行为。
类型:	整数
保存位置:	注册表
初始值:	1
FILLETPOLYARC 仅影响“圆角”命令的“多段线”选项。

值 | 说明
0 | AutoCAD 2014 及更早版本中的旧行为（未在多线段弯折圆弧段）。
1 | 弯折圆弧段的当前行为，在某些情况下，可能导致意外的扭折。
* FILLETRAD
存储二维对象的当前圆角半径。
类型:	实数
保存位置:	图形
初始值:	0.0000
如果使用 FILLET 命令更改二维圆角的半径，将更改此系统变量的值以与半径的值匹配。
* FILLETRAD3D
存储三维对象的当前圆角半径。
类型:	实数
保存位置:	图形
初始值:	1.0000
存储使用 FILLETEDGE 和 SURFFILLET 命令创建的三维实体和曲面圆角的默认半径。如果用户在使用 FILLETEDGE 或 SURFFILLET 命令时更改半径，FILLETRAD 系统变量不会更新为此新值。
* FILLMODE
指定是否填充图案填充、二维实体以及宽多段线。
类型:	整数
保存位置:	图形
初始值:	1
值 | 说明
0 | 不填充对象
1 | 填充对象
* FONTALT
指定找不到指定的字体文件时要使用的替换字体。

类型:	字符串
保存位置:	注册表
初始值:	simplex.shx
如果打开的图形文件具有已定义的文字样式但未指定替换字体，将显示“替换字体”对话框。
* FONTMAP
指定要用于替换字体的字体映射文件。
类型:	字符串
保存位置:	注册表
初始值:	acad.fmp (AutoCAD) 或 acadlt.fmp (AutoCAD LT)
字体映射文件的每一行包含一个字体映射。图形中使用的原始字体和替换字体通过分号 (;) 隔开。例如，要使用 Times TrueType 字体替换罗马字体，在映射文件中将如下表达：

romanc.shx;times.ttf
如果 FONTMAP 没有指向字体映射文件，或未找到 FMP 文件，或者未找到 FMP 文件中指定的字体文件名，则将使用样式中定义的字体。如果未找到样式中的字体，将会根据替换规则替换字体。

FONTMAP 只能用于通过 MTEXT 命令创建的文字。
* FRAME
控制所有图像、贴图图像、参考底图、剪裁外部参照和区域覆盖对象的边框的显示。

类型:	整数
保存位置:	图形
初始值:	3
更改 FRAME 的设置会将 IMAGEFRAME、DWFFRAME、PDFFRAME、DGNFRAME、XCLIPFRAME 和 WIPEOUTFRAME 设置更改为与新的 FRAME 设置相同的设置。

值

说明

 
0

边框不可见且不打印。

在选择集预览或对象选择期间，将暂时重新显示该边框。

   查找
1

显示并打印边框。

   查找
2

显示但不打印边框。

   查找
3

对于当前图形中具有边框的所有对象，这些设置也各不相同：图像、参考底图、剪裁外部参照和区域覆盖对象并非都具有相同的边框设置。

   查找
注意:不能手动将 FRAME 设置为值 3。仅当其他某个对象特定的边框设置更改为不同于其他对象的值时，FRAME 的设置才恢复为 3。

* FRAMESELECTION
控制是否可以选择图像、参考底图、剪裁外部参照或区域覆盖的隐藏边框。
类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 无法选择隐藏边框。
1 | 可以选择隐藏边框。

注意:FRAME 系统变量控制是显示还是隐藏所有类型的边框。
PREVIEWFILTER 系统变量防止在选择集预览期间重新显示边框，但仍然可以选择边框。
* FRONTZ
以图形单位存储当前视口前向剪裁平面到目标平面的偏移。
（只读）
类型:	实数
保存位置:	图形
初始值:	0.0000
VIEWMODE 中的“前向剪裁”和“前向剪裁不在视点”位码选项处于打开状态。FRONTZ 值为上一个使用 CAMERA、DVIEW 或 3DCLIP 命令置为当前的前向剪裁平面值。前向剪裁平面到相机点的距离等于相机到目标的距离减去 FRONTZ 的值。

* FULLOPEN
指示当前图形是否局部打开。
（只读）
类型:	整数
保存位置:	未保存
初始值:	1
值 | 说明
0 | 指示局部打开的图形
1 | 指示完全打开的图形
* FULLPLOTPATH
控制是否将图形文件的完整路径发送到后台打印。
类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 仅发送图形文件名
1 | 发送图形文件的完整路径



* GALLERYVIEW
控制功能区下拉库中的预览类型。
型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 显示列表视图。
1 | 显示缩略图视图。

注意:单元样式和文字样式功能区库不会显示列表视图。
* GEOLATLONGFORMAT
控制“地理位置”对话框和状态栏中纬度值和经度值的格式。
类型:	整数
保存位置:	注册表
初始值:	0
值 | 说明
0 | 纬度和经度值的格式为十进制度数 (DD)
1 | 纬度和经度值的格式为度/分/秒 (DMS)

* GEOLOCATEMODE
指示位置追踪是处于打开状态还是关闭状态。
（只读）
类型:	参数
保存位置:	未保存
初始值:	0
值	说明
0 | 位置跟踪处于禁用状态
1 | 位置追踪处于启用状态
* GEOMAPMODE
控制用于当前视口中的联机地图的样式。
（只读）
类型:	整数
保存位置:	图形
初始值:	0
值 | 说明
0 | 地图不可见
1 | 地图将显示为卫星图像。
2 | 地图将显示为一系列道路、建筑和地理的矢量图像。
3 | 地图将显示为具有矢量图像（道路叠加在顶部）的卫星图像。


* GEOMARKERVISIBILITY
控制地理标记的可见性。

类型:	整数
保存位置:	图形
初始值:	1
值	说明
0 | 地理标记不可见
1 | 地理标记可见
* GEOMARKPOSITIONSIZE
指定在创建位置标记时，用于点对象和多行文字对象的比例因子。
类型:	整数
保存位置:	图形
初始值:	1
仅可以为此系统变量指定正数。
* GFANG
指定渐变填充的角度。
类型:	实数
保存位置:	未保存
初始值:	0
有效值的范围从 0 到小于 360（度）。负值和等于或大于 360 的值都会被接受，但它们将被转换为介于 0 到 360 之间的等量值。

* GFCLR1
指定单色渐变填充的颜色或双色渐变填充的第一种颜色。
类型:	字符串
保存位置:	未保存
初始值:	“蓝色”
有效值包括：

AutoCAD 颜色索引 (ACI)：介于 1 和 255 之间的整数值，或前七种颜色中的一种颜色名称
真彩色：介于 000 和 255 之间的 RGB 或 HSL 值，格式为“RGB:130,200,240”
配色系统：标准配色系统、导向或设定的文字，例如“DIC COLOR GUIDE(R)$DIC 43”
* GFCLR2
指定双色渐变填充的第二种颜色。
类型:	字符串
保存位置:	未保存
初始值:	“黄色”
有效值包括：

AutoCAD 颜色索引 (ACI)：介于 1 和 255 之间的整数值，或前七种颜色中的一种颜色名称
真彩色：介于 000 和 255 之间的 RGB 或 HSL 值，格式为“RGB:130,200,240”
配色系统：标准配色系统、导向或设定的文字，例如“DIC COLOR GUIDE(R)$DIC 43”
* GFCLRLUM
控制单色渐变填充中的明级别或暗级别。

类型:	实数
保存位置:	未保存
初始值:	1.0000
白色的明渐变转场和黑色的暗渐变转场。有效值介于 0.0（最暗）和 1.0（最亮）之间。
* GFCLRSTATE
指定渐变填充是使用单色还是双色。

类型:	整数
保存位置:	未保存
初始值:	0
值 | 说明
0 | 双色渐变填充
1 | 单色渐变填充
* GFNAME
指定渐变填充的图案。

类型:	整数
保存位置:	未保存
初始值:	1
值 | 说明
1 | 线性
2 | 柱坐标
3 | 反转圆柱形
4 | 球坐标
5 | 半球形
6 | 曲线式
7 | 反转球形
8 | 反转半球形
9 | 反转曲线式
* GFSHIFT
指定渐变填充中的图案是居中还是向上和向左移动。

类型:	整数
保存位置:	未保存
初始值:	0
值 | 说明
0 | 居中
1 | 向上和向左移动
* GLOBALOPACITY
控制所有选项板的透明度级别。
类型:	整数
保存位置:	注册表
初始值:	100
值 | 说明
0 | 完全透明
100 | 完全不透明

输入一个 0 到 100 之间的值以设定透明度级别。
此系统变量决定“透明度”对话框 >“禁用所有窗口透明度(全局)”选项的默认设置。
* GRIDDISPLAY
控制栅格的显示行为和显示界限。

类型:	位码
保存位置:	图形
初始值:	3
系统将使用下列位码值之和将该设置存储为一个位码：

值 | 说明
0 | 将栅格限制在 LIMITS 命令指定的区域内
1 | 不会将栅格限制在 LIMITS 命令指定的区域内
2 | 打开自适应栅格显示，从而可以在缩小时限制栅格密度
4 | 如果栅格设定为自适应显示，放大时将以与主栅格线间隔相同的比例生成其他更加紧密的栅格线
8 | 更改栅格平面以跟随动态 UCS 的 XY 平面。（不适用于 AutoCAD LT。）

注意: 除非指定设置 2，否则将忽略设置 4。
* GRIDMAJOR
控制主栅格线与次栅格线相比较的频率。
类型:	整数
保存位置:	图形
初始值:	5
有效值范围为从 1 到 100。
* GRIDMODE
指定栅格处于打开状态还是关闭状态。
类型:	整数
保存位置:	图形
初始值:	1
值 | 说明
0 | 关闭栅格
1 | 打开栅格
* GRIDSTYLE
控制是将栅格显示为点还是线。
类型:	整数
保存位置:	注册表
初始值:	0
系统将使用以下值之和将该设置存储为一个位码：

值 | 说明
0 | 为模型空间、块编辑器、图纸和图纸空间布局显示线栅格。
1 | 为模型空间显示点栅格。
2 | 为块编辑器显示点栅格。
4 | 为图纸和图纸空间布局显示点栅格。
* GRIDUNIT
指定当前视口的栅格间距（X 和 Y 方向）。
类型:	二维点
保存位置:	图形
初始值:	(0.5000,0.5000)（英制）或 (10,10)（公制）
要使栅格间距默认为捕捉间距，请将 GRIDUNIT 设置为 0,0。对 GRIDUNIT 所做的更改在重生成视图之前不会显示在栅格中。

* GRIPBLOCK
控制块中夹点的显示。

类型:	整数
保存位置:	注册表
初始值:	0
值 | 说明
0 | 只为块的插入点指定夹点
1 | 为块中的对象指定夹点
* GRIPCOLOR
控制未选定夹点的颜色。

类型:	整数
保存位置:	注册表
初始值:	150
旧式的。有效取值范围为 1 到 255。
* GRIPCONTOUR
控制夹点轮廓的颜色。

类型:	整数
保存位置:	注册表
初始值:	251
有效取值范围为 1 到 255。
* GRIPDYNCOLOR
控制动态块的自定义夹点的颜色。
类型:	整数
保存位置:	注册表
初始值:	140
有效取值范围为 1 到 255。
* GRIPHOT
控制选定夹点的颜色。
类型:	整数
保存位置:	注册表
初始值:	12
有效取值范围为 1 到 255。
* GRIPHOVER
控制光标暂停在未选定夹点上时该夹点的填充颜色。

类型:	整数
保存位置:	注册表
初始值:	11
旧式的。有效取值范围为 1 到 255。
* GRIPMULTIFUNCTIONAL
指定多功能夹点选项的访问方法。
类型:	位码
保存位置:	注册表
初始值:	3
值 | 说明
0 | 多功能夹点选项不可用
1 | 通过按 Ctrl 键可访问多功能夹点选项以更改夹点的行为（按 Ctrl 键循环改变对象编辑方式）
2 | 多功能夹点选项可以通过将光标悬停在夹点上时显示的夹点菜单进行访问

注意:此系统变量是一个位码，并且已添加值来确定行为。例如，值为 3 表示既可按 Ctrl 键循环改变对象编辑方式，也可以使用夹点菜单访问多功能夹点选项。
* GRIPOBJLIMIT
选择集包括的对象多于指定数量时，不显示夹点。
类型:	整数
保存位置:	注册表
初始值:	100
有效取值范围为 0 到 32,767。例如，设定为 1 时，如果选择了多个对象，则会消除夹点。设定为 0 时，始终显示夹点。

注意:当 GRIPBLOCK 设定为 1 且超出选定对象的数量时，块将仅显示其插入点夹点，而不是块中每个对象的所有夹点。

* GRIPS
控制夹点在选定对象上的显示。
类型:	整数
保存位置:	注册表
初始值:	2
值 | 说明
0 | 隐藏夹点
1 | 显示夹点
2 | 在多段线线段上显示其他中点夹点

捕捉夹点时，要调整夹点大小和光标的有效选择区域，请使用 GRIPSIZE 系统变量。
* GRIPSIZE
设置夹点框的尺寸（以设备独立像素为单位）。

类型:	整数
保存位置:	注册表
初始值:	5
有效取值范围为 1 到 255。
* GRIPSUBOBJMODE
控制在选定子对象时是否自动使夹点成为活动夹点。
类型:	位码
保存位置:	注册表
初始值:	1
当夹点处于选定状态时，它们将更改颜色并成为活动夹点，这意味着它们可用于修改关联的对象或子对象。可以使用下列值之和将该设置存储为一个位码：

值 | 说明
0 | 在选定子对象时，夹点不会成为活动夹点。
1 | 在选定子对象时，以下点将处于活动状态：用于块的属性的夹点和用于面、边、顶点的夹点以及实体、网格或 NURBS 曲面的控制点。
2 | 在选定这些子对象时，多段线线段的夹点将成为活动夹点。

将此系统变量设定为 1 对于快速成组修改网格对象上的面、边和顶点特别有用。
* GRIPTIPS
控制当光标悬停在支持夹点提示的动态块和自定义对象的夹点上时，夹点提示的显示.

类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 关闭夹点提示的显示
1 | 打开夹点提示的显示
* GROUPDISPLAYMODE
控制在组选择打开并且选定组中的对象时如何显示夹点。

类型:	整数
保存位置:	注册表
初始值:	2

值 | 说明
0 | 显示选定组中所有对象上的夹点
1 | 显示位于编组对象的中心处的单个夹点
2 | 在分组对象周围显示边界框，并在中心位置显示单个夹点

默认情况下，选择组中的某个对象将导致选定属于该组的所有对象。组选择由 PICKFIRST 系统变量控制。

* GTAUTO
控制在具有三维视觉样式的视口中启动命令之前选择对象时，是否自动显示三维小控件。
类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 在启动命令之前选择对象时，小控件不会自动显示。
1 | 小控件在创建选择集后自动显示。

此系统变量会影响三维移动小控件、三维旋转小控件和三维缩放小控件的显示。小控件之前称为“夹点工具”。

* GTDEFAULT
控制在具有三维视觉样式的视口中启动 MOVE、ROTATE 或 SCALE 命令时，是自动启动三维移动操作、三维旋转操作还是三维缩放操作。
类型:	整数
保存位置:	注册表
初始值:	0
值 | 说明
0 | 在三维视图中启动 MOVE、ROTATE 或 SCALE 命令后，不会自动启动 3DMOVE、3DROTATE 或 3DSCALE 命令。
1 | 在三维视图中启动 MOVE、ROTATE 或 SCALE 命令后自动启动 3DMOVE、3DROTATE 或 3DSCALE 命令。

* GTLOCATION
控制在具有三维视觉样式的视口中启动命令之前选择对象时，三维移动小控件、三维旋转小控件或三维缩放小控件的初始位置。

类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 将三维移动小控件、三维旋转小控件或三维缩放小控件置于 UCS 图标的相同位置。小控件的方向与当前 UCS 对齐。
1 | 将三维移动小控件、三维旋转小控件或三维缩放小控件置于选择集的几何中心。

此系统变量会影响三维移动小控件、三维旋转小控件和三维缩放小控件的显示。小控件之前称为“夹点工具”。

* HALOGAP
指定一个对象被另一个对象遮挡时显示的间隙。

类型:	整数
保存位置:	图形
初始值:	0
按照一英寸的百分比指定该值，并且它不受缩放级别的影响。

在基于 AutoCAD 的产品中，HALOGAP 仅在二维视图中可用。在三维视图中，将使用 VSHALOGAP 系统变量。

在 AutoCAD LT 中，使用 HIDE 或 SHADEMODE 的“隐藏”选项时，晕圈线将在其隐藏的点处缩短。也可以在“隐藏线设置”对话框的“光晕间隔百分比”区域设置光晕间隔。
* HANDLES
报告应用程序是否可以访问对象句柄。
（只读）
类型:	整数
保存位置:	图形
初始值:	1
因为句柄不能再被关闭，所以此系统变量只用于保持脚本的完整性，没有其他影响。
* HELPPREFIX
设定帮助系统的文件路径。

类型:	字符串
保存位置:	注册表
初始值:	不确定
此系统变量决定“选项”对话框 “文件”选项卡 “帮助和其他文件名”选项 “帮助位置”选项中的默认设置。

* HIDETEXT
指定执行 HIDE 命令时是否处理由 TEXT 或 MTEXT 命令创建的文字对象。

类型:	参数
保存位置:	图形
初始值:	1
值 | 说明
0 | 不隐藏文字和其他对象
1 | 隐藏文字但不隐藏其他对象

在 AutoCAD LT 中，也可以在“隐藏线设置”对话框中设置 HIDETEXT。
* HIGHLIGHT
控制对象的亮显；不影响使用夹点选定的对象。
类型:	整数
保存位置:	未保存
初始值:	1
值 | 说明
0 | 关闭选定对象亮显
1 | 打开选定对象亮显
* HPANG
在此会话中设置新填充图案的默认角度。
类型:	实数
保存位置:	未保存
初始值:	0.0000
* HPANNOTATIVE
控制新填充图案在此会话中是否为注释性。

类型:	整数
保存位置:	未保存
初始值:	0
值 | 说明
0 | 非注释性
1 | 注释性
* HPASSOC
控制图案填充和填充是否为注释性。

类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 图案填充和填充未与其定义边界对象关联
1 | 图案填充和填充与其定义边界对象关联，并且会随边界对象的更改而更新

* HPBACKGROUNDCOLOR
为当前图形中的新填充图案设置默认背景颜色。
类型:	字符串
保存位置:	图形
初始值:	无
有效值包括：

“无”或“.”适用于无背景色
AutoCAD 颜色索引 (ACI)：介于 1 和 255 之间的整数值，或前七种颜色中的一种颜色名称
真彩色：介于 000 和 255 之间的 RGB 或 HSL 值，格式为“RGB:130,200,240”
配色系统：标准配色系统、导向或设定的文字，例如“DIC COLOR GUIDE(R)$DIC 43”
注意:图形中的每个图案填充对象都可以具有不同的背景色。
* HPBOUND
控制此会话中由 HATCH 和 BOUNDARY 创建的对象类型。

类型:	整数
保存位置:	未保存
初始值:	1
值 | 说明
0 | 创建面域
1 | 创建多段线

仅当 HPBOUNDRETAIN 系统变量处于打开状态时，才会创建多段线或面域对象。
* HPBOUNDRETAIN
控制是否在此会话中为新图案填充和填充创建边界对象。
类型:	整数
保存位置:	未保存
初始值:	0
值 | 说明
0 | 不创建边界对象
1 | 根据 HPBOUND 系统变量创建边界对象

* HPCOLOR
设置当前图形中新图案填充的默认颜色。

类型:	字符串
保存位置:	图形
初始值:	使用当前值
有效值包括：

"." 用于使用 CECOLOR 系统变量中的当前颜色集
ByLayer 或 ByBlock
AutoCAD 颜色索引 (ACI)：介于 1 和 255 之间的整数值，或前七种颜色中的一种颜色名称
真彩色：介于 000 和 255 之间的 RGB 或 HSL 值，格式为“RGB:130,200,240”
配色系统：标准配色系统、导向或设定的文字，例如“DIC COLOR GUIDE(R)$DIC 43”
除“.”以外的值以外的值替代当前颜色值 (CECOLOR)。
* HPDLGMODE
控制“图案填充和渐变色”对话框以及“图案填充编辑”对话框的显示。
类型:	整数
保存位置:	用户设置
初始值:	2
值 | 说明
0 | 除非在命令提示下输入设置，否则不针对 HATCH 和 GRADIENT 显示“图案填充和渐变色”对话框。
1 | 针对 HATCH 和 GRADIENT 显示“图案填充和渐变色”对话框。
2 | 当功能区处于活动状态 (RIBBONSTATE = 1) 时，不针对 HATCH 和 GRADIENT 显示“图案填充和渐变色”对话框。当功能区处于不活动状态 (RIBBONSTATE = 0) 时，显示“图案填充和渐变色”对话框。

* HPDOUBLE
控制此会话中是否为用户定义的图案翻倍填充图案。
类型:	整数
保存位置:	未保存
初始值:	0
双向将指定与原始直线成 90 度角绘制的第二组直线。

值 | 说明
0 | 关闭双向填充图案
1 | 打开双向填充图案
* HPDRAWORDER
控制此会话中新图案填充和填充的默认绘制顺序。
类型:	整数
保存位置:	未保存
初始值:	3
控制图案填充和填充对象是显示在所有其他对象之前还是之后，或者显示在其关联边界之前还是之后。

值 | 说明
0 | 无。未为图案填充或填充指定绘图次序。
1 | 后置。将图案填充或填充置于其他对象之后。
2 | 前置。将图案填充或填充置于其他对象之前。
3 | 置于边界之后。将图案填充或填充置于图案填充的边界对象之后。
4 | 置于边界之前。将图案填充或填充置于图案填充的边界对象之前。

* HPGAPTOL
指定一组对象（几乎封闭一个仍视为闭合的图案填充边界的区域）之间的最大间隙。

类型:	实数
保存位置:	注册表
初始值:	0.0000
默认值为 0，指定对象封闭了该区域并没有间隙。按图形单位输入一个值（从 0 到 5000），以设置将对象用作图案填充边界时可以忽略的最大间隙。
* HPINHERIT
控制在当前图形中使用 HATCH 和 HATCHEDIT 中的“继承特性”选项时是否继承图案填充原点。

类型:	整数
保存位置:	图形
初始值:	0
值 | 说明
0 | 图案填充原点取自 HPORIGIN
1 | 图案填充原点取自源图案填充对象

* HPISLANDDETECTION
*在此会话中控制如何处理新图案填充边界中的孤岛。
类型:	整数
保存位置:	未保存
初始值:	1
值 | 说明
0 | 普通。填充孤岛内的孤岛。
1 | 外部。仅填充孤岛外部的区域。
2 | 忽略。填充边界内的所有对象。

孤岛是要填充的区域中的封闭区域。
* HPISLANDDETECTIONMODE
控制是否在此会话中检测新图案填充和填充内的孤岛。

类型:	整数
保存位置:	未保存
初始值:	1
值 | 说明
0 | 关闭。
1 | 打开（建议）。根据 HPISLANDDETECTION 填充或忽略孤岛。

* HPLAYER
指定当前图形中新图案填充和填充的默认图层。

类型:	字符串
保存位置:	图形
初始值:	使用当前值
此控件可从“图案填充编辑器”上下文选项卡的“特性”下拉面板中访问。

除“.”以外的值（使用当前）值替代当前图层值（CLAYER 系统变量）。 可以将当前不存在的图层指定为新图案填充和填充的默认图层。
* HPLINETYPE
控制非连续性线型在填充图案中的显示方式。
类型:	参数
保存位置:	注册表
初始值:	0
在基于 AutoCAD 2015 的产品中为图案填充添加了性能和内存增强功能。使用非连续性线型的填充图案不会从这些增强功能中受益。建议您选择使用非连续性线型定义的预定义填充图案，而不是将非连续性线型指定给填充图案。

值 | 说明
0 | 在预定义和自定义的填充图案中显示连续性线型，不考虑指定的线型。
1 | 在填充图案中显示非连续性线型（传统行为）

注意:使用 REGEN 命令更新现有填充图案的线型显示。
* HPMAXAREAS
设置单个图案填充对象可以拥有且仍可以在缩放操作过程中自动切换实体和图案填充的“封闭区域”的最大数量。
类型:	整数
保存位置:	注册表
初始值:	100
有效值为 0 到 10,000,000。

当设置为值 0 时，图案填充在执行缩放操作时会以其指定的图案显示。这样可以获得最佳视觉保真度，但可能会影响缩放操作的性能。图案填充按预期打印和发布。

注意:关联阵列和块中图案填充的显示不受此系统变量的影响。
* HPMAXLINES
设置在图案填充操作中生成的图案填充线的最大数目。
类型:	整数
保存位置:	注册表
初始值:	100000
有效值为 100 到 10,000,000。
* HPNAME
在此会话中设置默认的填充图案名称。

类型:	字符串
保存位置:	未保存
初始值:	ANSI31（英制）或 ANGLE（公制）
有效名称最多可以包含 34 个字符，不含空格。值 "" 指示没有默认值。输入句点 (.)将 HPNAME 重置为默认值。

* HPOBJWARNING
设定可以选择的图案填充边界对象的数量（超过此数量将显示警告消息）。

类型:	整数
保存位置:	注册表
初始值:	10000
最大值可以更改，但是要明显大于 100000000（一亿）。
* HPORIGIN
在当前图形中相对于当前用户坐标系为新填充图案设置图案填充原点。
类型:	二维点
保存位置:	图形
初始值:	0.0000,0.0000
* HPORIGINMODE
控制默认图案填充原点的确定方式。

类型:	整数
保存位置:	注册表
初始值:	0
值 | 说明
0 | 使用 HPORIGIN
1 | 使用图案填充边界矩形范围的左下角
2 | 使用图案填充边界矩形范围的右下角
3 | 使用图案填充边界矩形范围的右上角
4 | 使用图案填充边界矩形范围的左上角
5 | 使用图案填充边界矩形范围的中心

* HPPICKMODE
控制用于指定图案填充区域的默认方法是在封闭位置中单击，还是选择边界对象。
（只读）
类型:	整数
保存位置:	注册表
初始值:	0
值 | 说明
0 | 单击封闭区域内的位置
1 | 选择边界对象

注意:启动 HATCH 命令后，默认方法将设置在功能区上的“边界”面板的“图案填充”上下文选项卡上，从中可以选择“拾取点”选项或“选择”选项。
* HPQUICKPREVIEW
控制在指定填充区域时是否显示填充图案的预览。
类型:	参数
保存位置:	用户设置
初始值:	1
值 | 说明
0 | 无预览
1 | 快速预览
* HPQUICKPREVTIMEOUT
设置预览在自动取消之前生成填充图案预览的最长时间。

类型:	整数
保存位置:	注册表
初始值:	2
如果达到指定的持续时间而且预览尚未完成，预览将取消，但命令保持为活动状态。

持续时间以秒计算。有效值范围为从 1 到 300。

注意:HPQUICKPREVIEW 系统变量控制当使用 HATCH 命令时是否生成预览。
* HPSCALE
在此会话中设置新填充图案的默认缩放因子。
类型:	实数
保存位置:	未保存
初始值:	1.0000
* HPSEPARATE
控制在几个闭合边界上进行操作时，是创建单个图案填充对象，还是创建独立的图案填充对象。

类型:	整数
保存位置:	注册表
初始值:	0
值 | 说明
0 | 创建单个图案填充对象
1 | 分别创建各个图案填充对象

* HPSPACE
在此会话中为用户定义的新填充图案设置默认行距。
类型:	实数
保存位置:	未保存
初始值:	1.0000
* HPTRANSPARENCY
为当前图形中的新图案填充和填充设置默认透明度。

类型:	字符串
保存位置:	图形
初始值:	使用当前值
有效值包括“使用当前值”（或“.”）、“ByLayer”、“ByBlock”以及介于 0（零）和 90 之间的整数值。值越大，图案填充越透明。

除“使用当前值”或“.”以外值替代当前透明度值（CETRANSPARENCY 系统变量）。

更改此值并不影响现有的图案填充对象。
* HYPERLINKBASE
指定图形中用于所有相对超链接的路径。
类型:	字符串
保存位置:	图形
初始值:	""
如果未指定值，图形路径将用于所有相对超链接。

* IBLENVIRONMENT
启用基于图像的照明并指定当前图像贴图。

类型:	整数
保存位置:	图形
初始值:	0
大于 0 的值将启用基于图像的照明并指定应该在渲染时应用于环境的图像贴图。

0 或负值指示禁用基于图像的照明。如果指定为负值，则将保留当前的图像贴图，但不会由渲染器使用。例如，值 -3 指示广场图像贴图已置为当前，而且基于图像的照明处于禁用状态。

支持的有效值范围为 -11 到 11。

下表列出了用于将特定图像贴图设置为当前贴图的可输入值。

值 | 说明
1 | 陨石坑
2 | 干涸的湖床
3 | 广场
4 | 雪地
5 | 村庄
6 | 锐化高光
7 | 边缘高光
8 | 栅格光源
9 | 冷光
10 | 暖光
11 | 柔光
* IMAGEFRAME
控制是否显示和打印图像和贴图图像边框。
类型:	整数
保存位置:	图形
初始值:	1
FRAME 系统变量将替代 DWFFRAME 设置。在 FRAME 系统变量后使用 IMAGEFRAME 系统变量以重置图像边框设置。

值 | 说明
0 | 不显示也不打印图像边框。在选择集预览或对象选择期间，将暂时重新显示该边框。
1 | 显示并打印图像边框。
2 | 显示但不打印图像边框。
* IMAGEHLT
控制是亮显整个光栅图像还是仅亮显光栅图像边框。
类型:	整数
保存位置:	注册表
初始值:	0
值 | 说明
0 | 仅亮显光栅图像边框
1 | 亮显整个光栅图像
* IMPLIEDFACE
控制隐含面的检测。

类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 无法检测隐含面。
1 | 可以检测隐含面。

隐含面是一个可通过与三维实体对象上的面相交或重叠来创建边界的闭合区域。
此变量会影响按 Ctrl+Shift+E 组合键并拖动边界内部的区域以动态创建拉伸时使用隐含面的功能。

要选择或修改隐含面，该变量必须设置为 1。
* INDEXCTL
控制是否创建图层和空间索引并将其保存到图形文件中。

类型:	整数
保存位置:	图形
初始值:	0
为了最大限度地发挥按需加载的优势，请将用作外部参照的图形与图层索引和空间索引一起保存。

值 | 说明
0 | 不创建索引
1 | 创建图层索引
2 | 创建空间索引
3 | 创建图层和空间索引
* INETLOCATION
存储 BROWSER 命令和“浏览 Web”对话框所使用的 Internet 网址。
类型:	字符串
保存位置:	注册表
初始值:	https://www.autodesk.com/autocad (AutoCAD), https://www.autodesk.com/acltuser (AutoCAD LT)

* INPUTHISTORYMODE
控制用户输入历史记录的内容和位置。

类型:	位码
保存位置:	注册表
初始值:	15
系统将使用下列位码值之和将该设置存储为一个位码：

值 | 说明
0 | 不显示最近的输入历史记录。
1 | 在命令行或动态提示工具提示中显示最近的输入历史纪录。在命令提示或在输入提示下使用向上箭头键和向下箭头键键访问。
2 | 在“最近的输入”下的快捷菜单中显示当前 命令的最近输入历史记录。
4 | 在“最近的输入”下的快捷菜单中显示当前任务中所有命令的最近输入历史记录。
8 | 显示最近输入点位置的标记。在命令提示下使用箭头键指定点的位置。

* INPUTSEARCHDELAY
设置显示命令行建议列表之前要延迟的毫秒数。

类型:	整数
保存位置:	注册表
初始值:	300
输入 100 到 10,000 毫秒之间的值。
* INSBASE
存储 BASE 命令设置的插入基点，用当前空间的 UCS 坐标表示。
类型:	三维点
保存位置:	图形
初始值:	0.0000,0.0000,0.0000
* INSNAME
为 INSERT 命令设置默认块名。
类型:	字符串
保存位置:	未保存
初始值:	""
此名称必须符合符号命名约定。如果没有设置默认值，将返回 ""。输入句点 (.)将设定为无默认值。

* INSUNITS
指定插入或附着到图形时，块、图像或外部参照进行自动缩放所使用的图形单位值。

类型:	整数
保存位置:	图形
初始值:	1（英制）或 4（公制）
注意:将注释性块插入图形时将忽略 INSUNITS 设置。
值 | 说明
0 | 不指定（无单位）
1 | 英寸
2 | 英尺
3 | 英里
4 | 毫米
5 | 厘米
6 | 米
7 | 千米
8 | 微英寸
9 | 英里
10 | 码
11 | 埃
12 | 毫微米
13 | 微米
14 | 分米
15 | 十米
16 | 百米
17 | 百万公里
18 | 天文单位
19 | 光年
20 | 秒差距
21 | 美制测量英尺

注意:美制测量英尺是一个历史测量单位，大约大于国际英尺单位 2 百万分率。在美国，此差异只有在按比例用于映射时才比较明显。从基于 AutoCAD 2017 的产品开始，美制测量英尺设置仅支持用于插入或附着图形。使用早期版本打开的图形会将美制测量英尺设置视为“无单位”。
* INSUNITSDEFSOURCE
当 INSUNITS 设定为 0 时，设置源内容单位值。
当 INSUNITS 设定为 0 时，设置源内容单位值。

类型:	整数
保存位置:	注册表
初始值:	1
有效取值范围为 0 到 20。
* INSUNITSDEFTARGET
当 INSUNITS 设定为 0 时，设置目标图形单位值。

类型:	整数
保存位置:	注册表
初始值:	1
有效取值范围为 0 到 20。
* INTELLIGENTUPDATE
控制图形的刷新率。

类型:	整数
保存位置:	注册表
初始值:	20
默认值为 20 帧每秒。如果遇到与图形生成或定时相关的问题，可将此变量为 0 以关闭此变量。INTELLIGENTUPDATE 的工作方式为禁止图形更新，直到计时器到期为止。随后发生的更新将重置计时器。

性能的改善将会显著地影响脚本和 AutoLISP 图形的更新。那些常规的 AutoCAD 命令操作在性能上没有显著的差异。

* INTERFERECOLOR
为干涉对象设置颜色。
类型:	字符串
保存位置:	图形
初始值:	1
有效值包括“BYLAYER”、“BYBLOCK”、颜色名称以及 0 到 255 之间的整数。

真彩色的有效值是一个前面带有 RGB 的整数字符串，每个整数（0 到 255）之间用逗号分隔。真彩色设置的输入如下：

RGB:000,000,000

如果已安装配色系统，则可以指定系统中定义的任意颜色。
* INTERFEREOBJVS
为干涉对象设置视觉样式。

类型:	字符串
保存位置:	图形
初始值:	真实
INTERFEREOBJVS 只能设定为保存在图形中的视觉样式。

无法通过 PURGE 命令删除为 INTERFEREOBJVS 指定的视觉样式。
* INTERFEREVPVS
指定检查干涉时视口的视觉样式。

类型:	字符串
保存位置:	图形
初始值:	线框
INTERFEREVPVS 只能设定为保存在图形中的视觉样式。

无法通过 PURGE 命令删除为 INTERFEREVPVS 指定的视觉样式。
* INTERSECTIONCOLOR
控制视觉样式设定为“二维线框”时三维曲面交线处的多段线的颜色。
类型:	整数
保存位置:	图形
初始值:	257
值 0 指定“ByBlock”，值 256 指定“ByLayer”，值 257 指定“ByEntity”。1 到 255 之间的值可指定 AutoCAD 颜色索引 (ACI) 颜色。还可以指定真彩色和配色系统颜色。

仅当 INTERSECTIONDISPLAY 处于打开状态且使用 HIDE 命令时，INTERSECTIONCOLOR 设置才可见。

* INTERSECTIONDISPLAY
用于控制当视觉样式设置为“二维线框”以及执行 HIDE 时三维实体和曲面相交处的显示。

类型:	参数
保存位置:	图形
初始值:	0
值 | 说明
0 | 不显示相交边
1 | 显示相交边

注意:VSINTERSECTIONEDGES 用于控制所有其他视觉样式的三维实体和曲面相交处的显示。
* ISAVEBAK
控制保存图形文件时是否创建 BAK 文件。
类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 不创建 BAK 文件
1 | 创建 BAK 文件
* ISAVEPERCENT
控制在 DWG 文件中分配的用于增量保存的空间量，这会影响在要求完全保之前可以执行的快速保存操作数。
类型:	整数
保存位置:	注册表
初始值:	50
当文件保存估计数超过指定的百分比时，下一次将进行完全保存。有效值的范围为 0 到 100%。

值为 0 意味着所有保存操作都是完全保存。完全保存将优化 DWG 文件的大小，但会显著降低处理大型图形的速度。
值为 100 将增加可用空间，以附加最大可能的更改。此值会导致完全保存之间最大数量的增量快速保存操作，但文件大小较大。
注意:要优化速度，自动保存将递增，并用值 90 临时替代 ISAVEPERCENT 的值。当更改数目超过 ISAVEPERCENT 设置时，将执行完全保存。保存为其他格式时，将始终执行完全保存。
* ISOLINES
指定显示在三维实体的曲面上的等高线数量。

类型:	整数
保存位置:	图形
初始值:	4
有效设置的范围为 0 到 2047。

* LARGEOBJECTSUPPORT
控制打开和保存图形时大型对象的大小限制。
类型:	整数
保存位置:	注册表
初始值:	0
如果使用特大型对象，此限制是相关的，并且需要将图形保存为早期的格式。

值 | 说明
0 | 使用基于 AutoCAD 2009 的产品和早期版本的传统对象大小限制：对于图形中的任意单个对象，未压缩的大小限制为 256 MB
1 | 使用基于 AutoCAD 2010 的对象大小限制：对于图形中的任意单个对象，未压缩的大小限制为 4 GB

* LASTANGLE
存储相对于当前 UCS 的 XY 平面输入的最后一个圆弧、直线或多段线的端点切向的角度。
（只读）
类型:	实数
保存位置:	未保存
初始值:	0.0000
* LASTPOINT
存储指定的最后一点，用当前空间的 UCS 坐标表示。

类型:	三维点
保存位置:	未保存
初始值:	0.0000,0.0000,0.0000
可以通过在点提示下输入 @ 符号来参照指定的最后一个点。这等效于输入 @0,0,0。
* LASTPROMPT
存储回显到命令提示的上一个字符串。
（只读）
类型:	字符串
保存位置:	未保存
初始值:	""
此字符串与在命令提示下看到的最后一行相同，包含所有用户输入。
* LATITUDE
指定地理标记的纬度。
类型:	实数
保存位置:	图形
初始值:	37.7950
如果没有将任何地理位置指定给图形文件，则默认值是加利福尼亚旧金山的纬度。有效取值范围为 -90 到 +90。正值表示北纬。

此值受 LUPREC 系统变量设置的影响。

该值不受 GEOLATLONGFORMAT 系统变量的影响。它总是使用十进制度数格式。
* LAYERDLGMODE
控制打开传统还是当前图层特性管理器。
类型:	整数
保存位置:	注册表
初始值:	1
LAYER 命令可以使用 CLASSICLAYER 或 LAYERPALETTE 命令。

值 | 说明
0 | LAYER 命令使用传统模式图层特性管理器。必须先关闭它才能继续工作。
1 | LAYER 命令将使用当前的无模式图层特性管理器。它在您工作时仍可保持打开状态。

* LAYEREVAL
指定将新图层添加至图形或附着的外部参照时是否计算新图层的图层列表。
类型:	整数
保存位置:	图形
初始值:	0
将使用以下值之一将该设置存储为一个整数：

值 | 说明
0 | 关闭
1 | 检测何时将新外部参照图层添加到图形中
2 | 检测何时将新图层添加到图形和外部参照中

注意:如果 LAYEREVALCTL 系统变量设置为 0（零），将忽略 LAYEREVAL 和 LAYERNOTIFY 的设置。

* LAYEREVALCTL
控制图层特性管理器中针对新图层计算的“未协调的新图层”过滤器列表。
类型:	整数
保存位置:	用户设置
初始值:	1
此系统变量还控制是否显示新图层通知。

值 | 说明
0 | 禁用新图层的计算和通知
1 | 使用 LAYEREVAL 的设置启用新图层的计算

注意:如果 LAYEREVALCTL 系统变量设置为 0（零），将忽略 LAYEREVAL 和 LAYERNOTIFY 的设置。

* LAYERFILTERALERT
删除多余的图层过滤器可提高性能。

类型:	整数
保存位置:	注册表
初始值:	2
图形有 100 个或更多的图层过滤器，并且图层过滤器的数目超过图层的数目时，可以使用 LAYERFILTERALERT 删除图层过滤器以提高性能。

值 | 说明
0 | 关闭
1 | 打开图层管理器时，将删除所有图层过滤器；并且不显示信息
2 | 打开图层管理器时，将显示信息指示出现问题，建议删除所有过滤器，并提供选择：“是否要立即删除所有图层过滤器？”
3 | 打开图形后，将显示信息，用以说明出现问题，并显示一个对话框，从中可以选择要删除的过滤器

* LAYERMANAGERSTATE
指示图层特性管理器处于打开状态还是关闭状态。
（只读）
类型:	整数
保存位置:	未保存
初始值:	不确定
值 | 说明
0 | 关闭
1 | 打开
* LAYERNOTIFY
指定如果找到未协调的新图层，何时显示警告。
类型:	位码
保存位置:	图形
初始值:	0
值 | 说明
0 | 关闭
1 | 打印
2 | 打开
4 | 为外部参照加载/重载/附着
8 | 恢复图层状态
16 | 保存
32 |插入

注意:如果 LAYEREVALCTL 系统变量设置为 0（零），将忽略 LAYEREVAL 和 LAYERNOTIFY 的设置。

* LAYEROVERRIDEHIGHLIGHT
针对具有替代的图层切换背景色亮显的可见性。

类型:	整数
保存位置:	注册表
初始值:	0
值 | 说明
0 | 针对具有替代的图层禁用背景色亮显。
1 | 针对具有替代的图层启用背景色亮显。

* LAYLOCKFADECTL
控制锁定图层上对象的淡入程度。
类型:	整数
保存位置:	注册表
初始值:	50

淡入锁定图层上的对象以将其与未锁定图层上的对象进行对比，并降低图形的视觉复杂程度。锁定图层上的对象仍对参照和对象捕捉可见。

控制锁定图层上对象淡入度的范围为从 -90 到 90。

值 | 说明
0 | 锁定图层不淡入
>0 | 当该值为正时，将淡入度的百分比控制到最高淡入 90%
<0 | 当该值为负时，不淡入锁定图层，但是将保存该值，以通过更改符号切换至该值

注意: 将淡入度值限制到 90%，以免与关闭或冻结的图层混淆。
* LAYOUTCREATEVIEWPORT
控制是否在添加到图形的每个新布局中自动创建视口。
类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 新创建的布局不包含任何视口
1 | 使用每个新布局创建单一布局视口
* LAYOUTREGENCTL
指定“模型”选项卡和布局选项卡中的显示列表的更新方式。
类型:	整数
保存位置:	注册表
初始值:	2
对于每个选项卡，更新显示列表的方法可以是切换到该选项卡时重生成图形，也可以是切换到该选项卡时将显示列表保存到内存并只重生成修改的对象。修改 LAYOUTREGENCTL 设置可以提高性能。

值 | 说明
0 | 每次切换选项卡都会重生成图形。
1 | 当在当前“模型”选项卡和上一个布局选项卡之间切换时，显示列表将被保存到内存中并禁止对它们进行重生成。对于所有其他的布局选项卡，切换到它们时仍然进行重生成。
2 | 第一次切换选项卡时会重生成图形。对于绘图任务中的其余选项卡，显示列表保存到内存，切换到这些选项卡时禁止重生成。

修改 LAYOUTREGENCTL 设置得到的性能取决于若干个因素，包括图形大小和类型、包含在图形中的对象、可用内存容量以及其他打开的图形或应用程序的影响。LAYOUTREGENCTL 设定为 1 或 2 时，所使用的额外内存量为“模型”选项卡的显示列表的大小乘以为之保存显示列表的每个布局中的视口数目。

当 LAYOUTREGENCTL 设定为 1 或 2，性能总体变慢时，或者在显示列表为之保存的选项卡之间进行切换时，可以考虑设置为 0 或 1 以寻求工作环境的最优平衡。有关性能设置的其他信息，请参见“系统”选项卡（位于“选项”对话框中）。

不论 LAYOUTREGENCTL 设置为何值，如果重新定义块或放弃选项卡切换，在第一次切换到任意包含保存视口的选项卡时重生成图形。
* LAYOUTTAB
切换“模型”和“布局”选项卡的可见性。
类型:	整数
保存位置:	注册表
初始值:	1

值 | 说明
0 | 将隐藏“模型”和“布局”选项卡。
1 | 将显示“模型”和“布局”选项卡。
* LEGACYCODESEARCH
控制搜索可执行文件是否包括启动程序所在的文件夹。

类型:	整数
保存位置:	注册表
初始值:	0，可能已由 CAD 管理员锁定
禁用后，此系统变量可防止常见漏洞，即从 AutoLISP 产生的漏洞以及从“起始”文件夹和图形文件夹（通过桌面快捷方式图标在会话开始时设置或通过双击文件）自动加载的其他可执行文件产生的漏洞。

值 | 说明
0 | 在搜索可执行文件时忽略“起始”文件夹和图形文件夹。
1 | 在搜索可执行文件时包括“起始”文件夹和图形文件夹。此选项将保留传统行为，但不建议使用。

注意:此设置不影响手动加载可执行文件。您仍然可以指定“起始”文件夹或图形文件夹的完整路径，并且可执行文件将会加载。

* LEGACYCTRLPICK
指定用于循环选择和子对象选择的 Ctrl 键的行为。
类型:	整数
保存位置:	注册表
初始值:	2
值 | 说明
0 | Ctrl+单击用于选择三维实体、曲面和网格上的子对象（面、边和顶点）。
1 | Ctrl + 单击的操作用于在重叠对象之间循环。禁止使用 Ctrl+单击来选择三维实体、曲面和网格上的子对象。
2 | 在 SUBOBJSELECTIONMODE 设为 0（零）时，Ctrl+单击用于选择三维实体、曲面和网格上的子对象（面、边和顶点）。如果 SUBOBJSELECTIONMODE 设为 1、2、3、4 或 5，则无需按住 Ctrl 键也可选择子对象。如果在 SUBOBJSELECTIONMODE 设为 1、2、3、4 或 5 时按住 Ctrl 键，则在释放 Ctrl 键之前，子对象筛选器都将处于关闭状态。
* LENSLENGTH
存储透视视图中使用的焦距（以毫米为单位）。

类型:	实数
保存位置:	图形
初始值:	50.0000
* LIGHTGLYPHDISPLAY
打开和关闭光线轮廓的显示。
类型:	整数
保存位置:	图形
初始值:	1

光线轮廓是点光源、聚光灯和光域灯光的符号表示。

该系统变量处于关闭状态时，不显示图形中代表光线的轮廓。

值 | 说明
0 | 关闭
1 | 打开
* LIGHTINGUNITS
指定图形的光源单位。
类型:	整数
保存位置:	图形
初始值:	2
值 | 说明
0 | 从基于 AutoCAD 2017 的产品开始，其不再为有效设置。注意:建议将旧图形更新为 1 或 2。
1 | 使用美制光源单位（呎烛光），并启用光度控制光源
2 | 使用国际光源单位（勒克斯），并启用光度控制光源

注意:将 LIGHTINGUNITS 设置为 0（零）的脚本必须进行更改，否则从基于 AutoCAD 2017 的产品开始它们将不再有效。

* LIGHTLISTSTATE
指示“模型中的光源”选项板处于打开还是关闭状态。
（只读）
类型:	整数
保存位置:	未保存
初始值:	0
值 | 说明
0 | 关闭
1 | 打开
* LIGHTSINBLOCKS
控制渲染时是否使用块中包含的光源。

类型:	整数
保存位置:	图形
初始值:	1
此系统变量关闭时，块中的光源不影响当前视口中三维对象的渲染。

值 | 说明
0 | 关闭块中的光源
1 | 打开块中的光源
* LIMCHECK
控制是否可以在栅格界限外创建对象。
类型:	整数
保存位置:	图形
初始值:	0
值 | 说明
0 | 可以在栅格界限外创建对象
1 | 不可以在栅格界限外创建对象

* LIMMAX
存储当前空间的右上方栅格界限，用世界坐标系坐标表示。

类型:	二维点
保存位置:	图形
初始值:	12.0000,9.0000（英制）或 420.0000,297.0000（公制）
如果激活了图纸空间而且显示了图纸背景或可打印区域，则 LIMMAX 是只读的。
* LIMMIN
存储当前空间的左下角的栅格界限，用世界坐标系坐标表示。

类型:	二维点
保存位置:	图形
初始值:	0.0000,0.0000
如果激活了图纸空间而且显示了图纸背景或可打印区域，则 LIMMIN 是只读的。
* LINEFADING
控制当硬件加速处于启用状态且您已超出线密度限制时，是否淡入线显示。

类型:	参数
保存位置:	注册表
初始值:	1
缩放会增加内存使用量且性能会降低。例如，将视图缩得过小时，线可能会显得很模糊。若要在硬件加速处于启用的状态下改进性能，请在达到线密度限制时，将线设置为淡入。

值 | 说明
0 | 线不淡入
1 | 淡入线
* LINEFADINGLEVEL
启用硬件加速后，控制线淡入效果的强度。
类型:	整数
保存位置:	注册表
初始值:	2
值 | 说明
1 | 低
2 | 中
3 | 高

注意:此系统变量仅适用于 DirectX 11（或更高版本）虚拟设备。
* LINESMOOTHING
控制是否将反走样应用于二维线框视觉样式中的二维对象。
类型:	参数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 反走样处于禁用状态
1 | 反走样处于启用状态

注意:“二维显示”、“高级模式”、“详图”下的“图形性能”对话框（GRAPHICSCONFIG 命令）中提供有线平滑控件。

* LISPSYS
控制使用 VLISP 命令启动的默认 AutoLISP 开发环境和编辑器。

类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | Visual LISP IDE (VL IDE) 被设置为默认编辑器，AutoLISP 函数不完全支持 Unicode 字符。AutoLISP 源 (LSP) 文件在保存和编译时使用 ASCII (MBCS) 字符集。注意:此设置导致 AutoCAD 2020 和早期版本的行为，并且仅在 Windows 上受支持。
1 | Visual Studio (VS) Code 被设置为默认编辑器，AutoLISP 函数完全支持 Unicode 字符。AutoLISP 源 (LSP) 文件在保存时，使用在 VS Code 中设置的编码，在编译时，它们使用 Unicode 字符集。
2 | Visual Studio (VS) Code 被设置为默认编辑器，AutoLISP 函数完全支持 Unicode 字符。AutoLISP 源 (LSP) 文件在保存时，使用在 VS Code 中设置的编码，在编译时，它们使用 ASCII (MBCS) 字符集。

注意:更改 LISPSYS 系统变量的当前值后，必须重新启动 AutoCAD 才能切换 AutoLISP 开发环境。

* LOCALE
显示用于指示当前语言的代码。
（只读）
类型:	字符串
保存位置:	未保存
初始值:	因国家/地区而异
此代码显示为表示当前语言的两个或多个字母缩写形式，由使用 LOCALE_SISO639LANGNAME 常量的 Windows GetLocaleInfo 函数返回。

注意:在 AutoCAD 2019 系列产品之前，此代码显示为三个字母的缩写形式，由使用 LOCALE_SABBREVLANGNAME 常量的 Windows GetLocaleInfo 函数返回。三个字母的缩写形式基于两条信息；两个字母的语言缩写形式以及指示子语言的第三个字母。例如，ENU 表示英语语言 (EN) 和作为子语言的美国 (U) 的组合。
* LOCALROOTPREFIX
存储根文件夹的完整路径，该文件夹中安装了本地可自定义文件。
（只读）
类型:	字符串
保存位置:	注册表
初始值:	不确定
Template 和 Textures 文件夹位于此处，用户可以添加任何不希望在网络上漫游的自定义文件。有关可漫游文件的位置，请参见 ROAMABLEROOTPREFIX。
* LOCKUI
锁定工具栏、面板及可固定窗口（例如“设计中心”和“特性”选项板）的位置和大小。

类型:	位码
保存位置:	注册表
初始值:	0
单击状态栏中的锁定图标以控制是否锁定指定的用户界面元素。此操作将应用到通过箭头或快捷菜单选定的所有用户界面元素。

锁定的工具栏和窗口仍然可以打开和关闭。要临时将它们解锁，可按住 Ctrl 键。

系统将使用下列位码值之和将该设置存储为一个位码：

值 | 说明
0 | 不锁定工具栏、面板和窗口
1 | 锁定固定工具栏和面板
2 | 锁定固定或定位窗口
4 | 锁定浮动工具栏和面板
8 | 锁定浮动窗口
* LOFTANG1
设置在放样操作中通过第一个横截面的拔模斜度。
类型:	实数
保存位置:	图形
初始值:	90
0 方向从曲线平面上的曲线向外测量。正方向对着下一个横截面测量。有效值的范围从 0（零）到小于 360。

* LOFTANG2
设置在放样操作中通过最后一个横截面的拔模斜度。
类型:	实数
保存位置:	图形
初始值:	90
0 方向从曲线平面上的曲线向外测量。正方向对着上一个横截面测量。有效值的范围从 0（零）到小于 360。

* LOFTMAG1
设置在放样操作中通过第一个横截面的拔模斜度的幅值。

类型:	实数
保存位置:	图形
初始值:	0.0000
控制曲面开始朝向下一个横截面折弯的时间。
* LOFTMAG2
设置在放样操作中通过最后一个横截面的拔模斜度的幅值。

类型:	实数
保存位置:	图形
初始值:	0.0000
控制曲面开始朝向下一个横截面折弯的时间。
* LOFTNORMALS
控制放样对象通过横截面处的法线。
类型:	整数
保存位置:	图形
初始值:	1
指定路径或导向曲线时忽略该设置。

值 | 说明
0 | 直纹
1 | 平滑拟合
2 | 起点横截面
3 | 端点横截面
4 | 起点横截面和端点横截面
5 | 所有横截面
6 | 使用拔模斜度和幅值

* LOFTPARAM
控制放样实体和曲面的形状。

类型:	位码
保存位置:	图形
初始值:	7
系统将使用下列位码值之和将该设置存储为一个位码：

值 | 说明
1 | 无扭曲（最小化横截面之间的扭曲）
2 | 对齐方向（对齐每条横截面曲线的开始和结束方向）
4 | 简化（生成简单的实体和曲面，例如圆柱体或平面，而非样条曲线实体和样条曲线曲面）
8 | 闭合（闭合第一个和最后一个横截面之间的曲面或实体）
* LOGFILEMODE
指定是否将命令历史记录的内容写入日志文件。
类型:	整数
保存位置:	注册表
初始值:	0
值 | 说明
0 | 不维护日志文件
1 | 维护日志文件
* LOGFILENAME
指定当前图形的命令历史记录日志文件的路径和名称。
（只读）
类型:	字符串
保存位置:	图形
初始值:	不确定
初始值因当前图形的名称和安装文件夹而异。
* LOGFILEPATH
指定任务中所有图形的命令历史记录日志文件的路径。
类型:	字符串
保存位置:	注册表
初始值:	不确定
也可以使用 OPTIONS 命令指定路径。初始值由安装文件夹决定。
* LOGINNAME
显示当前用户的登录名，并随 DWG 文件和相关文件的文件特性统计信息一起保存。
（只读）
类型:	字符串
保存位置:	未保存
初始值:	不确定
* LONGITUDE
指定地理标记的经度。

类型:	实数
保存位置:	图形
初始值:	-122.3940
当图形文件不包含地理位置信息时，默认值是加利福尼亚旧金山的经度。有效取值范围为 -180 到 +180。正值表示东经。

此值受 LUPREC 系统变量设置的影响。

此值不受 GEOLATLONGFORMAT 系统变量设置的影响。它总是使用十进制度数格式。
* LTGAPSELECTION
控制是否可以在使用非连续性线型定义的对象上选择或捕捉到间隙。

类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 防止在间隙内选择或捕捉（传统行为）
1 | 允许在间隙内选择或捕捉

启用后，间隙将由对象捕捉标识，这使您即使在空白空间上选择时也能够捕捉到对象。

注意: 必须启用硬件加速和高质量几何图形才能使 LTGAPSELECTION 生效。
* LTSCALE
设定全局线型比例因子。

类型:	实数
保存位置:	图形
初始值:	1.0000
线型比例因子不能为零。该系统变量的名称与命令相同。使用 SETVAR 命令可访问此系统变量。
* LUNITS
设置用于创建对象的线性单位格式。

类型:	整数
保存位置:	图形
初始值:	2
值 | 说明
1 | 科学
2 | 小数
3 | 工程
4 | 建筑
5 | 分数

LUNITS 不会影响标注文字的单位格式，单位格式由 DIMLUNIT 系统变量控制且通常与标注样式一起保存。

* LUPREC
设定线性单位和坐标的显示精度。

类型:	整数
保存位置:	图形
初始值:	4
但是，无论显示精度如何设置，将始终保留距离、面积、体积的值以及线型坐标的内部精度。LUPREC 并不影响标注文字的显示精度，标注文字由 DIMDEC 系统变量控制而且通常与标注样式一起保存。

有效值为 0 到 8 之间的整数。
* LWDEFAULT
设置默认线宽值。

类型:	枚举
保存位置:	注册表
初始值:	25
可以以毫米的百分之一为单位将默认线宽设置为任一有效线宽，包括：0、5、9、13、15、18、20、25、30、35、40、50、53、60、70、80、90、100、106、120、140、158、200 和 211。

所有的值都必须以毫米的百分之一为单位输入。（乘上 2540 可以将值的单位从英寸转换为毫米的百分之一。）

* LWDISPLAY
控制是否显示对象的线宽。

类型:	参数
保存位置:	图形
初始值:	0
值 | 说明
0 | 不显示线宽
1 | 显示线宽
* LWUNITS
控制线宽单位是以英寸显示还是以毫米显示。

类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 英寸
1 | 毫米

* MATBROWSERSTATE
指示材质浏览器是处于打开还是关闭状态。
（只读）
类型:	整数
保存位置:	用户设置
初始值:	0
值 | 说明
0 | 关闭
1 | 打开
* MATEDITORSTATE
指示材质编辑器是处于打开状态还是关闭状态。
（只读）
类型:	整数
保存位置:	用户设置
初始值:	0
值 | 说明
0 | 关闭
1 | 打开
* MAXACTVP
设置布局中可同时激活的视口的最大数目。
类型:	整数
保存位置:	图形
初始值:	64
MAXACTVP 不影响打印视口的数目。
* MAXSORT
设置项目的最大数目，例如，在对话框、下拉列表和选项板中按字母顺序进行排序的文件名、图层名和块名称。

类型:	整数
保存位置:	注册表
初始值:	1000
如果项目（也称为命名对象）总数超出此值，则不会对任何项排序。

MAXSORT 的值为 0 到 32767 之间的整数。
* MAXTOUCHES
标识所连接数字化仪支持的触点数。
（只读）
类型:	整数
保存位置:	未保存
初始值:	0
* MBUTTONPAN
控制定点设备上的第三个按钮或滚轮的行为。

类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 支持自定义文件中定义的操作
1 | 当按住并拖动按钮或滑轮时，支持平移操作

* MEASUREINIT
控制从头创建的图形是使用英制还是使用公制默认设置。
类型:	整数
保存位置:	注册表
初始值:	因国家/地区而异
具体来说，MEASUREINIT 控制使用哪个填充图案和线型文件。启动程序时打开的 Drawing1.dwg 是从头创建的图形。

值 | 说明
0 | 英制；使用 ANSIHatch 和 ANSILinetype 注册表设置指定的填充图案文件和线型文件
1 | 公制；使用 ISOHatch 和 ISOLinetype 注册表设置指定的填充图案文件和线型文件

* MEASUREMENT
控制当前图形是使用英制还是公制填充图案和线型文件。

类型:	整数
保存位置:	图形
初始值:	0（英制）或 1（公制）
值 | 说明
0 | 英制；使用 ANSIHatch 和 ANSILinetype 注册表设置指定的填充图案文件和线型文件
1 | 公制；使用 ISOHatch 和 ISOLinetype 注册表设置指定的填充图案文件和线型文件

* MENUBAR
控制菜单栏的显示。

类型:	整数
保存位置:	注册表
初始值:	0
值 | 说明
0 | 隐藏菜单栏
1 | 显示菜单栏
* MENUECHO
设置菜单回显和提示控制位。

类型:	整数
保存位置:	未保存
初始值:	0
该值是下列位码值之和：

值 | 说明
1 | 禁止菜单项回显（菜单项中的 ^P 开关控制回显）
2 | 显示菜单时不显示提示
4 | 禁用控制菜单回显的 ^P 开关
8 | 显示用于调试 DIESEL 宏的输入or输出字符串
* MENUNAME
存储自定义文件名，包括文件名的路径。
（只读）
类型:	字符串
保存位置:	注册表
初始值:	customization_file_name
* MESHTYPE
控制通过 REVSURF、TABSURF、RULESURF 和 EDGESURF 命令创建的网格的类型。

类型:	整数
保存位置:	图形
初始值:	1
值 | 说明
0 | 为 REVSURF、TABSURF、RULESURF 和 EDGESURF 创建传统多边形或多面网格对象
1 | 为 REVSURF、TABSURF、RULESURF 或 EDGESURF 创建当前网格对象（建议）

此选项不影响使用 3DMESH 和 PFACE 命令创建的网格。
* MILLISECS
存储自系统启动后已经过的毫秒数。
（只读）
类型:	整数
保存位置:	未保存
初始值:	不确定
MILLISECS 中存储的毫秒数与 Windows API 中的 GetTickCount 函数返回的值相等。系统重新启动时，GetTickCount 函数返回的毫秒数会重置为 0。

通过减去 MILLISECS 返回的数值，可计算时间差。通过将 MILLISECS 的值除以 1000，可计算秒数。

在基于 AutoCAD 的产品（非 AutoCAD LT）中，AutoLISP 可用于基于 MILLISECS 返回的值计算秒数。

(setq ms (getvar "MILLISECS"))
(setq seconds (/ ms 1000.0))
注意:从基于 AutoCAD 2017 的产品开始，CDATE 和 DATE 系统变量返回的时间不再包括毫秒。如果需要计算小于一秒的时间差，将需要使用 MILLISECS。
* MIRRHATCH
控制 MIRROR 反映填充图案的方式。

类型:	整数
保存位置:	图形
初始值:	0
值 | 说明
0 | 保持填充图案方向
1 | 镜像填充图案方向
* MIRRTEXT
控制 MIRROR 反映文字的方式。
类型:	整数
保存位置:	图形
初始值:	0
值 | 说明
0 | 保持文字方向
1 | 镜像显示文字
* MLEADERSCALE
设置应用到多重引线对象的全局比例因子。

类型:	实数
保存位置:	图形
初始值:	1.0000
使用 DIMSCALE 缩放通过 LEADER 命令创建的引线对象。

值 | 说明
0.0 | 将根据当前模型空间视口和图纸空间两者之间的比例计算出一个合理的默认值。如果当前处于图纸空间或模型空间，但未使用图纸空间的特征，则该比例因子为 1.0。
>0 | 将计算出比例因子，使文字大小、箭头大小以及其他按比例缩放的距离均按它们的字面值进行打印。

MLEADERSCALE 不影响测量的长度、坐标或角度。

MLEADERSCALE 设定为 0（零）且当前多重引线样式不是注释性时，在图纸空间视口中创建的多重引线对象的全局多重引线比例由视口比例确定。当前多重引线样式为注释性时，MLEADERSCALE 值设定为 0。忽略对 MLEADERSCALE 值的更改，并将该值重置为 0。

* MODEMACRO
在状态行中显示文字字符串，例如当前图形的名称、时间/日期戳记或特殊模式。

类型:	字符串
保存位置:	未保存
初始值:	""
使用 MODEMACRO 显示文字字符串，或使用由 DIESEL 宏语言编写的特殊文字字符串，不断计算宏的值，并基于用户选定的条件将其显示在状态行中。
* MSLTSCALE
按注释比例缩放“模型”选项卡上显示的线型。

类型:	整数
保存位置:	图形
初始值:	1
值 | 说明
0 | 显示在“模型”选项卡上的线型不按注释比例缩放
1 | 显示在“模型”选项卡上的线型按注释比例缩放

注意:打开在 2007 版本及更早版本中创建的图形时，MSLTSCALE 设定为 0（零）。
* MSMSTATE
指示标记集管理器处于打开状态还是关闭状态。
（只读）
类型:	整数
保存位置:	未保存
初始值:	不确定
值 | 说明
0 | 关闭
1 | 打开
* MSOLESCALE
控制具有粘贴到模型空间中的文字的 OLE 对象的大小。

类型:	实数
保存位置:	图形
初始值:	1.0000
MSOLESCALE 仅控制初始大小。更改比例因子值不会影响图形中现有的 OLE 对象。

正数按数值进行缩放。零 (0) 按 DIMSCALE 值进行缩放。
* MTEXTAUTOSTACK
控制 MTEXT 命令的自动堆叠。

类型:	参数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 自动堆叠处于禁用状态
1 | 自动堆叠处于启用状态

自动堆叠在插入符、正斜杠或井号前后输入的数字字符。例如，如果键入 1#3，后跟有效的特殊字符或空格，则输入的文字自动堆叠为斜分数。
* MTEXTCOLUMN
为多行文字对象设置默认分栏设置。
类型:	整数
保存位置:	注册表
初始值:	2
值 | 说明
0 | 不分栏
1 | 自动调整高度的动态栏
2 | 手动调整高度的动态栏

* MTEXTDETECTSPACE
控制是否在 MTEXT 命令中将键盘上的空格键用于创建列表项。

类型:	参数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 按空格键不会创建格式化的列表项。
1 | 按空格键将创建格式化的列表项。

当 MTEXTDETECTSPACE 处于启用状态时，文本编辑器将识别字母、数字或符号后的空格并进入列表输入模式。例如，输入“1.<空格> 样例”将创建一个编号列表，如下所示。

样例
要继续添加到列表，请在每次输入结束时按 Enter 键。

要退出列表输入，请在行的末端按 Enter 键两次。

当 MTEXTDETECTSPACE 处于禁用状态时，仍然可以使用 Tab 键以开始创建列表。
* MTEXTED
设置用于编辑多行文字对象的应用程序。

类型:	字符串
保存位置:	注册表
初始值:	"Internal"
可以为 MTEXT 命令指定不同的文本编辑器。如果 MTEXTED 设定为“Internal”或空 (.)，将显示在位文字编辑器。如果 MTEXTED 设定为“OldEditor”，将显示多行文字编辑器。如果为另一个文字编辑器或字处理器指定了可执行文件的路径和名称，将改为显示该路径和文件名。

文字编辑器（内部文字编辑器除外）在段落文字中显示格式代码。

注意:从 AutoCAD 2022 开始，可以使用 MTEXTEDENCODING 系统变量指定所需的外部编辑器输出编码。

* MTEXTEDENCODING
设置在编辑多行文字的同时从外部编辑器读取输出时要使用的所需编码。
类型:	整数
保存位置:	注册表
初始值:	0
值 | 说明
0 | 自动检测输出文件的格式
1 | ANSI 格式
2 | UTF-8 格式
3 | UTF-8（包含 BOM）格式
4 | UTF-16LE 格式
5 | UTF-16BE 格式

注意:可以使用 MTEXTED 系统变量指定用于编辑多行文字的外部编辑器。
* MTEXTFIXED
为多行文字设置在位文字编辑器的显示大小和方向行为。
类型:	整数
保存位置:	注册表
初始值:	2
如果将 MTEXTED 设置为“内部”，MTEXTFIXED 将具有以下结果：

值 | 说明
0 或 1 | 显示在位文字编辑器，并且其中的多行文字采用图形中多行文字对象的大小、位置和旋转角度。
2 | 显示在位文字编辑器，将暂时以适当的大小在水平方向显示多行文字，以便可以轻松读取和编辑它；否则，多行文字将难以读取（例如当文字很小、很大或已旋转时）。
* MTEXTTOOLBAR
控制“文字格式”工具栏的显示。

类型:	整数
保存位置:	用户设置
初始值:	2
值 | 说明
0 | 从不显示“文字格式”工具栏。
1 | 选择 MTEXT 对象后显示“文字格式”工具栏。
2 | 功能区处于打开状态时不显示“文字格式”工具栏。

* MTJIGSTRING
设置启动 MTEXT 命令时显示在光标位置的样例文字内容。
类型:	字符串
保存位置:	注册表
初始值:	"abc"
按当前文字大小和字体显示文字字符串。最多可以输入包含 10 个字母或数字的任意字符串，或输入句点 (.)以不显示样例文字。

* MVIEWPREVIEW
控制插入已命名或新布局视口时的预览行为。

类型:	整数
保存位置:	注册表
初始值:	0
值 | 说明
0 | 仅显示矩形边框（最佳性能）
1 | 显示完整预览图像
* MYDOCUMENTSPREFIX
存储用户当前登录的“我的文档”文件夹的完整路径。
（只读）
类型:	字符串
保存位置:	注册表
初始值:	不确定

* NAVBARDISPLAY
控制导航栏在所有视口中的显示。

类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 不显示导航栏
1 | 显示导航栏
* NAVSWHEELMODE
指定 SteeringWheel 的当前模式。

类型:	整数
保存位置:	注册表
初始值:	2
值 | 说明
0 | 查看对象控制盘（基本型）
1 | 巡视建筑控制盘（基本型）
2 | 全导航控制盘
3 | 二维导航控制盘
4 | 查看对象控制盘（小）
5 | 巡视建筑控制盘（小）
6 | 全导航控制盘（小）

* NAVSWHEELOPACITYBIG
控制大型 SteeringWheels 的不透明度。

类型:	整数
保存位置:	注册表
初始值:	50
有效值为从 25％ 到 90％。当设定为 90 时，大控制盘将几乎完全不透明地显示在图形窗口中，并遮挡住控制盘下面的对象的视图。当设定为小于 90 的值时，大控制盘将在图形窗口中淡显，不太遮挡控制盘下面的对象。
* NAVSWHEELOPACITYMINI
控制小型 SteeringWheels 的不透明度。
类型:	整数
保存位置:	注册表
初始值:	50
有效值为从 25％ 到 90％。当设定为 90 时，小控制盘将几乎完全不透明地显示在图形窗口中，并遮挡住控制盘下面的对象的视图。当设定为小于 90 的值时，小控制盘将在图形窗口中淡显，不太遮挡控制盘下面的对象。
* NAVSWHEELSIZEBIG
指定大型 SteeringWheels 的大小。
类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 小
1 | 正常
2 | 大
* NAVSWHEELSIZEMINI
指定小型 SteeringWheels 的大小。

类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 小
1 | 正常
2 | 大
3 | 最大
* NAVVCUBEDISPLAY
控制 ViewCube 工具在当前视觉样式和当前视口中的显示。

类型:	整数
保存位置:	图形
初始值:	3
值 | 说明
0 | 不在二维和三维视觉样式中显示 ViewCube
1 | 在三维视觉样式中但不在二维视觉样式中显示 ViewCube
2 | 在二维视觉样式中但不在三维视觉样式中显示 ViewCube
3 | 在二维和三维视觉样式中显示 ViewCube
* NAVVCUBELOCATION
标识显示 ViewCube 工具的视口中的角点。
类型:	整数
保存位置:	注册表
初始值:	0
值 | 说明
0 | 右上
1 | 左上
2 | 左下
3 | 右下
* NAVVCUBEOPACITY
控制 ViewCube 工具处于未激活状态时的不透明度。

类型:	整数
保存位置:	注册表
初始值:	50
有效值为从 0％ 到 100％。当设定为 100 时，ViewCube 将完全不透明地显示在图形窗口中，并遮挡住视口中 ViewCube 下面的所有对象。当设定为小于 100 的值时，ViewCube 将在图形窗口中淡显，不太遮挡 ViewCube 下面的对象。如果设定为 0（零），ViewCube 不会显示在视口中，除非将光标放在 ViewCube 位置的上方。
* NAVVCUBEORIENT
控制 ViewCube 工具是反映当前 UCS 还是反映 WCS。
类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 |  ViewCube 确定为反映 WCS
1 | 将 ViewCube 确定为反映当前 UCS

* NAVVCUBESIZE
指定 ViewCube 工具的大小。
类型:	整数
保存位置:	注册表
初始值:	4
值 | 说明
0 | 小
1 | 正常
2 | 大
3 | 极小
4 | 自动；ViewCube 工具的大小可根据活动视口、活动布局的缩放因子或图形窗口的大小放大或缩小。

* NOMUTT
不显示通常情况下显示的消息（即不进行消息反馈）。
类型:	短整数
保存位置:	未保存
初始值:	0
显示所有命令行消息和反馈为普通模式，但在脚本、AutoLISP 例程等运行期间可禁止消息显示。

值 | 说明
0 | 恢复普通模式的消息反馈
1 | 禁止不确定的消息反馈
* NORTHDIRECTION
指定 WCS 的 Y 轴和栅格北向之间的角度。
类型:	实数
保存位置:	图形
初始值:	0.0000
该值不受 AUNITS 和 AUPREC 系统变量设置的影响。GEOGRAPHICLOCATION 和 GEOREORIENTMARKER 命令更新此系统变量。

* OBJECTISOLATIONMODE
控制隐藏的对象在绘图任务之间是否保持隐藏状态。
类型:	整数
保存位置:	用户设置
初始值:	0
OJBECTISOLATIONMODE 控制使用 ISOLATEOBJECTS 或 HIDEOBJECTS 命令隐藏的对象在保存并重新打开图形后是否保持隐藏状态。

值 | 说明
0 | 孤立/隐藏的对象在当前绘图任务中是临时的
1 | 孤立/隐藏的对象在绘图任务之间永久存在

* OBSCUREDCOLOR
指定遮挡线的颜色。

类型:	整数
保存位置:	图形
初始值:	257
暗显直线是一种隐藏线，通过更改其颜色和线型可使其可见。OBSCUREDCOLOR 仅在二维视图中可用。在三维视图中，将使用 VSOBSCUREDCOLOR 系统变量。

值 | 说明
0	按 ByBlock 设置颜色。
256	按 ByLayer 设置颜色。
257	按 ByEntity 设置颜色（或按对象设置）。
1-255	颜色基于 AutoCAD 颜色索引 (ACI)。
仅当 OBSCUREDLTYPE 系统变量的值设置为非 0（零）时，打开它时 OBSCUREDCOLOR 设置才可见。


* OBSCUREDLTYPE
指定遮挡线的线型。

类型:	整数
保存位置:	图形
初始值:	0
暗显直线是一种隐藏线，通过更改其颜色和线型可使其可见。OBSCUREDLTYPE 仅在二维视图中可用。在三维视图中，将使用 VSOBSCUREDLTYPE 系统变量。

与常规线型不同，暗显直线的线型不受缩放级别的影响。线型值详述如下：

值 | 说明
0 | 关闭
1 | 实体______________________________________________
2 | 虚线__  __  __  __  __  __  __  __  __  __  __  __
3 | 点划线.  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .
4 | 短划线__    __    __    __    __    __    __    __
5 | 中划线___   ___   ___   ___   ___   ___   ___   ___
6 | 长划线____  ____  ____  ____  ____  ____  ____  ____
7 | 双短划线___        ___        ___        ___        ___
8 | 双中划线______    ______    ______    ______    ______
9 | 双长划线_________   _________   _________   _________
10 | 中长划线____   ____   ____   ____   ____   ____   ____
11 | 疏点 .     .     .     .     .     .     .     .     .
* OFFSETDIST
设置默认的偏移距离。

类型:	实数
保存位置:	未保存
初始值:	-1.0000
值 | 说明
<0 | 通过指定点偏移对象
>=0 | 设置默认的偏移距离
* OFFSETGAPTYPE
控制偏移多段线时处理线段之间的潜在间隙的方式。
类型:	整数
保存位置:	注册表
初始值:	0
值 | 说明
0 | 将线段延伸到投影交点。
1 | 将线段在其投影交点处进行圆角。每个圆弧段的半径等于偏移距离。
2 | 将线段在其投影交点处进行倒角。在原始对象上从每个倒角到其相应顶点的垂直距离等于偏移距离。

* OLEFRAME
控制是否显示和打印图形中所有 OLE 对象的边框。
类型:	整数
保存位置:	图形
初始值:	2
必须显示 OLE 对象的边框，这样才能看见栅格。

值 | 说明
0 | 不显示也不打印边框
1 | 显示并打印边框
2 | 显示但不打印边框
* OLEHIDE
控制 OLE 对象的显示和打印。

类型:	整数
保存位置:	注册表
初始值:	0
值 | 说明
0 | 所有 OLE 对象均可见并可打印
1 | OLE 对象仅在图纸空间中可见并可打印
2 | OLE 对象仅在模型空间中可见并可打印
3 | 所有 OLE 对象均不可见也不可打印
* OLEQUALITY
为所有 OLE 对象设置默认打印质量。
类型:	整数
保存位置:	注册表
初始值:	3
使用 OLEQUALITY，可以将所有 OLE 对象的打印质量指定为 0（单色）、1（低质量图形）或 2（高质量图形）。

当 OLEQUALITY 设定为 3 时，将自动基于对象类型指定质量级别。例如，电子表格和表设定为单色，彩色文字和饼图设定为低质量图形，照片设定为高质量图形。

OLE 对象的打印质量由以下值控制。

值 | 说明
0 | 单色
1 | 低质量图形
2 | 高质量图形
3 | 根据 OLE 对象的类型自动设置质量

* OLESTARTUP
控制打印时是否加载嵌入 OLE 对象的源应用程序。
类型:	整数
保存位置:	图形
初始值:	0
加载 OLE 源应用程序可以提高打印质量。

值 | 说明
0 | 不加载 OLE 源应用程序
1 | 打印时加载 OLE 源应用程序

* ONLINEUSERID
显示与当前已登录到此产品的用户的 Autodesk 帐户关联的用户 ID。
（只读）
类型:	字符串
保存位置:	未保存
初始值:	不确定
如果当前没有用户登录，则返回的值为空字符串。
* ONLINEUSERNAME
显示当前已登录到此产品的用户的 Autodesk 帐户名称。
（只读）
类型:	字符串
保存位置:	未保存
初始值:	不确定
如果当前没有用户登录，则返回的值为空字符串。
* OPMSTATE
指示“特性”选项板处于打开、关闭还是隐藏状态。
（只读）
类型:	整数
保存位置:	未保存
初始值:	0
值 | 说明
0 | 关闭
1 | 打开
2 | 自动隐藏：在光标移离选项板时，选项板处于打开状态但仅显示标题栏

* ORBITAUTOTARGET
控制为 3DORBIT 命令获取目标点的方式。

类型:	整数
保存位置:	注册表
初始值:	1
将 3DORBIT 命令的“动态观察自动目标”选项设为启用或禁用。当您单击“动态观察”时，目标点将暂时显示为一个小的黑色球体。此行为在您通过按住 Shift 键和鼠标滚轮，然后移动光标以暂时进入“三维动态观察”模式时，同样适用。

值 | 说明
0 | 	关闭。目标点取决于您单击的位置。当您的光标悬停在对象上时，目标点将捕捉到对象上最近的要素。3DORBIT 命令将显示所有对象，不论它们是否已被预先选中。
1 | 	打开。目标点将自动居中并与绘图区域中可见的对象相对。3DORBIT 命令仅显示您预先选中的对象。

* ORTHOMODE
限定光标在垂直方向移动。

类型:	整数
保存位置:	图形
初始值:	0
打开 ORTHOMODE 后，光标只能相对 UCS 和当前栅格旋转角度水平或垂直移动

值 | 说明
0 | 关闭正交模式
1 | 打开正交模式
* OSMODE
设置执行对象捕捉。
类型:	位码
保存位置:	注册表
初始值:	4133
系统将使用下列位码值之和将该设置存储为一个位码：

值 | 说明
0 | 无
1 | END（端点）
2 | MID（中点）
4 | CEN（圆心）
8 | NOD（节点）
16 | QUA（象限点）
32 | INT（交点）
64 | INS（插入点）
128 | PER（垂足）
256 | TAN（切点）
512 | NEA（最近点）
1024 | 几何中心
2048 | APP（外观交点）
4096 | EXT（延伸）
8192 | PAR（平行）
16384 | 禁用当前的执行对象捕捉

要指定多个执行对象捕捉，请输入各值之和。例如，输入 3 可指定“端点”(位码 1) 和“中点”(位码 2) 对象捕捉模式。

注意:创建自定义例程的开发人员可以使用 16384 位码来暂时禁用当前的执行对象捕捉设置，而不会丢失原始设置。

* OSNAPCOORD
控制在命令行输入的坐标是否替代运行的对象捕捉。
类型:	整数
保存位置:	注册表
初始值:	2
值 | 说明
0 | 执行对象捕捉设置替代键盘输入坐标
1 | 键盘输入替代对象捕捉设置
2 | 键盘输入替代对象捕捉设置，脚本中的设置除外。
* OSNAPNODELEGACY
控制“节点”对象捕捉是否可用于捕捉到多行文字对象。

类型:	整数
保存位置:	注册表
初始值:	0
多行文字对象捕捉上节点的数量和位置取决于多行文字对象的垂直和水平对正方式。

值 | 说明
0 | 节点对象捕捉可用于多行文字对象
1 | 节点对象捕捉将忽略多行文字对象

* OSNAPOVERRIDE
防止替代默认对象捕捉设置。
类型:	整数
保存位置:	未保存
初始值:	0
默认对象捕捉（也称为“执行对象捕捉”）可以在“草图设置”对话框中的“对象捕捉”选项卡中指定（DSETTINGS 命令）。OSNAPOVERRIDE 系统变量可以强制运行当前的“执行对象捕捉”设置 (OSMODE)，从而防止手动替代，而手动替代仅在特定应用程序中有用。

值 | 说明
0 | 可以替代“执行对象捕捉”设置。
1 | 将强制运行“执行对象捕捉”。
* OSNAPZ
控制对象捕捉是否自动投影到与当前 UCS 中位于当前标高的 XY 平面平行的平面上。

类型:	整数
保存位置:	未保存
初始值:	0
值 | 说明
0 | 对象捕捉使用指定点的 Z 值
1 | 对象捕捉用为当前 UCS 设置的标高 (ELEV) 替换指定点的 Z 值

* OSOPTIONS
控制是否在图案填充对象、使用动态 UCS 时具有负 Z 值的几何图形或者尺寸界线上禁用对象捕捉。

类型:	位码
保存位置:	注册表
初始值:	7
系统将使用下列位码值之和将该设置存储为一个位码：

值 | 说明
0 | 对象捕捉会对以下项进行操作：图案填充对象、使用动态 UCS 时具有负 Z 值的几何图形，以及尺寸界线的端点。要在更改为此设置后捕捉到填充交点，则需要使用 REGEN。在从此设置更改为包含 1 在内的值后，出于性能方面的原因，建议使用 REGEN。
1 | 对象捕捉忽略填充图案对象。
2 | 在使用动态 UCS 期间对象捕捉忽略具有负 Z 值的几何图形。 （在 AutoCAD LT 中不可用。）
4 | 对象捕捉将忽略尺寸界线的端点。

注意: 在 AutoCAD LT 中，默认值为 5。

* PALETTEOPAQUE
控制是否可以使选项板透明。
类型:	整数
保存位置:	注册表
初始值:	0
当透明度可用并处于打开状态时，可以使用快捷菜单中的“透明度”选项为当前选项板或所有选项板设置不同的透明度。透明度在下列情况下不可用：选项板或窗口被固定；当前操作系统不支持透明度；已启用硬件加速键。

值 | 说明
0 | 选项板透明度已打开
1 | 选项板透明度已关闭
2 | 透明度已打开，且不受硬件或操作系统的支持
3 | 透明度已关闭，但不受硬件或操作系统的支持

如果启用硬件加速，则设置 2 和 3 可用；如果禁用硬件加速，则仅设置 0 和 1 可用。

注意:此系统变量还可以从选项板快捷菜单中的“透明度”选项中找到。在“透明度”对话框中的底部，“禁用所有窗口透明度(全局)”选项控制 PALETTEOPAQUE 系统变量并同时受该系统变量控制。
* PAPERUPDATE
控制当尝试以不同于为绘图仪配置文件默认指定的图纸尺寸打印布局时，警告对话框的显示。
控制当尝试以不同于为绘图仪配置文件默认指定的图纸尺寸打印布局时，警告对话框的显示。

类型:	整数
保存位置:	注册表
初始值:	0
值 | 说明
0 | 如果打印机不支持布局中指定的图纸大小，将显示警告对话框
1 | 将图纸设定为打印配置文件配置的图纸大小
* PARAMETERCOPYMODE
控制在图形、模型空间和布局以及块定义之间复制约束对象时处理约束和参照的用户参数的方式。
类型:	整数
保存位置:	注册表
初始值:	1
参数及其值仅应用于当前空间。模型空间、各个图纸空间布局以及块编辑器中的各种块定义不能访问彼此的参数。有几个命令（包括 PASTECLIP 和 EXPLODE）可以将标注约束和约束参数引入参照的用户参数无法再访问或发生冲突的环境中。

PARAMETERCOPYMODE 系统变量提供了用于处理这些情况的几个选项。

值 | 说明
0 | 不复制任何标注约束或约束参数。已从复制的对象中删除约束。
1 | 复制标注约束和约束参数。始终用数值常量替换表达式。如果存在命名冲突，请重命名标注参数。
2 | 复制标注约束、约束参数和用户参数。参照现有用户参数（如果可用），否则，用数值常量替换表达式。
3 | 复制标注约束、约束参数和用户参数。参照现有用户参数（如果可用），否则，创建任何缺少的用户参数。将缺少的参照标注约束更改到用户参数中。
4 | 复制所有标注约束、约束参数和表达式。如果复制的参数发生值冲突，则请重命名复制对象的参数。

* PARAMETERSSTATUS
指示“参数管理器”是处于显示状态还是隐藏状态。
（只读）
类型:	整数
保存位置:	注册表
初始值:	0
值 | 说明
0 | 消隐
1 | 显示
* PCMSTATE
指示点云管理器处于打开状态还是关闭状态。
（只读）
类型:	整数
保存位置:	注册表
初始值:	0
值 | 说明
0 | 关闭
1 | 打开
* PDFFRAME
确定 PDF 参考底图边框是否可见。
类型:	整数
保存位置:	图形
初始值:	1
FRAME 系统变量将替代 PDFFRAME 设置。在 FRAME 系统变量后使用 PDFFRAME 系统变量以重置 PDF 边框设置。

值 | 说明
0 | 不显示也不打印 PDF 参考底图边框。在选择集预览或对象选择期间，将暂时重新显示该边框。
1 | 显示并打印 PDF 参考底图框架。
2 | 显示但不打印 PDF 参考底图框架。
* PDFIMPORTFILTER
控制哪些数据类型要从 PDF 文件中输入并转换为 AutoCAD 对象。

类型:	位码
保存位置:	注册表
初始值:	8
值 | 说明
0 | 输入所有受支持的数据类型。
1 | 排除几何对象。
2 | 排除 TrueType 文字对象。
4 | 排除实体填充。
8 | 排除光栅图像。

PDF 文件中的标记对象是不受支持的数据类型，因此将被自动排除。

注意:最初使用 AutoCAD SHX 字体创建的文字将以几何对象的形式输出为 PDF 文件。在输入此类 PDF 文件后，任何 SHX 几何图形都不会自动转换回文字，需要使用 PDFSHXTEXT 命令才能进行转换。
* PDFIMPORTIMAGEPATH
指定在输入 PDF 文件后用于提取和保存参照图像文件的文件夹。
类型:	字符串
保存位置:	注册表
初始值:	“PDF Images”
当您输入含有光栅图像的 PDF 文件后，这些图像将进行提取并另存为 PNG 文件。这些提取的图像将附着到图形文件。

默认情况下，这些图像将保存在名为“PDF Images”的当前图形文件的子文件夹中。您既可以使用 PDFIMPORTIMAGEPATH 系统变量来更改这些参照图像文件的文件夹位置，也可以依次单击“选项”对话框、“文件”选项卡和“PDF 输入图像位置”节点进行更改。

是否生成光栅图像取决于 PDFIMPORTFILTER 系统变量。
* PDFIMPORTLAYERS
控制将哪些图层指定给输入自 PDF 文件的对象。

类型:	整数
保存位置:	注册表
初始值:	0
值 | 说明
0 | 创建对应于 PDF 图层的图层。这些图层的前缀为 PDF_。如果 PDF 文件中不存在任何图层，则改为使用设置 1。
1 | 创建对应于以下常规对象类型的图层：PDF_Geometry、PDF_Solid Fills、PDF_Images 和 PDF_Text。
2 | 使用当前图层。所有对象都将输入到当前图层中，即使图层已在 PDF 文件中定义也是如此。如有必要，请打开当前图层。

PDF 文件中的光栅和标记对象是不受支持的数据类型，因此将自动排除。

注意:最初使用 AutoCAD SHX 字体创建的文字以几何对象的形式存储在 PDF 文件中。
* PDFIMPORTMODE
控制从 PDF 文件输入对象时的默认处理。

类型:	位码
保存位置:	注册表
初始值:	6
值 | 说明
0 | 请勿在输入对象后对其进行处理。这包括将贝塞尔曲线转换为圆弧，以及将路径转换为多段线。
1 | 将输入的对象组合到块中。
2 | 应用线宽特性。
4 | 尽可能将连续的直线段和圆弧段合并为多段线。
8 | 将填充转换为实体填充的图案填充而非二维实体。
16 | 将各组共线线段合并为多段线线段。
* PDFOSNAP
决定是否为附着在图形中的 PDF 参考底图中的几何图形激活对象捕捉。
类型:	整数
保存位置:	注册表
初始值:	1

UOSNAP 系统变量将替代 PDFOSNAP 设置。

值 | 说明
0 | 为附着在图形中的所有 PDF 参考底图中的几何图形禁用对象捕捉
1 | 为附着在图形中的所有 PDF 参考底图中的几何图形启用对象捕捉

* PDFSHX
控制是否在将图形输出为 PDF 文件时，将使用 SHX 字体的文字对象存储在 PDF 文件中作为注释。

类型:	整数
保存位置:	注册表
初始值:	1
因为 PDF 中支持使用 SHX 字体的文字，所以输出为 PDF 文件的图形可采用标记为“AutoCAD SHX 文字”的注释形式存储该文字。然而，某些较旧的 PDF 查看器会在图形中显示这些注释以及其他任何注释，这通常并非是用户所希望看到的。

值 | 说明
0 | 当输出 PDF 文件时，不会创建任何附加注释。使用 SHX 字体的文字直观地保留为几何对象。
1 | 从使用 SHX 字体的文字对象创建注释。

注意:在 AutoCAD 2016 SP1 中，此系统变量命名为 EPDFSHX。
* PDFSHXBESTFONT
在将输入的 PDF 几何图形转换为文字时，控制 PDFSHXTEXT 命令使用最佳匹配字体或使用超过识别阈值的第一个选定字体。

类型:	整数
保存位置:	注册表
初始值:	0
使用最佳字体选项需花费较长的时间进行处理，但可确保在相似字体之间取得最佳结果。

值 | 说明
0 | 使用超过识别阈值的第一个字体
1 | 与所有选定字体比较，然后使用超过识别阈值的最佳匹配字体

* PDFSHXLAYER
控制在将 SHX 几何图形转换为文字对象时，指定给新创建的文字对象的图层。

类型:	整数
保存位置:	注册表
初始值:	1
此系统变量值可直接访问 PDFSHXTEXT 命令中“PDF 文字识别设置”对话框中的“创建文字位置”设置。

值 | 说明
0 | 在要转换的几何图形的相同层上创建文字。
1 | 在当前图层上创建文字。
* PDFSHXTHRESHOLD
设置所选几何图形在转换为文字对象之前必须匹配某个字体的百分比。

类型:	整数
保存位置:	注册表
初始值:	95
此系统变量值可直接访问 PDFSHXTEXT 命令中“PDF 文字识别设置”对话框中的“识别阈值”设置。该百分比适用于在转换过程中分析的每个几何图形群集。较低的值可在某些字符无法识别时依旧创建文字。较高的值可确保尽可能使用最匹配的选定字体。

有效值范围是 1 到 100。
* PDMODE
控制点对象的显示方式。

类型:	整数
保存位置:	图形
初始值:	0
值 0、2、3 和 4 提供点对象的不同几何表示。值 1 指定不显示任何图形。

将值指定为 32、64 或 96，除了绘制通过点的几何图形外，还可以指定在点的周围绘制形：

PDSIZE 控制点表示的尺寸。

更改 PDMODE 和 PDSIZE 后，现有点的外观将在下次重新生成图形时更新。
* PDSIZE
设置点对象的显示大小。

类型:	实数
保存位置:	图形
初始值:	0.0000
值 | 说明
0 | 在绘图区域高度的 5% 处创建点
>0 | 指定绝对尺寸
<0 | 指定视口尺寸的百分比

PDMODE 控制点的几何表达。

更改 PDMODE 和 PDSIZE 后，现有点的外观将在下次重新生成图形时更改。
* PEDITACCEPT
自动将选定对象转换为多段线，而在使用 PEDIT 时不显示提示。

类型:	整数
保存位置:	注册表
初始值:	0
值 | 说明
0 | 将显示提示，允许用户选择将选定对象转换为多段线
1 | 自动将选定对象转换为多段线，而不显示提示
* PELLIPSE
控制通过 ELLIPSE 命令创建的椭圆类型。
类型:	整数
保存位置:	图形
初始值:	0
值 | 说明
0 | 创建真正的椭圆对象
1 | 创建用多段线表示的椭圆
* PERIMETER
存储由 AREA 和 LIST 命令计算的上一个周长值。
（只读）
类型:	实数
保存位置:	未保存
初始值:	0.0000
在 AutoCAD 中，PERIMETER 还存储由 DBLIST 计算的周长值。
* PERSPECTIVE
指定当前视口是否显示透视视图。

类型:	整数
保存位置:	图形
初始值:	不确定

值 | 说明
0 | 关闭透视视图
1 | 打开透视视图

透视视图仅在模型空间中的三维视图样式中可用。在 AutoCAD LT 中，用户仅可关闭使用 AutoCAD 或基于 AutoCAD 的应用程序创建的图形中的透视，但不能再打开透视。

注意: 将图形文件或 DXF 文件保存为 AutoCAD 2007 之前的文件格式时，PERSPECTIVE 设定为 0。

* PERSPECTIVECLIP
决定眼点剪裁的位置。

类型:	实数
保存位置:	注册表
初始值:	5.0000
该值以百分比形式确定眼点剪裁出现的位置。值的范围在 0.01 和 10.0 之间。如果选择较小的值，则对象的 z 值将压缩到目标视图和远处。如果选择值，例如 0.5，则剪裁将出现在距离视图眼点很近的位置。在极端情况下，使用 0.1 可能合适，但是建议用户将设置更改为较高的值，例如 5。
* PFACEVMAX
设置多面网格中面顶点的最大数量。
（只读）
类型:	整数
保存位置:	未保存
初始值:	4
此系统变量仅影响传统多面网格（例如由 PFACE 创建的网格）。
* PICKADD
控制后续选择项是替换当前选择集还是添加到其中。

类型:	整数
保存位置:	用户设置
初始值:	2
值 | 说明
0 | 关闭 PICKADD。最新选定的对象将成为选择集。前一次选定的对象将自动从选择集中清除。
1 | 打开 PICKADD。每个选定的对象（单独选择或通过窗口选择）都将添加到当前选择集。
2 | 打开 PICKADD。每个选定的对象（单独选择或通过窗口选择）都将添加到当前选择集。若使用 SELECT 命令，则在该命令结束后保持对象处于选定状态。

注意:在选择时按住 SHIFT 键可以将对象添加到选择集或从选择集中删除对象。在 AutoCAD 中，在选择时按住 CTRL 键可以选择三维实体、曲面和网格的部件子对象。
* PICKAUTO
控制用于对象选择的自动窗口选择。
类型:	位码
保存位置:	注册表
初始值:	5
系统将使用下列位码值之和将该设置存储为一个位码：

值 | 说明
0 | 关闭自动窗口选择和窗交选择。
1 | 单击时若光标没有直接放置在对象上，将开始窗口或窗交选择。
2 | 即使光标直接放置在对象上，也将开始窗口或窗交选择。仅在使用单击、拖动以及释放方法启动命令之前选择对象时才应用该选项。
4 | 在您单击并拖动时，若光标没有直接放置在对象上，将开始窗口或窗交套索选择。如果“栏选”选项处于活动状态，单击并拖动将开始自由栏选。

要指定多个选项，请输入各值之和。例如，输入 5 可指定位码 1 和位码 4 选项。

注意:结合 PICKDRAG 系统变量使用。
* PICKBOX
设置对象选择目标的高度（以设备独立像素为单位）。
类型:	整数
保存位置:	注册表
初始值:	3
注意: 如果 PICKBOX 设定为 0，对象选择预览不可用。
* PICKDRAG
控制绘制选择窗口的方法。
类型:	整数
保存位置:	注册表
初始值:	2
值 | 说明
0 | 使用两个点指定选择窗口。单击一次以开始选择窗口，再次单击以完成选择。
1 | 通过单击并拖动，来指定套索选择。释放鼠标键以完成选择。
2 | 使用以上任一方法指定选择窗口。

注意:结合 PICKAUTO 系统变量使用。
* PICKFIRST
控制是否可以在启动命令之前选择对象。

类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 关闭。仅在启动命令后才可以选择对象
1 | 打开。也可以在启动命令之前选择对象

* PICKSTYLE
控制组选择和关联图案填充选择的使用。
类型:	整数
保存位置:	注册表
初始值:	1
 查找
值 | 说明
0 | 不使用编组选择和关联图案填充选择
1 | 组选择
2 | 使用关联图案填充选择
3 | 使用编组选择和关联图案填充选择

* PLATFORM
指示正在使用的操作系统。
（只读）
类型:	字符串
保存位置:	未保存
初始值:	不确定
* PLINECONVERTMODE
指定将样条曲线转换为多段线时使用的拟合方法。
类型:	整数
保存位置:	注册表
初始值:	0
值 | 说明
0 | 使用线性线段创建多段线
1 | 使用圆弧段创建多段线

* PLINEGCENMAX
设置多段线可以拥有的最大线段数量，以便应用程序计算几何中心。
类型:	整数
保存位置:	注册表
初始值:	50000
有效值为 0 到 10,000,000。当多段线的线段数超过 PLINEGCENMAX 值时，应用程序将停止计算中心点，并且不显示几何中心对象捕捉。

若要恢复传统行为（即不管多段线线段的数目如何，应用程序都将保持计算中心点），请将 PLINEGCENMAX 设置为 0（零）。

* PLINEGEN
控制绘制时，绕二维多段线的顶点生成线型图案的方式。
类型:	整数
保存位置:	图形
初始值:	0
更改此值并不影响现有的多段线。

值 | 说明
0 | 生成在每个多段线顶点以划线开始和结束的线型
1 | 生成穿过多段线顶点的连续图案的线型

注意:此设置不适用于带变宽线段的多段线。
* PLINEREVERSEWIDTHS
控制反转多段线的方向时多段线的外观。

类型:	整数
保存位置:	注册表
初始值:	0
可以使用 REVERSE 命令或使用 PEDIT 命令的“反转”选项来反转多段线方向。

值 | 说明
0 | 将反转选定多段线的线段的顺序，但不会反转线段宽度的顺序
1 | 将反转选定多段线的线段的顺序和方向
* PLINETYPE
指定是否使用优化的二维多段线。

类型:	整数
保存位置:	注册表
初始值:	2
PLINETYPE 控制如何使用 PLINE 命令创建新多段线以及是否转换早期版本图形中的现有多段线。

值 | 说明
0 | 打开旧图形时不转换其中的多段线；PLINE 创建旧格式的多段线
1 | 打开旧图形时不转换其中的多段线；PLINE 创建优化的多段线
2 | 打开 AutoCAD 14 或旧图形时转换其中的多段线；PLINE 创建优化的多段线

PLINETYPE 还控制用以下命令创建的多段线类型：BOUNDARY（当对象类型设置为“多段线”时）、DONUT、PEDIT（当选择直线或圆弧时）、POLYGON 和 SKETCH（当 SKPOLY 设置为 1 时）。有关这两种格式的详细信息，请参见 CONVERT 命令。


* PLINEWID
存储默认的多段线宽度。

类型:	实数
保存位置:	图形
初始值:	0.0000
* PLOTOFFSET
控制打印偏移是相对于可打印区域还是相对于图纸边。

类型:	整数
保存位置:	注册表
初始值:	0
值 | 说明
0 | 将打印偏移设定为相对于可打印区域。
1 | 将打印偏移设定为相对于图纸边
* PLOTROTMODE
控制打印方向。
类型:	整数
保存位置:	注册表
初始值:	2
值 | 说明
0 | 旋转有效的打印区域，使带有“旋转”图标的角点在图纸上定界为：左下角为 0、左上角为 90、右上角为 180、右下角为 270。X 和 Y 原点偏移是相对于左下角计算的。
1 | 将有效打印区域的左下角与图纸的左下角对齐。
2 | 与变量值为 0 时相似，但 X 和 Y 原点偏移将相对旋转后的原点位置进行计算。

* PLOTTRANSPARENCYOVERRIDE
控制是否打印对象透明度。

类型:	整数
保存位置:	用户设置
初始值:	1
值 | 说明
0 | 不使用透明度打印对象
1 | 使用“页面设置”或“打印”对话框中指定的设置
2 | 使用透明度打印对象

将 PLOTTRANSPARENCYOVERRIDE 系统变量设定为 0 或 2 会替代“页面设置”或“打印”对话框中的“使用透明度打印”选项。

注意:由于此系统变量可以影响全局打印性能，因此强烈建议用户将该值设置保留为 1，并在打印时管理透明度打印。

* PLQUIET
控制可选的打印相关对话框和非致命脚本错误的显示。

类型:	整数
保存位置:	注册表
初始值:	0
值 | 说明 
0 | 显示打印对话框和非致命错误。
1 | 记录非致命错误，但不显示相关打印对话框

* POINTCLOUD2DVSDISPLAY
在使用二维线框视觉样式查看点云时，切换边界框和文字消息的显示。
类型:	整数
保存位置:	用户设置
初始值:	0
仅当三维图形卡可用且当前视觉样式不是二维线框时才显示点云。否则，边界框将作为点云的替代项显示。此系统变量提供了一种隐藏边界框的方式。

值 | 说明
0 | 在使用二维线框视觉样式查看点云时，显示点云的边界框以及警告消息“点云不采用二维视觉样式显示”
1 | 隐藏边界框和警告消息
* POINTCLOUDAUTOUPDATE
仅适用于传统（2015 之前）点云对象。控制在操作、平移、缩放或动态观察后是否自动重新生成点云。
类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 视图更改时必须手动重新生成传统点云。当此值为 0（零）时，POINTCLOUDRTDENSITY 值不会对实时缩放、平移或动态观察期间显示的点数产生影响。
1 | 视图更改后将自动重新生成传统点云。

为了获取更快速的性能，请在编辑具有较大传统点云的图形时，将此值保持为 0（零）。
* POINTCLOUDBOUNDARY
控制是否显示点云边界框。
类型:	整数
保存位置:	用户设置
初始值:	1
边界框定义点云的范围，包括任何裁剪的区域。可以在屏幕上隐藏或显示它，但它不会被打印出来。

值 | 说明
0 | 否
1 | 仅在选定时
2 | 始终显示

注意:在 AutoCAD LT 中，可以打开包含点云的图形，但不能附着或编辑点云。
* POINTCLOUDCACHESIZE
指定为显示点云而保留的内存量。

类型:	整数
保存位置:	注册表
初始值:	512
值 | 说明
0 | 将基于系统配置自动计算要保留的内存量
1 到 500 | 保留 500 MB
501 到 32,000 | 指定要保留的 MB 数
* POINTCLOUDCLIPFRAME
控制传统点云上的剪裁边界是否显示在屏幕上和打印输出中。

类型:	整数
保存位置:	图形
初始值:	2
当您需要调整边界范围时，启用剪裁边界显示。禁用该选项可处理点云本身。

值 | 说明
0 | 无法显示或打印点云剪裁边界。
1 | 显示和打印所有的点云剪裁边界。
2 | 显示但不打印所有的点云剪裁边界。

注意:FRAME 系统变量可替代这些设置。您可能需要在修改 FRAME 设置之后重置 POINTCLOUDCLIPFRAME。

* POINTCLOUDDENSITY
仅适用于传统（2015 之前）点云对象。控制工程视图中为所有传统点云显示的点的百分比。

类型:	整数
保存位置:	用户设置
初始值:	15
为每个图形输入最大点数的百分比（由 POINTCLOUDPOINTMAX 定义）。例如，如果当前最大为 2,000,000 点，输入 1 可将 20,000 个点均匀地分布到所有显示的传统点云中。

注意:在 AutoCAD LT 中，可以打开包含点云的图形，但不能附着或编辑点云。
* POINTCLOUDLIGHTING
控制点云的光源效果的显示方式。
类型:	整数
保存位置:	图形
初始值:	2
该设置存储在图形中，并应用于附着到图形的所有点云。

注意: 传统点云将忽略此设置。
值 | 说明
0 | 没有光源效果。
1 | 单面光源（采用观察角度的光源）。
2 | 双面照明。负方向法线矢量的处理方式与正方向法线矢量相同，例如，墙的背面照亮方式与正面所用方式相同。
* POINTCLOUDLIGHTSOURCE
当光源处于打开状态时，确定点云的光源。
类型:	整数
保存位置:	图形
初始值:	0
该设置存储在图形中，并应用于附着到图形的所有点云。当使用 POINTCLOUDLIGHTING 系统变量打开光源时，它将适用。

注意: 传统点云将忽略此设置。
值 | 说明
0 | 使用默认点云光源：两个光源与环境光一起分别位于视图的两侧。
1 | 使用类似于 Autodesk ReCap 光源的视图方向的单个光源。

* POINTCLOUDLOCK
控制是否可以操纵、移动、裁剪或旋转附着的点云。

类型:	整数
保存位置:	注册表
初始值:	0
为新点云对象设定默认的“锁定”特性。

值 | 说明
0 | 不锁定新点云对象，并且可以操作这些对象。“锁定”特性设定为“否”。
1 | 已锁定新点云对象而无法进行编辑，并且不能操作这些对象。“锁定”特性设定为“是”。

注意: 此设置不会影响现有点云对象的“锁定”特性。
* POINTCLOUDLOD
为点云设置显示的细节级别。

类型:	整数
保存位置:	图形
初始值:	10

为选定点云显示的细节级别 (LOD) 指定一个从 1 到 10 的值。较低的 LOD 值会显示较少的点并提高显示速度。

* POINTCLOUDPOINTMAX
设置可以为所有附着到图形的点云显示的最大点数。不会影响传统（2015 之前）点云。
类型:	整数
保存位置:	注册表
初始值:	10,000,000
增加限制会提高点云的视觉逼真度。降低限制会提高系统性能。
* POINTCLOUDPOINTMAXLEGACY
仅适用于传统（2015 之前）点云。设置可以为所有附着到图形的传统点云显示的最大点数。
类型:	整数
保存位置:	注册表
初始值:	1,500,000
传统点云的最大点数为 2500 万。增加限制会提高点云的视觉逼真度。降低限制会提高系统性能。
* POINTCLOUDPOINTSIZE
控制新点云对象的点的大小。

类型:	整数
保存位置:	图形
初始值:	2

指定一个从 1 到 10 的值用于表示点大小，以像素为测量单位。该设置存储在图形中，并应用于附着到图形的所有点云。

注意: 传统点云忽略此设置，并具有 1 个像素的点大小。
* POINTCLOUDRTDENSITY
通过在缩放、平移或动态观察期间减少显示的点数，可以提高性能。
类型:	整数
保存位置:	用户设置
初始值:	5
为每个图形输入最大点数的百分比（由 POINTCLOUDPOINTMAXLEGACY 定义）。例如，如果当前最大值为 2,000,000 点，则输入 1 以在缩放、平移和动态观察期间显示的所有传统点云中均匀地分布 20,000 个点。

仅适用于传统（2015 之前）点云对象。

如果 POINTCLOUDAUTOUPDATE 的值为 0（零），则 POINTCLOUDRTDENSITY 的值不会对缩放、平移或动态观察期间显示的点数产生影响。

如果您使用的是传统（2015 版之前）点云，将此系统变量设定为比 POINTCLOUDDENSITY 的值小的值可提高性能。

注意:在 AutoCAD LT 中，可以打开包含点云的图形，但不能附着或编辑点云。
* POINTCLOUDSHADING
指定点云中的点的亮度是漫射还是镜面反射。

类型:	整数
保存位置:	图形
初始值:	0
值 | 说明
0 | 使用漫射（兰伯特）着色可获得哑光的外观。
1 | 使用镜面（光滑体渲染）着色可获得更有光泽的外观。
* POINTCLOUDVISRETAIN
控制传统图形（在 AutoCAD 2014 中创建）是否保留单个扫描（RCS 文件）的打开或关闭状态和由附着的点云项目文件（RCP 文件）参照的面域。
类型:	整数
保存位置:	图形
初始值:	1
值 | 说明
0	当附着点云或使用参照的点云打开图形时，在由 ReCap 处理的文件中显示扫描和面域的打开/关闭状态。
1	在保存并重新打开图形时，在图形中使用上次的打开/关闭设置显示点云中的所有点（已删除的点除外）。

* POLARADDANG
存储极轴追踪和极轴捕捉的附加角度。

类型:	字符串
保存位置:	注册表
初始值:	""
最多可以添加 10 个角。可使用分号 (;) 分隔每个角度。AUNITS 系统变量设置角度显示的格式。与 POLARANG 不同，POLARADDANG 角度不会导致其值成倍增加。

必须将 POLARMODE 系统变量的位值设定为 4，POLARADDANG 才能生效。

使用角度的分数时，请将 AUPREC 系统变量（角度精度）设定为更高的值。否则，POLARADDANG 的值将被舍入。


* POLARANG
设置极轴角增量。

类型:	实数
保存位置:	注册表
初始值:	90
值为 90、45、30、22.5、18、15、10 和 5。
* POLARDIST
当 SNAPTYPE 设定为 1 (PolarSnap) 时，设置捕捉增量。
类型:	实数
保存位置:	注册表
初始值:	0.0000
* POLARMODE
控制极轴追踪和对象捕捉追踪的设置。
类型:	位码
保存位置:	注册表
初始值:	0
系统将使用下列位码值之和将该设置存储为一个位码：

极轴角的测量方式

值 | 说明
0 | 基于当前 UCS 测量极轴角（绝对角度）
1 | 从选定对象开始测量极轴角（相对角度）

对象捕捉追踪

值 | 说明
0 | 仅按正交方式追踪
2 | 在对象捕捉追踪中使用极轴追踪设置

使用其他极轴追踪角度

值 | 说明
0 | 否
4 | 是

获取对象捕捉追踪点的方式

值  | 说明
0 | 自动获取
8 | 按 SHIFT 键获取

注意:在 AutoCAD 三维环境中，也显示平行于 UCS 的 Z 轴的追踪矢量，并且工具提示基于沿 Z 轴的方向显示角度的 +Z 和 -Z。

* POLYSIDES
为 POLYGON 命令设置默认边数。

类型:	整数
保存位置:	未保存
初始值:	4
有效取值范围为 3 到 1024。
* POPUPS
显示当前配置的显示驱动程序状态。
（只读）
类型:	整数
保存位置:	未保存
初始值:	1
值 | 说明
0 | 不支持对话框、菜单条和图标菜单
1 | 支持这些功能
* PREVIEWCREATIONTRANSPARENCY
控制在使用 SURFBLEND、SURFPATCH、SURFFILLET、FILLETEDGE、CHAMFEREDGE 和 LOFT 时生成的预览透明度。
类型:	整数
保存位置:	注册表
初始值:	60
有效值范围为 0 到 90，其中 0 是最低的透明度值（不透明），90 是最高的透明度值。
* PREVIEWFILTER
从选择预览中排除指定的对象类型。
类型:	位码
保存位置:	注册表
初始值:	3
系统将使用下列位码值之和将该设置存储为一个位码：

值 | 说明
0 | 不排除任何对象
1 | 排除锁定图层上的对象
2 | 排除外部参照中的对象
4 | 排除表
8 | 排除多行文字对象
16 | 排除图案填充对象
32 | 排除组中的对象
* PREVIEWTYPE
控制要用于图形缩略图预览的视图。
类型:	整数
保存位置:	图形
初始值:	0
值 | 说明
0 | 使用上次保存的视图
1 | 使用主视图
* PRODUCT
显示产品名称。

* PROGRAM
显示程序名称。

* PROJECTNAME
为当前图形指定工程名称。
类型:	字符串
保存位置:	图形
初始值:	""
在原始路径中没有找到外部参照、图像、DWF、PDF、DGN、协调模型（NWC 或 NWD）外部参照文件时使用。此工程名称指向注册表中的一段，其中包含每个已定义工程名称的一个或多个搜索路径。工程名称和它们的搜索路径在“选项”对话框的“文件”选项卡上创建。

当图形在客户之间进行交换，或者用户将不同的驱动器映射到服务器上的同一位置时，项目名称可使这些类型文件的管理更加方便。

如果在原始路径中没有找到该文件，将搜索与项目名称关联的项目路径。如果在使用项目路径时没有找到该文件，将使用 AutoCAD 搜索路径。
* PROJMODE
设置当前投影模式以进行修剪或延伸。

类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 真三维模式（无投影）
1 | 投影到当前 UCS 的 XY 平面上
2 | 投影到当前视图平面
* PROPERTYPREVIEW
控制在将鼠标悬停在控制特性的下拉列表和库上时，是否可以预览对当前选定对象的更改。

类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 关闭鼠标悬停特性预览
1 | 显示鼠标悬停特性预览

注意:特性预览仅在功能区和“特性”选项板中显示。在其他选项板中不可用。
* PROPOBJLIMIT
限制可以使用“特性”和“快捷特性”选项板一次更改的对象数。
类型:	整数
保存位置:	用户设置
初始值:	25000
有效范围为 0 到 32767。值 0（零）可以禁用此限制，但是在非常大的图形中可能会影响性能。如果超出限制，选项板中的特性字段将灰显以表明其无法更改。

注意:功能区特性控件和功能区上下文选项卡上的类似的限制由 RIBBONCONTEXTSELLIM 系统变量独立存储。

* PROPPREVTIMEOUT
设置可用于生成特性预览的最大时间量。

类型:	整数
保存位置:	注册表
初始值:	1

如果达到指定的持续时间但仍然在生成预览，预览将被取消。

持续时间以秒计算。有效值范围为从 1 到 5。
* PROXYGRAPHICS
指定是否将代理对象的图像保存在图形中。
类型:	整数
保存位置:	图形
初始值:	1
值 | 说明
0 | 不将代理对象的图像与图形一起保存，仅显示一个边框
1 | 将代理对象的图像与图形一起保存
* PROXYNOTICE
创建代理时显示通知。
类型:	整数
保存位置:	注册表
初始值:	1
在打开包含自定义对象的图形时，如果创建此自定义对象的应用程序不存在，则创建代理。当发出命令卸载自定义对象的父应用程序时也将创建代理。

值 | 说明
0 | 不显示代理警告
1 | 显示代理警告
* PROXYSHOW
控制代理对象在图形中的显示。
类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 不显示代理对象
1 | 显示所有代理对象的图形图像
2 | 仅显示所有代理对象的边框
* PSLTSCALE
控制在图纸空间视口中显示的对象的线型比例缩放。

类型:	整数
保存位置:	图形
初始值:	1
可以根据每个布局视口的放大比例或统一根据图纸空间的全局比例来设置非连续性线型的线型比例。对于 PSLTSCALE，不同的布局选项卡可能具有不同的设置。

值 | 说明
0 | 无特殊线型比例。线型的虚线长度基于创建对象的空间（图纸或模型）的图形单位。使用由 LTSCALE 命令设置的全局比例因子。
1 | 视口比例决定线型比例。如果 TILEMODE 系统变量设置为 0（零），则虚线长度基于图纸空间的图形单位（即使对于模型空间中的对象也是如此）。在这种模式下，视口可以有多种缩放比例，但显示的线型相同。对于特殊线型，视口中直线的虚线长度与图纸空间中直线的虚线长度相同。用户仍可以使用 LTSCALE 控制虚线长度

如果修改 PSLTSCALE 的设置，或在 PSLTSCALE 设置为 1 时使用诸如 ZOOM 等命令，则视口中的对象不会按照新的线型比例自动重生成。使用 REGEN 或 REGENALL 命令更新每一个视口中的线型比例。
* PSOLHEIGHT
控制通过 POLYSOLID 命令创建的扫掠实体对象的默认高度。
类型:	实数
保存位置:	图形
初始值:	4.0000（英制）或 80.0000（公制）
该值反映使用 POLYSOLID 命令时最后一次输入的高度值。用户不能将该值输入为 0。
* PSOLWIDTH
控制使用 POLYSOLID 命令创建的扫掠实体对象的默认宽度。
类型:	实数
保存位置:	图形
初始值:	0.2500（英制）或 5.0000（公制）
该值反映使用 POLYSOLID 命令时最后一次输入的高度值。用户不能将该值输入为 0。
* PSTYLEMODE
指示当前图形处于颜色相关打印样式模式还是命名打印样式模式。
（只读）
类型:	整数
保存位置:	图形
初始值:	1
值 | 说明
0 | 当前图形使用命名打印样式表
1 | 当前图形使用颜色相关打印样式表

* PSTYLEPOLICY
控制打开在 AutoCAD 2000 之前的版本中创建的图形或不使用图形模板从头创建新图形时，使用的打印样式模式（颜色相关打印样式模式或命名打印样式模式）。

类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 图形设定为使用命名打印样式。新对象的打印样式被设置为 DEFPLSTYLE 系统变量定义的默认样式。新图层的打印样式被设置为 DEFLPLSTYLE 系统变量定义的默认样式。
1 | 图形设定为使用颜色相关打印样式。对象的打印样式由对象的颜色决定。
* PSVPSCALE
为所有新创建的视口设置视图比例因子。
类型:	实数
保存位置:	图形
初始值:	0.0000
视图比例因子是通过比较图纸空间与新创建模型空间视口中单位的比率进行定义的。用户设置的视图比例因子将与 VPORTS 命令结合使用。其值为 0 意味着比例因子为“按图纸空间缩放”。比例必须是一个正实数值。
* PUBLISHALLSHEETS
指定在“发布”对话框中是加载激活文档的内容还是加载所有打开文档的内容。

类型:	整数
保存位置:	用户设置
初始值:	1
值 | 说明
0 | 仅当前文档的内容（布局和/或模型空间）自动加载到发布列表中
1 | 所有打开的 AutoCAD 文档的内容（布局和/或模型空间）都自动加载到发布列表中

* PUBLISHCOLLATE
控制打印图纸集、多页打印文件或后台打印文件时是否可以被其他打印作业中断。
类型:	整数
保存位置:	用户设置
初始值:	1
将图纸发布为单个作业要求具有支持多页打印或打印选项的打印驱动程序。

值 | 说明
0 | 一次处理已发布的图纸集中的一张图纸。为每张图纸创建单独的 PLT 文件。如果发布图纸集，图纸可能与其他打印作业交错。
1 | 将已发布的图纸集作为单个作业处理。已创建一个多页 PLT 文件。如果发布图纸集，图纸集从不与其他打印作业交错。
* PUBLISHHATCH
控制是否将发布为 DWF 或 DWFx 格式的填充图案视为单个对象。
类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 当发布为 DWF 或 DWFx 格式时，将填充图案组件看作各个单独的对象
1 | 当发布为 DWF 或 DWFx 格式时，将填充图案组件看作单个对象

注意:此变量仅影响发布为 DWF 或 DWFx 格式的图形，
* PUCSBASE
存储定义正交 UCS 设置（仅用于图纸空间）的原点和方向的 UCS 名称。

类型:	字符串
保存位置:	图形
初始值:	""
* PUSHTODOCSSTATE
将指示“Push to Autodesk Docs”选项板是处于打开状态还是处于关闭状态。
（只读）
类型:	整数
保存位置:	用户设置
初始值:	0
值 | 说明
0 | 关闭
1 | 打开

* QCSTATE
指示“快速计算器”计算器处于打开状态还是关闭状态。
（只读）
类型:	整数
保存位置:	未保存
初始值:	不确定
值 | 说明
0 | 关闭
1 | 打开
* QPLOCATION
设置“快捷特性”选项板的位置。

类型:	整数
保存位置:	注册表
初始值:	0
值 | 说明
0 | 在相对于光标的位置显示“快捷特性”选项板
1 | 在与光标无关的固定位置显示“快捷特性”选项板

* QPMODE
控制在选定对象时是否显示“快捷特性”选项板。
类型:	整数
保存位置:	注册表
初始值:	-1
值 | 说明
0 | 在绘图区域中选择了所有对象时，关闭所有对象的“快捷特性”选项板的显示
1 | 在绘图区域中选择了所有对象时，打开所有对象的“快捷特性”选项板的显示
2 | 打开“快捷特性”选项板的显示，但仅对于在“自定义用户界面 (CUI)” 编辑器中受支持的对象，以便当它们在图形区域中选定时显示“快捷特性”

注意:此系统变量设定为负数时，将关闭此功能，但保留该值。要使用此功能，PICKFIRST 系统变量必须设定为 1（开）。

* QTEXTMODE
控制文字的显示方式。

类型:	整数
保存位置:	图形
初始值:	0
值 | 说明
0 | 关闭快速文字模式；显示字符
1 | 打开快速文字模式；显示文本外框代替文字

* QVDRAWINGPIN
控制图形预览图像的默认显示状态。
类型:	整数
保存位置:	注册表
初始值:	0
值 | 说明
0 | 以不固定状态显示图形的预览图像
1 | 以固定状态显示图形的预览图像


* QVLAYOUTPIN
控制图形中模型空间和布局的预览图像的默认显示状态。

类型:	整数
保存位置:	注册表
初始值:	0
值 | 说明
0 | 以非固定状态显示模型空间和图形中布局的预览图像
1 | 以固定状态显示模型空间和图形中布局的预览图像

* RASTERDPI
控制在标注输出设备和无标注输出设备之间切换时的图纸尺寸和打印比例。
类型:	整数
保存位置:	注册表
初始值:	300
在毫米或英寸和像素之间转换。有效值为 100 到 32,767 之间的整数。 主要适用于 AutoCAD Map 3D 工具集，以用于涉及 Autodesk 驱动程序和使用 Alpha 混合打印透明度的输出。RASTERDPI 与 PDF、DWF 或 DWFx 输出无关。

* RASTERPERCENT
设置允许用于打印每个光栅图像或 OLE 对象的最大可用虚拟内存百分比。

类型:	整数
保存位置:	注册表
初始值:	20
如果超出最大百分比，则打印将以斑马纹完成。
* RASTERPREVIEW
控制是否将缩略图预览图像随图形一起创建和保存。

类型:	整数
保存位置:	注册表
初始值:	1
旧式的。此系统变量已重命名为 THUMBSAVE。

值 | 说明
0 | 不在图形中创建预览图像
1 | 在图形中创建和保存预览图像
* RASTERTHRESHOLD
在打印时，为每个光栅图像或 OLE 对象指定阈值（以兆字节为单位）。

类型:	整数
保存位置:	注册表
初始值:	20
如果光栅图像或 OLE 对象超出该阈值，将检查系统内存的可用性。如果光栅图像或 OLE 对象对于可用内存过大，则打印将在条带中完成。
* REBUILD2DCV
设定重新生成样条曲线时的控制点数量。
类型:	整数
保存位置:	注册表
初始值:	6
有效值为 2 到 32767。
* REBUILD2DDEGREE
设定重新生成样条曲线时的全局阶数。

类型:	整数
保存位置:	注册表
初始值:	3
有效值为 1 到 11。

阶数为 1 的曲线为直线，阶数为 2 的曲线将具有一个折弯。Bezier 曲线的阶数为 3。更高的阶数会创建更加复杂的曲线，但需要计算。
* REBUILD2DOPTION
控制重新生成样条曲线时是否删除原始曲线。

类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 保留原始曲线
1 | 删除原始曲线
* REBUILDDEGREEU
设定重新生成 NURBS 曲面时 U 方向上的阶数。

类型:	整数
保存位置:	注册表
初始值:	3
有效值为 2 到 11。
* REBUILDDEGREEV
设定重新生成 NURBS 曲面时 V 方向上的阶数。

类型:	整数
保存位置:	注册表
初始值:	3
有效值为 2 到 11。
* REBUILDOPTIONS
控制重新生成 NURBS 曲面时的删除和修剪选项。

类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 不删除原始曲面，且修剪的区域不会应用到重新生成的对象。
1 | 删除原始曲面，且修剪的区域不会应用到重新生成的对象。
2 | 不删除原始曲面，且修剪的区域将应用到重新生成的对象。
3 | 删除原始曲面，且修剪的区域将应用到重新生成的对象。
* REBUILDU
设定重新生成 NURBS 曲面时 U 方向上的栅格线数量。
类型:	整数
保存位置:	注册表
初始值:	6
有效值为 2 到 32767，增大或减小 U 方向上所用的轴线数以重新生成 NURBS 曲面。
* REBUILDV
设定重新生成 NURBS 曲面时 V 方向上的栅格线数量。
类型:	整数
保存位置:	注册表
初始值:	6
有效值为 2 到 32767，增大或减小 V 方向上所用的轴线数以重新生成 NURBS 曲面。

* RECOVERAUTO
控制在打开损坏的图形文件之前或之后恢复通知的显示。

类型:	位码
保存位置:	注册表
初始值:	0
值 | 说明
0 | 显示一个对话框通知以修复损坏的图形。将中断任何正在运行的脚本。修复文件后，打开图形，然后在对话框中显示报告。
1 | 自动修复损坏的图形，打开该图形，然后在对话框中显示报告。如果脚本正在运行时，不会显示通知。
2 | 显示一个对话框通知以修复损坏的图形。修复文件后，打开图形，然后在“命令”窗口中显示报告。
3 | 自动修复损坏的图形，打开该图形，然后在“命令”窗口中显示报告。
* RECOVERYMODE
控制系统出现故障后是否记录图形修复信息。

类型:	整数
保存位置:	注册表
初始值:	2
值 | 说明
0 | 不记录修复信息，系统出现故障后不自动显示“图形修复”窗口，并且系统注册表中的任何修复信息都将被删除
1 | 记录修复信息，但是系统出现故障后不自动显示“图形修复”窗口
2 | 记录修复信息，系统出现故障后自动在下一个任务中显示“图形修复”窗口

* REFEDITNAME
显示正在编辑的参照名称。

* REFPATHTYPE
控制当参照文件第一次附着到宿主图形文件时是使用完整路径、相对路径还是无路径。
类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 使用“无路径”作为默认值
1 | 使用“相对路径”作为默认值
2 | 使用“完整路径”作为默认值

注意:此系统变量对已附着到宿主图形的参照没有影响。
* REGENMODE
旧式的。控制图形的自动重生成。

类型:	整数
保存位置:	图形
初始值:	1
REGENMODE 系统变量不再需要，并不起作用。
* RE-INIT
重新初始化数字化仪、数字化仪端口和 acad.pgp 文件。
类型:	位码
保存位置:	未保存
初始值:	0
系统将使用下列位码值之和将该设置存储为一个位码：

值 | 说明
1 | 重新初始化数字化仪 I/O 端口
4 | 重新初始化数字化仪
16 | 重新初始化 PGP 文件（重载）

要指定多个重新初始化部件，请输入各位码值之和。例如，输入 5 可指定同时重新初始化数字化仪端口 (1) 和数字化仪 (4)。

* REMEMBERFOLDERS
控制显示在标准文件选择对话框中的默认路径。
类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 恢复 AutoCAD 2000 及其早期版本的功能。通过双击快捷方式图标启动程序时，如果在图标特性中指定了起始路径，则该路径将用作所有标准文件选择对话框的默认设置。
1 | 每个标准文件选择对话框中的默认路径是指在该对话框中使用过的最后路径。未使用为 AutoCAD 快捷方式图标指定的起始文件夹。
* RENDERENVSTATE
指示“环境和曝光”选项板处于打开状态还是关闭状态。
（只读）
类型:	整数
保存位置:	未保存
初始值:	0
值 | 说明
0  | 关闭
1  | 打开
* RENDERLEVEL
指定渲染引擎为创建渲染图像而执行的层级数或迭代数。
类型:	整数
保存位置:	图形
初始值:	5
渲染引擎将分析不同层级之间的渲染图像结果，以确定可以改进的地方。增加层级数可提高渲染图像的质量，但会增加总体渲染时间。

有效取值范围为 0 到 50。

RENDERTARGET 系统变量指定渲染引擎是使用层级还是使用时间限制来控制渲染图像的质量。层级数由此系统变量指定，而渲染时间限制由 RENDERTIME 系统变量指定。
* RENDERLIGHTCALC
控制光源和材质的渲染精度。

类型:	整数
保存位置:	图形
初始值:	1
值 | 说明
0 | 简化的光源和材质模型；最快但最不真实。全局照明、反射和折射处于禁用状态。
1 | 基本光源和材质模型；平衡性能和真实感。全局照明处于启用状态，反射和折射处于禁用状态。
2 | 高级光源和材质模型；较慢但更真实。全局照明、反射和折射处于启用状态。


* RENDERPREFSSTATE
指示“渲染预设管理器”选项板是处于打开状态还是关闭状态。
（只读）
类型:	整数
保存位置:	未保存
初始值:	0
值 、 说明
0 | 关闭
1 | 打开
* RENDERTARGET
控制渲染引擎要使用的渲染持续时间类型。

类型:	整数
保存位置:	图形
初始值:	0
值 | 说明
0 | 按级别渲染；渲染图像的质量取决于由 RENDERLEVEL 系统变量指定的层级数或迭代。将继续迭代渲染，直至实现目标渲染级别。
1 | 按时间渲染；渲染图像的质量取决于由 RENDERTIME 系统变量指定的分钟数。将继续迭代渲染，直到用完该时间。注意:渲染器在指定的时间内可完成的层级数或迭代取决于三维模型的复杂程度。
2 | 持续渲染，直至满意；将继续重复细化渲染图像，直至取消渲染操作。

* RENDERTIME
指定渲染引擎用于反复细化渲染图像的分钟数。
类型:	整数
保存位置:	图形
初始值:	10
渲染引擎将分析不同迭代（或层级）之间的渲染图像结果，以确定可以改进的地方。增加渲染时间可提高渲染图像的质量，因为可以执行更多的迭代，但是使用较长的渲染时间可能会使迭代之间的改进变得难以区分。

有效取值范围为 1 到 32767。

RENDERTARGET 系统变量指示渲染是基于固定层级数还是时间限制来控制渲染图像的质量。渲染时间限制由此系统变量指定，而级别数或迭代数由 RENDERLEVEL 系统变量指定。
* RENDERUSERLIGHTS
控制是否在渲染过程中替代视口光源的设置。

类型:	整数
保存位置:	注册表
初始值:	1
提供一种方式，在保留用于在视口中进行操作的设置的同时替代用于渲染的 DEFAULTLIGHTING 系统变量。

值 | 说明
0 | 在渲染的场景中使用视口中的当前光源，或者使用默认光源或者使用用户光源，这由 DEFAULTLIGHTING 系统变量指定。
1 | 替代 DEFAULTLIGHTING 系统变量的设置。仅渲染用户光源。
* REPORTERROR
控制程序异常关闭时是否可以向 Autodesk 发送错误报告。

类型:	整数
保存位置:	注册表
初始值:	1
错误报告帮助 Autodesk 诊断软件问题。

值 | 说明
0 | 不显示错误报告信息，并且不能向 Autodesk 发送报告。
1 | 显示错误报告消息，并且可以向 Autodesk 发送错误报告。

如果 REPORTERROR 设定为 0（零）而且操作系统支持错误报告，则可以通过操作系统发送错误报告。

* REVCLOUDAPPROXARCLEN
存储修订云线的当前近似弧长。

类型:	实数
保存位置:	注册表
初始值:	0.0000
当 REVCLOUDARCVARIANCE 设置为 1 时，存储的值将用于计算修订云线的最小和最大弧长。

最小弧长 = 值 x 2/3
最大弧长 = 值 x 1 1/3
如果 REVCLOUDARCVARIANCE 设置为 0，则存储的值将用作修订云线的实际弧长。
* REVCLOUDARCVARIANCE
控制在创建修订云线圆弧时是使用不同弦长还是大致均匀的弦长。
类型:	参数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 使用大致均匀的弦长创建圆弧
1 | 弧是使用不同弦长创建的，从而产生手绘感更强的外观。

注意:均匀弦长会稍有不同，具体取决于修订云线的大小、形状和周长。
* REVCLOUDCREATEMODE
指定用于创建修订云线的默认输入。

类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 徒手画
1 | 矩形
2 | 多边形
* REVCLOUDGRIPS
控制修订云线上显示的夹点数。

类型:	参数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 为修订云线上的每个圆弧段显示夹点（传统行为）
1 | 在修订云线上显示有限数量的夹点
* REVCLOUDMAXARCLENGTH
旧式的。存储修订云线的最大弧长。

* REVCLOUDMINARCLENGTH
旧式的。存储修订云线的最小弧长。

* RIBBONBGLOAD
控制功能区选项卡是否在处理器空闲时间由后台进程加载到内存中。
类型:	整数
保存位置:	注册表
初始值:	1
将工作空间中所有功能区选项卡的内容加载到内存中，可以显著提高在单击功能区选项卡时它们的显示速度。所用的内存不超过分别打开工作空间中的每个选项卡时所用的内存。

值 | 说明
0 | 仅在需要时将功能区选项卡的内容加载到内存中。
1 | 在处理器空闲时间将功能区选项卡的内容加载到内存中。

* RIBBONCONTEXTSELLIM
限制可以使用功能区特性控件或上下文选项卡一次更改的对象数。
类型:	整数
保存位置:	用户设置
初始值:	2500
有效范围为 0 到 32767。如果设定为 0，则会关闭限制。如果超出限制，功能区特性控件和面板将灰显。

如果选择大量对象并使用“特性”面板或某个功能区上下文选项卡更改这些对象，可能会导致响应时间很慢。此系统变量可防止出现此类情况，尤其对于内存有限的计算机。

注意:“特性”和“快捷特性”选项板不受此系统变量影响，但会受 PROPOBJLIMIT 系统变量的限制。

* RIBBONDOCKEDHEIGHT
确定是将水平固定的功能区设定为当前选项卡的高度还是预先定义的高度。

类型:	整数
保存位置:	注册表
初始值:	100
有效范围从 0 到 500。设定为 0 时，功能区会始终将自身大小调整为符合选定选定卡的高度。设定为 1 到 500 之间的任意值时，功能区的高度会始终为该像素数。
* RIBBONICONRESIZE
控制是否将功能区上的图标大小调整为标准大小。

类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 图像大小不会调整；它们基于其实际尺寸显示
1 | 调整图像大小以使其适合；小图像大小调整到 16x16 像素，大图像大小调整到 32x32 像素

* RIBBONSELECTMODE
决定调用功能区上下文选项卡并完成命令后预先选择集是否仍处于选中状态。

类型:	整数
保存位置:	用户设置
初始值:	1
值 | 说明
0 | 在执行功能区上下文选项卡中的命令后，预先选择的选择集将不再处于选中状态。注意:对于某些命令可能例外。
1 | 从功能区上下文选项卡执行命令后，预先选择集保持选定状态。
* RIBBONSTATE
指示功能区选项板处于打开状态还是关闭状态。
（只读）
类型:	整数
保存位置:	未保存
初始值:	1
值 | 说明
0 | 关闭
1 | 打开
* ROAMABLEROOTPREFIX
存储根文件夹的完整路径，该文件夹中安装了可漫游的可自定义文件。
（只读）
类型:	字符串
保存位置:	注册表
初始值:	不确定
如果在支持漫游的网络上工作，则不管当前使用哪台计算机，您都可以访问位于漫游配置中的自定义文件。

这些自定义文件存储在以下路径：

drive_letter:\Users\user_name\AppData\Roaming\Autodesk\product_name\version\language_code\

* ROLLOVEROPACITY
控制光标移动到选项板上时选项板的透明度。

类型:	整数
保存位置:	注册表
初始值:	100
值 | 说明
0 | 完全透明
100 | 完全不透明
输入一个 0 到 100 之间的值以设定透明度级别。

此系统变量决定“透明度”对话框中的默认设置 >“鼠标悬停”区域 >“鼠标悬停于上方时选项板的透明度:”选项。

* ROLLOVERTIPS
控制当光标悬停在对象上时鼠标悬停工具提示的显示。

类型:	整数
保存位置:	注册表
初始值:	1
可以在自定义用户界面 (CUI) 编辑器中对工具提示中的内容进行自定义。

值 | 说明
0 | 不显示对象光标悬停工具提示
1 | 显示对象光标悬停工具提示
* RTDISPLAY
控制执行实时 ZOOM 或 PAN 命令时光栅图像和 OLE 对象的显示。
类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 显示光栅图像和 OLE 内容
1 | 仅显示轮廓
* RTREGENAUTO
控制实时平移和缩放操作中的自动重生成。

类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 阻止在平移和缩放时自动重新生成。
1 | 允许在平移和缩放时自动重新生成。

此系统变量主要用于控制在非常大的图形中平移和缩放时的自动重新生成。

* SAFEMODE
指示是否可在当前 AutoCAD 任务中加载和执行可执行代码。
（只读）
类型:	整数
保存位置:	未保存
初始值:	0
该系统变量由 /safemode 启动开关控制，应当仅用于禁用恶意代码的紧急情况。

值 | 说明
0 | 允许执行可执行代码
1 | 禁止执行可执行代码

注意:禁用可执行代码将使 Express Tool 和某些 AutoCAD 命令工具停止运行。它还会禁止将 AutoLISP 代码复制和粘贴到“命令”窗口。

* SAVEFIDELITY
在 AutoCAD 2007 及更早版本中控制注释性对象的视觉逼真度。
类型:	整数
保存位置:	注册表
初始值:	1
保存为 AutoCAD 2007 或早期版本的文件格式时，此设置仅影响图形。

值 | 说明
0 | 注释性对象保留在其指定的图层上。
1 | 已指定给注释对象的注释性比例将保存至使用的每种比例的独立图层中。

* SAVEFILE
存储当前自动保存的文件名。

* SAVEFILEPATH
指定当前任务中所有自动保存文件的文件夹路径。

* SAVENAME
显示最近保存的图形的文件名和文件夹路径。

* SAVETIME
设置自动保存时间间隔，以分钟为测量单位。
类型:	整数
保存位置:	注册表
初始值:	10
值 | 说明
0 | 关闭自动保存
>0 | 以指定的时间间隔（分钟）自动保存图形。

SAVETIME 的值为从 0 到 600 的整数。

一旦用户对图形进行更改，SAVETIME 计时器就开始计时。手动执行 QSAVE、SAVE 或 SAVEAS 命令后，计时器将被重置并重新开始计时。当前图形将被保存到由 SAVEFILEPATH 系统变量指定的路径。文件名则存储在 SAVEFILE 系统变量中。

注意:要优化速度，自动保存将递增，并用值 90 临时替代 ISAVEPERCENT 的值。仅当更改数目超过 ISAVEPERCENT 设置时，才会发生完全保存。
* SCREENMODE
指示显示的状态。
（只读）
类型:	整数
保存位置:	未保存
初始值:	3
系统将使用下列位码值之和将该设置存储为一个位码：

值 | 说明
0 | 显示文本屏幕
1 | 显示绘图区域
2 | 配置为双屏幕显示
* SCREENSIZE
以像素为单位存储当前视口大小（X 和 Y）。
（只读）
类型:	二维点
保存位置:	未保存
初始值:	不确定
* SECTIONOFFSETINC
设定单击控件时截面对象到截面平面的偏移距离。
设定单击控件时截面对象到截面平面的偏移距离。

类型:	实数
保存位置:	图形
初始值:	6.0000
此值可控制“截面平面”选项卡 “调整切片”面板上“截面偏移”控件的默认增量或减小值。

例如，如果 SECTIONOFFSETINC 设置为 10.000 个点，则在“截面平面”选项卡 “调整切片”面板 “截面偏移”控件上按一次上箭头，可偏移截面对象 10 个点。同样，按一次下箭头可减小 10 个点的偏移。
* SECTIONTHICKNESSINC
设置截面切片厚度控件增加或减少的点数。

类型:	实数
保存位置:	图形
初始值:	1.0000
该值可控制切片厚度控件的默认增量值。该控件位于“截面平面”选项卡 “调整切片”面板上。

例如，如果 SECTIONTHICKNESSINC 值设置为 5.000 点，则单击向上或向下箭头将使截面切片厚度一次增加或减少 5 点。

* SECURELOAD
控制可执行文件是否限于仅从受信任文件夹加载
类型:	整数
保存位置:	注册表
初始值:	1，可能已由 CAD 管理员锁定
值 | 说明
0 | 从任何位置加载可执行文件，而不显示警告。此选项将保留传统行为，但不建议使用。
1 | 仅当可执行文件的位置位于 TRUSTEDPATHS 系统变量中指定的受信任位置时才进行加载。从其他位置的可执行文件加载请求时，将显示一条警告。
2 | 仅当可执行文件的位置位于 TRUSTEDPATHS 系统变量中指定的受信任位置时才允许进行加载。

受 SECURELOAD 影响的可执行文件类型包括以下几种：

ARX、DBX、CRX、HDI 文件
LSP、FAS、VLX、MNL 文件
SCR 文件（来自网络路径）
.NET 程序集
VBA 宏（DVB 文件）
acad.rx
JavaScript
DLL 文件
重要信息:
LEGACYCODESEARCH 系统变量控制搜索可执行文件是否包括程序启动时所在的文件夹。
ACADLSPASDOC 系统变量确定是将 acad.lsp 文件加载到每个图形中，还是仅加载到任务中打开的第一个图形中。使用 LOAD 函数时，AutoLISP 文件必须位于要查找的“支持文件搜索路径”中，否则相对路径必须包含在 Filename 参数中。
SECUREREMOTEACCESS 系统变量控制是否限制从 Internet 位置或远程服务器访问文件。

* SECUREREMOTEACCESS
控制是否限制ObjectARX程序访问Internet位置或远程服务器。
类型:	参数
保存位置:	注册表
初始值:	1
为帮助防止ObjectARX网络API调用中的恶意代码，将值设置为1会阻止以下操作：

使用AcadHostApplicationServices :: getRemoteFile（）将远程文件复制到本地计算机。
使用AcadHostApplicationServices :: putRemoteFile（）将文件上载到远程位置。
值 | 说明
0 | 允许使用ObjectARX访问任何位置，包括Internet或远程服务器。此选项可维护旧行为。
1 | 阻止使用ObjectARX访问Internet或远程服务器。仅当文件是本地文件时才加载文件。此设置在2020.1产品更新中进行了扩展，可能会干扰某些应用程序。

启用SECUREREMOTEACCESS会降低使用ObjectARX将应用程序或恶意软件加载到本地计算机或从本地计算机复制文件的可能性。

* SELECTIONANNODISPLAY
控制选定注释性对象后，备用比例图示是否暂时以暗显状态显示。

类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 关闭
1 | 打开

暗显度由 XFADECTL 系统变量控制。
* SELECTIONAREA
控制选择区域的显示效果。

类型:	整数
保存位置:	注册表
初始值:	1
当选择对象时，选择区域是通过“窗口(W)”、“窗交(C)”、“圈围(WP)”和“圈交(CP)”选项创建的。

值 | 说明
0 | 关闭
1 | 打开
* SELECTIONAREAOPACITY
控制进行窗口选择和窗交选择时选择区域的透明度。
类型:	整数
保存位置:	注册表
初始值:	25
有效取值范围为 0 到 100。设置越低，区域越透明。值为 100 时，区域将变得不透明。必须打开 SELECTIONAREA 系统变量，才能查看此效果。
* SELECTIONCYCLING
控制与重叠对象和选择循环关联的显示选项。
类型:	整数
保存位置:	注册表
初始值:	0
将鼠标悬停在重叠的二维对象上时，会提供选项以发送警告并在对象之间选择。

值 | 说明
0 | 已禁用显示选项
1 | 当您将鼠标悬停在重叠的对象上时，将显示标记
2 | 将同时显示标记和“选择”对话框

按 Ctrl+W 组合键可以切换打开和关闭当前设置。

当 SELECTIONCYCLING 设置为负值时，将关闭选择循环，但会存储该设置。
* SELECTIONEFFECT
指定对象处于选中状态时所使用的视觉效果。
类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 虚线
1 | 当硬件加速处于启用状态时，将显示光晕线亮显效果

* SELECTIONEFFECTCOLOR
设置对象选择上的光晕亮显效果的颜色。

类型:	整数
保存位置:	注册表
初始值:	0
有效值为从 1 到 255（AutoCAD 颜色索引 (ACI) 颜色）。

注意:SELECTIONEFFECTCOLOR 系统变量仅在 SELECTIONEFFECT 设置为 1 时才适用。
* SELECTIONOFFSCREEN
控制屏幕外对象的选择。
类型:	整数
保存位置:	注册表
初始值:	1
SELECTIONOFFSCREEN 设置为启用时，屏幕外的对象（图形中的点 1 位于主要显示屏幕之外）现在可以参与选择。


值 | 说明
0 | 屏幕外选择处于禁用状态
1 | 屏幕外选择处于启用状态，具有仅支持鼠标输入的限制。此外，在选择时“缩放/平移”会达到某些限制。
2 | 屏幕外选择处于启用状态，无限制.注意:将 SELECTIONOFFSCREEN 设置为 2 时，选择结果有可能不正确。这仅适用于实验目的。
* SELECTIONPREVIEW
控制选择预览的显示。
类型:	位码
保存位置:	注册表
初始值:	3
当拾取框光标滚动过对象时，对象将被亮显。亮显表示通过单击可选定对象。系统将使用下列位码值之和将该设置存储为一个位码：

值 | 说明
0 | 关闭
1 | 当无激活的命令时开
2 | 当命令提示选择对象时开

注意:如果 COMMANDPREVIEW 处于打开状态，将忽略 SELECTIONPREVIEW 系统变量的值。
* SELECTIONPREVIEWLIMIT
限制在窗口或窗交选择期间可以显示预览亮显的对象数。

类型:	整数
保存位置:	注册表
初始值:	20000
使用窗口选择或窗交方法选择大量对象时，预览亮显有时会影响程序性能。在处理大型、复杂的图形时，您可能想要减小此数值。一旦选择集超出此设置中的数值，将停止所有预览亮显。

除非 SELECTIONPREVIEW 处于启用状态，否则此设置将不起作用。
* SELECTSIMILARMODE
控制对于将使用 SELECTSIMILAR 选择的同类型对象，必须匹配哪些特性。
类型:	位码
保存位置:	用户设置
初始值:	130
默认值为 130。如果类型相同的对象位于同一个图层上，则视为类似对象；而对于参照对象，如果其名称相同，则视为类似对象。

系统将使用下列位码值之和将该设置存储为一个位码：

值 | 说明
0 | 对象类型
1 | 颜色
2 | 图层
4 | 线型
8 | 线型比例
16 | 线宽
32 | 打印样式
64 | 对象样式，包括文字样式、标注样式和表格样式
128 | 名称，用于参照对象（包括块、外部参照和图像）

* SETBYLAYERMODE
控制为 SETBYLAYER 命令选择哪些特性。

类型:	整数
保存位置:	注册表
初始值:	255
系统将使用以下值之和将该设置存储为一个整数：

值 | 说明
0 | 未选择特性
1 | 颜色特性
2 | 线型特性
4 | 线宽特性
8 | 材质特性
16 | 打印样式特性
32 | 将“ByBlock”更改为“Bylayer”
64 | 将“ByBlock”更改为“ByLayer”时包括块
128 | 透明度特性
* SHADEDGE
控制边的着色。

类型:	整数
保存位置:	图形
初始值:	3
值 | 说明
0 | 表面着色，边缘不亮显
1 | 表面着色，边以背景色绘制
2 | 表面不填充，边以对象的颜色绘制
3 | 表面为对象的颜色，边以背景色绘制

* SHADEDIF
设置漫反射光与环境光的比率。

类型:	整数
保存位置:	图形
初始值:	70
SHADEDGE 设置为 0 或 1 时，该比率为漫反射光百分比。
* SHADOWPLANELOCATION
控制用于显示阴影的不可见地平面的位置。

类型:	实数
保存位置:	图形
初始值:	0.0000
该值为当前 Z 轴上的位置。地平面不可见，但会投射和接收阴影。位于地平面之下的对象由地平面投射阴影。VSSHADOWS 系统变量设置为显示全阴影或地面阴影时，可使用地平面。

* SHAREDVIEWSTATE
指示“共享视图”选项板处于打开状态还是关闭状态。
（只读）
类型:	整数
保存位置:	注册表
初始值:	0
值 | 说明
0 | 关闭
1 | 打开
* SHAREVIEWPROPERTIES
控制共享视图是否包含图形特性。

类型:	整数
保存位置:	注册表
初始值:	0
值 | 说明
0 | 共享视图不包含图形特性。
1 | 共享视图包含图形特性。
* SHAREVIEWTYPE
控制是从当前视图、模型空间或某一布局中创建共享视图，还是从整个图形中创建共享视图。

类型:	整数
保存位置:	注册表
初始值:	0
值 | 说明
0 | 为当前空间、模型空间或某一布局创建共享视图。
1 | 为整个图形、模型空间和所有布局创建共享视图。

* SHORTCUTMENU
控制“默认”、“编辑”和“命令”模式的快捷菜单在绘图区域是否可用。
类型:	整数
保存位置:	注册表
初始值:	11
系统将使用下列位码值之和将该设置存储为一个位码：

值 | 说明
0 | 禁用所有默认模式、编辑模式和命令模式的快捷菜单。
1 | 启用默认模式的快捷菜单。
2 | 启用编辑模式的快捷菜单。
4 | 一旦有命令处于活动状态，就可以启用命令模式的快捷菜单。
8 | 仅当命令选项当前于命令提示下可用时，才启用命令模式的快捷菜单。
16 | 当以足够长的时间按下定点设备上的右键时，才会显示快捷菜单

注意:如果将此系统变量设置为大于 15 的值，则 SHORTCUTMENUDURATION 系统变量确定必须按住定点设备上的右键多长时间才显示快捷菜单。
* SHORTCUTMENUDURATION
指定必须按下定点设备的右键多长时间才会在绘图区域中显示快捷菜单。
类型:	整数
保存位置:	注册表
初始值:	250
该值以毫秒为单位，有效范围为 100 到 10000。

如果按住右键的时长等于或大于此系统变量的值，将显示快捷菜单。

如果按住右键的时间较短，其结果与按 Enter 键相同。

注意:SHORTCUTMENU 系统变量必须设置为大于 15 的值，此系统变量才生效。
* SHOWHIST
控制图形中实体的“显示历史记录”特性。
类型:	整数
保存位置:	图形
初始值:	1
值 | 说明
0 | 将所有实体的“显示历史记录”特性设定为“否”（只读）。替代实体的各个“显示历史记录”特性设置。用户无法查看用于创建实体的原始对象。
1 | 不替代实体的各个“显示历史记录”特性设置。
2 | 通过替代实体的各个“显示历史记录”特性设置，显示所有实体的历史记录。用户可以查看用于创建实体的原始对象。
* SHOWLAYERUSAGE
在图层特性管理器中显示图标以指示图层是否处于使用状态。

类型:	整数
保存位置:	注册表
初始值:	0
值 | 说明
0 | 禁用，可在图层特性管理器中提高性能
1 | 启用，将显示用来指示图层是否正被使用的图标
* SHOWMOTIONPIN
控制缩略图图像的默认状态。
类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 以不固定状态显示缩略图快照
1 | 以固定状态显示缩略图快照

* SHOWNEWSTATE
指示更新中亮显的新功能是否处于活动状态。
类型:	整数
保存位置:	注册表
初始值:	0
该系统变量由 HIGHLIGHTNEW 命令控制。

值 | 说明
0 | 常规行为
1 | 通过在功能区按钮、对话框和选项板上显示点来亮显更新到当前版本后的新增功能

* SHOWPAGESETUPFORNEWLAYOUTS
指定在创建新布局时是否显示页面设置管理器。

类型:	整数
保存位置:	注册表
初始值:	0
值 | 说明
0 | 关闭：创建新布局时，不显示页面设置管理器
1 | 打开：创建新布局时，显示页面设置管理器

* SHOWPALETTESTATE
指示是否通过 HIDEPALETTES 命令隐藏选项板，或通过 SHOWPALETTES 命令恢复选项板。
（只读）
类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 表明存在由 HIDEPALETTES 命令隐藏的选项板
1 | 表明由 HIDEPALETTES 命令隐藏的所有选项板都已由 SHOWPALETTES 命令恢复

* SHPNAME
设置默认的形名称（必须遵守符号命名约定）。
类型:	字符串
保存位置:	未保存
初始值:	""
如果没有设置默认名称，则返回 ""。输入句点 (.)将设定为无默认值。
* SIGWARN
控制打开附着数字签名的文件时是否发出警告。
类型:	整数
保存位置:	注册表
初始值:	1
如果在该系统变量为“打开”时打开一个带有有效数字签名的文件，则显示数字签名状态。如果在该系统变量为“关闭”时打开一个文件，则仅在数字签名无效时才显示数字签名状态。可以使用“选项”对话框“打开和保存”选项卡上的“显示数字签名信息”选项设置该变量。

值 | 说明
0 | 当文件具有有效签名时不发出警告
1 | 发出警告
* SKETCHINC
设置用于 SKETCH 命令的记录增量。

* SKPOLY
确定 SKETCH 命令生成的是直线、多段线还是样条曲线。

* SKTOLERANCE
确定样条曲线布满手画线草图的紧密程度。

* SKYSTATUS
决定渲染时是否计算天空照明。

* SMOOTHMESHCONVERT
控制是对转换为三维实体或曲面的网格对象进行平滑处理还是进行镶嵌，以及是否合并它们的面。

* SMOOTHMESHGRID
设置底层网格镶嵌面栅格显示在三维网格对象中时的最大平滑度。

* SMOOTHMESHMAXFACE
设置网格对象允许使用的最大面数。

* SMOOTHMESHMAXLEV
设置网格对象的最大平滑度。

* SNAPANG
相对于当前 UCS 设置当前视口的捕捉和栅格旋转角度。

* SNAPBASE
相对于当前 UCS 设置当前视口的捕捉和栅格原点。

* SNAPGRIDLEGACY
控制光标是否仅在操作正在进行时捕捉到捕捉栅格。

* SNAPISOPAIR
控制当前视口的等轴测平面。

* SNAPMODE
在当前视口中打开和关闭捕捉模式。

* SNAPSTYL
将栅格和栅格捕捉设置为当前视口的矩形或等轴测。

* SNAPTYPE
为当前视口设置捕捉类型（矩形或环形）。

* SNAPUNIT
设置当前视口的捕捉间距。

* SOLIDCHECK
为当前任务打开和关闭三维实体校验。

* SOLIDHIST
控制新复合实体是否保留其原始零部件的历史记录。

* SORTENTS
控制对象排序，以支持若干操作的绘图次序。
类型:	整数
保存位置:	图形
初始值:	127
系统将使用下列位码值之和将该设置存储为一个位码：

值 | 说明
0 | 关闭所有对象排序
1 | 为选择的对象排序
2 | 为捕捉的对象排序
4 | 已废弃，不起作用
8 | 已废弃，不起作用
16 | 已废弃，不起作用
32 | 为打印排序
64 | 已废弃，不起作用
* SORTORDER
指定是使用自然排序顺序还是 ASCII 值来排序图层列表。
类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | ASCII 排序顺序（传统行为）
1 | 自然排序顺序（从基于 AutoCAD 2014 的产品开始）

* SPACESWITCH
控制是否可以通过在布局视口内双击来访问模型空间。

类型:	整数
保存位置:	未保存
初始值:	1
如果图纸空间中有注释并且您不希望出现意外激活布局视口中模型空间的情况，请将此系统变量更改为 0（零）。您仍然可以使用 MSPACE 命令访问模型空间。

值 | 说明
0 | 阻止对模型空间的访问
1 | 允许对模型空间的访问
* SPLDEGREE
存储最近使用的样条曲线阶数设置，并设定在指定控制点时 SPLINE 命令的默认阶数设置。

* SPLFRAME
控制螺旋和平滑处理的网格对象的显示。

* SPLINESEGS
设置要为每条样曲线条拟合多段线（此多段线通过 PEDIT 命令的“样条曲线”选项生成）生成的线段数目。

* SPLINETYPE
设置由 PEDIT 命令的“样条曲线”选项生成的曲线类型。

* SPLKNOTS
当指定拟合点时，存储 SPLINE 命令的默认节点选项。

* SPLMETHOD
存储用于 SPLINE 命令的默认方法是拟合点还是控制点。

* SPLPERIODIC
控制是否生成具有周期性特性的闭合样条曲线和 NURBS 曲面以保持在闭合点或接合口处的最平滑的连续性。

* SSFOUND
如果搜索图纸集成功，则显示图纸集路径和文件名。

* SSLOCATE
控制打开图形时是否找到并打开与该图形相关联的图纸集。

* SSMAUTOOPEN
控制打开与图纸相关联的图形时图纸集管理器的显示行为。

* SSMPOLLTIME
控制图纸集中状态数据的自动刷新时间间隔。

* SSMSHEETSTATUS
控制图纸集中状态数据的刷新方式。

* SSMSTATE
指示“图纸集管理器”窗口处于打开状态还是关闭状态。

* STANDARDSVIOLATION
指定创建或修改非标准对象时，是否通知用户当前图形中存在标准冲突。

* STARTINFOLDER
存储从中启动产品的驱动器和文件夹路径。
（只读）
类型:	字符串
保存位置:	注册表
初始值:	不确定
“起始”文件夹可以由使用桌面快捷方式图标设置的“起始”属性确定，或由双击文件以启动产品所在的文件夹确定。作为一项安全措施，LEGACYCODESEARCH 系统变量可以排除搜索“起始”文件夹中的可执行文件。LEGACYCODESEARCH 系统变量在 AutoCAD LT 中不可用或不需要。

根据产品的安装方式和启动方式，“起始”文件夹可能会有所不同。典型的路径可能是 C:\Program Files\Autodesk\AutoCAD 20xx\UserDataCache\，其中 20xx 是版本号。
* STARTMODE
控制“开始”选项卡的显示。
类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 关闭“开始”选项卡，它将在您下次启动应用程序时禁用。
1 | “开始”选项卡处于启用和显示状态。

注意: 将 STARTMODE 的值从 0（零）更改为 1 时，您必须重新启动 AutoCAD 以显示“开始”选项卡。如果您在单个文档模式 (SDI =1) 下运行 AutoCAD，“开始”选项卡将在您将 SDI 的值更改为 0（零）并重新启动 AutoCAD 之后显示。

* STARTUP
控制在应用程序启动时或打开新图形时显示的内容。

类型:	整数
保存位置:	注册表
初始值:	3
控制使用 NEW 和 QNEW 命令创建新图形时，是否显示“创建新图形”对话框。还控制当应用程序启动时是显示“启动”对话框还是显示“开始”选项卡。

如果将 FILEDIA 系统变量设定为 0（零），则将不显示文件对话框。

值 | 说明
0 | 在未定义设置的情况下启动图形。
1 | 显示“启动”或“创建新图形”对话框。
2 | 将显示“开始”选项卡。如果该选项卡在应用程序中可用，将显示自定义对话框。
3 | 在您打开或创建新图形时，将显示“开始”选项卡并预加载功能区。
* STATUSBAR
控制状态栏的显示。

类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0  | 隐藏状态栏
1  | 显示状态栏
* STEPSIZE
指定漫游或飞行模式中每一步的大小（以图形单位表示）。
类型:	实数
保存位置:	图形
初始值:	6.0000
用户可以输入 1E-6 到 1E+6 之间的任意实数。
* STEPSPERSEC
指定漫游或飞行模式中每秒执行的步数。

类型:	实数
保存位置:	图形
初始值:	2.0000
用户可以输入 1 到 30 之间的任意实数。
* STUDENTDRAWING
报告当前图形是否已与 Autodesk 学生版产品一起保存。

* SUBOBJSELECTIONMODE
过滤在将鼠标悬停于面、边、顶点或实体历史记录子对象上时是否亮显它们。

* SUNPROPERTIESSTATE
指示“阳光特性”窗口处于打开状态还是关闭状态。

* SUNSTATUS
打开和关闭当前视口中阳光的光源效果。
* SUPPRESSALERTS
控制关于在早期版本的产品中打开和保存新图形时可能会丢失数据的警告。

* SURFACEASSOCIATIVITY
控制曲面是否保留与从中创建了曲面的对象的关系。

* SURFACEASSOCIATIVITYDRAG
设置关联曲面的拖动预览行为。

* SURFACEAUTOTRIM
设定在将几何图形投影到曲面上时是否自动修剪曲面。

* SURFACEMODELINGMODE
控制是将曲面创建为程序曲面还是 NURBS 曲面。

* SURFTAB1
为 RULESURF 和 TABSURF 命令设置要生成的表格数目。

* SURFTAB2
为 REVSURF 和 EDGESURF 命令设置在 N 方向的网格密度。

* SURFTYPE
控制 PEDIT 命令的“平滑”选项要执行的曲面拟合类型。

* SURFU
为 PEDIT 命令的“平滑”选项设置在 M 方向的曲面密度以及曲面对象上的 U 素线密度。

* SURFV
为 PEDIT 命令的“平滑”选项设置在 N 方向的曲面密度以及曲面对象上的 V 素线密度

* SYSCODEPAGE
指示由操作系统决定的系统代码页。

* SYSFLOATING
控制图形文件选项卡的固定状态。

* SYSMON
控制是否监视定义的系统变量列表。
类型:	整数
保存位置:	用户设置
初始值:	1
值 | 说明
0 | 不监视系统变量。
1 | 监视系统变量。将在命令行和状态栏上显示关于系统变量值修改的通知。
2 | 监视系统变量。将在命令行和状态栏上显示关于系统变量值修改的通知。还会显示气泡式通知。

* TABLEINDICATOR
控制当打开在位文字编辑器以编辑表格单元时，行编号和列字母的显示。

类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 关闭
1 | 打开
* TABLETOOLBAR
控制表格工具栏的显示。
类型:	整数
保存位置:	注册表
初始值:	2
值 | 说明
0 | 从不显示表格工具栏。
1 | 选择表格单元时将显示表格工具栏。
2 | 功能区处于打开状态时不显示表格工具栏。
* TABMODE
控制数字化仪输入设备的使用。

类型:	整数
保存位置:	未保存
初始值:	0
有关使用和配置数字化仪的详细信息，请参见 TABLET 命令。

值 | 说明
0 | 关闭
1 | 打开
* TARGET
存储目标点的 UCS 坐标以用于当前视口中的透视投影。
（只读）
类型:	三维点
保存位置:	图形
初始值:	0.0000,0.0000,0.0000
* TBCUSTOMIZE
控制是否可以自定义工具选项板组。
类型:	参数
保存位置:	注册表
初始值:	1
控制 CUSTOMIZE 命令是否可用于工具选项板组自定义，以及是否在工具栏快捷菜单中显示“自定义”选项。

值 | 说明
0 | 禁止访问自定义
1 | 允许访问自定义
* TBSHOWSHORTCUTS
指定使用 Ctrl 键和 Alt 键的快捷键是否显示在工具栏的工具提示上。
类型:	字符串
保存位置:	注册表
初始值:	是
值 | 说明
是 | 显示 Ctrl 键和 Alt 键的快捷键
NO | 不显示 Ctrl 键和 Alt 键的快捷键

* TDCREATE
存储创建图形时的本地时间和日期。
（只读）
类型:	实数
保存位置:	图形
初始值:	不确定
注意:从基于 AutoCAD 2017 的产品开始，TDCREATE 中存储的时间将精确到最接近的秒；但在以前的版本中，该时间还包括毫秒。
相关
* TDINDWG
存储总的编辑时间，即在两次保存当前图形之间花费的总时间。
（只读）
类型:	实数
保存位置:	图形
初始值:	不确定
格式为：

<number of days>.<decimal fraction of a day>
要计算秒数，请将 TDINDWG 中的小数部分乘以 86400 秒。

注意:从基于 AutoCAD 2017 的产品开始，TDINDWG 中存储的时间将精确到最接近的秒；但在以前的版本中，该时间还包括毫秒。

* TDUCREATE
存储创建图形时的通用时间和日期。
（只读）
类型:	实数
保存位置:	图形
初始值:	不确定
注意:从基于 AutoCAD 2017 的产品开始，TDUCREATE 中存储的时间将精确到最接近的秒；但在以前的版本中，该时间还包括毫秒。

* TDUPDATE
存储上次更新/保存时的本地时间和日期。
（只读）
类型:	实数
保存位置:	图形
初始值:	不确定
注意:从基于 AutoCAD 2017 的产品开始，TDUPDATE 中存储的时间将精确到最接近的秒；但在以前的版本中，该时间还包括毫秒。

* TDUSRTIMER
存储用户花费时间计时器。
（只读）
类型:	实数
保存位置:	图形
初始值:	不确定
注意:从基于 AutoCAD 2017 的产品开始，TDUSRTIMER 中存储的时间将精确到最接近的秒；但在以前的版本中，该时间还包括毫秒。
* TDUUPDATE
存储上次更新或保存时的世界标准时间和日期。
（只读）
类型:	实数
保存位置:	图形
初始值:	不确定
注意:从基于 AutoCAD 2017 的产品开始，TDUUPDATE 中存储的时间将精确到最接近的秒；但在以前的版本中，该时间还包括毫秒。

* TEMPOVERRIDES
打开或关闭用于绘图辅助的临时替代键。

类型:	整数
保存位置:	注册表
初始值:	1
按下临时替代值键可以临时打开或关闭在“草图设置”对话框中设置的某一个绘图辅助工具；例如，正交模式、对象捕捉或极轴模式。

值 | 说明
0 | 关闭
1 | 打开
* TEMPPREFIX
存储为临时文件指定的文件夹名称，附带路径分隔符。
（只读）
类型:	字符串
保存位置:	注册表
初始值:	不确定
窗口中临时文件的组合文件名和路径最多包含 255 个字符。可以在“选项”对话框中“文件”选项卡的“临时图形文件位置”下修改此限制。

* TEXTALIGNMODE
存储对齐文字的对齐选项。
类型:	整数
保存位置:	注册表
初始值:	9
这些设置可以在 TEXTALIGN 命令的对齐选项中更改。

值 | 说明
0 | 左上 - 在文字的顶部左对正（仅适用于水平方向的文字）。
1 | 上中 - 在文字的顶部居中（仅适用于水平方向的文字）。
2 | 右上 - 在文字的顶部右对正（仅适用于水平方向的文字）。
3 | 左中 - 在文字的中间左对正（仅适用于水平方向的文字）。
4 | 正中 - 在文字的中间以水平和垂直方向居中（仅适用于水平方向的文字）。
5 | 右中 - 在文字的中间右对正（仅适用于水平方向的文字）。
6 | 左下 - 在基线上左对正（仅适用于水平方向的文字）。
7 | 下中 - 在基线上居中（仅适用于水平方向的文字）。
8 | 右下 - 在基线上右对正（仅适用于水平方向的文字）。
9 | 左 - 在基线上左对正。
10 | 中 - 从基线的水平中心对齐。
11 | 右 - 在基线上右对正。
* TEXTALIGNSPACING
存储对齐文字的间距选项。

类型:	整数
保存位置:	注册表
初始值:	2
这些设置可以在 TEXTALIGN 命令的选项中更改。

值 | 说明
0 | 分布 - 将文字沿指定的对齐矢量均匀分布。
1 | 设置间距 - 按指定的距离沿指定的对齐矢量设置文字间距。
2 | 当前垂直 - 沿指定的对齐矢量使用当前垂直文字间距。
3 | 当前水平 - 沿指定的对齐矢量使用当前水平文字间距。
* TEXTALLCAPS
将通过 TEXT 或 MTEXT 命令创建的所有新文字转换为大写。
类型:	参数
保存位置:	注册表
初始值:	0
值 | 说明
0 | 关闭自动文字大写（传统行为）
1 | 打开自动文字大写
* TEXTAUTOCORRECTCAPS
更正因意外启用 Caps Lock 而导致的常见文本错误。

类型:	整数
保存位置:	注册表
初始值:	1
当此系统变量处于打开状态时，如果按 Shift 键来将首字符变为大写，AutoCAD 会自动更正它并关闭 Caps Lock 键。

值 | 说明
0 | 如果在键入时 Caps Lock 键被意外启用，请不要禁用它。
1 | 如果在键入时 Caps Lock 键被意外启用，请禁用它。
* TEXTED
指定创建和编辑单行文字时显示的用户界面。
类型:	整数
保存位置:	注册表
初始值:	2
这些设置将应用于使用 TEXT 命令创建的单行文字。

值 | 说明
0 | 创建或编辑单行文字时显示在位编辑器。
1 | 在创建单行文字时，接收命令行上的文字。编辑单行文字时显示“编辑文字”对话框。
2 | 与 0（零）相同，不同之处在于它将自动重复文字输入。
* TEXTEDITMODE
控制是否自动重复 TEXTEDIT 命令。
类型:	整数
保存位置:	注册表
初始值:	0
值 | 说明
0 | 将 TEXTEDIT 命令设置为自动重复
1 | 将 TEXTEDIT 命令设置为编辑单个文字对象

* TEXTEVAL
控制如何判定用 TEXT（使用 AutoLISP）或 -TEXT 输入的文字字符串。

类型:	整数
保存位置:	未保存
初始值:	0
值 | 说明
0 | 当提示输入文字字符串和属性值时，所有的响应都被视为文本。
1 | 以左圆括号“(”或叹号“!”开头的所有文字将被当作 AutoLISP 表达式进行计算，而不是用于非文本输入。

默认情况下，TEXT 命令将把所有输入内容都视为文本，而不考虑 TEXTEVAL 的设置，除非完全用脚本或 AutoLISP 表达式执行此命令。在命令提示下，-TEXT 命令遵循 TEXTEVAL 的设置。

注意:在 AutoCAD LT 中，TEXT 命令将把所有输入内容照字面意义视为文本，无论 TEXTEVAL 的设置如何，除非完全用脚本执行此命令。在命令提示下，-TEXT 命令遵循 TEXTEVAL 的设置。
* TEXTFILL
控制是否填充 TrueType 字体以用于打印。
类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 以轮廓线形式显示文字
1 | 以填充图像形式显示文字
* TEXTJUSTIFY
显示 TEXT 命令在创建单行文字时使用的默认对正方式。
（只读）
类型:	字符串
保存位置:	图形
初始值:	左
此设置将通过 TEXT 命令的“对正”选项进行更改。

值 | 说明
左 | 在基线上左对正。
中心 | 从基线的水平中心对齐。
右 | 在基线上右对正。
对齐 | 通过指定基线的端点来设置高度和文字方向。根据高度按比例调整字符大小。文字字符串越长，字符越矮。
中间 | 在基线的水平中点和高度的垂直中点上对齐。中间对齐的文字不保持在基线上。
调整 | 按照由两点和一个高度定义的方向布满一个区域（仅适用于水平方向的文字）。
左上 | 在文字的顶部左对正（仅适用于水平方向的文字）。
中上 | 在文字的顶部居中（仅适用于水平方向的文字）。
右上 | 在文字的顶部右对正（仅适用于水平方向的文字）。
左中 | 在文字的中间左对正（仅适用于水平方向的文字）。
MC | 在文字的中间以水平和垂直方向居中（仅适用于水平方向的文字）。
右中 | 在文字的中间右对正（仅适用于水平方向的文字）。
左下 | 在基线上左对正（仅适用于水平方向的文字）。
中下 | 在基线上居中（仅适用于水平方向的文字）。
右下 | 在基线上右对正（仅适用于水平方向的文字）。
* TEXTOUTPUTFILEFORMAT
提供日志文件的 Unicode 选项。
类型:	整数
保存位置:	注册表
初始值:	0
值 | 说明
0 | ANSI 格式
1 | UTF-8 (Unicode)
2 | UTF-16LE (Unicode)
3 | UTF-16BE (Unicode)
* TEXTQLTY
设置打印和渲染时 TrueType 文字的分辨率。
类型:	整数
保存位置:	未保存
初始值:	50
使用从 0 到 100 的整数值。较小的值会降低文字的平滑度，但会加快速度。较大的值会增加文字的平滑度，但会降低速度。

* TEXTSIZE
设置创建新文字对象时默认的文字高度。
类型:	实数
保存位置:	图形
初始值:	0.2000（英制）或 2.5000（公制）

如果当前文字样式具有固定的高度，那么 TEXTSIZE 将无效。
* TEXTSTYLE
设置当前文字样式的名称。

类型:	字符串
保存位置:	图形
初始值:	标准
* THICKNESS
在创建二维几何对象时，设置默认的三维厚度特性。

类型:	实数
保存位置:	图形
初始值:	0.0000
注意:在您想要向使用 RECTANG 和 TEXT 命令创建的对象添加三维厚度时，其中的例外是，三维厚度特性将使用“特性”选项板或 CHPROP 命令单独设置。单行文字必须设置为 SHX 文字字体以接受三维厚度。
* THUMBSAVE
控制是否将缩略图预览图像保存在图形中。
类型:	整数
保存位置:	注册表
初始值:	1
此系统变量替换 RASTERPREVIEW。

值 | 说明
0 | 无预览图像保存在图形中
1 | 在图形中创建和保存预览图像

预览图像处于启用状态时，在每次保存图形时都会更新以供所有缩略图图像使用。

注意:如果将图形保存为 AutoCAD 2010 或更早版本格式，图像可能不会有很高的质量。预览图像的显示质量由 THUMBSIZE 系统变量控制（不适用于 AutoCAD LT）。
* THUMBSIZE
为所有缩略图预览图像指定显示分辨率（以像素为单位）。

类型:	整数
保存位置:	注册表
初始值:	3
将预览图像保存到图形中的行为是否由 THUMBSAVE 系统变量控制。

值 | 说明
0 | 64x64
1 | 128x128
2 | 256x256
3 | 512 x 512
4 | 1024 x 1024
5 | 1440 x 1440
6 | 1600 x 1600
7 | 1920 x 1920
8 | 2560 x 2560
* THUMBSIZE2D
指定二维线框缩略图预览的大小是否由 THUMBSIZE 系统变量控制。如果禁用，则使用二维线框视觉样式的图形预览的显示分辨率将设置为 256 x 256 像素。
指定二维线框缩略图预览的大小是否由 THUMBSIZE 系统变量进行控制。如果禁用，则使用二维线框视觉样式的图形预览的显示分辨率将设置为 256 x 256 像素。

类型:	整数
保存位置:	注册表
初始值:	0
值 | 说明
0 | 所有缩略图预览的最大大小为 256 像素。此值为默认值。
1 | 所有二维视觉样式的缩略图预览均由 THUMBSIZE 系统变量进行控制。

注意:您也可以在“命名”视图组下的“缩略图预览设置”对话框中设置此值。

* TILEMODE
控制是否可以访问图纸空间。

类型:	整数
保存位置:	图形
初始值:	1
值 | 说明
0 | 命名的布局选项卡处于活动状态，或将最近访问的命名布局设置为当前布局
1 | “模型”选项卡处于活动状态，或将该选项卡设置为活动状态
* TIMEZONE
设置图形中阳光的时区。
类型:	枚举
保存位置:	图形
初始值:	-8000
表中的值以与格林尼治标准时间的差值表示（小时和分钟）。在设置或编辑图形文件的地理位置信息时，您也可以在“地理位置”对话框中更改此值。

表格（略）
* TOOLTIPMERGE
将草图工具提示合并为单个工具提示。
类型:	整数
保存位置:	注册表
初始值:	0
值 | 说明
0 | 绘图工具提示是独立的
1 | 绘图工具提示已合并
* TOOLTIPS
控制工具提示在功能区、工具栏及其他用户界面元素中的显示。

类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 不显示工具栏提示
1 | 显示工具栏提示
* TOOLTIPSIZE
设定绘图工具提示和动态输入文字的显示大小。
类型:	整数
保存位置:	注册表
初始值:	0
有效取值范围为 -3 到 6。值越大，绘图工具提示就越大，命令提示下的自动完成文字也越大。负值表示比默认值更小的尺寸。

* TOOLTIPTRANSPARENCY
设置绘图工具提示的透明度。
类型:	整数
保存位置:	注册表
初始值:	0
有效取值范围为 0 到 100。当使用值 0（零）时，绘图工具提示不透明。较大的值会增加绘图工具提示的透明度。

* TOUCHMODE
对于那些使用支持触摸的屏幕或界面的用户，可以控制功能区上“触摸”面板的显示。
类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0	“触摸”面板未显示在功能区上。
1	如果您使用的是触摸屏幕，则“触摸”面板将显示在功能区上，以便您可以轻松地取消当前操作。
系统变量 MAXTOUCHES 指示正在使用的是数字化仪还是触摸板。
* TPSTATE
指示“工具选项板”窗口处于打开状态还是关闭状态。
（只读）
类型:	整数
保存位置:	未保存
初始值:	不确定
值 | 说明
0 | 关闭
1 | 打开
* TRACECURRENT
当 TRACEMODE=1 或 2 时，显示活动跟踪的名称。
类型:	字符串
保存位置:	未保存
初始值:	不确定
* TRACEDISPLAYMODE
当跟踪处于活动状态时，指示跟踪图纸效果处于显示状态（前）还是不显示状态（后）。
（只读）
类型:	整数
保存位置:	未保存
初始值:	2
值  说明

0	跟踪模式不处于活动状态
1	后 - 不显示跟踪图纸、暗显跟踪几何图形、宿主几何图形完全饱和
2	前 - 显示跟踪图纸、跟踪几何图形完全饱和、暗显宿主几何图形
注意:当跟踪模式未处于活动状态时，TRACEDISPLAYMODE 为 0。
* TRACEFADECTL
当 TRACEMODE 处于活动状态时，控制淡入程度。该设置仅影响不在进行编辑的对象 - 宿主图形几何图形或跟踪几何图形。
（只读）
类型:	整数
保存位置:	注册表
初始值:	40
有效范围从 0 到 90。
* TRACEMODE
指示跟踪是否处于活动状态以及当前所处模式 - 编辑或查看。
（只读）
类型:	整数
保存位置:	未保存
初始值:	0
值  说明
0	跟踪模式不处于活动状态
1	查看跟踪（当前宿主图形空间）
2	编辑跟踪（当前跟踪空间）
注意:可以在桌面、Web 应用程序或移动应用程序中查看跟踪。使用 Web 和移动设备时，只能创建或编辑跟踪。

* TRACEOSNAP
控制在查看跟踪时对象捕捉是否应用于跟踪几何图形。
类型:	整数
保存位置:	注册表
初始值:	0
当跟踪几何图形由低保真度标记组成时，则在查看跟踪时支持跟踪几何图形上的对象捕捉可能会使更新宿主图形的几何图形更加困难。但在查看跟踪中的高保真度几何图形时，对象捕捉可能会很有用。

注意:仅当 TRACEMODE=1 时，TRACEOSNAP 才适用。当 TRACEMODE=2 时，对象捕捉始终应用于跟踪几何图形。
值 | 说明
0 | 查看跟踪时，禁用对象捕捉
1 | 查看跟踪时，启用对象捕捉

* TRACEPALETTESTATE
报告“跟踪”选项板是处于打开状态还是处于关闭状态。
（只读）
类型:	整数
保存位置:	注册表
初始值:	0
值 | 说明
0 | 关闭
1 | 打开
* TRACEPAPERCTL
控制跟踪图纸效果的不透明度。
（只读）
类型:	整数
保存位置:	未保存
初始值:	20
值 | 说明
0-50 | 控制跟踪图纸的不透明度。数字越小，跟踪图纸越透明。

* TRACKPATH
控制极轴追踪和对象捕捉追踪对齐路径的显示。

类型:	整数
保存位置:	注册表
初始值:	0
值 | 说明
0 | 全屏显示极轴追踪和对象捕捉追踪路径
1 | 全屏显示极轴追踪路径；仅显示对齐点与光标位置起点之间的对象捕捉追踪路径
2 | 全屏显示对象捕捉追踪路径；不显示极轴追踪路径
3 | 不显示极轴追踪路径；仅显示对齐点与光标位置起点之间的对象捕捉追踪路径

* TRANSPARENCYDISPLAY
控制指定给单个对象或 ByLayer 的透明度特性是可见还是被禁用。
类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 对象透明度被禁用
1 | 对象透明度可见

注意:透明度可单独进行控制，以便从“打印”对话框或“页面设置”对话框打印。
* TRAYICONS
控制是否在状态栏上显示状态托盘。

类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 不显示状态托盘
1 | 显示状态托盘
* TRAYNOTIFY
控制是否在状态栏托盘中显示服务通知。
类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 不显示通知
1 | 显示通知
* TRAYTIMEOUT
控制服务通知的显示时间长度（以秒为单位）。

类型:	整数
保存位置:	注册表
初始值:	0
有效值范围为 0 到 10。
* TREEDEPTH
指定最大深度，即树状结构的空间索引可以分出分支的次数。
类型:	整数
保存位置:	图形
初始值:	3020
值 | 说明
0 | 禁用整个空间索引。处理大的图形时，这可能会抵消其对系统性能的改善。此设置可以确保始终按照数据库顺序处理对象。

>0 | 打开空间索引。值为整数，最多可包含五位数字。前三位针对模型空间，后两位针对图纸空间。

<0 | 将模型空间对象视为二维对象（忽略 Z 坐标），就像图纸空间对象一样。此设置适于二维图形，它可以充分利用内存而不会降低性能

注意:不能透明使用 TREEDEPTH。
* TREEMAX
通过限制空间索引（八分树）中的节点数目，从而限制重生成图形时占用的内存。
类型:	整数
保存位置:	注册表
初始值:	10000000
通过用 TREEMAX 规定一个固定的限定值，可以加载在内存大于本系统内存，而其 TREEDEPTH 设置超出本系统处理能力的系统上创建的图形。如果这些图形未经检查，可能会产生一个很大的八叉树，消耗的内存最终可能超出本系统上可用的内存。TREEMAX 还提供了一种防范机制避免 TREEDEPTH 的值过大。

TREEMAX 的初始默认值是 10000000（一千万），这个值足够大，可有效避免 TREEMAX 控制 TREEDEPTH 的情形发生。TREEMAX 应当设置的值取决于系统可用的 RAM。每兆内存可以处理约 15,000 个八叉树节点。

如果一个八叉树需要使用多达 2M 的内存，请将 TREEMAX 设定为 30000 (2 x 15,000)。如果程序为八叉树节点所分配的内存不足，请重新启动程序，并将 TREEMAX 设定为较小的数值，然后再次尝试加载图形。

程序有时可能会达到 TREEMAX 设置的限制。请按照结果提示说明进行操作。能否增加 TREEMAX 的值取决于计算机可用的内存。

* TRIMEDGES
控制使用“快速”模式修剪和延伸到图案填充的操作是限于图案填充的边缘，还是包括填充图案内的对象。

类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 使用所有图案填充对象作为边界
1 | 仅使用图案填充边

注意:如果设置为 1，要将对象仅延伸到图案填充边界，请按住 Shift 键并选择，以切换 TRIM 命令来扩展模式。

* TRIMEXTENDMODE
控制 TRIM 和 EXTEND 命令是否使用简化的输入。
类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 标准操作
1 | 快速操作

此系统变量控制使用 TRIM 和 EXTEND 命令时的默认模式。在“标准”模式下，首先指定所有剪切或延伸边界。“快速”模式具有以下效果：

图形中的所有对象将自动用作剪切或延伸边界。
默认情况下，可以使用两点围栏、按住并拖动套索或单独选择要修剪或延伸的对象。
注意:简化的操作与 AutoCAD Web 和 Mobile 中的 TRIM 和 EXTEND 操作匹配。

* TRIMMODE
控制是否为倒角和圆角修剪选定边。

类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 不修剪选定边
1 | 将选定边修剪到倒角直线和圆角圆弧的端点

* TRUSTEDDOMAINS
指定域名或 URL，以便 AutoCAD 可从其运行 JavaScript 代码。

类型:	字符串
保存位置:	注册表
初始值:	不确定
注意:此系统变量主要供 Autodesk 和第三方开发人员使用。仅追踪 AutoCAD Javascript API 调用 - 不会追踪所有其他 Javascript 调用。
要最小化加载和执行恶意代码的可能性，请始终将 TRUSTEDDOMAINS 系统变量设置为唯一·Internet·域名或·URL，以供 AutoCAD JavaScript API·和可能包含·AutoCAD Javascript API 调用的·HTML·文件使用。当 TRUSTEDDOMAINS 设置为 ""（空字符串）或 "."（句点）时，即没有受信任的域或 URL。

在 TRUSTEDPATHS 中指定的任何 Web 页面始终是隐式信任的。

以下是一些包含通配符的受信任域的样例：

*.autodesk.com/*                // trust anything from Autodesk
*.codeplex.com/site/MyProject/* // trust anything from a specified subdomain
https://144.111.123.123/*       // trust only the https protocol from a specified IP address
有关通配符的信息，请参见通配符参考。
* TRUSTEDPATHS
指定哪些文件夹具有加载并执行包含代码的文件的权限。
类型:	字符串
保存位置:	注册表
初始值:	会有变化，可能已由 CAD 管理员锁定
要最小化加载和执行恶意代码的可能性，请始终将 TRUSTEDPATHS 系统变量设置到您的授权应用程序所在的唯一只读文件夹。这包括以下文件类型：

ARX、DBX、CRX、HDI 文件
LSP、FAS、VLX、MNL、SCR 文件
.NET 程序集
VBA 宏（DVB 文件）
acad.rx
JavaScript
DLL 文件
有效字符串包括以下内容：

将 TRUSTEDPATHS 设置到一个或多个带引号并以分号分隔的文件夹路径时，前面列出的文件类型将从指定的文件夹进行加载。
将 TRUSTEDPATHS 设置为 ""（空字符串）或 "."（句点），除了隐式信任的文件夹路径外，没有受信任的文件夹路径。
当 TRUSTEDPATHS 包括以 \...（反斜杠和三个点）结束的文件夹时，其所有的子文件夹也将受信任。
以下文件夹始终受信任：

C:\Program Files\ 及其子文件夹
C:\Program Files (x86) 及其子文件夹
注意:在某些情况下，这样可能会在使用 LOAD 函数时，更方便地在 Filename 参数中指定相对文件路径。
也可以在“选项”对话框 “文件”选项卡的“安全选项”对话框中，或在“展开向导”中指定这些受信任的路径。
SECURELOAD 系统变量的设置确定其他位置（包括当前图形文件夹）是否受信任。签名 DLL 将自动受信任。
注意:从 AutoCAD 2013 SP1 开始，仅可从文件各自的默认安装文件夹（<安装文件夹>\Support 和 <安装文件夹>\Support\<语言>）加载保留的 acad2013.lsp 和 acad2013doc.lsp 文件及其后续文件。
* TSPACEFAC
控制多行文字的行间距（按文字高度的因子测量）。
类型:	实数
保存位置:	未保存
初始值:	1.0000
有效值为 0.25 到 4.0。
* TSPACETYPE
控制多行文字中使用的行间距类型。

类型:	整数
保存位置:	注册表
初始值:	1
至少基于行中的最高字符调整行间距。精确使用指定的行间距，而不必考虑单个字符大小。

值 | 说明
1 | 至少
2 | 精确
* TSTACKALIGN
控制堆叠文字的垂直对齐。
类型:	整数
保存位置:	图形
初始值:	1
值 | 说明
0 | 底部对齐
1 | 中心对齐
2 | 顶部对齐
* TSTACKSIZE
控制堆叠文字分数高度相对于选定文字的当前高度的百分比。

类型:	整数
保存位置:	图形
初始值:	70
有效值从 25 到 125。
* UCS2DDISPLAYSETTING
在二维线框视觉样式设置为当前时显示 UCS 图标。
类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 关闭。当二维线框视觉样式设置为当前时，不会显示 UCS 图标。
1 | 打开。当二维线框视觉样式设置为当前时，会显示 UCS 图标。

注意:UCSICON 命令也必须设置为“开”才能显示 UCS 图标。
* UCS3DPARADISPLAYSETTING
在透视视图处于禁用状态且三维视觉样式设置为当前时显示 UCS 图标。

类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 关闭。当透视处于关闭状态并且三维视觉样式置为当前时，不会显示 UCS 图标。
1 | 打开。当透视处于关闭状态并且三维视觉样式置为当前时，将显示 UCS 图标。

注意:UCSICON 命令也必须设置为“开”才能显示 UCS 图标。
* UCS3DPERPDISPLAYSETTING
在透视视图处于启用状态且三维视觉样式设置为当前时显示 UCS 图标。

类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 关闭。当透视处于打开状态并且三维视觉样式置为当前时，不会显示 UCS 图标。
1 | 打开。当透视处于打开状态并且三维视觉样式置为当前时，将显示 UCS 图标。

注意:UCSICON 命令也必须设置为“开”才能显示 UCS 图标。
* UCSAXISANG
使用 UCS 命令的 X、Y 或 Z 选项绕其一个轴旋转 UCS 时，存储默认角度。
类型:	整数
保存位置:	注册表
初始值:	90
该角度值必须以度数的形式输入（有效值包括：5、10、15、18、22.5、30、45、90、180）。
* UCSBASE
存储定义正交 UCS 设置的原点和方向的 UCS 名称。

类型:	字符串
保存位置:	图形
初始值:	""
有效值可以是任何命名 UCS。
* UCSDETECT
控制创建涉及三维平整面的对象时是否激活动态 UCS 获取。

类型:	整数
保存位置:	注册表
初始值:	1
创建对象时，您可以在光标悬停在三维实体上的平整面、平面网格元素或平面点云线段上方时，动态地对齐 UCS。

注意:动态 UCS 对齐不会检测平整面对象或二维几何图形。
值 | 说明
0 | 未激活
1 | 已激活

提示如果性能有问题，可能希望将 UCSDETECT 设置为 0。
* UCSFOLLOW
从一个 UCS 转换为另一个 UCS 时生成平面视图。
类型:	整数
保存位置:	图形
初始值:	0
将分别为每个视口单独保存 UCSFOLLOW 设置。如果某个视口的 UCSFOLLOW 处于打开状态，那么在每次更改为其他用户坐标系时，都会在该视口中生成平面视图。

值 | 说明
0 | 更改 UCS 不会影响当前视图
1 | 更改 UCS 导致在当前视口中生成新 UCS 的平面视图

注意:在图纸空间中，将忽略 UCSFOLLOW 设置。
* UCSICON
控制 UCS 图标可见性和位置。
类型:	整数
保存位置:	图形
初始值:	3
此系统变量的设置是特定于视口和布局的。

值 | 说明
0 | 关；不显示图标
1 | 开；仅在当前视口或布局的左下角显示图标
2 | 关；如果图标处于打开状态，将在 UCS 原点处显示图标（如果可能）
3 | 开；在原点处显示 UCS 图标（如果可能）。

注意:此系统变量的名称与 UCSICON 命令相同。使用 SETVAR 命令可访问此系统变量。
* UCSNAME
存储在当前空间中用于当前视口的当前用户坐标系的名称。
（只读）
类型:	字符串
保存位置:	图形
如果当前 UCS 尚未命名，则返回一个空字符串。
* UCSORG
存储在当前空间中用于当前视口的当前用户坐标系的原点。
（只读）
类型:	三维点
保存位置:	图形
初始值:	0.0000,0.0000,0.0000
将使用世界坐标系 (WCS) 存储坐标。
* UCSORTHO
决定 UCS 的 XY 平面是否在正交视图恢复时自动与当前视图的平面恢复对齐。

类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 指定恢复正交视图时 UCS 保持不变
1 | 指定恢复正交视图时 UCS 将自动对齐

* UCSSELECTMODE
控制是否可以使用夹点选择和操纵 UCS 图标。

类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | UCS 图标不可选。
1 | UCS 图标可选。
* UCSVIEW
决定当前 UCS 是否随命名视图一起保存。
类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 当前 UCS 不随命名视图一起保存
1 | 一旦创建命名视图，就随之保存当前 UCS

* UCSVP
确定在其他视口中的 UCS 是从属于还是独立于当前视口的 UCS。

类型:	整数
保存位置:	图形
初始值:	1
此系统变量的设置是特定于视口的。

值 | 说明
0 | 解锁；UCS 反映当前视口的 UCS 状态
1 | 锁定；UCS 存储在视口中并独立于当前视口的 UCS 状态

* UCSXDIR
为当前空间中当前视口存储当前 UCS 的 X 方向。
（只读）
类型:	三维点
保存位置:	图形
初始值:	1.0000,0.0000,0.0000
对于每个视口，UCS 的 X 方向可以不同。
* UCSYDIR
为当前空间中当前视口存储当前 UCS 的 Y 方向。
（只读）
类型:	三维点
保存位置:	图形
初始值:	0.0000,1.0000,0.0000
对于每个视口，UCS 的 Y 方向可以不同。
* UNDOCTL
显示在 UNDO 命令中使用的选项。
（只读）
类型:	整数
保存位置:	未保存
初始值:	53
系统将使用下列位码值之和将该设置存储为一个位码：

值 | 说明
0 | UNDO 关闭
1 | UNDO 打开
2 | 只能放弃一条命令
4 | 打开“自动”
8 | 一个编组处于当前活动状态
16 | 将缩放和平移操作编组为单个操作
32 | 将图层特性操作编组为单个操作

* UNDOMARKS
显示放置在 UNDO 控制流中的标记数。
（只读）
类型:	整数
保存位置:	未保存
初始值:	0
如果一个编组处于当前活动状态，则“标记”和“后退”选项不可用。
* UNITMODE
控制单位的显示格式。

类型:	整数
保存位置:	图形
初始值:	0
默认情况下，测量值的显示格式与用于输入测量值的格式略微不同。（输入测量值时，不能包括空格。）

值 | 说明
0 | 按照“报告”格式（将空格用作分隔符）来显示分数、英尺-英寸和勘测的角度
1 | 按照“输入”格式（不包括空格，并且在某些情况下以划线代替空格）来显示分数、英尺-英寸和勘测的角度

* UOSNAP
确定对象捕捉是否可用于 DWF、DWFx、PDF 和 DGN 参考底图中的几何图形。

类型:	整数
保存位置:	注册表
初始值:	1
UOSNAP 将替代 DWFOSNAP、PDFOSNAP 和 DGNOSNAP 设置。反之，用户可以通过为 DWFOSNAP、PDFOSNAP 或 DGNOSNAP 系统变量输入值来替代 DWF、DWFx、PDF 和 DGN 参考底图的 UOSNAP 设置。

值 | 说明
0 | 对图形中所有参考底图中的几何图形禁用对象捕捉
1 | 对图形中所有参考底图中的几何图形启用对象捕捉
2 | 图形中所有参考底图的各个设置有所不同：DWF、DWFx 和 DGN。

* UPDATETHUMBNAIL
控制视图和布局的缩略图预览的更新。
类型:	位码
保存位置:	图形
初始值:	15
系统将使用下列位码值之和将该设置存储为一个位码：

值 |说明
0 | 不更新预览
1 | 更新模型空间视图的预览
2 | 更新布局视图的预览
4 | 更新布局的预览
8 | 创建、修改或恢复布局或视图时更新预览
16 | 保存图形时更新预览

这些预览显示在图纸集管理器中。图纸预览显示在“图纸列表”选项卡中、图纸视图的预览显示在“视图列表”选项卡中，而模型空间视图的预览显示在“资源图形”选项卡中。
* USERI1-5
提供整数值的存储和检索功能。

类型:	整数
保存位置:	图形
初始值:	0
共有五个系统变量：USERI1、USERI2、USERI3、USERI4 和 USERI5。
* USERR1-5
提供实数的存储和检索功能。

类型:	实数
保存位置:	图形
初始值:	0.0000
* USERS1-5
提供文字字符串数据的存储和检索功能。

类型:	字符串
保存位置:	未保存
初始值:	""
* VIEWBACKSTATUS
存储上一个视图是否可用于 VIEWBACK 命令。

类型:	参数
保存位置:	未保存
初始值:	不确定

* VIEWCTR
存储当前视口中视图的中心。
（只读）
类型:	三维点
保存位置:	图形
初始值:	不确定
用 UCS 坐标表示。
* VIEWDIR
存储当前视口中的观察方向（用 UCS 坐标表示）。
（只读）
类型:	三维矢量
保存位置:	图形
初始值:	0.0000,0.0000,1.0000
它将相机点描述为到目标点的三维偏移量。
* VIEWFWDSTATUS
存储上一个视图是否可用于 VIEWFORWARD 命令。

类型:	参数
保存位置:	未保存
初始值:	不确定
* VIEWMODE
存储当前视口的视图设置。
（只读）
类型:	整数
保存位置:	图形
初始值:	0
系统将使用下列位码值之和将该设置存储为一个位码：

值 | 说明
0 | 关闭
1 | 透视图
2 | 前向剪裁
4 | 后向剪裁
8 | UCS 跟随模式
16 | 前向剪裁不在相机上（在 AutoCAD LT 中不可用）
16 | 如果启用，则 FRONTZ 将确定前向剪裁平面。
16 | 如果禁用，则忽略 FRONTZ，并且前向剪裁平面将经过相机点。如果前向剪裁位 2 设定为关，则本设置将被忽略。
* VIEWSIZE
存储当前视口中显示的视图的高度（按图形单位测量）。
（只读）
类型:	实数
保存位置:	图形
初始值:	不确定
* VIEWSKETCHMODE
指示系统是否在符号草图模式中。
（只读）
类型:	参数
保存位置:	注册表
初始值:	0
值 | 说明
0 | 不在符号草图模式下
1 | 在符号草图模式中
* VIEWTWIST
存储相对于 WCS 测量的当前视口的视图旋转角度。
（只读）
类型:	实数
保存位置:	图形
初始值:	0.0000
* VIEWUPDATEAUTO
控制在更改源模型时模型文档工程视图是否会自动更新。
类型:	整数
保存位置:	图形
初始值:	1
值 | 说明
0 | 在更改源模型时，工程视图不会自动更新。
1 | 在更改源模型时，工程视图会自动更新。
* VISRETAIN
控制外部参照相关图层的特性。
类型:	整数
保存位置:	图形
初始值:	1
控制可见性、颜色、线型、线宽和打印样式。 将此系统变量与 VISRETAINMODE 系统变量结合使用，可管理重新加载时要自动同步哪些外部参照图层特性替代。

值 | 说明
0 | 存储在参照图形（外部参照）中的图层表具有优先权。对当前图形中依赖外部参照的图层所做的更改仅在当前任务中有效，并不随图形一起保存。当前图形重新打开时，将从参照图形重新加载图层表，当前图形将反映所有此类图层特性设置。
1 | 在当前图形中对依赖外部参照的图层的修改具有优先权。图层设置将与当前图形的图层表一起保存，并且在各个任务中保持一致。
* VISRETAINMODE
当 VISRETAIN 系统变量设置为 1 时，控制其行为。

类型:	位码
保存位置:	注册表
初始值:	0
将此系统变量与 VISRETAIN 系统变量结合使用，可控制重新加载时要自动同步哪些外部参照图层特性。

注意:重新加载外部参照时，不会同步带有替代的外部参照图层特性。若清除任何替代，请使用快捷菜单选项，在“图层特性管理器”上“重置以下对象的外部参照图层特性”。
值 | 说明
0 | 未同步设置。您将拥有与在 AutoCAD 2017 或早期版本中将 VISRETAIN 设置为 1 时相同的体验。
1 | 启用/禁用同步。
2 | 冻结/解冻同步。
4 | 锁定/解锁同步。
8 | 打印/不打印同步。
16 | 颜色同步。
32 | 线型同步。
64 | 线宽同步。
128 | 透明度同步。
256 | 打印样式同步。
512 | 新视口冻结同步。
1024 | 描述同步。

要指定多个图层特性以进行同步，请输入各位码值之和。例如，值 3 指定在重新加载外部参照时，“打开/关闭”(1) 和“冻结/解冻”(2) 图层特性将自动同步。
* VPCONTROL
控制每个视口的左上角是否显示视口、视图和视觉样式的选项。
类型:	参数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 隐藏视口控件
1 | 显示视口控件
* VPLAYEROVERRIDES
指示对于当前图层视口是否存在任何具有视口(VP) 特性替代的图层。
（只读）
类型:	整数
保存位置:	图形
初始值:	0
值 | 说明
0 | 当前视口没有任何关联的图层特性替代
1 | 当前视口具有关联的图层特性替代
* VPLAYEROVERRIDESMODE
控制是否显示和打印布局视口的图层特性替代。
类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 在布局视口中不显示图层特性替代并且不打印
1 | 在布局视口中显示图层特性替代并且打印
* VPMAXIMIZEDSTATE
指示是否将视口最大化。
（只读）
类型:	整数
保存位置:	未保存
初始值:	0
如果启动 PLOT 命令，那么最大化视口状态将被取消。

值 | 说明
0 | 不最大化
1 | 最大化
* VPROTATEASSOC
控制旋转视口时视口内的视图是否随视口一起旋转。

类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 旋转视口时，内部的视图不随之旋转。
1 | 旋转视口时，内部的视图随之旋转以符合视口的旋转。

* VSACURVATUREHIGH
设定在曲率分析(ANALYSISCURVATURE) 过程中使曲面显示为绿色的值。
类型:	实数
保存位置:	图形
初始值:	1.0000
* VSACURVATURELOW
设定在曲率分析(ANALYSISCURVATURE) 过程中使曲面显示为蓝色的值。
类型:	实数
保存位置:	图形
初始值:	-1.0000
* VSACURVATURETYPE
控制使用(ANALYSISCURVATURE) 命令时进行哪种类型的曲率分析。

类型:	整数
保存位置:	图形
初始值:	0
值 | 说明
0 | 高斯曲率（评估高曲率和低曲率的区域）
1 | 平均曲率（评估 U 和 V 曲面曲率值的平均曲率）
2 | 最大曲率（评估 U 和 V 曲面曲率值的最大曲率）
3 | 最小曲率（评估 U 和 V 曲面曲率值的最小曲率）
* VSADRAFTANGLEHIGH
设定在拔模分析(ANALYSISDRAFT) 过程中使模型显示为绿色的值。
类型:	实数
保存位置:	图形
初始值:	3.0000
拔模斜度是曲面法线和 UCS 平面之间的角度（以度为单位）。通过此系统变量设定高值。

值 | 说明
-90 | 曲面与 UCS 平行，且曲面法线朝向与构造平面相反的方向
0 | 曲面与构造平面垂直
90 | 曲面与构造平面平行，且曲面法线朝向与 UCS 相同的方向
* VSADRAFTANGLELOW
设定在拔模分析(ANALYSISDRAFT) 过程中使模型显示为蓝色的值。
类型:	实数
保存位置:	图形
初始值:	-3.0000
拔模斜度是曲面法线和 UCS 平面之间的角度（以度为单位）。通过此系统变量设定低值。

值 | 说明
-90 | 曲面与 UCS 平行，且曲面法线朝向与构造平面相反的方向。
0 | 曲面与构造平面垂直。
90 |曲面与构造平面平行，且曲面法线朝向与 UCS 相同的方向。
* VSAZEBRACOLOR1
设定在斑纹分析(ANALYSISZEBRA) 过程中所显示的斑纹条纹的第一种颜色。

类型:	字符串
保存位置:	图形
初始值:	RGB:255,255,255
1 到 255 之间的值可指定 AutoCAD 颜色索引 (ACI) 颜色。

RGB 真彩色的值表示为 000 到 255 之间的整数组成的字符串（以逗号分隔）。默认值为 RGB:255,255,255。

注意:安装配色系统时，可以使用系统中定义的任何颜色。
* VSAZEBRACOLOR2
设定在斑纹分析 (ANALYSISZEBRA) 过程中所显示的斑纹条纹的第二种（对比）颜色。

类型:	字符串
保存位置:	图形
初始值:	RGB:0,0,0
1 到 255 之间的值可指定 AutoCAD 颜色索引 (ACI) 颜色。

RGB 真彩色的值表示为 000 到 255 之间的整数组成的字符串（以逗号分隔）。默认值为 RGB:0,0,0。

注意:安装配色系统时，可以使用系统中定义的任何颜色。
* VSAZEBRADIRECTION
控制在斑纹分析 (ANALYSISBRA) 过程中斑纹条纹是水平显示、竖直显示还是以某一角度显示。
类型:	整数
保存位置:	图形
初始值:	90
值 ｜ 说明
0 | 水平
90 | 垂直

注意:输入介于 0 和 90 度之间的值以按该角度设定斑纹条纹。
* VSAZEBRASIZE
控制在斑纹分析 (ANALYSISZEBRA) 过程中所显示的斑纹条纹的宽度。

类型:	整数
保存位置:	图形
初始值:	45
有效值为 1 到 100。
* VSAZEBRATYPE
设定在使用斑纹分析(ANALYSISZEBRA) 时斑纹显示的类型。
类型:	整数
保存位置:	图形
初始值:	1
值 | 说明
0 | 铬球
1 | 圆柱体
* VSBACKGROUNDS
控制是否以应用于当前视口的视觉样式显示背景。
类型:	整数
保存位置:	图形
初始值:	1
值 | 说明
0 | 关闭
1 | 打开

注意:输入此系统变量的新值时，现有视觉样式不会更改。为此系统变量临时输入的所有新值都将创建未保存的新视觉样式。

* VSEDGECOLOR
设置当前视口视觉样式中边的颜色。

类型:	字符串
保存位置:	图形
初始值:	BYENTITY
值 0 指定“ByBlock”，值 256 指定“ByLayer”，值 257 指定“ByEntity”。1 到 255 之间的值可指定 AutoCAD 颜色索引 (ACI) 颜色。还可以指定真彩色和配色系统颜色。

真彩色的有效值是一个前面带有 RGB 的整数字符串，每个整数（0 到 255）之间用逗号分隔。真彩色设置的输入如下：

RGB:000,000,000

如果已安装配色系统，则可以指定系统中定义的任意颜色。

注意:
当 VSFACESTYLE 设为 1 或 2 时，将 VSEDGECOLOR 系统变量设为 ByEntity 将使平移、缩放和动态观察操作的三维性能得到增强。
当 VSFACESTYLE 设为 0（零）时，将 VSEDGECOLOR 系统变量设为与 VSOBSCUREDCOLOR 相同的值将使平移、缩放和动态观察操作的三维性能得到增强。
输入此系统变量的新值时，现有视觉样式不会更改。为此系统变量临时输入的所有新值都将创建未保存的新视觉样式。

* VSEDGEJITTER
使对象上的边看起来具有多个线性笔划，就像它们是用铅笔绘制的。

类型:	整数
保存位置:	图形
初始值:	-2
不能将抖动量设定为“低”、“中”或“高”。负数可存储值，但会关闭效果。打印样式不适用于应用了抖动边修改器的对象。

值 | 说明
0 | 标准边
1 | 低
2 | 中
3 | 高

注意:
当 VSFACESTYLE 设为 1 或 2 时，将 VSEDGEJITTER 系统变量设为 0（零）或负值（关）将使平移、缩放和动态观察操作的三维性能得到增强。
输入此系统变量的新值时，现有视觉样式不会更改。为此系统变量临时输入的所有新值都将创建未保存的新视觉样式。
* VSEDGELEX
控制线和边显示延伸至其端点之外的像素数，以产生手绘效果。
类型:	整数
保存位置:	图形
初始值:	-6
可以将线延伸量设置为 1 到 100 像素之间。负值可存储值，但会关闭效果。

注意:输入此系统变量的新值时，现有视觉样式不会更改。为此系统变量临时输入的所有新值都将创建未保存的新视觉样式。

* VSEDGEOVERHANG
旧式的。替换为 VSOCCLUDEDCOLOR 系统变量。
类型:	整数
保存位置:	图形
初始值:	-6
* VSEDGES
控制显示在视口中的边的类型。
类型:	整数
保存位置:	图形
初始值:	1

素线, 镶嵌面边

值 | 说明
0 | 不显示边
1 | 显示素线
2 | 显示镶嵌面边

注意:输入此系统变量的新值时，现有视觉样式不会更改。为此系统变量临时输入的所有新值都将创建未保存的新视觉样式。

* VSEDGESMOOTH
指定折缝边的显示角度。
类型:	整数
保存位置:	图形
初始值:	1
取值范围为 0 到 180。

注意: 输入此系统变量的新值时，现有视觉样式不会更改。为此系统变量临时输入的所有新值都将创建未保存的新视觉样式。

* VSFACECOLORMODE
控制如何计算面的颜色。
类型:	整数
保存位置:	图形
初始值:	0
值 | 说明
0 | 常规：不应用面颜色修改器。
1 | 单色：以在 VSMONOCOLOR 系统变量中指定的颜色显示所有面。
2 | 染色：以在 VSMONOCOLOR 系统变量中指定的颜色，通过更改颜色的色调和饱和度值对所有面进行着色。
3 | 降饱和度：通过将颜色的饱和度分量降低百分之三十来使颜色变柔和。

注意:输入此系统变量的新值时，现有视觉样式不会更改。为此系统变量临时输入的所有新值都将创建未保存的新视觉样式。

* VSFACEHIGHLIGHT
控制当前视口中不具有材质的面上镜面亮显的显示。
类型:	整数
保存位置:	图形
初始值:	-30
取值范围为 -100 到 100。数值越大，亮显区域越大。启用 VSMATERIALMODE 时，具有附着材质的对象将忽略 VSFACEHIGHLIGHT 的设置。

注意:输入此系统变量的新值时，现有视觉样式不会更改。为此系统变量临时输入的所有新值都将创建未保存的新视觉样式。

* VSFACEOPACITY
为三维对象打开和关闭透明度预设级别。
类型:	整数
保存位置:	图形
初始值:	-60

可以在 100% 不透明和 0% 不透明之间设置将三维实体和曲面的透明度。负数可存储值，但会关闭效果。


注意:
当 VSFACESTYLE 设为 1 或 2 时，将单个设置或全局设置的 VSFACEOPACITY 系统变量设为 100（不透明）将使平移、缩放和动态观察操作的三维性能得到增强。
输入此系统变量的新值时，现有视觉样式不会更改。为此系统变量临时输入的所有新值都将创建未保存的新视觉样式。

* VSFACESTYLE
控制面、实体填充图案和渐变在当前视口中的显示方式。
类型:	整数
保存位置:	图形
初始值:	0
值 | 说明
0 | 不使用样式
1 | 真实：非常接近于面在现实中的表现方式
2 | 古式：使用冷色和暖色（而不是暗色和亮色）来增强面的显示效果，这些面可以添加阴影并且很难在真实显示中看到

“隐藏”和“勾画”视觉样式会自动将实体图案填充和渐变的颜色更改为背景色，从而使其不可见。若要使这些视觉样式的原始颜色可见，请将 VSFACESTYLE 设置为 1 或 2。

注意:输入此系统变量的新值时，现有视觉样式不会更改。为此系统变量临时输入的所有新值都将创建未保存的新视觉样式。

* VSHALOGAP
设置应用于当前视口的视觉样式中的光晕间隔。

类型:	整数
保存位置:	图形
初始值:	0
取值范围为 0 到 100。

注意:
当 VSFACESTYLE 设为 1 或 2 时，将 VSHALOGAP 系统变量设为 0（零）将使平移、缩放和动态观察操作的三维性能得到增强。
输入此系统变量的新值时，现有视觉样式不会更改。为此系统变量临时输入的所有新值都将创建未保存的新视觉样式。

* VSHIDEPRECISION
旧式的。控制应用于当前视口的视觉样式中的隐藏和着色精度。

类型:	整数
保存位置:	图形
初始值:	0
此系统变量将不再起作用，但已保留以实现兼容性。

值 | 说明
0 | 单精度；使用较少内存
1 | 双精度；使用较多内存

注意:输入此系统变量的新值时，现有视觉样式不会更改。为此系统变量临时输入的所有新值都将创建未保存的新视觉样式。

* VSINTERSECTIONCOLOR
设置独立三维实体、曲面和网格的相交边颜色以实现某种视觉样式。

类型:	整数
保存位置:	图形
初始值:	7
- 必须启用 VSINTERSECTIONEDGES 系统变量才能使其生效。
- 此系统变量不适用于“二维线框”、“线框”或“真实”视觉样式。

通过该系统变量，您可以临时替代当前视口中的视觉样式设置。但是，现有视觉样式不会自动更新。若要执行此操作，您将需要创建新的视觉样式。

注意: 对于已执行 HIDE 操作后的“二维线框”视觉样式，请使用 INTERSECTIONCOLOR 系统变量。

* VSINTERSECTIONEDGES
控制独立三维实体、曲面和网格相交边显示以实现某种视觉样式。
类型:	整数
保存位置:	图形
初始值:	0
此系统变量不适用于“二维线框”、“线框”或“真实”视觉样式，因为它无需处理相交面。

值 | 说明
0 | 关闭
1 | 显示相交边

注意:
当 VSFACESTYLE 设为 1 或 2 时，将 VSINTERSECTIONEDGES 系统变量设为 0（零）（关）将使平移、缩放和动态观察操作的三维性能得到增强。
通过该系统变量，您可以临时替代当前视口中的视觉样式设置。但是，现有视觉样式不会自动更新。若要执行此操作，您将需要创建新的视觉样式。
对于已执行 HIDE 操作后的“二维线框”视觉样式，请使用 INTERSECTIONDISPLAY 系统变量。

* VSINTERSECTIONLTYPE
设置独立三维实体、曲面和网格的交点线型以实现某种视觉样式。
类型:	整数
保存位置:	图形
初始值:	1
有效取值范围为 1 到 11。

值 | 说明
1 | 实体
2 | 虚线
3 | 点划线
4 | 短划线
5 | 中划线
6 | 长划线
7 | 双短划线
8 | 双中划线
9 | 双长划线
10 | 中长划线
11 | 疏点

必须启用 VSINTERSECTIONEDGES 系统变量才能使其生效。
此系统变量不适用于“二维线框”、“线框”或“真实”视觉样式。
通过该系统变量，您可以临时替代当前视口中的视觉样式设置。但是，现有视觉样式不会自动更新。若要执行此操作，您将需要创建新的视觉样式。
* VSISOONTOP
显示应用于当前视口的视觉样式中着色对象顶部的素线。

类型:	整数
保存位置:	图形
初始值:	0
值 | 说明
0 | 关闭
1 | 打开

注意:输入此系统变量的新值时，现有视觉样式不会更改。为此系统变量临时输入的所有新值都将创建未保存的新视觉样式。

* VSLIGHTINGQUALITY
设置当前视口中的光源质量。

类型:	整数
保存位置:	图形
初始值:	1
值 | 说明
0 | 镶嵌面的。为曲面或三维实体的每个面计算单色。
1 | 平滑。将颜色计算为各面顶点之间的渐变色。
2 | 最平滑。如果在“手动性能调节”对话框中打开了“单像素光照”设置，则为各个像素计算颜色。如果未打开，则将使用平滑设置。

注意:输入此系统变量的新值时，现有视觉样式不会更改。为此系统变量临时输入的所有新值都将创建未保存的新视觉样式。

* VSMATERIALMODE
控制当前视口中材质的显示。

类型:	整数
保存位置:	图形
初始值:	0
关闭材质和纹理的显示以使执行无关操作时达到最高性能。

关闭纹理的显示以修改材质或提升执行无关操作时的性能。

将设置关闭后，可以恢复材质和纹理的显示。

值 | 说明
0 | 不显示材质
1 | 显示材质，不显示纹理
2 | 显示材质和纹理

注意:输入此系统变量的新值时，现有视觉样式不会更改。为此系统变量临时输入的所有新值都将创建未保存的新视觉样式。

* VSMAX
存储当前视口虚拟屏幕的右上角。
（只读）
类型:	三维点
保存位置:	图形
初始值:	不确定
该值用 UCS 坐标表示。
* VSMIN
存储当前视口虚拟屏幕的左下角。
（只读）
类型:	三维点
保存位置:	图形
初始值:	不确定
该值用 UCS 坐标表示。
* VSMONOCOLOR
为应用于当前视口的视觉样式中面的单色和染色显示设置颜色。

类型:	字符串
保存位置:	图形
初始值:	RGB:255,255,255
初始值为白色。

注意:输入此系统变量的新值时，现有视觉样式不会更改。为此系统变量临时输入的所有新值都将创建未保存的新视觉样式。

* VSOBSCUREDCOLOR
旧式的。替换为 VSOCCLUDEDCOLOR 系统变量。

类型:	字符串
保存位置:	图形
初始值:	BYENTITY
* VSOBSCUREDEDGES
旧式的。替换为 VSOCCLUDEDEDGES 系统变量。

类型:	整数
保存位置:	图形
初始值:	1
* VSOBSCUREDLTYPE
旧式的。替换为 VSOCCLUDEDLTYPE 系统变量。

类型:	整数
保存位置:	图形
初始值:	1
* VSOCCLUDEDCOLOR
指定为视觉样式显示的隐藏线的颜色。
类型:	字符串
保存位置:	图形
初始值:	ByEntity
有效值包括“ByLayer”(256)、“ByBlock”(0)、“ByEntity”(257) 以及任何 AutoCAD 颜色索引 (ACI) 颜色（1 到 255 之间的整数）。

用户还可以指定一种真彩色或一种配色系统颜色。真彩色的有效值是一个前面带有 RGB 的整数字符串，每个整数（1 到 255）之间用逗号分隔。真彩色设置的输入如下：

RGB:000,000,000

输入此系统变量的新值时，现有视觉样式不会更改。为此系统变量临时输入的所有新值都将创建未保存的新视觉样式。 此系统变量并不会影响二维线框视觉样式。

注意: 当 VSFACESTYLE 设为 0（零）时，将 VSOCCLUDEDCOLOR 系统变量设为与 VSEDGECOLOR 系统变量相同的值将使平移、缩放和动态观察操作的三维性能得到增强。
* VSOCCLUDEDEDGES
控制是否为视觉样式显示隐藏的边。
类型:	整数
保存位置:	图形
初始值:	1
值 | 说明
0 | 关闭
1 | 打开

输入此系统变量的新值时，现有视觉样式不会更改。为此系统变量临时输入的所有新值都将创建未保存的新视觉样式。 此系统变量并不会影响二维线框视觉样式。

注意:
当 VSFACESTYLE 设置为 1 或 2 时，将 VSOCCLUDEDEDGES 系统变量设置为 0（关）将使平移、缩放和动态观察操作的三维性能得到增强。
当 VSFACESTYLE 设置为 0 时，将 VSOCCLUDEDEDGES 系统变量设置为 1（开）将使平移、缩放和动态观察操作的三维性能得到增强。
* VSOCCLUDEDLTYPE
指定为视觉样式显示的隐藏线的线型。

类型:	整数
保存位置:	图形
初始值:	1
有效取值范围为 0 到 11。

值 | 说明
0 | 关闭
1 | 实体 ______________________________________________
2 | 虚线 __  __  __  __  __  __  __  __  __  __  __  __
3 | 点划线 .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .
4 | 短划线 __    __    __    __    __    __    __    __
5 | 中划线 ___   ___   ___   ___   ___   ___   ___   ___
6 | 长划线 ____  ____  ____  ____  ____  ____  ____  ____
7 | 双短划线 ___        ___        ___        ___        ___
8 | 双中划线 ______    ______    ______    ______    ______
9 | 双长划线 _________   _________   _________   _________
10 | 中长划线 ____   ____   ____   ____   ____   ____   ____
11 | 疏点 .     .     .     .     .     .     .     .     .

VSOCCLUDEDLTYPE 的初始值取决于当前的视觉样式。

视觉样式 | 初始值
二维线框 | 1
概念 | 1
消隐 | 2
着色 | 1
带边缘着色 | 2
灰度 | 1
勾画 | 1
线框 | 1
X 射线 | 1
真实 | 1

注意:输入此系统变量的新值时，现有视觉样式不会更改。为此系统变量临时输入的所有新值都将创建未保存的新视觉样式。

* VSSHADOWS
控制视觉样式是否显示阴影。
类型:	整数
保存位置:	图形
初始值:	0
仅当硬件加速处于启用状态时才可以显示投射在对象上的阴影。使用 GRAPHICSCONFIG 命令访问“图形性能”对话框中的硬件加速设置。

值 | 说明
0 | 不显示阴影
1 | 仅显示地面阴影
2 | 显示全阴影

注意:
当 VSFACESTYLE 设为 1 或 2 时，将 VSSHADOWS 系统变量设为 0（零）（关）将使平移、缩放和动态观察操作的三维性能得到增强。
输入此系统变量的新值时，现有视觉样式不会更改。为此系统变量临时输入的所有新值都将创建未保存的新视觉样式。

* VSSILHEDGES
控制应用于当前视口的视觉样式中实体对象轮廓边的显示。

类型:	整数
保存位置:	图形
初始值:	0
值 | 说明
0 | 关闭
1 | 打开

VSSILHEDGES 的初始值取决于当前的视觉样式。

视觉样式 | 初始值
二维线框 | 0
概念 | 1
消隐 | 1
着色 | 0
带边缘着色 | 1
灰度 | 1
勾画 | 1
线框 | 0
X 射线 | 0
真实 | 0

注意:
当 VSFACESTYLE 设为 1 或 2 时，将 VSSILHEDGES 系统变量设为 0（零）（关）将使平移、缩放和动态观察操作的三维性能得到增强。
输入此系统变量的新值时，现有视觉样式不会更改。为此系统变量临时输入的所有新值都将创建未保存的新视觉样式。

* VSSILHWIDTH
以像素为单位指定当前视口中轮廓边的宽度。
类型:	整数
保存位置:	图形
初始值:	5
取值范围为 1 到 25。

注意: 输入此系统变量的新值时，现有视觉样式不会更改。为此系统变量临时输入的所有新值都将创建未保存的新视觉样式。

* VSSTATE
指示“视觉样式”窗口处于打开状态还是关闭状态。
（只读）
类型:	整数
保存位置:	未保存
初始值:	0
值 | 说明
0 | 关闭
1 | 打开
* VTDURATION
以毫秒为单位设置平滑视图转场的时长。

类型:	整数
保存位置:	注册表
初始值:	750
有效取值范围为 0 到 5000。
* VTENABLE
控制何时使用平滑视图转场。

类型:	整数
保存位置:	注册表
初始值:	3
对于平移和缩放、修改视图角度或脚本，可以打开或关闭平滑视图转场。有效取值范围为 0 到 7。

值 | 平移/缩放 | 查看角度 | 脚本
0 | 关闭 | 关闭 | 关闭
1 | 打开 | 关闭 | 关闭
2 | 关闭 | 打开 | 关闭
3 | 打开 | 打开 | 关闭
4 | 关闭 | 关闭 | 打开
5 | 打开 | 关闭 | 打开
6 | 关闭 | 打开 | 打开
7 | 打开 | 打开 | 打开
* VTFPS
以帧/每秒为单位设置平滑视图转场的最小速度。

类型:	整数
保存位置:	注册表
初始值:	7
如果平滑视图过渡不能保持此速度，将使用即时过渡。有效取值范围为 1 到 30。
* WBLOCKCREATEMODE
在将块另存为文件后，使用 WBLOCK 和 -WBLOCK 命令设置选定对象的行为。

类型:	整数
保存位置:	用户设置
初始值:	1
值	说明
0	在将选定对象另存为文件后，使用 WBLOCK 或 -WBLOCK 命令将选定对象转换为当前图形中的块。
1	在将选定对象另存为文件后，使用 WBLOCK 或 -WBLOCK 命令将选定对象保留在当前图形中。
2	在将选定对象另存为文件后，使用 WBLOCK 或 -WBLOCK 命令将选定对象从当前图形中删除。
* WHIPARC
旧式的。覆盖圆和圆弧显示的平滑度。
类型:	整数
保存位置:	注册表
初始值:	0
值 | 说明
0 | 曲线式对象将显示为由 VIEWRES 设置控制的一系列矢量（推荐）
1 | 具有连续线型的圆、圆弧和多段线圆弧段将显示为真实的圆和圆弧

注意:这是一项实验设置，用于测试内存使用情况以及圆和圆弧的显示性能。将 VIEWRES 设为 1000 或更高几乎总是能够提供更好的结果。
* WHIPTHREAD
控制是否使用额外的处理器来提高操作速度（例如用于重画或重生成图形的 ZOOM）。
类型:	整数
保存位置:	注册表
初始值:	1
值 | 说明
0 | 将操作限制为单个处理器。
1 | 在多处理器计算机上，自动支持要在两个处理器之间分配的特定操作。
2 | 旧式的。
3 | 旧式的。

WHIPTHREAD 对单处理器计算机无效。
* WINDOWAREACOLOR
控制窗口选择时透明选择区域的颜色。

类型:	整数
保存位置:	注册表
初始值:	150
有效取值范围为 1 到 255。必须打开 SELECTIONAREA 系统变量以显示颜色。
* WIPEOUTFRAME
控制区域覆盖对象的框架的显示。

类型:	整数
保存位置:	图形
初始值:	1
值 | 说明
0 | 不显示或不打印框架，为对象选择和选择预览临时显示框架。
1 | 显示和打印框架
2 | 显示框架但不打印

注意:FRAME 系统变量将替代 WIPEOUTFRAME 设置。

* WMFBKGND
控制以 Windows 图元文件(WMF) 格式插入对象时背景的显示。
类型:	参数
保存位置:	未保存
初始值:	0
可以使用以下任意一种方法插入对象：

使用 WMFOUT 输出为 Windows 图元文件
复制到剪贴板并作为 Windows 图元文件粘贴
作为 Windows 图元文件拖动
值 | 说明
0 | 背景色为透明。前景色取决于 WMFFOREGND 系统变量的设置。
1 | 无论在模型空间还是在布局中，背景色均与图形中的当前背景色相同。前景色保持不变
* WMFFOREGND
控制以 Windows 图元文件(WMF) 格式插入对象时前景色的指定。

类型:	参数
保存位置:	未保存
初始值:	0
可以使用以下任意一种方法插入对象：

使用 WMFOUT 输出为 Windows 图元文件
复制到剪贴板并作为 Windows 图元文件粘贴
作为 Windows 图元文件拖动
仅当 WMFBKGND 系统变量设置为“关”时才会应用 WMFFOREGND。

值 | 说明
0 | 如果需要，前景色和背景色将互换以确保前景色比背景色暗
1 | 如果需要，前景色和背景色将互换以保证前景色比背景色亮

* WORKINGFOLDER
存储开发人员可能关心的、操作系统工作文件夹的驱动器和文件夹路径以供处理。
（只读）
类型:	字符串
保存位置:	注册表
初始值:	不确定
也称为“当前目录”，工作文件夹原本设置为“起始”文件夹，但通过文件操作进行了更新。
* WORKSPACELABEL
控制是否在状态栏中显示当前工作空间的名称。

类型:	整数
保存位置:	注册表
初始值:	0
值 | 说明
0 | 隐藏工作空间的名称
1 | 显示工作空间的名称

* WORLDUCS
指示 UCS 是否应与 WCS 重合。
（只读）
类型:	整数
保存位置:	未保存
初始值:	1
值 | 说明
0 | UCS 与 WCS 不同
1 | UCS 与 WCS 相同
* WORLDVIEW
确定响应 DVIEW 和 VPOINT 命令的输入是相对于 WCS（默认）还是相对于当前 UCS。

类型:	整数
保存位置:	图形
初始值:	1
值 | 说明
0 | UCS 保持不变
1 | 在命令执行期间 UCS 转换为 WCS；命令输入相对于当前 UCS

DVIEW 在 AutoCAD LT 中不可用。
* WRITESTAT
指示图形文件是只读的还是可修改的。
（只读）
类型:	整数
保存位置:	未保存
初始值:	1
开发人员需要通过 AutoLISP 确定文件的读写状态。

值 | 说明
0 | 无法写入图形
1 | 允许写入图形
* WSAUTOSAVE
切换到另一个工作空间时，将保存对工作空间所做的更改。

类型:	整数
保存位置:	注册表
初始值:	0
此系统变量决定“工作空间设置”对话框的“切换工作空间时”区域中的默认设置。

值 | 说明
0 | 关闭
1 | 打开
* WSCURRENT
在命令提示下显示当前工作空间名称并将指定的工作空间设置为当前。

类型:	字符串
保存位置:	用户设置
初始值:	不确定
* XCLIPFRAME
决定外部参照剪裁边界在当前图形中是否可见或进行打印。
类型:	整数
保存位置:	图形
初始值:	2
FRAME 系统变量将替代 XCLIPFRAME 设置。在 FRAME 系统变量后使用 XCLIPFRAME 系统变量以重置剪裁外部参照边框设置

值 | 说明
0 | 边框不可见且不打印。在选择集预览或对象选择期间，将暂时重新显示该边框。
1 | 显示并打印剪裁外部参照边框
2 | 显示但不打印剪裁外部参照边框
* XCOMPAREBAKPATH
指定存储备份外部参照文件的路径。

类型:	字符串
保存位置:	注册表
初始值:	不确定
用户也可以在“选项”对话框中更改路径。
* XCOMPAREBAKSIZE
设置存储备份外部参照文件的文件夹的大小。

类型:	整数
保存位置:	注册表
初始值:	500
有效范围为 200 到 32000 兆字节 (MB)。
* XCOMPARECOLORMODE
在外部参照比较期间，切换对象在宿主图形中的视觉效果。

类型:	参数
保存位置:	注册表
初始值:	1
值	说明
0	在比较过程中，宿主图形中的对象会淡入。
1	在比较过程中，宿主图形中的对象将以白色亮显。
* XCOMPAREENABLE
支持在外部参照和参照图形文件之间进行比较。

类型:	整数
保存位置:	注册表
初始值:	1
值	说明
0	关闭
1	打开
相关参考
* XDWGFADECTL
控制所有 DWG 外部参照对象的淡入度。
类型:	整数
保存位置:	注册表
初始值:	50

XDWGFADECTL 系统变量的有效值从 -90 到 90。如果 XDWGFADECTL 设定为负值，则外部参照淡入功能将不会打开，但会存储设置。

值 | 说明
0 | DWG 外部参照对象不会淡入。
>0 | 当该值为正时，将淡入百分比控制为最高淡入 90%。
<0 | 当该值为负时，不淡入外部参照对象，但是将保存该值，以通过更改符号切换为该值。
* XEDIT
控制当前图形被其他图形参照时是否可以在位编辑。

类型:	整数
保存位置:	图形
初始值:	1
值 | 说明
0 | 防止在位参照编辑
1 | 允许在位参照编辑
* XFADECTL
控制要在位编辑的参照中的淡入程度。此设置仅影响不在参照中编辑的对象。
类型:	整数
保存位置:	注册表
初始值:	70
有效值从 0 到 90。

同时控制以较暗状态显示的换算对象图示（例如注释性对象的换算比例图示）的淡入度百分比。

SELECTIONANNODISPLAY 控制是否显示注释性对象的换算比例图示。
* XLOADCTL
打开或关闭外部参照的按需加载功能，并控制是打开参照的图形还是打开副本。
类型:	整数
保存位置:	注册表
初始值:	2
值 | 说明
0 | 关闭按需加载，加载整个图形
1 | 打开按需加载。打开并锁定参照图形。
2 | 打开按需加载。打开并锁定参照图形的副本；不锁定参照图形

当 XLOADCTL 设定为 2 时，每个参照图形文件的副本将存储在由 XLOADPATH 系统变量指定的文件夹或临时文件夹（设置在“选项”对话框中）中。
此外，如果跨网络进行操作，外部参照的加载速度会更快：打开带有多个外部参照的图形时，这种性能提高尤为明显。
* XLOADPATH
创建用于存储按需加载的外部参照文件临时副本的路径。
类型:	字符串
保存位置:	注册表
初始值:	不确定
详细信息请参见 XLOADCTL。
* XREFCTL
控制是否创建外部参照日志(XLG) 文件。
类型:	整数
保存位置:	注册表
初始值:	0

值 | 说明
0 | 不写入记录文件
1 | 写入记录文件

注意:XLG 文件仅记录最近执行的外部参照函数。
* XREFLAYER
为新的外部参照指定默认图层。

类型:	字符串
保存位置:	图形
初始值:	使用当前值
使用 XATTACH、ATTACH 和 XREF 命令控制 DWG 外部参照在附着时放置于其上的图层。

除“.”以外的值（使用当前）值替代当前图层值（CLAYER 系统变量）。
* XREFNOTIFY
控制关于已更新外部参照或缺少外部参照的通知。
类型:	整数
保存位置:	注册表
初始值:	2
值 | 说明
0 | 禁用外部参照通知
1 | 启用外部参照通知。通过在状态栏托盘中显示外部参照图标，通知用户外部参照已附着至当前图形。打开图形时，将显示带有黄色警告符号 (!) 的外部参照图标，以警告用户缺少外部参照。
2 | 启用外部参照通知和气泡式消息。如上面的 1 所示显示外部参照。当外部参照被修改时，还在相同的区域显示气泡式消息。检查修改的外部参照的时间间隔（分钟数）由 XNOTIFYTIME 环境变量控制。
* XREFOVERRIDE
控制参照图层上对象特性的显示。
类型:	整数
保存位置:	图形
初始值:	0
XREFOVERRIDE 系统变量可影响显示和打印，还可以配合 VISRETAIN 系统变量一起使用。如果您希望外部参照图层仍保留其原始图层设置，建议将 VISRETAIN 和 XREFOVERRIDE 系统变量设置为 0（零）。

值 | 说明
0 | 当外部参照图形上的对象特性（例如颜色、线型、线宽、透明度或打印样式）设置为 ByLayer 时，对外部参照图层特性所做的任何更改将显示在当前图形中（传统行为）
1 | 当外部参照图形上的对象的可视特性未设置为 ByLayer 时，外部参照图层上的对象将被视为已将其特性设置为 ByLayer 且每个外部参照图层都可以有其自己的图层替代集

注意:XREFOVERRIDE 系统变量仅适用于 DWG 外部参照，而不适用于其他参照，例如参考底图。
* XREFREGAPPCTL
控制存储在加载的外部参照中的已注册应用程序(RegApp) 记录是否将复制到宿主图形中。
类型:	字符串
保存位置:	注册表
初始值:	不确定
用户也可以在“选项”对话框中更改路径。
* XREFTYPE
控制附着或覆盖外部参照时的默认参照类型。

类型:	整数
保存位置:	注册表
初始值:	0
值 | 说明
0 | “附加型”为默认值
1 | “覆盖”为默认值
* ZOOMFACTOR
控制向前或向后滑动鼠标滚轮时比例的变化程度。
类型:	整数
保存位置:	注册表
初始值:	60
有效值为 3 到 100 之间的整数。数值越高，变化越大。

注意:与基于 AutoCAD 2013 之前的版本的产品相反，相同数量的鼠标滚轮切口放大和缩小操作的结果不会对放大产生任何网状改变。
* ZOOMWHEEL
滚动鼠标中间的滑轮时，切换透明缩放操作的方向。
类型:	整数
保存位置:	注册表
初始值:	0
值 | 说明
0 | 向前滚动滑轮为放大操作，向后滚动滑轮为缩小操作。
1 | 向前滚动滑轮为缩小操作，向后滚动滑轮为放大操作。
* 系统变量Z
ZOOMFACTOR
ZOOMWHEEL
请输入变量全称获取变量用途。
* 系统变量X
XCLIPFRAME
XDWGFADECTL
XEDIT
XFADECTL
XLOADCTL
XLOADPATH
XREFCTL
XREFLAYER
XREFNOTIFY
XREFOVERRIDE
XREFREGAPPCTL
XREFTYPE
请输入变量全称获取变量用途。
* 系统变量W
WHIPARC
WHIPTHREAD
WINDOWAREACOLOR
WIPEOUTFRAME
WMFBKGND
WMFFOREGND
WORKINGFOLDER
WORKSPACELABEL
WORLDUCS
WORLDVIEW
WRITESTAT
WSAUTOSAVE
WSCURRENT
请输入变量全称获取变量用途。
* 系统变量V
VIEWBACKSTATUS
VIEWCTR
VIEWDIR
VIEWFWDSTATUS
VIEWMODE
VIEWSIZE
VIEWSKETCHMODE
VIEWTWIST
VIEWUPDATEAUTO
VISRETAIN
VISRETAINMODE
VPCONTROL
VPLAYEROVERRIDES
VPLAYEROVERRIDESMODE
VPMAXIMIZEDSTATE
VPROTATEASSOC
VSACURVATUREHIGH
VSACURVATURELOW
VSACURVATURETYPE
VSADRAFTANGLEHIGH
VSADRAFTANGLELOW
VSAZEBRACOLOR1
VSAZEBRACOLOR2
VSAZEBRADIRECTION
VSAZEBRASIZE
VSAZEBRATYPE
VSBACKGROUNDS
VSEDGECOLOR
VSEDGEJITTER
VSEDGELEX
VSEDGEOVERHANG
VSEDGES
VSEDGESMOOTH
VSFACECOLORMODE
VSFACEHIGHLIGHT
VSFACEOPACITY
VSFACESTYLE
VSHALOGAP
VSHIDEPRECISION
VSINTERSECTIONCOLOR
VSINTERSECTIONEDGES
VSINTERSECTIONLTYPE
VSISOONTOP
VSLIGHTINGQUALITY
VSMATERIALMODE
VSMAX
VSMIN
VSMONOCOLOR
VSOBSCUREDCOLOR
VSOBSCUREDEDGES
VSOBSCUREDLTYPE
VSOCCLUDEDCOLOR
VSOCCLUDEDEDGES
VSOCCLUDEDLTYPE
VSSHADOWS
VSSILHEDGES
VSSILHWIDTH
VSSTATE
VTDURATION
VTENABLE
VTFPS
请输入变量全称获取变量用途。
* 系统变量U
UCS2DDISPLAYSETTING
UCS3DPARADISPLAYSETTING
UCS3DPERPDISPLAYSETTING
UCSAXISANG
UCSBASE
UCSDETECT
UCSFOLLOW
UCSICON
UCSNAME
UCSORG
UCSORTHO
UCSSELECTMODE
UCSVIEW
UCSVP
UCSXDIR
UCSYDIR
UNDOCTL
UNDOMARKS
UNITMODE
UOSNAP
UPDATETHUMBNAIL
USERI1-5
USERR1-5
USERS1-5
请输入变量全称获取变量用途。
* 系统变量T
TABLEINDICATOR
TABLETOOLBAR
TABMODE
TARGET
TBCUSTOMIZE
TBSHOWSHORTCUTS
TDCREATE
TDINDWG
TDUCREATE
TDUPDATE
TDUSRTIMER
TDUUPDATE
TEMPOVERRIDES
TEMPPREFIX
TEXTALIGNMODE
TEXTALIGNSPACING
TEXTALLCAPS
TEXTAUTOCORRECTCAPS
TEXTED
TEXTEDITMODE
TEXTEVAL
TEXTFILL
TEXTJUSTIFY
TEXTOUTPUTFILEFORMAT
TEXTQLTY
TEXTSIZE
TEXTSTYLE
THICKNESS
THUMBSAVE
THUMBSIZE
THUMBSIZE2D
TILEMODE
TIMEZONE
TOOLTIPMERGE
TOOLTIPS
TOOLTIPSIZE
TOOLTIPTRANSPARENCY
TOUCHMODE
TPSTATE
TRACKPATH
TRANSPARENCYDISPLAY
TRAYICONS
TRAYNOTIFY
TRAYTIMEOUT
TREEDEPTH
TREEMAX
TRIMMODE
TRUSTEDDOMAINS
TRUSTEDPATHS
TSPACEFAC
TSPACETYPE
TSTACKALIGN
TSTACKSIZE
请输入变量全称获取变量用途。
* 系统变量S
SAFEMODE
SAVEFIDELITY
SAVEFILE
SAVEFILEPATH
SAVENAME
SAVETIME
SCREENMODE
SCREENSIZE
SECTIONOFFSETINC
SECTIONTHICKNESSINC
SECURELOAD
SECUREREMOTEACCESS
SELECTIONANNODISPLAY
SELECTIONAREA
SELECTIONAREAOPACITY
SELECTIONCYCLING
SELECTIONEFFECT
SELECTIONEFFECTCOLOR
SELECTIONOFFSCREEN
SELECTIONPREVIEW
SELECTIONPREVIEWLIMIT
SELECTSIMILARMODE
SETBYLAYERMODE
SHADEDGE
SHADEDIF
SHADOWPLANELOCATION
SHAREVIEWPROPERTIES
SHAREVIEWTYPE
SHORTCUTMENU
SHORTCUTMENUDURATION
SHOWHIST
SHOWLAYERUSAGE
SHOWMOTIONPIN
SHOWNEWSTATE
SHOWPAGESETUPFORNEWLAYOUTS
SHOWPALETTESTATE
SHPNAME
SIGWARN
SKETCHINC
SKPOLY
SKTOLERANCE
SKYSTATUS
SMOOTHMESHCONVERT
SMOOTHMESHGRID
SMOOTHMESHMAXFACE
SMOOTHMESHMAXLEV
SNAPANG
SNAPBASE
SNAPGRIDLEGACY
SNAPISOPAIR
SNAPMODE
SNAPSTYL
SNAPTYPE
SNAPUNIT
SOLIDCHECK
SOLIDHIST
SORTENTS
SORTORDER
SPACESWITCH
SPLDEGREE
SPLFRAME
SPLINESEGS
SPLINETYPE
SPLKNOTS
SPLMETHOD
SPLPERIODIC
SSFOUND
SSLOCATE
SSMAUTOOPEN
SSMPOLLTIME
SSMSHEETSTATUS
SSMSTATE
STANDARDSVIOLATION
STARTINFOLDER
STARTMODE
STARTUP
STATUSBAR
STEPSIZE
STEPSPERSEC
STUDENTDRAWING
SUBOBJSELECTIONMODE
SUNPROPERTIESSTATE
SUNSTATUS
SUPPRESSALERTS
SURFACEASSOCIATIVITY
SURFACEASSOCIATIVITYDRAG
SURFACEAUTOTRIM
SURFACEMODELINGMODE
SURFTAB1
SURFTAB2
SURFTYPE
SURFU
SURFV
SYSCODEPAGE
SYSMON
请输入变量全称获取变量用途。
* 系统变量R
RASTERDPI
RASTERPERCENT
RASTERPREVIEW
RASTERTHRESHOLD
REBUILD2DCV
REBUILD2DDEGREE
REBUILD2DOPTION
REBUILDDEGREEU
REBUILDDEGREEV
REBUILDOPTIONS
REBUILDU
REBUILDV
RECOVERAUTO
RECOVERYMODE
REFEDITNAME
REFPATHTYPE
REGENMODE
RE-INIT
REMEMBERFOLDERS
RENDERENVSTATE
RENDERLEVEL
RENDERLIGHTCALC
RENDERPREFSSTATE
RENDERTARGET
RENDERTIME
RENDERUSERLIGHTS
REPORTERROR
REVCLOUDCREATEMODE
REVCLOUDGRIPS
RIBBONBGLOAD
RIBBONCONTEXTSELLIM
RIBBONDOCKEDHEIGHT
RIBBONICONRESIZE
RIBBONSELECTMODE
RIBBONSTATE
ROAMABLEROOTPREFIX
ROLLOVEROPACITY
ROLLOVERTIPS
RTDISPLAY
请输入变量全称获取变量用途。
* 系统变量Q
QCSTATE
QPLOCATION
QPMODE
QTEXTMODE
QVDRAWINGPIN
QVLAYOUTPIN
请输入变量全称获取变量用途。
* 系统变量P
PALETTEOPAQUE
PAPERUPDATE
PARAMETERCOPYMODE
PARAMETERSSTATUS
PCMSTATE
PDFFRAME
PDFIMPORTFILTER
PDFIMPORTIMAGEPATH
PDFIMPORTLAYERS
PDFIMPORTMODE
PDFOSNAP
PDFSHX
PDFSHXBESTFONT
PDFSHXLAYER
PDFSHXTHRESHOLD
PDMODE
PDSIZE
PEDITACCEPT
PELLIPSE
PERIMETER
PERSPECTIVE
PERSPECTIVECLIP
PFACEVMAX
PICKADD
PICKAUTO
PICKBOX
PICKDRAG
PICKFIRST
PICKSTYLE
PLATFORM
PLINECONVERTMODE
PLINEGCENMAX
PLINEGEN
PLINEREVERSEWIDTHS
PLINETYPE
PLINEWID
PLOTOFFSET
PLOTROTMODE
PLOTTRANSPARENCYOVERRIDE
PLQUIET
POINTCLOUD2DVSDISPLAY
POINTCLOUDAUTOUPDATE
POINTCLOUDBOUNDARY
POINTCLOUDCACHESIZE
POINTCLOUDCLIPFRAME
POINTCLOUDDENSITY
POINTCLOUDLIGHTING
POINTCLOUDLIGHTSOURCE
POINTCLOUDLOCK
POINTCLOUDLOD
POINTCLOUDPOINTMAX
POINTCLOUDPOINTMAXLEGACY
POINTCLOUDPOINTSIZE
POINTCLOUDRTDENSITY
POINTCLOUDSHADING
POINTCLOUDVISRETAIN
POLARADDANG
POLARANG
POLARDIST
POLARMODE
POLYSIDES
POPUPS
PREVIEWCREATIONTRANSPARENCY
PREVIEWFILTER
PREVIEWTYPE
PRODUCT
PROGRAM
PROJECTNAME
PROJMODE
PROPERTYPREVIEW
PROPOBJLIMIT
PROPPREVTIMEOUT
PROXYGRAPHICS
PROXYNOTICE
PROXYSHOW
PSLTSCALE
PSOLHEIGHT
PSOLWIDTH
PSTYLEMODE
PSTYLEPOLICY
PSVPSCALE
PUBLISHALLSHEETS
PUBLISHCOLLATE
PUBLISHHATCH
PUCSBASE
请输入变量全称获取变量用途。
* 系统变量O
OBJECTISOLATIONMODE
OBSCUREDCOLOR
OBSCUREDLTYPE
OFFSETDIST
OFFSETGAPTYPE
OLEFRAME
OLEHIDE
OLEQUALITY
OLESTARTUP
OPMSTATE
ORBITAUTOTARGET
ORTHOMODE
OSMODE
OSNAPCOORD
OSNAPNODELEGACY
OSNAPOVERRIDE
OSNAPZ
OSOPTIONS
请输入变量全称获取变量用途。
* 系统变量N
NAVBARDISPLAY
NAVSWHEELMODE
NAVSWHEELOPACITYBIG
NAVSWHEELOPACITYMINI
NAVSWHEELSIZEBIG
NAVSWHEELSIZEMINI
NAVVCUBEDISPLAY
NAVVCUBELOCATION
NAVVCUBEOPACITY
NAVVCUBEORIENT
NAVVCUBESIZE
NOMUTT
NORTHDIRECTION
请输入变量全称获取变量用途。
* 系统变量M
MATBROWSERSTATE
MATEDITORSTATE
MAXACTVP
MAXSORT
MAXTOUCHES
MBUTTONPAN
MEASUREINIT
MEASUREMENT
MENUBAR
MENUECHO
MENUNAME
MESHTYPE
MILLISECS
MIRRHATCH
MIRRTEXT
MLEADERSCALE
MODEMACRO
MSLTSCALE
MSMSTATE
MSOLESCALE
MTEXTAUTOSTACK
MTEXTCOLUMN
MTEXTDETECTSPACE
MTEXTED
MTEXTFIXED
MTEXTTOOLBAR
MTJIGSTRING
MVIEWPREVIEW
MYDOCUMENTSPREFIX
请输入变量全称获取变量用途。
* 系统变量L
LARGEOBJECTSUPPORT
LASTANGLE
LASTPOINT
LASTPROMPT
LATITUDE
LAYERDLGMODE
LAYEREVAL
LAYEREVALCTL
LAYERFILTERALERT
LAYERMANAGERSTATE
LAYERNOTIFY
LAYEROVERRIDEHIGHLIGHT
LAYLOCKFADECTL
LAYOUTCREATEVIEWPORT
LAYOUTREGENCTL
LAYOUTTAB
LEGACYCODESEARCH
LEGACYCTRLPICK
LENSLENGTH
LIGHTGLYPHDISPLAY
LIGHTINGUNITS
LIGHTLISTSTATE
LIGHTSINBLOCKS
LIMCHECK
LIMMAX
LIMMIN
LINEFADING
LINEFADINGLEVEL
LINESMOOTHING
LOCALE
LOCALROOTPREFIX
LOCKUI
LOFTANG1
LOFTANG2
LOFTMAG1
LOFTMAG2
LOFTNORMALS
LOFTPARAM
LOGFILEMODE
LOGFILENAME
LOGFILEPATH
LOGINNAME
LONGITUDE
LTGAPSELECTION
LTSCALE
LUNITS
LUPREC
LWDEFAULT
LWDISPLAY
LWUNITS
请输入变量全称获取变量用途。
* 系统变量I
IBLENVIRONMENT
IMAGEFRAME
IMAGEHLT
IMPLIEDFACE
INDEXCTL
INETLOCATION
INPUTHISTORYMODE
INPUTSEARCHDELAY
INSBASE
INSNAME
INSUNITS
INSUNITSDEFSOURCE
INSUNITSDEFTARGET
INTELLIGENTUPDATE
INTERFERECOLOR
INTERFEREOBJVS
INTERFEREVPVS
INTERSECTIONCOLOR
INTERSECTIONDISPLAY
ISAVEBAK
ISAVEPERCENT
ISOLINES
请输入变量全称获取变量用途。
* 系统变量H
HALOGAP
HANDLES
HELPPREFIX
HIDETEXT
HIGHLIGHT
HIGHLIGHTSMOOTHING
HPANG
HPANNOTATIVE
HPASSOC
HPBACKGROUNDCOLOR
HPBOUND
HPBOUNDRETAIN
HPCOLOR
HPDLGMODE
HPDOUBLE
HPDRAWORDER
HPGAPTOL
HPINHERIT
HPISLANDDETECTION
HPISLANDDETECTIONMODE
HPLAYER
HPLINETYPE
HPMAXAREAS
HPMAXLINES
HPNAME
HPOBJWARNING
HPORIGIN
HPORIGINMODE
HPPICKMODE
HPQUICKPREVIEW
HPQUICKPREVTIMEOUT
HPSCALE
HPSEPARATE
HPSPACE
HPTRANSPARENCY
HYPERLINKBASE
请输入变量全称获取变量用途。
* 系统变量G
GALLERYVIEW
GEOLATLONGFORMAT
GEOLOCATEMODE
GEOMAPMODE
GEOMARKERVISIBILITY
GEOMARKPOSITIONSIZE
GFANG
GFCLR1
GFCLR2
GFCLRLUM
GFCLRSTATE
GFNAME
GFSHIFT
GLOBALOPACITY
GRIDDISPLAY
GRIDMAJOR
GRIDMODE
GRIDSTYLE
GRIDUNIT
GRIPBLOCK
GRIPCOLOR
GRIPCONTOUR
GRIPDYNCOLOR
GRIPHOT
GRIPHOVER
GRIPMULTIFUNCTIONAL
GRIPOBJLIMIT
GRIPS
GRIPSIZE
GRIPSUBOBJMODE
GRIPTIPS
GROUPDISPLAYMODE
GTAUTO
GTDEFAULT
GTLOCATION
请输入变量全称获取变量用途。
* 系统变量F
FACETERDEVNORMAL
FACETERDEVSURFACE
FACETERGRIDRATIO
FACETERMAXEDGELENGTH
FACETERMAXGRID
FACETERMESHTYPE
FACETERMINUGRID
FACETERMINVGRID
FACETERPRIMITIVEMODE
FACETERSMOOTHLEV
FACETRATIO
FACETRES
FIELDDISPLAY
FIELDEVAL
FILEDIA
FILETABPREVIEW
FILETABSTATE
FILETABTHUMBHOVER
FILLETPOLYARC
FILLETRAD
FILLETRAD3D
FILLMODE
FONTALT
FONTMAP
FRAME
FRAMESELECTION
FRONTZ
FULLOPEN
FULLPLOTPATH
请输入变量全称获取变量用途。
* 系统变量E
EDGEMODE
ELEVATION
ENTERPRISEMENU
ERHIGHLIGHT
ERRNO
ERSTATE
EXPERT
EXPLMODE
EXPORTMODELSPACE
EXPORTPAGESETUP
EXPORTPAPERSPACE
EXPVALUE
EXPWHITEBALANCE
EXTMAX
EXTMIN
EXTNAMES
请输入变量全称获取变量用途。
* 系统变量D
DATALINKNOTIFY
DATE
DBCSTATE
DBLCLKEDIT
DBMOD
DCTCUST
DCTMAIN
DEFAULTGIZMO
DEFAULTLIGHTING
DEFAULTLIGHTINGTYPE
DEFLPLSTYLE
DEFPLSTYLE
DELOBJ
DEMANDLOAD
DGNFRAME
DGNIMPORTMAX
DGNIMPORTMODE
DGNMAPPINGPATH
DGNOSNAP
DIASTAT
DIGITIZER
DIMADEC
DIMALT
DIMALTD
DIMALTF
DIMALTRND
DIMALTTD
DIMALTTZ
DIMALTU
DIMALTZ
DIMANNO
DIMAPOST
DIMARCSYM
DIMASSOC
DIMASZ
DIMATFIT
DIMAUNIT
DIMAZIN
DIMBLK
DIMBLK1
DIMBLK2
DIMCEN
DIMCLRD
DIMCLRE
DIMCLRT
DIMCONSTRAINTICON
DIMCONTINUEMODE
DIMDEC
DIMDLE
DIMDLI
DIMDSEP
DIMEXE
DIMEXO
DIMFRAC
DIMFXL
DIMFXLON
DIMGAP
DIMJOGANG
DIMJUST
DIMLAYER
DIMLDRBLK
DIMLFAC
DIMLIM
DIMLTEX1
DIMLTEX2
DIMLTYPE
DIMLUNIT
DIMLWD
DIMLWE
DIMPICKBOX
DIMPOST
DIMRND
DIMSAH
DIMSCALE
DIMSD1
DIMSD2
DIMSE1
DIMSE2
DIMSOXD
DIMSTYLE
DIMTAD
DIMTDEC
DIMTFAC
DIMTFILL
DIMTFILLCLR
DIMTIH
DIMTIX
DIMTM
DIMTMOVE
DIMTOFL
DIMTOH
DIMTOL
DIMTOLJ
DIMTP
DIMTSZ
DIMTVP
DIMTXSTY
DIMTXT
DIMTXTDIRECTION
DIMTXTRULER
DIMTZIN
DIMUPT
DIMZIN
DISPSILH
DISTANCE
DIVMESHBOXHEIGHT
DIVMESHBOXLENGTH
DIVMESHBOXWIDTH
DIVMESHCONEAXIS
DIVMESHCONEBASE
DIVMESHCONEHEIGHT
DIVMESHCYLAXIS
DIVMESHCYLBASE
DIVMESHCYLHEIGHT
DIVMESHPYRBASE
DIVMESHPYRHEIGHT
DIVMESHPYRLENGTH
DIVMESHSPHEREAXIS
DIVMESHSPHEREHEIGHT
DIVMESHTORUSPATH
DIVMESHTORUSSECTION
DIVMESHWEDGEBASE
DIVMESHWEDGEHEIGHT
DIVMESHWEDGELENGTH
DIVMESHWEDGESLOPE
DIVMESHWEDGEWIDTH
DONUTID
DONUTOD
DRAGMODE
DRAGP1
DRAGP2
DRAGVS
DRAWORDERCTL
DRSTATE
DTEXTED
DWFFRAME
DWFOSNAP
DWGCHECK
DWGCODEPAGE
DWGNAME
DWGPREFIX
DWGTITLED
DXEVAL
DYNCONSTRAINTMODE
DYNDIGRIP
DYNDIVIS
DYNINFOTIPS
DYNMODE
DYNPICOORDS
DYNPIFORMAT
DYNPIVIS
DYNPROMPT
DYNTOOLTIPS
请输入变量全称获取变量用途。
* 系统变量C
CACHEMAXFILES
CACHEMAXTOTALSIZE
CALCINPUT
CAMERADISPLAY
CAMERAHEIGHT
CANNOSCALE
CANNOSCALEVALUE
CAPTURETHUMBNAILS
CBARTRANSPARENCY
CCONSTRAINTFORM
CDATE
CECOLOR
CELTSCALE
CELTYPE
CELWEIGHT
CENTERCROSSGAP
CENTERCROSSSIZE
CENTEREXE
CENTERLAYER
CENTERLTSCALE
CENTERLTYPE
CENTERLTYPEFILE
CENTERMARKEXE
CENTERMT
CETRANSPARENCY
CGEOCS
CHAMFERA
CHAMFERB
CHAMFERC
CHAMFERD
CHAMMODE
CIRCLERAD
CLAYER
CLAYOUT
CLEANSCREENSTATE
CLIPROMPTLINES
CLIPROMPTUPDATE
CLISTATE
CMATERIAL
CMDACTIVE
CMDDIA
CMDECHO
CMDINPUTHISTORYMAX
CMDNAMES
CMFADECOLOR
CMFADEOPACITY
CMLEADERSTYLE
CMLJUST
CMLSCALE
CMLSTYLE
CMOSNAP
COLORTHEME
COMMANDPREVIEW
COMPARECOLOR1
COMPARECOLOR2
COMPARECOLORCOMMON
COMPAREFRONT
COMPAREHATCH
COMPAREPROPS
COMPARERCMARGIN
COMPARERCSHAPE
COMPARESHOW1
COMPARESHOW2
COMPARESHOWCOMMON
COMPARESHOWRC
COMPARETEXT
COMPARETOLERANCE
COMPASS
COMPLEXLTPREVIEW
CONSTRAINTBARDISPLAY
CONSTRAINTBARMODE
CONSTRAINTINFER
CONSTRAINTNAMEFORMAT
CONSTRAINTSOLVEMODE
COORDS
COPYMODE
CPLOTSTYLE
CPROFILE
CROSSINGAREACOLOR
CTAB
CTABLESTYLE
CULLINGOBJ
CULLINGOBJSELECTION
CURSORBADGE
CURSORSIZE
CURSORTYPE
CVIEWDETAILSTYLE
CVIEWSECTIONSTYLE
CVPORT
请输入变量全称获取变量用途。
* 系统变量B
BACKGROUNDPLOT
BACKZ
BACTIONBARMODE
BACTIONCOLOR
BCONSTATUSMODE
BDEPENDENCYHIGHLIGHT
BGRIPOBJCOLOR
BGRIPOBJSIZE
BINDTYPE
BLOCKEDITLOCK
BLOCKEDITOR
BLOCKMRULIST
BLOCKNAVIGATE
BLOCKREDEFINEMODE
BLOCKSTATE
BLOCKTESTWINDOW
BPARAMETERCOLOR
BPARAMETERFONT
BPARAMETERSIZE
BPTEXTHORIZONTAL
BTMARKDISPLAY
BVMODE
请输入变量全称获取变量用途。
* 系统变量A
ACADLSPASDOC
ACADPREFIX
ACADVER
ACTPATH
ACTRECORDERSTATE
ACTRECPATH
ACTUI
ADCSTATE
AFLAGS
ANGBASE
ANGDIR
ANNOALLVISIBLE
ANNOAUTOSCALE
ANNOMONITOR
ANNOTATIVEDWG
APBOX
APERTURE
APPAUTOLOAD
APPLYGLOBALOPACITIES
APSTATE
AREA
ARRAYASSOCIATIVITY
ARRAYEDITSTATE
ARRAYTYPE
ATTDIA
ATTIPE
ATTMODE
ATTMULTI
ATTREQ
AUDITCTL
AUNITS
AUPREC
AUTODWFPUBLISH
AUTOMATICPUB
AUTOSNAP
请输入变量全称获取变量用途。
