* :vlax-null
com接口(null)
* :vlax-false
com接口(false,假,0)
* :vlax-true
com接口(true,真,-1)
* :constants-prefix
(vlax-import-type-library :tlb-filename filename [:methods-prefix mprefix :properties-prefix pprefix :constants-prefix  cprefix])
指示符号，指示函数 vlax-import-type-library 的参数 cprefix 
* :properties-prefix
(vlax-import-type-library :tlb-filename      filename [:methods-prefix    mprefix  :properties-prefix pprefix  :constants-prefix  cprefix])
指示符号，指示函数 vlax-import-type-library 的参数 pprefix
* :methods-prefix
(vlax-import-type-library  :tlb-filename      filename [:methods-prefix    mprefix  :properties-prefix pprefix  :constants-prefix  cprefix])
指示符号，指示函数 vlax-import-type-library 的参数 mprefix 
* :tlb-filename
(vlax-import-type-library  :tlb-filename      filename [:methods-prefix    mprefix  :properties-prefix pprefix  :constants-prefix  cprefix])
指示符号，指示函数 vlax-import-type-library 的参数 filename
* :vlr-objectClosed
反应器；对对象的修改已经完成，将被触发。
* :vlr-modified
对象已被修改。如果取消修改，还将激发:vlr-cancelled 和:vlr-modifyUndone。
* :vlr-documentToBeActivated
docmanager反应器事件：有非活动的文档刚接受到激活信号，意味着将要成为活动文档。
* :vlr-documentToBeDeactivated
docmanager 反应器事件：另一个窗口（在 AutoCAD 内部或外部）已被激活。
* :vlr-documentBecameCurrent
docmanager 反应器事件：当前文档已经产生变更（并没有意味当前文档已被激活）。
* :vlr-documentLockModeChanged
docmanager 反应器事件：文档所定权已被占据或释放。
* :vlr-documentLockModeChangeVetoed
docmanager 反应器事件：documentLockModeChange 被拒绝
* :vlr-documentLockModeWillChange
docmanager 反应器事件：文档元素将被修改或完成修改将要引起对文档锁定权的占据或释放。
* :vlr-documentToBeDestroyed
docmanager 反应器事件：有文档将被“销毁”（内存中）。
* :vlr-documentCreated
docmanager 反应器事件：新文件加入（通过全文档范围的反应器可获取）。
* :vlr-endDeepClone
deepclone 反应器事件：深拷贝将要结束。
* :vlr-abortDeepClone
deepclone 反应器事件：正要取消深拷贝。
* :vlr-beginDeepCloneXlation
deepclone 反应器事件：完成深拷贝的对象拷贝部分，将要开始对象 ID 引用变换。
* :vlr-beginDeepClone
deepclone 反应器事件：深拷贝将要开始。
* :vlr-objectUnErased
acdb 反应器事件：有对象已被移除删除标记。
* :vlr-objectErased
acdb 反应器事件：有对象已被附上删除标记。
* :vlr-objectModified
acdb 反应器事件：有对象已被修改。
* :vlr-objectOpenedForModify
acdb 反应器事件：有对象将被修改。
* :vlr-objectReAppended
acdb 反应器事件：有被拆离的对象已在数据库中被恢复。
* :vlr-objectUnAppended
acdb 反应器事件：有对象被从图形数据库拆离。
* :vlr-objectAppended
acdb 反应器事件：有对象被附加到图形数据库中。
