#+prefix: DCL框件
* boxed_column,带框竖向框集
分组框件，用于将组框件组织为一列，列周围有边框。
* boxed_radio_column,带框单选竖向框集
分组框件，用于将单选按钮框件组织为一列，列周围有边框。
* boxed_radio_row,带框单选水平框集
分组框件，用于将单选按钮框件组织为一行，行周围有边框。
* boxed_row,带框水平框集
分组框件，用于将组框件组织为一行，行周围有边框。
* button,按钮
DCL 按钮。
* clusters,框集,dcl框集
您可以将框件分组为复合行或列（统称为框集）。
出于布局目的，框集被视为单个框件。可以使用可选标签将行或列装箱（没有方框的框集不能标记）。
用户无法选择框集，只能选择框集中的单个框件。除了单选行和单选列之外，不能为框集分配操作。以下框件定义了框集：
- boxed_column
- dialog
- boxed_radio_column
- radio_column
- boxed_radio_row
- radio_row
- boxed_row
- row
- column
 
* column,竖向框集
分组磁贴，用于将磁贴组织为一列，而列周围没有边框。
* concatenation
串联是由多个串联的文本块组成的一行文本。
* dialog,对话框
dialog 是定义对话框的框件。
* edit_box,编辑框
编辑框是允许用户输入或编辑单行文本的字段。
* errtile,错误信息框件
错误框件是出现在对话框底部的文本框件。
* image Tile,图像
图像是显示矢量图形图片的矩形框件。
* image_button,图像按钮
图像按钮框件是显示图形图像而不是标签的按钮。
* list_box,列表框件
列表框包含按行排列的文本字符串列表。
* ok_cancel
ok_cancel互动程序框件是“确定”和“取消”按钮的组合，是可以发起数据更改的对话框的标准组合。
* ok_cancel_help
此框件是与“帮助”按钮组合的ok_cancel框集。
* ok_cancel_help_errtile
ok_cancel_help_errtile框件提供了一种方便的方法，可以同时指定退出按钮和错误框件。
* ok_cancel_help_info
ok_cancel_help_info框件执行ok_cancel _help框件执行的所有操作，但它还包括一个用于显示其他材料的信息按钮。
* ok_only
ok_only框件是一个单独的ok按钮，例如警报框使用的那种。
* paragraph,段落框集
段落是垂直排列的text_part或concatenation 框件的框集。
* popup_list,弹出列表
弹出列表或简单的弹出列表在功能上等同于列表框。
* radio_button,单选按钮
单选按钮是组成单选列或单选行的一组按钮之一。
* radio_column,单选竖向框集
单选列包含单选按钮磁贴，一次只能选择其中一个。
* radio_row,单选水平框集
单选行和单选列一样，包含单选按钮块，一次只能选择其中一个。
* row,水平框集
分组框集，用于将框件组织成一行，周围没有边框。
* slider,滑块框件
滑块获取数值。
* spacer
该框件用于在对话框定义中的其他框件之间添加空间。
* spacer_0
该框件用于在对话框定义中的其他框件之间添加空间。
* spacer_1
该框件用于在对话框定义中的其他框件之间添加空间。
* text Tile,文本框件
文本本框件显示用于标题或信息目的的文本字符串。
* text_part,文本片断框件
文本部分是一块较大文本的一部分的文本框件。
* toggle,开关框件,复选框件
切换显示为一个小框，框右侧有一个可选标签。
* destroy_button
** destroy_button : retirement_button {label = "&Destroy"; key = "destroy";}
用于替换默认的退出按钮。
···
destroy_button : retirement_button {
  label = "&Destroy";
  key = "destroy";
}
···
