* -5
App: permanent reactor chain
* -4
App: conditional operator (only used with ssget)
* -3
App: extended data (XDATA) tag (fixed)
* -2
App: element name reference (fixed)
* -1
App: element name. Every time you open a drawing, the element name changes and is never saved (fixed)
* 0
String representing element type (fixed)
* 1
Primary text value of the element
* 2
Name (attribute tag, block name, etc.)
* 3-4
Other text or name values
* 5
Primitive handle; String of up to 16 hexadecimal digits (fixed)
* 6
Linetype name (fixed) (appears if it is not bylayer). The special name "byblock" indicates a variable linetype (optional)
* 7
Text style name (fixed)
* 8
Layer name (fixed)
* 9
DXF: variable name identifier (only used in header section of DXF file)
* 10
Main points; The starting point of a line or text element, the center of a circle, and so on
DXF: x value of main point (followed by Y and Z value codes 20 and 30)
App: 3D points (list of three real numbers)
* 11-18
Other points
DXF: x value of other points (followed by y value code 21-28 and Z value code 31-38)
App: 3D points (list of three real numbers)
* 20, 30
DXF: y and Z values of major points
* 21-28, 31-37
DXF: y and Z values of other points
* 38
DXF: if it is not zero, it is the elevation of the element
* 39
If it is not zero, it is the thickness of the element (fixed)
* 40-48
Double precision floating point value (text height, scale, etc.)
* 48
Linetype scale; Double precision floating-point scalar value; The default value applies to all element types
* 49
Duplicate double precision floating-point value. Multiple 49 groups may appear in the variable length table of an entity (for example, the dashed line length in the Ltype table). 7x group always appears before the first 49 group to specify the length of the table
* 50-58
Angle (in degrees in DXF files and radians in AutoLISP and ObjectARX applications)
* 60
Element visibility; Integer value; If it is not assigned or the value is 0, it means it is visible; A value of 1 means invisible
* 62
Color number (fixed)
* 66
"Heel element" flag (fixed)
* 67
Space - model space or paper space (fixed)
Non existence or zero indicates that the element is in model space. 1 indicates that the element is in paper space (optional)
* 68
App: indicates whether the viewport is open but completely invisible on the screen, or inactive or closed
* 69
App: viewport ID
* 70-78
Integer value, such as repeat count, flag bit or mode
* 90-91,93-99
DWORD 32-bit integer value
* 92
The number of bytes in the proxy primitive graphics represented in the following 310 groups (binary data block records) (optional)
* 100
Subclass data tag (using the derived class name as a string) all object and element classes derived from other concrete classes must have this tag. Subclass data tags are used to separate data defined by different classes in the inheritance chain of the same object. 
This is an additional requirement that must be met for the DXF name of each different concrete class derived from ObjectARX (see "subclass marking")
* 102
Control string followed by "{< any name >" or "}". Similar to the extended data 1002 group code, the difference is that when the string starts with "{", it can be followed by any string, and the interpretation of the string depends on the application. The only other allowed control string is "}" as the end of the group. AutoCAD does not interpret these strings outside the drawing review operation. They are supplied for use by programs
"{acad_reactors" indicates the beginning of the AutoCAD permanent reactor group. This group exists only when permanent reactors are attached to this object (optional)
* 105
Object handle of dimvar symbol table entry
* 110
UCS origin (displayed only when code 72 is set to 1)
DXF: x value; App: 3D points
* 111
UCS X axis (displayed only when code 72 is set to 1)
DXF: x value; App: 3D vector
* 112
UCS Y axis (displayed only when code 72 is set to 1)
DXF: x value; App: 3D vector
* 120-122
DXF: y value of UCS origin, UCS X axis and UCS Y axis
* 130-132
DXF: Z value of UCS origin, UCS X axis and UCS Y axis
* 140-149
Double precision floating-point values (such as point, elevation, and dimstyle settings)
* 170-179
Word 16 bit integer value, for example, indicating the flag bit set by dimstyle
* 210
Stretching direction (fixed)
DXF: x value of extrusion direction
App: 3D extrusion direction vector
* 220, 230
DXF: y and Z values of extrusion direction
* 270-279
16 bit integer value
* 280-283,285-289
16 bit integer value
* 284
Shadow mode
0 = cast and receive shadows
1 = cast shadow
2 = receive shadow
3 = ignore shadows
Note: this feature has been deprecated since AutoCAD 2016 based products, but it is still supported for backward compatibility. 
* 290-299
Boolean flag value
* 300-309
Any string
* 310
Proxy primitive graphics data (multiple lines; 256 characters per line at most) (optional)
Any binary block with the same representation and 1004 group code limit: a hexadecimal string with a maximum length of 254 characters is used to represent a data block with a maximum length of 127 bytes
* 311-319
Any binary block with the same representation and 1004 group code limit: a hexadecimal string with a maximum length of 254 characters is used to represent a data block with a maximum length of 127 bytes
* 320-329
Any object handle; Handle value obtained "as is". They are not converted during insert and XRef operations
* 330-339
Soft pointer handle; Any soft pointer to another object in the same DXF file or drawing. Convert during insert and XRef operations
330 owner block_Soft pointer ID / handle of record object
* 340-349
Hard pointer handle; Any hard pointer to another object in the same DXF file or drawing. Convert during insert and XRef operations
347 hard pointer ID / handle of material object (appears if it is not "bylayer")
* 350-359
Soft owner handle; Any soft owner pointer to another object in the same DXF file or drawing. Convert during insert and XRef operations
* 360-369
Hard owner handle; Any hard owner pointer to another object in the same DXF file or drawing. Convert during insert and XRef operations
Hard owner ID / handle of owner Dictionary (optional)
* 370-379
Line width enumeration value (acdb:: lineweight). Stored and moved as a 16 bit integer. Custom non entity objects can use the whole range of group codes, but the drawing element class can only use the 371-379 DXF group codes in its representation, because AutoCAD and AutoLISP always assume that the 370 group code is the line width of the entity. This makes 370 group codes behave similarly to other "common" primitive fields
* 380-389
Plotstylename type enumeration (acdb:: plotstylenametype). Stored and moved as a 16 bit integer. Custom non primitive objects can use the group code in the whole range, but the primitive class can only be used in its representation
* 390-399
A string representing the handle value of the plotstylename object. It is a hard pointer in nature, but has different ranges, making it easier to handle backward compatibility. It is stored and moved as object ID (handle in DXF file) and special type in AutoLISP. User defined non primitive objects can use the group codes in the whole range, but the graphic element class can only use 391-399 DXF group codes in its representation, for the same reason as the above line width range
* 400-409
Word 16 bit integer
* 410-419
String, 410 app: Layout tab name
* 420-427
DWORD is a 32-bit integer value. When used with true color, it is a 32-bit integer representing a 24 bit color value. High order byte (8 bits) is 0; The lower order byte is an unsigned character containing a "blue" value (0-255) followed by a "green" value; The next higher byte is the "red" value. Converting this integer value to hexadecimal value will get the following bitmask: 0x00rrggbb. For example, the true colors of red = = 200, green = = 100 and blue = = 50 are 0x00c86432, while in DXF, they are 13132850 in decimal notation
* 430-437
character string; When used for true color, it is a string representing the color name
* 440-447
DWORD is a 32-bit integer value. When used for true color, it indicates the transparency value
* 450-459
long integer
* 460-469
Double precision floating point value
* 470-479
character string
* 480-481
Hard pointer handle; Any hard pointer to another object in the same DXF file or drawing. Convert during insert and XRef operations
* 999
DXF: 999 group code indicates that the following line is a comment string. SaveAs does not include such groups in the DXF output file, but open includes these groups and ignores comments. You can use the 999 group to include comments in DXF files that you have edited
* 1000
Ascii string in extended data (up to 255 bytes)
* 1001
Registered application name of extended data (can contain up to 31 byte ascii string)
* 1002
XDATA control string ('{' or '}')
* 1003
Extended data layer name
* 1004
Byte data block in extended data (up to 127 bytes)
* 1005
Primitive handle in extended data; A string that can contain up to 16 hexadecimal digits
* 1010
Points in extended data
DXF: x value (followed by 1020 and 1030 groups)
App: 3D points
* 1020, 1030
DXF: y and Z values of points
* 1011
3D world space position in XDATA
DXF: x value (followed by groups 1021 and 1031)
App: 3D points
* 1021, 1031
DXF: y and Z values of world space position
* 1012
3D world spatial displacement in XDATA
DXF: x value (followed by 1022 and 1032 groups)
App: 3D vector
* 1022, 1032
DXF: y and Z values of world space displacement
* 1013
3D spatial direction in XDATA
DXF: x value (followed by 1022 and 1032 groups)
App: 3D vector
* 1023, 1033
DXF: y and Z values of world space direction
* 1040
XDATA double precision floating point value
* 1041
Extended data distance value
* 1042
Extended data scaling
* 1070
Extended data 16 bit signed integer
* 1071
Extended data 32-bit signed long integer
* 3DFACE
** 100
Subclass marker (acdbface)
** 10
First corner (in WCS)
DXF: x value; App: 3D points
** 20, 30
DXF: y and Z values of the first corner (in WCS)
** 11
Second corner (in WCS)
DXF: x value; App: 3D points
** 21, 31 
DXF: y and Z values of the second corner (in WCS)
** 12
Third point (in WCS)
DXF: x value; App: 3D points
** 22, 32
DXF: y and Z values of the third triangle point (in WCS)
** 13
The fourth corner (in WCS). If only three corners are input, the fourth corner is the same as the third corner
DXF: x value; App: 3D points
** 23, 33
DXF: y and Z values of the fourth corner (in WCS)
** 70
Invisible edge flag (optional; default = 0): 
1 = the first edge is invisible
2 = the second edge is invisible
4 = the third edge is invisible
8 = the fourth edge is invisible
* 3DSOLID
** 100
Subclass tag (acdbmodelergeometry)
** 70
Modeling format version number (current value = 1)
** 1
Ownership data (multiple lines, each line < 255 characters)
** 3
Additional row of ownership data (if the string length of the previous group 1 is greater than 255 characters) (optional)
** 100
Subclass tag (acdb3dsolid)
** 350
Soft owner ID / handle of history object
* ACAD_PROXY_ENTITY
** 100 DXF：AcDbProxyEntity
**90 DXF: proxy primitive class ID (always 498)
**91 DXF: class ID of application entity. The class ID is based on the order of the classes in the classes section. The ID of the first class is 500, the next is 501, and so on
**92 DXF: size of drawing data (in bytes)
**310 DXF: binary drawing data (multiple entries may occur) (optional)
**93 DXF: size of entity data (in bits)
**310 DXF: binary entity data (multiple entries may occur) (optional)
**330, 340, 350 or 360 DXF: object ID (multiple entries may occur) (optional)
**94 DXF: 0 (end of object ID segment)
**95 DXF: object graphics format when an object becomes a proxy (32-bit unsigned integer): 
The lower word is acdbdwgversion
The high word is maintenancerereleaseversion
**70 DXF: original custom object data format: 
0 = DWG format
1 = DXF format
* ARC
** 100
Subclass marker (acdbcircle)
** 39
Thickness (optional; default = 0)
** 10
Center point (in OCS)
DXF: x value; App: 3D points
** 20, 30
DXF: y and Z values of the center point (in OCS)
** 40
radius
** 100
Subclass marker (acdbarc)
** 50
Starting angle
** 51
End angle
** 210
Stretch direction (optional; default = 0, 0, 1)
DXF: x value; App: 3D vector
** 220, 230
DXF: y and Z values of extrusion direction (optional)
* ATTDEF
** 100
Subclass tag (acdbtext)
** 39
Thickness (optional; default = 0)
** 10
First alignment point (in OCS)
DXF: x value; App: 3D points
** 20, 30
DXF: y value and Z value of text starting point (in OCS)
** 40
Text height
** 1
Default value (string)
** 50
Text rotation angle (optional; default = 0)
** 41
X relative scale (width) (optional; default = 1). This value is also adjusted when fitting type text is used. 
** 51
Tilt angle (optional; default = 0)
** 7
Text style name (optional; default = standard)
** 71
Text generation flag (optional; default = 0); See text group code
** 72
Text horizontal alignment type (optional; default = 0); See text group code
** 11
Second alignment point (in OCS) (optional)
DXF: x value; App: 3D points
It is meaningful only when the 72 or 74 group values are non-zero
** 21, 31
DXF: y and Z values of the second alignment point (in OCS) (optional)
** 210
Stretch direction (optional; default = 0, 0, 1)
DXF: x value; App: 3D vector
** 220, 230
DXF: y and Z values of extrusion direction
** 100
Subclass tag (acdbattributeddefinition)
** 280
Version number: 
0 = 2010
** 3
Prompt string
** 2
Label string (cannot contain spaces)
** 70
Attribute tag: 
1 = attribute invisible (not present)
2 = fixed attribute
4 = require verification when entering attributes
8 = attribute is preset (no prompt when inserting)
** 73
Field length (optional; default = 0) (not currently used)
** 74
Text vertical alignment type (optional; default = 0); See group code 73 in text
** 280
Lock the position mark. Locks the location of attributes in a block reference
** 100
Subclass tag (acdbxrecord)
** 280
Duplicate record clone flag (determines how to merge duplicate entries): 
1 = keep existing
** 70
Multiline text mark: 
2 = multiline text attribute
4 = fixed multiline text attribute definition
** 70
Actual lock flag: 
0 = unlock
1 = lock
** 70
Number of secondary attributes or attribute definitions
** 340
Hard pointer ID of secondary attribute or attribute definition
** 10
Attribute or attribute definition alignment point
DXF: x value; App: 3D points
** 20,30
DXF: y and Z values of insertion point
** 40
Current annotation scale
** 2
Property or property definition label string
** 0
Element type (Mtext)
** 100
Subclass tag (acdbentity)
** 67
Non existence or zero indicates that the element is in model space. 1 indicates that the element is in paper space (optional)
** 8
Layer name
** 100
Subclass tag (acdbmtext)
** 10
insertion point
DXF: x value; App: 3D points
** 20,30
DXF: y and Z values of insertion point
** 40
Nominal (initial) text height
** 41
Reference rectangle width
** 46
Define annotation height
** 71
Attachment point: 
1 = upper left; 2 = upper middle; 3 = upper right
4 = left middle; 5 = center; 6 = right middle
7 = lower left; 8 = middle lower; 9 = lower right
** 72
Drawing direction: 
1 = left to right
3 = from top to bottom
5 = with style (inherited from relevant text style)
** 1
Text string
If the string length is less than 250 characters, all characters appear in group 1. If the string length is greater than 250 characters, the string will be divided into data blocks with a length of 250 characters and displayed in one or more group 3 codes. If the group 3 code is used, the last group will be group 1 and less than 250 characters. 
** 3
Additional text (always in a 250 character block) (optional)
** 7
DXF: x value; App: 3D vector text style name (standard if not provided) (optional)
** 210
Stretch direction (optional; default = 0, 0, 1)
DXF: x value; App: 3D vector
** 220,230
DXF: y and Z values of extrusion direction (optional)
** 11
X-axis direction vector (in WCS)
DXF: x value; App: 3D vector
** 21,31
DXF: y value and Z value of x-axis direction vector (in WCS)
** 42
The horizontal width of the characters that make up the Mtext entity. 
This value is always equal to or less than the value of group code 41 (read only, ignored if provided). 
** 43
Vertical height of Mtext element (read only, ignored if provided)
** 50
Rotation angle in radians
** 73
Line spacing style for multiline text (optional): 
1 = at least (will be replaced with higher characters)
2 = precise (will not be replaced with higher characters)
** 44
Line spacing ratio of multiline text (optional): 
The default percentage (three fifths) of line spacing to apply. 
Valid values range from 0.25 to 4.00
** 90
Background fill settings: 
0 = background fill off
1 = use background fill color
2 = use the graphics window color as the background fill color
** 63
Background color (color index number)
** 420-429
Background color (RGB color)
** 430-439
Background color (color name)
** 45
Fill box size (optional): 
Determines the size of the border around the text. 
** 63
Background fill color (optional): 
The color to be used for background filling when the group code 90 is 1. 
** 441
Transparency of background fill color (not implemented)
* ATTRIB
** 100
Subclass tag (acdbtext)
** 39
Thickness (optional; default = 0)
** 10
Text start point (in OCS)
DXF: x value; App: 3D points
** 20, 30
DXF: y value and Z value of text starting point (in OCS)
** 40
Text height
** 1
Default value (string)
** 100
Subclass tag (acdbattribute)
** 280
Version number: 
0 = 2010
** 2
Attribute label (string; cannot contain spaces)
** 70
Attribute tag: 
1 = attribute invisible (not present)
2 = fixed attribute
4 = require verification when entering attributes
8 = attribute is preset (no prompt when inserting)
** 73
Field length (optional; default = 0) (not currently used)
** 50
Text rotation angle (optional; default = 0)
** 41
X relative scale (width) (optional; default = 1). This value is also adjusted when fitting type text is used. 
** 51
Tilt angle (optional; default = 0)
** 7
Text style name (optional; default = standard)
** 71
Text generation flag (optional; default = 0). See "text group codes" 
** 72
Text horizontal justification type (optional; default = 0). See "text group codes" 
** 74
Vertical text justification type (optional; default = 0). See "group code 73 in text" 
** 11
Alignment point (in OCS) (optional)
DXF: x value; App: 3D points
It only appears when group 72 or 74 appears and is not zero
** 21, 31
DXF: y and Z values of alignment points (in OCS) (optional)
** 210
Stretch direction. Appears only when the extrusion direction of the element is not parallel to the Z axis of WCS (optional; default = 0, 0, 1)
DXF: x value; App: 3D vector
** 220, 230
DXF: y and Z values of extrusion direction (optional)
** 280
Lock the position mark. Locks the location of attributes in a block reference
** 100
Subclass tag (acdbxrecord)
** 280
Duplicate record clone flag (determines how to merge duplicate entries): 
1 = keep existing
** 70
Multiline text mark: 
2 = multiline text attribute
4 = fixed multiline text attribute definition
** 70
Actual lock flag: 
0 = unlock
1 = lock
** 70
Number of secondary attributes or attribute definitions
three hundred and forty
Hard pointer ID of secondary attribute or attribute definition
** 10
Attribute or attribute definition alignment point
DXF: x value; App: 3D points
** 20,30
DXF: y and Z values of insertion point
** 40
Current annotation scale
** 2
Property or property definition label string
** 0
Element type (Mtext)
** 100
Subclass tag (acdbentity)
** 67
Non existence or zero indicates that the element is in model space. 1 indicates that the element is in paper space (optional)
** 8
Layer name
** 100
Subclass tag (acdbmtext)
** 10
insertion point
DXF: x value; App: 3D points
** 20,30
DXF: y and Z values of insertion point
** 40
Nominal (initial) text height
** 41
Reference rectangle width
** 46
Define annotation height
** 71
Attachment point: 
1 = upper left; 2 = upper middle; 3 = upper right
4 = left middle; 5 = center; 6 = right middle
7 = lower left; 8 = middle lower; 9 = lower right
** 72
Drawing direction: 
1 = left to right
3 = from top to bottom
5 = with style (inherited from relevant text style)
** 1
Text string
If the string length is less than 250 characters, all characters appear in group 1. If the string length is greater than 250 characters, the string will be divided into data blocks with a length of 250 characters and displayed in one or more group 3 codes. If the group 3 code is used, the last group will be group 1 and less than 250 characters. 
** 3
Additional text (always in a 250 character block) (optional)
** 7
DXF: x value; App: 3D vector text style name (standard if not provided) (optional)
** 210
Stretch direction (optional; default = 0, 0, 1)
DXF: x value; App: 3D vector
** 220,230
DXF: y and Z values of extrusion direction (optional)
** 11
X-axis direction vector (in WCS)
DXF: x value; App: 3D vector
** 21,31
DXF: y value and Z value of x-axis direction vector (in WCS)
** 42
The horizontal width of the characters that make up the Mtext entity. 
This value is always equal to or less than the value of group code 41 (read only, ignored if provided). 
** 43
Vertical height of Mtext element (read only, ignored if provided)
** 50
Rotation angle in radians
** 73
Line spacing style for multiline text (optional): 
1 = at least (will be replaced with higher characters)
2 = precise (will not be replaced with higher characters)
** 44
Line spacing ratio of multiline text (optional): 
The default percentage (three fifths) of line spacing to apply. 
Valid values range from 0.25 to 4.00
** 90
Background fill settings: 
0 = background fill off
1 = use background fill color
2 = use the graphics window color as the background fill color
** 63
Background color (color index number)
** 420-429
Background color (RGB color)
** 430-439
Background color (color name)
** 45
Fill box size (optional): 
Determines the size of the border around the text. 
** 63
Background fill color (optional): 
The color to be used for background filling when the group code 90 is 1. 
** 441
Transparency of background fill color (not implemented)
* BODY
** 100
Subclass tag (acdbmodelergeometry)
** 70
Modeling format version number (current value = 1)
** 1
Ownership data (multiple lines, each line < 255 characters)
** 3
Additional row of ownership data (if the string length of the previous group 1 is greater than 255 characters) (optional)
* CIRCLE
** 100
Subclass marker (acdbcircle)
** 39
Thickness (optional; default = 0)
** 10
Center point (in OCS)
DXF: x value; App: 3D points
** 20, 30
DXF: y and Z values of the center point (in OCS)
** 40
radius
** 210
Stretch direction (optional; default = 0, 0, 1)
DXF: x value; App: 3D vector
** 220, 230
DXF: y and Z values of extrusion direction (optional)
* COORDINATION MODEL
** 0
Object name (coordination model)
** 5
handle
** 330
Soft pointer ID / handle of owner dictionary
** 100
Subclass tag (acdbnavisworksmodel)
** 340
Soft pointer ID / handle to acdbnavisworksmodeldef object
40, 40, 40, 40
40, 40, 40, 40
40, 40, 40, 40
40, 40, 40, 40
Model transformation in WCS coordinates (4x4 matrix)
** 40
Insert unit factor
* DIMENSION
** 100
Subclass tag (acdbdimension)
** 280
Version number: 
0 = 2010
** 2
The name of the block that contains the elements that make up the annotation picture
** 10
Define points (in WCS)
DXF: x value; App: 3D points
** 20, 30
DXF: define y and Z values of points (in WCS)
** 11
Midpoint of dimension text (in OCS)
DXF: x value; App: 3D points
** 21, 31
DXF: y and Z values of the midpoint of dimension text (in OCS)
** 70
Dimension type: 
The value 0-6 is an integer value representing the dimension type. The values 32, 64 and 128 are the bit values added to the integer value (the value 32 is always set in R13 and later versions)
0 = rotation, horizontal or vertical
1 = align
2 = angle
3 = diameter
4 = radius
5 = three point angle
6 = coordinates
32 = indicates that the block reference (group code 2) is only referenced by this dimension. 
64 = coordinate type. This is a bit value (bit 7), which is only used with integer value 6. If this value is set, the coordinate is of type X; If not set, the coordinates are of type y. 
128 = this is a bit value (bit 8) added to the 70 value of the other group (if the dimension text has been placed in the user-defined position instead of the default position)
** 71
Attachment point: 
1 = upper left
2 = middle upper
3 = upper right
4 = left center
5 = center
6 = right middle
7 = lower left
8 = middle lower
9 = lower right
** 72
Dimension text line spacing style (optional): 
1 (or missing) = at least (will be replaced with higher characters)
2 = precise (will not be replaced with higher characters)
** 41
Dimension text line spacing scale (optional): 
The default percentage (three fifths) of line spacing to apply. Valid values range from 0.25 to 4.00
** 42
Actual measurement result (optional; read-only value)
** 1
Dimension text explicitly entered by the user. Optional; The default value is the measurement result. If it is empty or "< >", the dimensioned measurement results will be drawn as text; If it is "" (a space), the text will be suppressed. Other content is drawn as text
** 53
Optional group code 53 is the rotation angle (dimension line direction) between dimension text and its default direction (optional)
** 51
All dimension types have optional 51 group codes, which represent the horizontal direction of dimension entities. Dimension elements determine the direction of dimension text and lines for horizontal, vertical, and rotational linear dimensions
This set of values is the negative angle between the OCS X axis and the UCS X axis. It is always on the XY plane of the OCS
** 210
Stretch direction (optional; default = 0, 0, 1)
DXF: x value; App: 3D vector
** 220, 230
DXF: y and Z values of extrusion direction (optional)
** 3
Dimension style name
* ELLIPSE
** 100
Subclass marker (acdbellipse)
** 10
Center point (in WCS)
DXF: x value; App: 3D points
** 20, 30
DXF: y and Z values of the center point (in WCS)
** 11
Long axis endpoint relative to the center (in WCS)
DXF: x value; App: 3D points
** 21, 31
DXF: y and Z values of the major axis endpoint relative to the center (in WCS)
** 210
Stretch direction (optional; default = 0, 0, 1)
DXF: x value; App: 3D vector
** 220, 230
DXF: y and Z values of extrusion direction (optional)
** 40
Ratio of minor axis to major axis
** 41
Start point parameter (0.0 for closed ellipse)
** 42
Endpoint parameter (2pi for closed ellipses)
* HATCH
#Boundary path data
** 100
Subclass tag (acdbhatch)
** 10
Elevation point (in OCS)
DXF: x value = 0; App: 3D point (x and y are always equal to 0, Z represents elevation)
** 20, 30
DXF: y and Z values of elevation points (in OCS)
Y = 0, z = elevation
** 210
Stretch direction (optional; default = 0, 0, 1)
DXF: x value; App: 3D vector
** 220, 230
DXF: y and Z values of extrusion direction
** 2
Pattern name
** 70
Solid fill flag (0 = hatch; 1 = solid fill); For mpolygon, it is the version of mpolygon
** 63
For mpolygon, the hatch color is ACI
** 71
Correlation flag (0 = no correlation; 1 = correlation); For mpolygon, set the solid filling flag (0 = no solid filling; 1 = solid filling)
** 91
Number of boundary paths (rings)
varied
Boundary path data. Repeat the number of times specified by code 91. See "boundary path data" 
** 75
Hatch pattern: 
0 = hatch the odd parity area (normal style)
1 = hatch only the outermost region (external style)
2 = hatch the entire area (ignore style)
** 76
Pattern type: 
0 = user defined
1 = predefined
2 = custom
** 52
Pattern angle (hatch only)
** 41
Hatch pattern scale or spacing (hatch only)
** 73
For mpolygon, set the boundary annotation flag: 
0 = boundary is not annotation boundary
1 = boundary is annotation boundary
** 77
Pattern bidirectional flag (hatch only): 
0 = non bidirectional flag
1 = two way sign
** 78
Number of pattern definition lines
varied
Pattern line data. The number of repetitions specified by code 78. See "pattern data" 
** 47
The pixel size used to determine the density of performing various intersecting and ray method operations in the pattern calculation of related hatches and hatches created using the "fill" method of hatches. 
** 98
Seed number
** 11
For mpolygon, is the offset vector
** 99
For mpolygon, it is the number of degenerate boundary paths (rings) (degenerate boundary paths are borders ignored by hatch)
** 10
Seed point (in OCS)
DXF: x value; App: two dimensional point (multiple entries)
** 20
DXF: y value of seed point (in OCS); (multiple entries)
** 450
Represents a solid hatch or gradient; If it is a solid hatch, the value of the remaining code is ignored, but it must exist. Optional; If code 450 is in the file, the following codes must also be in the file: 451, 452, 453, 460, 461, 462, and 470. If code 450 is not in the file, the following codes must also not be in the file: 451, 452, 453, 460, 461, 462, and 470
0 = solid hatch
1 = gradient
** 451
Keep zero for future use
four hundred and fifty-two
Record the method to define the color, only for dialog code: 
0 = two color gradient
1 = monochrome gradient
** 453
Number of colors: 
0 = solid hatch
2 = gradient
** 460
Rotation angle of gradient color in radians (default = 0, 0)
** 461
Gradient color definition; Corresponds to the center option in the gradient tab of the boundary hatch dialog box. Each gradient has two definitions: moving and non moving. The move value describes the transition between the two definitions that should be used. A value of 0.0 indicates that only the non mobile version should be used, and a value of 1.0 indicates that only the mobile version should be used. 
** 462
The tone value used by the dialog code (default = 0, 0; range from 0.0 to 1.0). The hue value is a gradient color used to control the hue in the dialog box when the hatch group code 452 is set to 1. 
** 463
Reserved for future use: 
0 = first value
1 = second value
** 470
String (default = linear)
#Pattern data
** 53
Pattern line angle
** 43
Pattern line base point, x component
** 44
Pattern line base point, Y component
** 45
Pattern line offset, x component
** 46
Pattern line offset, Y component
** 79
Number of dashed line length items
** 49
Dashed line length (multiple entries)
* HELIX
Spline data
** 100
Subclass marker (acdbhelix)
** 90
Major version number
** 91
Maintenance version number
10, 20, 30
Axis base point
11, 21, 31
starting point
** 12, 22, 32
Axis vector
** 40
radius
** 41
Number of turns
** 42
Circle height
** 290
Left and right hand habits: 
0 = left hand
1 = right hand
** 280
Constraint type: 
0 = constraint ring height
1 = number of restraint turns
2 = constraint height
* IMAGE
** 100
Subclass marker (AcDbRasterImage)
** 90
Class version
** 10
Insertion point (in WCS)
DXF: x value; App: 3D points
** 20, 30
DXF: y and Z values of insertion point (in WCS)
** 11
U vector of a single pixel (point along the visible bottom of the image, starting from the insertion point) (in WCS)
DXF: x value; App: 3D points
** 21, 31
DXF: y and Z values of u vector (in WCS)
** 12
V vector of a single pixel (the point on the left visible along the image, starting from the insertion point) (in WCS)
DXF: x value; App: 3D points
** 22, 32
DXF: y and Z values of V vector (in WCS)
** 13
Image size (pixels)
DXF: U value; App: two dimensional point (U value and V value)
** 23
DXF: V value of image size (pixels)
** 340
Hard reference of imagedef object
** 70
Image display characteristics: 
1 = display image
2 = display image when it is not aligned with the screen
4 = use clipping boundary
8 = transparency on
** 280
Clipping status: 
0 = off
1 = on
** 281
Brightness value (0-100; default = 50)
** 282
Contrast value (0-100; default = 50)
** 283
Fade value (0-100; default = 0)
** 360
imagedef_Hard reference of reactor object
** 71
Clipping boundary type. 1 = rectangle; 2 = polygon
** 91
Vertex number of the rear crop boundary
** 14
Crop boundary vertex (in OCS)
DXF: x value; App: two dimensional point (multiple entries)
Note 1) for the rectangular clipping boundary type, you must specify two diagonal points. The default values are (- 0.5, - 0.5), (size. X-0.5, size. Y-0.5). 2) For polygon clipping boundary types, you must specify three or more vertices. Polygon vertices must be listed in order
** 24
DXF: y value of clipping boundary vertex (in OCS) (multiple entries)
** 290
Clipping mode: 
0 = external mode
1 = internal mode
* INSERT
** 100
Subclass tag (acdbblockreference)
** 66
Variable attribute follow flag (optional; default = 0); If the value of the attribute follow flag is 1, a series of attribute entities will follow and insert, and end with a seqend entity
** 2
Block name
** 10
Insertion point (in OCS)
DXF: x value; App: 3D points
** 20, 30
DXF: y and Z values of insertion point (in OCS)
** 41
X scale (optional; default = 1)
** 42
Y scale (optional; default = 1)
** 43
Z scale (optional; default = 1)
** 50
Rotation angle (optional; default = 0)
** 70
Column count (optional; default = 1)
** 71
Row count (optional; default = 1)
** 44
Column spacing (optional; default = 0)
** 45
Line spacing (optional; default = 0)
** 210
Stretch direction (optional; default = 0, 0, 1)
DXF: x value; App: 3D vector
** 220, 230
DXF: y and Z values of extrusion direction (optional)
* LEADER
** 100
Subclass marker (acdbleader)
** 3
Dimension style name
** 71
Arrow mark: 0 = disabled; 1 = enabled
** 72
Leader path type: 0 = straight line segment; 1 = spline
** 73
Leader creation flag (default = 3): 
0 = created using text notes
1 = created using tolerance notes
2 = create with block reference annotation
3 = created without any annotation
** 74
Baseline direction sign: 
0 = the baseline (or the tangent end of the spline leader) is opposite to the direction of the horizontal vector
1 = the baseline (or tangent end of spline leader) is in the same direction as the horizontal vector (see code 75)
** 75
Baseline mark: 
0 = no baseline
1 = baseline
** 40
Text note height
** 41
文字注释宽度
                                
** 76
                                
引线顶点数（如果为 OPEN，则忽略）
                                
** 10
                                
顶点坐标（每个顶点一个条目）
                                
DXF：X 值；
                                APP：三维点
                                
** 20, 30
                                
DXF：顶点坐标的 Y 值和 Z 值
                                
** 77
                                
引线的 DIMCLRD = BYBLOCK时使用的颜色
                                
** 340
                                
相关注释的硬参照（多行文字、公差或插入图元）
                                
** 210
                                
法向矢量
                                
DXF：X 值；
                                APP：三维矢量
                                
** 220, 230
                                
DXF：法向矢量的 Y 值和 Z 值
                                
** 211
                                
引线的“水平”方向
                                
DXF：X 值；
                                APP：三维矢量
                                
** 221, 231
                                
DXF：引线的“水平”方向的 Y 值和 Z 值
                                
** 212
                                
上一个引线顶点距块参照插入点的偏移
                                
DXF：X 值；
                                APP：三维矢量
                                
** 222, 232
                                
DXF：偏移的 Y 值和 Z 值
                                
** 213
                                
上一个引线定点距注释位置点的偏移
                                
DXF：X 值；
                                APP：三维矢量
                                
** 223, 233
                                
DXF：偏移的 Y 值和 Z 值
                                
* LIGHT
                                
** 100
                                
子类标记 (AcDbLight)
                                
** 90
                                
版本号
                                
** 1
                                
光源名称
                                
** 70
                                
光源类型：
                                
1 = 平行光
                                
2 = 点光源
                                
3 = 聚光灯
                                
** 290
                                
状态
                                
** 291
                                
打印轮廓
                                
** 40
                                
强度
                                
** 10
                                
光源位置
                                
DXF：X 值；
                                APP：三维点
                                
** 20, 30
                                
DXF：光源位置的 X、 Y 和 Z 值
                                
** 11
                                
目标位置
                                
DXF：X 值；
                                APP：三维点
                                
** 21, 31
                                
DXF：目标位置的 X、 Y 和 Z 值
                                
** 72
                                
衰减类型：
                                
0 = 无
                                
1 = 线性反比
                                
2 = 平方反比
                                
** 292
                                
使用衰减界限
                                
** 41
                                
衰减起点界限
                                
** 42
                                
衰减端点界限
                                
** 50
                                
聚光角角度
                                
** 51
                                
照射角角度
                                
** 293
                                
投射阴影
                                
** 73
                                
阴影类型
                                
0 = 光线跟踪阴影
                                
1 = 阴影贴图
                                
** 91
                                
阴影贴图尺寸
                                
** 280
                                
阴影贴图柔和度
                                
* LINE
                                
** 100
                                
子类标记 (AcDbLine)
                                
** 39
                                
厚度（可选；默认值 = 0）
                                
** 10
                                
起点（在 WCS 中）
                                
DXF：X 值；
                                APP：三维点
                                
** 20, 30
                                
DXF：起点的 Y 值和 Z 值（在 WCS 中）
                                
** 11
                                
端点（在 WCS 中）
                                
DXF：X 值；
                                APP：三维点
                                
** 21, 31
                                
DXF：端点的 Y 值和 Z 值（在 WCS 中）
                                
** 210
                                
拉伸方向（可选；默认值 = 0, 0, 1）
                                
DXF：X 值；
                                APP：三维矢量
                                
** 220, 230
                                
DXF：拉伸方向的 Y 值和 Z 值（可选）
                                
* LWPOLYLINE
                                
** 100
                                
子类标记 (AcDbPolyline)
                                
** 90
                                
顶点数
                                
** 70
                                
多段线标志（按位编码）；
                                默认值为 0：
                                
1 = 关闭；
                                128 = Plinegen
                                
** 43
                                
固定宽度（可选；默认值 = 0）。
                                如果设定为可变宽度（代码 40 和/或 41），则不使用
                                
** 38
                                
标高（可选；默认值 = 0）
                                
** 39
                                
厚度（可选；默认值 = 0）
                                
** 10
                                
顶点坐标（在 OCS 中），多个条目；
                                每个顶点一个条目
                                
DXF：X 值；
                                APP：二维点
                                
** 20
                                
DXF：顶点坐标的 Y 值（在 OCS 中），多个条目；
                                每个顶点一个条目
                                
** 91
                                
顶点标识符
                                
** 40
                                
起点宽度（多个条目；每个顶点一个条目）（可选；默认值 = 0；多个条目）。
                                如果设定为固定宽度（代码 43），则不使用
                                
** 41
                                
端点宽度（多个条目；每个顶点一个条目）（可选；默认值 = 0；多个条目）。
                                如果设定为固定宽度（代码 43），则不使用
                                
** 42
                                
凸度（多个条目；每个顶点一个条目）（可选；默认值 = 0）
                                
** 210
                                
拉伸方向（可选；默认值 = 0, 0, 1）
                                
DXF：X 值；
                                APP：三维矢量
                                
** 220, 230
                                
DXF：拉伸方向的 Y 值和 Z 值（可选）
                                
* mesh
                                
** 100
                                
子类标记 (AcDbSubDMesh)
                                
** 71
                                	
                                
版本号
                                
** 72
                                
“光顺锐化”特性
                                
0 = 关闭
                                
1 = 打开
                                
** 91
                                
细分级别数目
                                
** 92
                                
0 级顶点数
                                
** 10
                                
顶点位置
                                
** 93
                                
0 级面列表的大小
                                
** 90
                                
面列表项目
                                
** 94
                                
0 级边数
                                
** 90
                                
每条边的顶点索引
                                
** 95
                                
0 级边锐化数
                                
** 140
                                
边创建值
                                
** 90
                                
特性已被替代的子图元数
                                
** 91
                                
子图元标记
                                
** 92
                                
已替代特性数
                                
** 90
                                
特性类型
                                
0 = 颜色
                                
1 = 材质
                                
2 = 透明度
                                
3 = 材质贴图器
                                
* MLEADER
                                
** 340
                                	
                                引线样式 ID
                                
** 90
                                	
                                特性替代标志
                                
** 170
                                	
                                引线类型
                                
** 91
                                	
                                引线颜色
                                
** 341
                                	
                                引线类型 ID
                                
** 171
                                	
                                引线线宽
                                
** 290
                                	
                                启用基线
                                
** 291
                                	
                                启用基线
                                
** 41
                                	
                                基线长度
                                
** 342
                                	
                                箭头 ID
                                
** 42
                                	
                                箭头大小
                                
** 172
                                	
                                内容类型
                                
** 343
                                	
                                文字样式 ID
                                
** 173
                                	
                                文字左附着样式
                                
** 95
                                	
                                文字右附着类型
                                
** 174
                                	
                                文字角度类型
                                
** 175
                                	
                                文字对齐类型
                                
** 92
                                	
                                文字颜色
                                
** 292
                                	
                                启用文字边框
                                
** 344
                                	
                                块内容 ID
                                
** 93
                                	
                                块内容颜色
                                
** 10
                                	
                                块内容比例
                                
** 43
                                	
                                块内容旋转
                                
** 176
                                	
                                块内容连接类型
                                
** 293
                                	
                                启用注释比例
                                
** 94
                                	
                                箭头索引
                                
** 345
                                	
                                箭头 ID
                                
** 330
                                	
                                块属性 ID
                                
** 177
                                	
                                块属性索引
                                
** 44
                                	
                                块属性宽度
                                
** 302
                                	
                                块属性文字字符串
                                
** 294
                                	
                                文字负方向
                                
** 178
                                	
                                IPE 中的文字对齐
                                
** 179
                                	
                                文字附着点
                                
** 271
                                
多行文字内容的文字附着方向：
                                
0 = 水平
                                
1 = 垂直
                                
** 272
                                
底部文字附着方向：
                                
9 = 居中
                                
10 = 下划线并居中
                                
** 273
                                
顶部文字附着方向：
                                
9 = 居中
                                
10 = 上划线并居中
                                
* MLEADERSTYLE
                                
** 170
                                
内容类型
                                
** 171
                                	
                                绘制多重引线次序类型
                                
** 172
                                	
                                绘制引线次序类型
                                
** 90
                                	
                                最大引线线段点
                                
** 40
                                	
                                第一线段角度约束
                                
** 41
                                	
                                第二线段角度约束
                                
** 173
                                	
                                引线类型
                                
** 91
                                	
                                引线颜色
                                
** 340
                                	
                                引线类型 ID
                                
** 92
                                	
                                引线线宽
                                
** 290
                                	
                                启用基线
                                
** 42
                                	
                                基线间隙
                                
** 291
                                	
                                启用基线
                                
** 43
                                	
                                基线长度
                                
** 3
                                	
                                多重引线样式说明
                                
** 341
                                	
                                箭头 ID
                                
** 44
                                	
                                箭头大小
                                
** 300
                                	
                                默认多行文字内容
                                
** 342
                                
多行文字样式 ID
                                
** 174
                                
文字左附着样式
                                
** 175
                                
文字角度类型
                                
** 176
                                	
                                文字对齐类型
                                
** 178
                                	
                                文字连接位置类型 - 右
                                
** 93
                                	
                                文字颜色
                                
** 45
                                	
                                文字高度
                                
** 292
                                	
                                启用文字边框
                                
** 297
                                	
                                文字始终左对齐
                                
** 46
                                	
                                对齐空间
                                
** 343
                                	
                                块内容 ID
                                
** 94
                                	
                                块内容颜色
                                
** 47
                                	
                                X 轴上的块内容比例
                                
** 49
                                	
                                Y 轴上的块内容比例
                                
** 140
                                	
                                Z 轴上的块内容比例
                                
** 293
                                	
                                启用块内容比例
                                
** 141
                                	
                                块内容旋转
                                
** 294
                                	
                                启用块内容旋转
                                
** 177
                                	
                                块内容连接类型
                                
** 142
                                	
                                比例
                                
** 295
                                	
                                覆盖特性值
                                
** 296
                                	
                                注释性
                                
** 143
                                	
                                打断间距大小
                                
** 271
                                
多行文字内容的文字附着方向：
                                
0 = 水平
                                
1 = 垂直
                                
** 272
                                
底部文字附着方向：
                                
9 = 居中
                                
10 = 下划线并居中
                                
** 273
                                
顶部文字附着方向：
                                
9 = 居中
                                
10 = 上划线并居中
                                
* mline
                                
** 100
                                
子类标记 (AcDbMline)
                                
** 2
                                
最大长度为 32 个字符的字符串。
                                该多线使用的样式名。
                                MLINESTYLE 词典中必须存在此样式的条目。
                                
如果不同时更新 MLINESTYLE 词典中的相关条目，则不要修改该字段。
                                
** 340
                                
MLINESTYLE 对象的指针句柄/ID
                                
** 40
                                
比例因子
                                
** 70
                                
对正：
                                
0 = 顶端对正
                                
1 = 无对正
                                
2 = 底端对正
                                
** 71
                                
标志（按位编码值）：
                                
1 = 至少有一个顶点（代码 72 大于 0）
                                
2 = 关闭
                                
4 = 禁止起点封口
                                
8 = 禁止端点封口
                                
** 72
                                
顶点数
                                
** 73
                                
MLINESTYLE 定义中的元素数
                                
** 10
                                
起点（在 WCS 中）
                                
DXF：X 值；
                                APP：三维点
                                
** 20, 30
                                
DXF：起点的 Y 值和 Z 值（在 WCS 中）
                                
** 210
                                
拉伸方向（可选；默认值 = 0, 0, 1）
                                
DXF：X 值；
                                APP：三维矢量
                                
** 220, 230
                                
DXF：拉伸方向的 Y 值和 Z 值（可选）
                                
** 11
                                
顶点坐标（多个条目；每个顶点一个条目）DXF：X 值；
                                APP：三维点
                                
** 21, 31
                                
DXF：顶点坐标的 Y 值和 Z 值
                                
** 12
                                
从该顶点开始的线段的方向矢量（多个条目；每个顶点一个条目）
                                
DXF：X 值；
                                APP：三维矢量
                                
** 22, 32
                                
DXF：从此顶点开始的线段的方向矢量的 Y 值和 Z 值
                                
** 13
                                
此顶点处的斜接方向矢量（多个条目；每个顶点一个条目）
                                
DXF：X 值；
                                APP：三维矢量
                                
** 23, 33
                                
DXF：斜接方向矢量的 Y 值和 Z 值
                                
** 74
                                
该元素的参数数目（对线段中的每个元素重复）
                                
** 41
                                
元素参数（根据上一个代码 74 重复）
                                
** 75
                                
该元素的区域填充参数的数目（对线段中的每个元素重复）
                                
** 42
                                
区域填充参数（根据前一个代码 75 重复）
                                
* MTEXT
                                
** 100
                                
子类标记 (AcDbMText)
                                
** 10
                                
插入点
                                
DXF：X 值；
                                APP：三维点
                                
** 20, 30
                                
DXF：插入点的 Y 值和 Z 值
                                
** 40
                                
标称（初始）文字高度
                                
** 41
                                
参照矩形宽度
                                
** 71
                                
附着点：
                                
1 = 左上
                                
2 = 中上
                                
3 = 右上
                                
4 = 左中
                                
5 = 正中
                                
6 = 右中
                                
7 = 左下
                                
8 = 中下
                                
9 = 右下
                                
** 72
                                
图形方向：
                                
1 = 从左到右
                                
3 = 从上到下
                                
5 = 随样式（从相关文字样式继承走向）
                                
** 1
                                
字符串。
                                如果字符串长度小于 250 个字符，所有字符均出现在组 1 中。
                                如果字符串长度大于 250 个字符，该字符串将分成长度为 250 个字符的数据块，并显示在一个或多个组 3 代码中。
                                如果使用组 3 代码，最后一个组将是组 1 并且字符数少于 250 个
                                
** 3
                                
附加文字（始终在长度为 250 个字符的数据块中）（可选）
                                
** 7
                                
文字样式名（如果未提供，则为“标准”）（可选）
                                
** 210
                                
拉伸方向（可选；默认值 = 0, 0, 1）
                                
DXF：X 值；
                                APP：三维矢量
                                
** 220, 230
                                
DXF：拉伸方向的 Y 值和 Z 值（可选）
                                
** 11
                                
X 轴方向矢量（在 WCS 中）
                                
DXF：X 值；
                                APP：三维矢量
                                
将作为 DXF 输入传递的组码 50（以弧度为单位的旋转角）转换为相等的方向矢量（如果同时传递代码 50 和代码 11、21、31，则对最后一个代码进行转换）。
                                这是从文字对象转换的一种简便方法。
                                
** 21, 31
                                
DXF：X 轴方向矢量的 Y 值和 Z 值（在 WCS 中）
                                
** 42
                                
构成多行文字图元的字符的水平宽度。
                                该值始终等于或小于组码 41 的值（只读，如果提供则忽略）
                                
** 43
                                
多行文字图元的垂直高度（只读，如果提供则忽略）
                                
** 50
                                
以弧度为单位的旋转角度
                                
** 73
                                
多行文字的行距样式（可选）：
                                
1= 至少（将替代为较高的字符）
                                
2 = 精确（将不替代为较高的字符）
                                
** 44
                                
多行文字的行距比例（可选）：
                                
要应用的行距的默认百分比（五分之三）。
                                有效值的范围从 0.25 到 4.00
                                
** 90
                                
背景填充设置：
                                
0 = 背景填充关闭
                                
1 = 使用背景填充颜色
                                
2 = 使用图形窗口颜色作为背景填充颜色
                                
** 420 - 429
                                
背景色（RGB 颜色）
                                
** 430 - 439
                                
背景色（颜色名）
                                
** 45
                                
填充框大小（可选）：
                                
确定文字周围的边框大小。
                                
** 63
                                
背景填充颜色（可选）：
                                
组码 90 为 1 时要用于背景填充的颜色。
                                
** 441
                                
背景填充颜色的透明度（未实现）
                                
** 75
                                
列类型
                                
** 76
                                	
                                列计数
                                
** 78
                                	
                                反转列走向
                                
** 79
                                	
                                列自动高度
                                
** 48
                                	
                                列宽
                                
** 49
                                	
                                列栏间距
                                
** 50
                                	
                                列高度；
                                此代码后跟列计数 (Int16)，然后是列高度数
                                
* oleframe
                                
** 100
                                
子类标记 (AcDbOleFrame)
                                
** 70
                                
OLE 版本号
                                
** 90
                                
二进制数据的长度
                                
** 310
                                
二进制数据（多行）
                                
** 1
                                
OLE 数据的结束（字符串“OLE”）
                                
* ole2frame
                                
** 100
                                
子类标记 (AcDbOle2Frame)
                                
** 70
                                
OLE 版本号
                                
** 3
                                
二进制数据的长度
                                
** 10
                                
左上角 (WCS)
                                
DXF：X 值；
                                APP：三维点
                                
** 20, 30
                                
DXF：左上角的 Y 值和 Z 值（在 WCS 中）
                                
** 11
                                
右下角 (WCS)
                                
DXF：X 值；
                                APP：三维点
                                
** 21, 31
                                
DXF：右下角的 Y 值和 Z 值（在 WCS 中）
                                
** 71
                                
OLE 对象类型，1 = 链接；
                                2 = 嵌入；
                                3 = 静态
                                
** 72
                                
平铺模式描述符：
                                
0 = 对象驻留在模型空间中
                                
1 = 对象驻留在图纸空间中
                                
** 90
                                
二进制数据的长度
                                
** 310
                                
二进制数据（多行）
                                
** 1
                                
OLE 数据的结束（字符串“OLE”）
                                
* point
                                
** 100
                                
子类标记 (AcDbPoint)
                                
** 10
                                
点位置（在 WCS 中）
                                
DXF：X 值；
                                APP：三维点
                                
** 20, 30
                                
DXF：点位置的 Y 值和 Z 值（在 WCS 中）
                                
** 39
                                
厚度（可选；默认值 = 0）
                                
** 210
                                
拉伸方向（可选；默认值 = 0, 0, 1）
                                
DXF：X 值；
                                APP：三维矢量
                                
** 220, 230
                                
DXF：拉伸方向的 Y 值和 Z 值（可选）
                                
** 50
                                
绘制点时所使用的 UCS 的 X 轴的角度（可选；默认值 = 0）；
                                当 PDMODE 非零时使用
                                
* polyline
                                
** 100
                                
子类标记（AcDb2dPolyline 或 AcDb3dPolyline）
                                
** 66
                                
已废弃；
                                以前是“后跟图元标志”（可选；如果存在则忽略）
                                
** 10
                                
DXF：始终为 0
                                
APP：“虚拟”点；
                                X 值和 Y 值始终为 0，Z 值是多段线的标高（二维时在 OCS 中，三维时在 WCS 中）
                                
** 20
                                
DXF：始终为 0
                                
** 30
                                
DXF：多段线的标高（二维时在 OCS 中，三维时在 WCS 中）
                                
** 39
                                
厚度（可选；默认值 = 0）
                                
** 70
                                
多段线标志（按位编码；默认值 = 0）：
                                
1 = 这是一个闭合多段线（或按 M 方向闭合的多边形网格）
                                
2 = 已添加曲线拟合顶点
                                
4 = 已添加样条曲线拟合顶点
                                
8 = 这是一条三维多段线
                                
16 = 这是一个三维多边形网格
                                
32 = 多边形网格以 N 方向闭合
                                
64 = 多段线是一个多面网格
                                
128 = 线型图案在该多段线顶点的周围连续生成
                                
** 40
                                
默认起点宽度（可选；默认值 = 0）
                                
** 41
                                
默认端点宽度（可选；默认值 = 0）
                                
** 71
                                
多边形网格 M 顶点计数（可选；默认值 = 0）
                                
** 72
                                
多边形网格 N 顶点计数（可选；默认值 = 0）
                                
** 73
                                
平滑曲面 M 密度（可选；默认值 = 0）
                                
** 74
                                
平滑曲面 N 密度（可选；默认值 = 0）
                                
** 75
                                
曲线和平滑曲面类型（可选；默认值 = 0）；
                                整数代码，非按位编码：
                                
0 = 不拟合平滑曲面
                                
5 = 二次 B 样条曲面
                                
6 = 三次 B 样条曲面
                                
8 = Bezier 曲面
                                
** 210
                                
拉伸方向（可选；默认值 = 0, 0, 1）
                                
DXF：X 值；
                                APP：三维矢量
                                
** 220, 230
                                
DXF：拉伸方向的 Y 值和 Z 值（可选）
                                
* ray
                                
** 100
                                
子类标记 (AcDbRay)
                                
** 10
                                
起点（在 WCS 中）
                                
DXF：X 值；
                                APP：三维点
                                
** 20, 30
                                
DXF：起点的 Y 值和 Z 值（在 WCS 中）
                                
** 11
                                
单位方向矢量（在 WCS 中）
                                
DXF：X 值；
                                APP：三维矢量
                                
** 21, 31
                                
DXF：单位方向矢量的 Y 值和 Z 值（在 WCS 中）
                                
* region
                                
** 100
                                
子类标记 (AcDbModelerGeometry)
                                
** 70
                                
建模格式版本号（当前值 = 1）
                                
** 1
                                
所有权数据（多行，每行 < 255 个字符）
                                
** 3
                                
所有权数据的附加行（如果前一个组 1 的字符串长度大于 255 个字符）（可选）
                                
* section
                                
** 100
                                
子类标记 (AcDbSection)
                                
** 90
                                
截面状态
                                
** 91
                                
截面标志
                                
** 1
                                
名称
                                
** 10, 20, 30
                                
垂直方向
                                
** 40
                                
顶部高度
                                
** 41
                                
底部高度
                                
** 70
                                
指示器透明度
                                
** 63, 411
                                
指示器颜色
                                
** 92
                                
顶点数
                                
** 11, 21, 31
                                
顶点（根据顶点数重复）
                                
** 93
                                
背面线顶点数
                                
** 12, 22, 32
                                
背面线顶点（根据背面线顶点数重复）
                                
** 360
                                
几何图形设置对象的硬指针 ID/句柄
                                
* seqend
                                
**  -2
                                
APP：开始序列的图元的名称。
                                该图元标记多段线顶点的结束（顶点类型名），或具有属性（由插入图元中出现的非零 66 组表示）的插入图元的属性图元的结束（属性类型名）。
                                该代码不保存在 DXF 文件中。
                                
* shape
                                
** 100
                                
子类标记 (AcDbShape)
                                
** 39
                                
厚度（可选；默认值 = 0）
                                
** 10
                                
插入点（在 WCS 中）
                                
DXF：X 值；
                                APP：三维点
                                
** 20, 30
                                
DXF：插入点的 Y 值和 Z 值（在 WCS 中）
                                
** 40
                                
大小
                                
** 2
                                
形名称
                                
** 50
                                
旋转角度（可选；默认值 = 0）
                                
** 41
                                
X 相对缩放比例（可选；默认值 = 1）
                                
** 51
                                
倾斜角（可选；默认值 = 0）
                                
** 210
                                
拉伸方向（可选；默认值 = 0, 0, 1）
                                
DXF：X 值；
                                APP：三维矢量
                                
** 220, 230
                                
DXF：拉伸方向的 Y 值和 Z 值（可选）
                                
* solid
                                
** 100
                                
子类标记 (AcDbTrace)
                                
** 10
                                
第一角点
                                
DXF：X 值；
                                APP：三维点
                                
** 20, 30
                                
DXF：第一角点的 Y 值和 Z 值
                                
** 11
                                
第二角点
                                
DXF：X 值；
                                APP：三维点
                                
** 21, 31
                                
DXF：第二角点的 Y 值和 Z 值
                                
** 12
                                
第三角点
                                
DXF：X 值；
                                APP：三维点
                                
** 22, 32
                                
DXF：第三角点的 Y 值和 Z 值
                                
** 13
                                
第四角点。
                                如果只输入三个角点来定义 SOLID，则第四个角点坐标与第三个角点坐标相同。
                                
DXF：X 值；
                                APP：三维点
                                
** 23, 33
                                
DXF：第四角点的 Y 值和 Z 值
                                
** 39
                                
厚度（可选；默认值 = 0）
                                
** 210
                                
拉伸方向（可选；默认值 = 0, 0, 1）
                                
DXF：X 值；
                                APP：三维矢量
                                
** 220, 230
                                
DXF：拉伸方向的 Y 值和 Z 值（可选）
                                
* spline
                                
** 100
                                
子类标记 (AcDbSpline)
                                
** 210
                                
法向矢量（如果样条曲线为非平面型，则省略）
                                
DXF：X 值；
                                APP：三维矢量
                                
** 220, 230
                                
DXF：法向矢量的 Y 值和 Z 值（可选）
                                
** 70
                                
样条曲线标志（按位编码）：
                                
1 = 闭合样条曲线
                                
2 = 周期性样条曲线
                                
4 = 有理样条曲线
                                
8 = 平面
                                
16 = 线性（同时还设置平面位）
                                
71
                                
样条曲线的阶数
                                
** 72
                                
节点数
                                
** 73
                                
控制点数
                                
** 74
                                
拟合点数（如果有）
                                
** 42
                                
节点公差（默认值 = 0.0000001）
                                
** 43
                                
控制点公差（默认值 = 0.0000001）
                                
** 44
                                
拟合公差（默认值 = 0.0000000001）
                                
** 12
                                
起点切向 — 可以省略（在 WCS 中）
                                
DXF：X 值；
                                APP：三维点
                                
** 22, 32
                                
DXF：起点切向的 Y 值和 Z 值 — 可以省略（在 WCS 中）
                                
** 13
                                
端点切向 — 可以省略（在 WCS 中）
                                
DXF：X 值；
                                APP：三维点
                                
** 23, 33
                                
DXF：端点切向的 Y 值和 Z 值 — 可以省略（在 WCS 中）
                                
** 40
                                
节点值（每个节点一个条目）
                                
** 41
                                
权值（如果不为 1）；
                                对于多组对，如果均不为 1，则出现。
                                
** 10
                                
控制点（在 WCS 中）；
                                每个控制点一个条目
                                
DXF：X 值；
                                APP：三维点
                                
** 20, 30
                                
DXF：控制点的 Y 值和 Z 值（在 WCS 中）；
                                每个控制点一个条目
                                
** 11
                                
拟合点（在 WCS 中）；
                                每个拟合点一个条目
                                
DXF：X 值；
                                APP：三维点
                                
** 21, 31
                                
DXF：拟合点的 Y 值和 Z 值（在 WCS 中）；
                                每个拟合点一个条目
                                
* sun
                                
** 100
                                
子类标记 (AcDbSun)
                                
** 90
                                
版本号
                                
** 290
                                
状态
                                
** 63
                                
颜色
                                
** 40
                                
强度
                                
** 291
                                
阴影
                                
** 91
                                
公历日期
                                
** 92
                                
时间（以午夜过后的秒数表示）
                                
** 292
                                
夏令时时间
                                
** 70
                                
阴影类型
                                
0 = 光线跟踪阴影
                                
1 = 阴影贴图
                                
** 71
                                
阴影贴图尺寸
                                
** 280
                                
阴影柔和度
                                
* surface
                                
** 100
                                
子类标记 (AcDbModelerGeometry)
                                
** 70
                                
建模格式版本号（当前值 = 1）
                                
** 1
                                
所有权数据（多行，每行 < 255 个字符）
                                
** 3
                                
所有权数据的附加行（如果前一个组 1 的字符串长度大于 255 个字符）（可选）
                                
** 100
                                
子类标记 (AcDbSurface)
                                
** 71
                                
U 素线数
                                
** 72
                                
V 素线数
                                
* table
                                
** 0
                                
图元名 (ACAD_TABLE)
                                
** 5
                                
图元句柄
                                
** 330
                                
所有者词典的软指针 ID
                                
** 100
                                
子类标记。
                                (AcDbEntity)
                                
** 92
                                
代理图元图形中的字节数
                                
** 310
                                
代理图元图形的数据（多行；每行最多 256 个字符）
                                
** 100
                                
子类标记。
                                (AcDbBlockReference)
                                
** 2
                                
块名；
                                无名块以 *T 值开始
                                
** 10,20,30
                                
插入点
                                
** 100
                                
子类标记。
                                (AcDbTable)
                                
** 280
                                
表格数据版本号：
                                
** 0 = 2010
                                
** 342
                                
TABLESTYLE 对象的硬指针 ID
                                
** 343
                                
属主 BLOCK 记录的硬指针 ID
                                
** 11,21,31
                                
水平方向矢量
                                
** 90
                                
标志的标志（无符号整数）
                                
** 91
                                
行数
                                
** 92
                                
列数
                                
** 93
                                
替代的标志
                                
** 94
                                
边框颜色的替代的标志
                                
** 95
                                
边框线宽的替代的标志
                                
** 96
                                
边框可见性的替代的标志
                                
** 141
                                
行高；
                                此值不断重复，每行值为 1
                                
** 142
                                
列高；
                                此值不断重复，每列值为 1
                                
** 171
                                
单元类型；
                                此值不断重复，每单元值为 1：
                                
1 = 文字类型
                                
2 = 块类型
                                
** 172
                                
单元标志值；
                                此值不断重复，每单元值为 1
                                
** 173
                                
单元合并值；
                                此值不断重复，每单元值为 1
                                
** 174
                                
布尔标志指示是否为单元设定自动调整选项；
                                此值不断重复，每单元值为 1
                                
** 175
                                
单元边框宽度（仅适用于合并单元）；
                                此值不断重复，每单元值为 1
                                
** 176
                                
单元边框高度（适用于合并单元）；
                                此值不断重复，每单元值为 1
                                
** 91
                                
单元替代标志；
                                此值不断重复，每单元值为 1（自 AutoCAD 2007 开始）
                                
** 178
                                
虚拟边的标志值
                                
** 145
                                
旋转角度值（实数；适用于块类型单元和文字类型单元）
                                
** 344
                                
FIELD 对象的硬指针 ID此 ID 仅适用于文字类型单元。
                                如果单元中的文字包含一个或多个字段，则仅保存 FIELD 对象的 ID。
                                忽略文字字符串（组码 1 和 3）
                                
** 1
                                
单元中的文字字符串。
                                如果字符串长度小于 250 个字符，所有字符均显示在代码 1 中。
                                如果字符串长度大于 250 个字符，该字符串将分成长度为 250 个字符的数据块。
                                这些数据块将包含在一个或多个代码 2 代码中。
                                如果使用代码 2 代码，最后一个组将为代码 1 并且长度小于 250 个字符。
                                此值仅适用于文字类型单元并不断重复，每单元值为 1
                                
** 2
                                	
                                
单元中的文字字符串，在长度为 250 个字符的数据块中；
                                可选。
                                此值仅适用于文字类型单元并不断重复，每单元值为 1
                                
** 340
                                
块表记录的硬指针 ID。
                                此值仅适用于块类型单元并不断重复，每单元值为 1
                                
** 144
                                
块的缩放比例（实数）。
                                此值仅适用于块类型单元并不断重复，每单元值为 1
                                
** 179
                                
块表记录中的属性定义数（仅适用于块类型单元）
                                
** 331
                                
块表记录中属性定义的软指针 ID，由组码 179 参照（仅适用于块类型单元）。
                                每出现一个属性定义此值便重复一次
                                
** 300
                                
属性定义的文字字符串值，每出现一个属性定义便重复一次并仅适用于块类型单元
                                
** 7
                                
文字样式名（字符串）；
                                应用于单元级别的替代
                                
** 140
                                
文字高度值；
                                应用于单元级别的替代
                                
** 170
                                
单元对齐值；
                                应用于单元级别的替代
                                
** 64
                                
单元内容的颜色值；
                                应用于单元级别的替代
                                
** 63
                                
单元内容的背景（填充）色的值；
                                应用于单元级别的替代
                                
** 69
                                
单元上边框的真彩色值；
                                应用于单元级别的替代
                                
** 65
                                
单元右边框的真彩色值；
                                应用于单元级别的替代
                                
** 66
                                
单元下边框的真彩色值；
                                应用于单元级别的替代
                                
** 68
                                
单元左边框的真彩色值；
                                应用于单元级别的替代
                                
** 279
                                
单元上边框的线宽；
                                应用于单元级别的替代
                                
** 275
                                
单元右边框的线宽；
                                应用于单元级别的替代
                                
** 276
                                
单元下边框的线宽；
                                应用于单元级别的替代
                                
** 278
                                
单元左边框的线宽；
                                应用于单元级别的替代
                                
** 283
                                
是否打开填充颜色的布尔标志；
                                应用于单元级别的替代
                                
** 289
                                
单元上边框可见性的布尔标志；
                                应用于单元级别的替代
                                
** 285
                                
单元右边框可见性的布尔标志；
                                应用于单元级别的替代
                                
** 286
                                
单元下边框可见性的布尔标志；
                                应用于单元级别的替代
                                
** 288
                                
单元左边框可见性的布尔标志；
                                应用于单元级别的替代
                                
** 70
                                
流向；
                                应用于表图元级别的替代
                                
** 40
                                
水平单元边距；
                                应用于表图元级别的替代
                                
** 41
                                
垂直单元边距；
                                应用于表图元级别的替代
                                
** 280
                                
是否抑制标题的标志；
                                应用于表图元级别的替代
                                
** 281
                                
是否抑制标题行的标志；
                                应用于表图元级别的替代
                                
** 7
                                
文字样式名（字符串）；
                                应用于表图元级别的替代。
                                每个单元类型可能有一个条目
                                
** 140
                                
文字高度（实数）；
                                应用于表图元级别的替代。
                                每个单元类型可能有一个条目
                                
** 170
                                
单元对齐（整数）；
                                应用于表图元级别的替代。
                                每个单元类型可能有一个条目
                                
** 63
                                
表的垂直左边框或单元背景的颜色值；
                                应用于表图元级别的替代。
                                每个单元类型可能有一个条目
                                
** 64
                                
表的水平上边框或单元内容的颜色值；
                                应用于表图元级别的替代。
                                每个单元类型可能有一个条目
                                
** 65
                                
水平内部边框线的颜色值；
                                应用于表图元级别的替代
                                
** 66
                                
水平下边框线的颜色值；
                                应用于表图元级别的替代
                                
** 68
                                
垂直内部边框线的颜色值；
                                应用于表图元级别的替代
                                
** 69
                                
垂直右边框线的颜色值；
                                应用于表图元级别的替代
                                
** 283
                                
是否启用背景色的标志（默认值 = 0）；
                                应用于表图元级别的替代。
                                每个单元类型可能有一个条目：
                                
0 = 禁用
                                
1 = 启用
                                
** 274-279
                                
每个单元边框类型的线宽（默认值 = kLnWtByBlock）；
                                应用于表图元级别的替代。
                                每个单元类型可能有一个组
                                
** 284-289
                                
每个单元边框类型的可见性标志（默认值 = 1）；
                                应用于表图元级别的替代。
                                每个单元类型可能有一个组：
                                
0 = 不可见
                                
1 = 可见
                                
** 97
                                
标准/标题/表头行数据类型
                                
** 98
                                
标准/标题/表头行单位类型
                                
** 4
                                
标准/标题/表头行格式字符串
                                
** 177
                                
单元替代标志值（AutoCAD 2007 之前）
                                
** 92
                                
延伸单元标志（自 AutoCAD 2007 开始）
                                
** 301
                                	
                                单元值块开始（自 AutoCAD 2007 开始）
                                
** 302
                                	
                                
单元中的文字字符串。
                                如果字符串长度小于 250 个字符，则所有字符均显示在代码 302 中。
                                如果字符串长度大于 250 个字符，该字符串将分成长度为 250 个字符的数据块。
                                这些数据块将包含在一个或多个代码 303 代码中。
                                如果使用代码 393 代码，则最后一个组将为代码 1 并且长度小于 250 个字符。
                                此值仅适用于文字类型单元并不断重复，每单元值为 1（自 AutoCAD 2007 开始）
                                
** 303
                                	
                                
单元中的文字字符串，在长度为 250 个字符的数据块中；
                                可选。
                                此值仅适用于文字类型单元并不断重复，每单元值为 302（自 AutoCAD 2007 开始）
                                
* text
                                
** 100
                                
子类标记 (AcDbText)
                                
** 39
                                
厚度（可选；默认值 = 0）
                                
** 10
                                
第一对齐点（在 OCS 中）
                                
DXF：X 值；
                                APP：三维点
                                
** 20, 30
                                
DXF：第一对齐点的 Y 值和 Z 值（在 OCS 中）
                                
** 40
                                
文字高度
                                
** 1
                                
默认值（字符串本身）
                                
** 50
                                
文字旋转角度（可选；默认值 = 0）
                                
** 41
                                
相对 X 比例因子 — 宽度（可选；默认值 = 1）
                                
使用拟合类型的文字时，该值也将进行调整。
                                
** 51
                                
倾斜角（可选；默认值 = 0）
                                
** 7
                                
文字样式名（可选；默认值 = 标准）
                                
** 71
                                
文字生成标志（可选；默认值 = 0）：
                                
2 = 文字反向（在 X 轴方向镜像）
                                
4 = 文字倒置（在 Y 轴方向镜像）
                                
** 72
                                
文字水平对正类型（可选；默认值 = 0）整数代码（非按位编码）：
                                
0 = 左对正
                                
1 = 居中对正
                                
2 = 右对正
                                
3 = 对齐（如果垂直对齐 = 0）
                                
4 = 中间（如果垂直对齐 = 0）
                                
5 = 拟合（如果垂直对齐 = 0）
                                
详细信息请参见组 72 和 73 整数代码表
                                
** 11
                                
第二对齐点（在 OCS 中）（可选）
                                
DXF：X 值；
                                APP：三维点
                                
只有当 72 或 73 组的值非零时，该值才有意义（如果对正不是基线对正/左对正）
                                
** 21, 31
                                
DXF：第二对齐点的 Y 值和 Z 值（在 OCS 中）（可选）
                                
** 210
                                
拉伸方向（可选；默认值 = 0, 0, 1）
                                
DXF：X 值；
                                APP：三维矢量
                                
** 220, 230
                                
DXF：拉伸方向的 Y 值和 Z 值（可选）
                                
** 100
                                
子类标记 (AcDbText)
                                
** 73
                                
文字垂直对正类型（可选；默认值 = 0）整数代码（不是按位编码）
                                
0 = 基线对正
                                
1 = 底端对正
                                
2 = 居中对正
                                
3 = 顶端对正
                                
详细信息请参见组 72 和 73 整数代码表
                                
* tolerance
                                
** 100
                                
子类标记 (AcDbFcf)
                                
** 3
                                
标注样式名
                                
** 10
                                
插入点（在 WCS 中）
                                
DXF：X 值；
                                APP：三维点
                                
** 20, 30
                                
DXF：插入点的 Y 值和 Z 值（在 WCS 中）
                                
** 1
                                
表示公差的形象化表示的字符串
                                
** 210
                                
拉伸方向（可选；默认值 = 0, 0, 1）
                                
DXF：X 值；
                                APP：三维矢量
                                
** 220, 230
                                
DXF：拉伸方向的 Y 值和 Z 值（可选）
                                
** 11
                                
X 轴方向矢量（在 WCS 中）
                                
DXF：X 值；
                                APP：三维矢量
                                
** 21, 31
                                
DXF：X 轴方向矢量的 Y 值和 Z 值（在 WCS 中）
                                
* trace
                                
** 100
                                
子类标记 (AcDbTrace)
                                
** 10
                                
第一角点（在 OCS 中）
                                
DXF：X 值；
                                APP：三维点
                                
** 20, 30
                                
DXF：第一角点的 Y 值和 Z 值（在 OCS 中）
                                
** 11
                                
第二角点（在 OCS 中）
                                
DXF：X 值；
                                APP：三维点
                                
** 21, 31
                                
DXF：第二角点的 Y 值和 Z 值（在 OCS 中）
                                
** 12
                                
第三角点（在 OCS 中）
                                
DXF：X 值；
                                APP：三维点
                                
** 22, 32
                                
DXF：第三角点的 Y 值和 Z 值（在 OCS 中）
                                
** 13
                                
第四角点（在 OCS 中）
                                
DXF：X 值；
                                APP：三维点
                                
** 23, 33
                                
DXF：第四角点的 Y 值和 Z 值（在 OCS 中）
                                
** 39
                                
厚度（可选；默认值 = 0）
                                
** 210
                                
拉伸方向（可选；默认值 = 0, 0, 1）
                                
DXF：X 值；
                                APP：三维矢量
                                
** 220, 230
                                
DXF：拉伸方向的 Y 值和 Z 值（可选）
                                
* underlay
                                
** 0
                                	
                                
对象名称。
                                
DGNUNDERLAY - 附着的 DGN 文件
                                
DWFUNDERLAY - 附着的 DWF 文件
                                
PDFUNDERLAY - 附着的 PDF 文件
                                
** 100
                                
子类标记 (AcDbUnderlayReference)
                                
** 340
                                
AcDbUnderlayDefinition 对象的 ID
                                
** 10,20,30
                                
参考底图插入点的 X、Y 和 Z 坐标。
                                这些是 OCS/ECS 坐标
                                
** 41,42,43
                                
DXF：X、Y 和 Z 比例因子
                                
** 50
                                
旋转角度（在 OCS/ECS 中。从坐标系 X 轴开始绕 Z 轴逆时针旋转）
                                
** 210,220,230
                                
法向矢量（在 WCS 中）
                                
** 280
                                
标志
                                
1 = 剪裁处于打开状态
                                
2 = 参考底图处于打开状态
                                
4 = 单色
                                
8 = 调整背景
                                
16 = 剪裁为内部模式
                                
** 281
                                
对比度（值介于 20 和 100 之间）
                                
** 282
                                
淡入度（值介于 0 和 80 之间）
                                
** 11, 21
                                
重复：OCS/ECS 中的二维点。
                                如果只有两个二维点，则它们就是剪裁矩形的左下角点和右上角点。
                                如果多于两个二维点，则它们就是剪裁多边形的顶点
                                
* vertex
                                
** 100
                                
子类标记 (AcDbVertex)
                                
** 100
                                
子类标记（AcDb2dVertex 或 AcDb3dPolylineVertex）
                                
** 10
                                
位置点（二维时在 OCS 中，三维时在 WCS 中）
                                
DXF：X 值；
                                APP：三维点
                                
** 20, 30
                                
DXF：位置点的 Y 值和 Z 值（二维时在 OCS 中，三维时在 WCS 中）
                                
** 40
                                
起点宽度（可选；默认值为 0）
                                
** 41
                                
端点宽度（可选；默认值为 0）
                                
** 42
                                
凸度（可选；默认值为 0）。
                                凸度是四分之一圆弧段角的切线，如果从起点到端点，圆弧为顺时针，则为负数。
                                凸度为 0 表示一条直线段，凸度为 1 表示一个半圆
                                
** 70
                                
顶点标志：
                                
1 = 由曲线拟合创建的额外顶点
                                
2 = 为该顶点定义的曲线拟合切线。
                                如果曲线拟合切线方向为 0，则在 DXF 输出时被省略，但是如果设值了该位，则不能省略
                                
4 = 未使用
                                
8 = 由样条曲线拟合创建的样条曲线顶点
                                
16 = 样条曲线框架控制点
                                
32 = 三维多段线顶点
                                
64 = 三维多边形网格
                                
128 = 多面网格顶点
                                
** 50
                                
曲线拟合切线方向
                                
** 71
                                
多面网格顶点索引（可选；非零时出现）
                                
** 72
                                
多面网格顶点索引（可选；非零时出现）
                                
** 73
                                
多面网格顶点索引（可选；非零时出现）
                                
** 74
                                
多面网格顶点索引（可选；非零时出现）
                                
** 91
                                
顶点标识符
                                
* viewport
                                
** 100
                                
子类标记 (AcDbViewport)
                                
** 10
                                
中心点（在 WCS 中）
                                
DXF：X 值；
                                APP：三维点
                                
** 20, 30
                                
DXF：中心点的 Y 值和 Z 值（在 WCS 中）
                                
** 40
                                
宽度，以图纸空间单位为测量单位
                                
** 41
                                
高度，以图纸空间单位为测量单位
                                
** 68
                                
视口状态字段：
                                
-1 = 打开，但是在屏幕上完全不可见，或者因为当前已超出 $MAXACTVP 计数，而成为一个不活动的视口。
                                
0 = 关闭
                                
<正值> = 开并处于活动状态。
                                该值表示视口堆栈的次序，其中 1 是活动视口，下一个是 2，依此类推
                                
** 69
                                
视口 ID
                                
** 12
                                
视口中心点（在 DCS 中）
                                
DXF：X 值；
                                APP：二维点
                                
** 22
                                
DXF：视口中心点的 Y 值（在 DCS 中）
                                
** 13
                                
捕捉基点
                                
DXF：X 值；
                                APP：二维点
                                
** 23
                                
DXF：捕捉基点的 Y 值
                                
** 14
                                
捕捉间距
                                
DXF：X 值；
                                APP：二维点
                                
** 24
                                
DXF：捕捉间距的 Y 值
                                
** 15
                                
栅格间距
                                
DXF：X 值；
                                APP：二维点
                                
** 25
                                
DXF：栅格间距的 Y 值
                                
** 16
                                
观察方向矢量（在 WCS 中）
                                
DXF：X 值；
                                APP：三维矢量
                                
** 26, 36
                                
DXF：观察方向矢量的 Y 值和 Z 值（在 WCS 中）
                                
** 17
                                
观察目标点（在 WCS 中）
                                
DXF：X 值；
                                APP：三维矢量
                                
** 27, 37
                                
DXF：观察目标点的 Y 值和 Z 值（在 WCS 中）
                                
** 42
                                
透视焦距
                                
** 43
                                
前向剪裁平面的 Z 值
                                
** 44
                                
后向剪裁平面的 Z 值
                                
** 45
                                
视图高度（以模型空间单位为测量单位）
                                
** 50
                                
捕捉角度
                                
** 51
                                
视图扭转角度
                                
** 72
                                
圆的缩放百分比
                                
** 331
                                
冻结图层对象 ID/句柄（可能存在多个条目）（可选）
                                
** 90
                                
视口状态按位编码标志：
                                
1 (0x1) = 启用透视模式
                                
2 (0x2) = 启用前向剪裁
                                
4 (0x4) = 启用后向剪裁
                                
8 (0x8) = 启用 UCS 跟随
                                
16 (0x10) = 如果不可见则启用前向剪裁
                                
32 (0x20) = 启用 UCS 图标可见性
                                
64 (0x40) = 启用 UCS 图标（位于原点）
                                
128 (0x80) = 启用快速缩放
                                
256 (0x100) = 启用捕捉模式
                                
512 (0x200) = 启用栅格模式
                                
1024 (0x400) = 启用等轴测捕捉样式
                                
2048 (0x800) = 启用隐藏打印模式
                                
4096 (0x1000) = kIsoPairTop。
                                如果设定了 kIsoPairTop，但未设定 kIsoPairRight，则启用 isopair top。
                                如果同时设定了 kIsoPairTop 和 kIsoPairRight，则启用 isopair left
                                
8192 (0x2000) = kIsoPairRight。
                                如果设定了 kIsoPairRight，但未设定 kIsoPairTop，则启用 isopair right
                                
16384 (0x4000) = 启用视口缩放锁定
                                
32768 (0x8000) = 当前始终启用
                                
65536 (0x10000) = 启用非矩形剪裁
                                
131072 (0x20000) = 关闭视口
                                
262144 (0x40000) = 启用图形界限外部的栅格的显示
                                
524288 (0x80000) = 启用自适应栅格显示
                                
1048576 (0x100000) = 当栅格显示为自适应时，启用设定的栅格间距下的栅格细分
                                
2097152 (0x200000) = 允许栅格遵循工作平面切换
                                
** 340
                                
用作视口剪裁边界的图元的硬指针 ID/句柄（仅当视口为非矩形时才出现）
                                
** 1
                                
指定给该视口的打印样式表名
                                
** 281
                                
渲染模式：
                                
0 = 二维优化（传统二维）
                                
1 = 线框
                                
2 = 隐藏线
                                
3 = 平面着色
                                
4 = 体着色
                                
5 = 带线框平面着色
                                
6 = 带线框体着色
                                
所有非二维优化渲染模式均使用新三维图形管道。
                                这些值直接与 SHADEMODE 命令和 AcDbAbstractViewTableRecord::RenderMode 枚举相对应
                                
** 71
                                
每个视口标志的 UCS：
                                
0 = 该视口处于活动状态时，UCS 不会改变。
                                
1 = 该视口存储自己的 UCS，只要视口被激活，UCS 将变成当前 UCS。
                                
** 74
                                
在 UCS 原点标志处显示 UCS 图标：
                                
控制 UCS 图标表示视口 UCS 还是当前 UCS（如果 UCSVP 为 1 且视口不活动，则两者存在差别）。
                                但是，该字段当前被忽略，且图标始终表示视口 UCS
                                
** 110
                                
UCS 原点
                                
DXF：X 值；
                                APP：三维点
                                
** 120, 130
                                
DXF：UCS 原点的 Y 值和 Z 值
                                
** 111
                                
UCS X 轴
                                
DXF：X 值；
                                APP：三维矢量
                                
** 121, 131
                                
DXF：UCS X 轴的 Y 值和 Z 值
                                
** 112
                                
UCS Y 轴
                                
DXF：X 值；
                                APP：三维矢量
                                
** 122, 132
                                
DXF：UCS Y 轴的 Y 值和 Z 值
                                
** 345
                                
如果 UCS 是命名 UCS，则为 AcDbUCSTableRecord 的 ID/句柄。
                                如果不存在，则为未命名 UCS
                                
** 346
                                
如果 UCS 为正交 UCS，则为基准 UCS 的 AcDbUCSTableRecord 的 ID/句柄（代码 79 非零）。
                                如果不存在，且代码 79 非零，则将基准 UCS 作为 WORLD
                                
** 79
                                
UCS 的正交类型：
                                
0 = UCS 为非正交视图
                                
1 = 俯视图；
                                2 = 仰视图
                                
3 = 主视图；
                                4 = 后视图
                                
5 = 左视图；
                                6 = 右视图
                                
** 146
                                
标高
                                
** 170
                                
着色打印模式：
                                
0 = 按显示
                                
1 = 线框
                                
2 = 消隐
                                
3 = 渲染
                                
** 61
                                
主栅格线与次栅格线比较的频率
                                
** 332
                                
背景 ID/句柄（可选）
                                
** 333
                                
着色打印 ID/句柄（可选）
                                
** 348
                                
视觉样式 ID/句柄（可选）
                                
** 292
                                
默认光源标志。
                                没有指定用户光源时处于打开状态。
                                
** 282
                                
默认光源类型：
                                
0 = 一条平行光
                                
1 = 两条平行光
                                
** 141
                                
视图亮度
                                
** 142
                                
视图对比度
                                
** 63,421,431
                                
环境光颜色。
                                只有不是黑色时才为白色。
                                
** 361
                                
阳光 ID/句柄（可选）
                                
** 335
                                
视口对象的软指针参照（用于图层视口特性替代）
                                
** 343
                                
视口对象的软指针参照（用于图层视口特性替代）
                                
** 344
                                
视口对象的软指针参照（用于图层视口特性替代）
                                
** 91
                                
视口对象的软指针参照（用于图层视口特性替代）
                                
* wipeout
                                
** 100
                                
子类标记 (AcDbRasterImage)
                                
** 90
                                
类版本
                                
** 10
                                
插入点（在 WCS 中）
                                
DXF：X 值；
                                APP：三维点
                                
** 20, 30
                                
DXF：插入点的 Y 值和 Z 值（在 WCS 中）
                                
** 11
                                
单像素的 U 矢量（沿图像可见底部的点，从插入点开始）（在 WCS 中）
                                
DXF：X 值；
                                APP：三维点
                                
** 21, 31
                                
DXF：U 矢量的 Y 值和 Z 值（在 WCS 中）
                                
** 12
                                
单像素的 V 矢量（沿图像可见左侧的点，从插入点开始）（在 WCS 中）
                                
DXF：X 值；
                                APP：三维点
                                
** 22, 32
                                
DXF：V 矢量的 Y 值和 Z 值（在 WCS 中）
                                
** 13
                                
图像大小（像素）
                                
DXF：U 值；
                                APP：二维点（U 值和 V 值）
                                
** 23
                                
DXF：图像大小（像素）的 V 值
                                
** 340
                                
imagedef 对象的硬参照
                                
** 70
                                
图像显示特性：
                                
1 = 显示图像
                                
2 = 当与屏幕不对齐时显示图像
                                
4 = 使用剪裁边界
                                
8 = 透明度打开
                                
** 280
                                
剪裁状态：0 = 关闭；
                                1 = 打开
                                
** 281
                                
亮度值（0-100；默认值 = 50）
                                
** 282
                                
对比度值（0-100；默认值 = 50）
                                
** 283
                                
淡入度值（0-100；默认值 = 0）
                                
** 360
                                
imagedef_
                                reactor 对象的硬参照
                                
** 71
                                
剪裁边界类型。
                                1 = 矩形；
                                2 = 多边形
                                
** 91
                                
后面的裁剪边界顶点数
                                
** 14
                                
裁剪边界顶点（在 OCS 中）
                                
DXF：X 值；
                                APP：二维点（多个条目）
                                
注意 1) 对于矩形剪裁边界类型，必须指定两个对角点。
                                默认值为 (-0.5,-0.5)，(size.x-0.5,size.y-0.5)。
                                2) 对于多边形剪裁边界类型，必须指定三个或更多顶点。
                                多边形顶点必须按顺序列出
                                
** 24
                                
DXF：剪裁边界顶点的 Y 值（在 OCS 中）（多个条目）
                                
* xline
                                
** 100
                                
子类标记 (AcDbXline)
                                
** 10
                                
第一点（在 WCS 中）
                                
DXF：X 值；
                                APP：三维点
                                
** 20, 30
                                
DXF：第一点的 Y 值和 Z 值（在 WCS 中）
                                
** 11
                                
单位方向矢量（在 WCS 中）
                                
DXF：X 值；
                                APP：三维矢量
                                
** 21, 31
                                
DXF：单位方向矢量的 Y 值和 Z 值（在 WCS 中）
                                
* datatype
                                
** 0-9
                                
字符串（自在 AutoCAD 2000 中引入扩展符号名称开始，字数限制已由 255 个字符扩大到 2049 个单字节字符，不包括行末的换行符），有关更多信息，请参见“字符串值的存储”部分
                                
** 10-39
                                
双精度三维点值
                                
** 40-59
                                
双精度浮点值
                                
** 60-79
                                
16 位整数值
                                
** 90-99
                                
32 位整数值
                                
** 100
                                
字符串（最多 255 个字符；对于 Unicode 字符串，字符数要少一些）；
                                有关更多信息，请参见“字符串值的存储”部分
                                
** 102
                                
字符串（最多 255 个字符；对于 Unicode 字符串，字符数要少一些）；
                                有关更多信息，请参见“字符串值的存储”部分
                                
** 105
                                
表示 16 进制 (hex) 句柄值的字符串
                                
** 110-119
                                
双精度浮点值
                                
** 120-129
                                
双精度浮点值
                                
** 130-139
                                
双精度浮点值
                                
** 140-149
                                
双精度标量浮点值
                                
** 160-169
                                
64 位整数值
                                
** 170-179
                                
16 位整数值
                                
** 210-239
                                
双精度浮点值
                                
** 270-279
                                
16 位整数值
                                
** 280-289
                                
16 位整数值
                                
** 290-299
                                
布尔标志值
                                
** 300-309
                                
任意字符串；
                                有关更多信息，请参见“字符串值的存储”部分
                                
** 310-319
                                
表示二进制数据块的十六进制值的字符串
                                
** 320-329
                                
表示 16 进制句柄值的字符串
                                
** 330-369
                                
表示十六进制对象 ID 的字符串
                                
** 370-379
                                
16 位整数值
                                
** 380-389
                                
16 位整数值
                                
** 390-399
                                
表示 16 进制句柄值的字符串
                                
** 400-409
                                
16 位整数值
                                
** 410-419
                                
字符串；
                                有关更多信息，请参见“字符串值的存储”部分
                                
** 420-429
                                
32 位整数值
                                
** 430-439
                                
字符串；
                                有关更多信息，请参见“字符串值的存储”部分
                                
** 440-449
                                
32 位整数值
                                
** 450-459
                                
长整数
                                
** 460-469
                                
双精度浮点值
                                
** 470-479
                                
字符串；
                                有关更多信息，请参见“字符串值的存储”部分
                                
** 480-481
                                
表示 16 进制句柄值的字符串
                                
** 999
                                
注释（字符串）；
                                有关更多信息，请参见“字符串值的存储”部分
                                
** 1000-1009
                                
字符串（与 0-9 代码范围的限制相同）；
                                有关更多信息，请参见“字符串值的存储”部分
                                
** 1010-1059
                                
双精度浮点值
                                
** 1060-1070
                                
16 位整数值
                                
** 1071
                                
32 位整数值
                                
* classes
                                
** 0
                                
记录类型 (CLASS)。
                                标识 CLASS 记录的开始
                                
** 1
                                
类 DXF 记录名；
                                始终唯一
                                
** 2
                                
C++ 类名。
                                用于与定义对象类行为的软件绑定；
                                始终唯一
                                
** 3
                                
应用程序名。
                                当前未加载本段列出的某个类定义时出现在“警告”框中
                                
** 90
                                
代理功能标志。
                                指示该对象作为代理时的功能的按位编码值：
                                
0 = 不允许操作 (0)
                                
1 = 允许删除 (0x1)
                                
2 = 允许转换 (0x2)
                                
4 = 允许更改颜色 (0x4)
                                
8 = 允许更改图层 (0x8)
                                
16 = 允许更改线型 (0x10)
                                
32 = 允许更改线型比例 (0x20)
                                
64 = 允许更改可见性 (0x40)
                                
128 = 允许克隆 (0x80)
                                
256 = 允许更改线宽 (0x100)
                                
512 = 允许更改打印样式名 (0x200)
                                
895 = 允许除克隆以外的所有操作 (0x37F)
                                
1023 = 允许所有操作 (0x3FF)
                                
1024 = 禁用代理警告对话框 (0x400)
                                
32768 = R13 格式代理 (0x8000)
                                
** 91
                                
自定义类的实例计数
                                
** 280
                                
“是代理”标志。
                                如果创建此 DXF 文件时未加载类，则设定为 1，否则设定为 0
                                
** 281
                                
“是图元”标志。
                                如果类从 AcDbEntity 类派生并可能位于 BLOCKS 或 ENTITIES 段中，则设定为 1。
                                如果设定为 0，则实例可能仅出现在 OBJECTS 段中
                                
* appid
                                
** 100
                                
子类标记 (AcDbRegAppTableRecord)
                                
** 2
                                
用户提供（或应用程序提供）的应用程序名称（用于扩展数据）。
                                这些表条目用于维护注册的所有应用程序的名称
                                
** 70
                                
标准标记值（按位编码值）：
                                
16 = 如果设定了此位，则表条目外部依赖于外部参照
                                
32 = 如果同时设定了此位和位 16，则表明已成功融入了外部依赖的外部参照
                                
64 = 如果设定了此位，则表明在上次编辑图形时，图形中至少有一个图元参照了表条目。
                                （此标志对 AutoCAD 命令很有用。大多数读取 DXF 文件的程序都可以忽略它，并且无需由写入 DXF 文件的程序对其进行设定）
                                
* block_
                                record
                                
** 100
                                
子类标记 (AcDbBlockTableRecord)
                                
** 2
                                
块名
                                
** 340
                                
关联的 LAYOUT 对象的硬指针 ID/句柄
                                
** 70
                                
块插入单位。
                                
** 280
                                
块分解性
                                
** 281
                                
块可测量性
                                
** 310
                                
DXF：位图预览的二进制数据（可选）
                                
** 1001
                                
扩展数据应用程序名称“ACAD”（可选）
                                
** 1000
                                
扩展数据字符串数据“设计中心数据”（可选）
                                
** 1002
                                
扩展数据的开始“{”（可选）
                                
** 1070
                                
AutoCAD 设计中心版本号
                                
** 1070
                                
插入单位：
                                
0 = 无单位
                                
1 = 英寸
                                
2 = 英尺
                                
3 = 英里
                                
4 = 毫米
                                
5 = 厘米
                                
6 = 米
                                
7 = 千米
                                
8 = 微英寸
                                
9 = 英里
                                
10 = 码
                                
11 = 埃
                                
12 = 毫微米
                                
13 = 微米
                                
14 = 分米
                                
15 = 十米
                                
16 = 百米
                                
17 = 百万公里
                                
18 = 天文单位
                                
19 = 光年
                                
20 = 秒差距
                                
21 = 美制测量英尺
                                
22 = 美制测量英寸
                                
23 = 美制测量码
                                
24 = 美制测量英里
                                
** 1002
                                
扩展数据的结束“}”
                                
* dimstyle
                                
** 100
                                
子类标记 (AcDbDimStyleTableRecord)
                                
** 2
                                
标注样式名
                                
** 70
                                
标准标记值（按位编码值）：
                                
16 = 如果设定了此位，则表条目外部依赖于外部参照
                                
32 = 如果同时设定了此位和位 16，则表明已成功融入了外部依赖的外部参照
                                
64 = 如果设定了此位，则表明在上次编辑图形时，图形中至少有一个图元参照了表条目。
                                （此标志对 AutoCAD 命令很有用。大多数读取 DXF 文件的程序都可以忽略它，并且无需由写入 DXF 文件的程序对其进行设定）
                                
** 3
                                
DIMPOST
                                
** 4
                                
DIMAPOST
                                
** 5
                                
DIMBLK（已废弃，现在为对象 ID）
                                
** 6
                                
DIMBLK1（已废弃，现在为对象 ID）
                                
** 7
                                
DIMBLK2（已废弃，现在为对象 ID）
                                
** 40
                                
DIMSCALE
                                
** 41
                                
DIMASZ
                                
** 42
                                
DIMEXO
                                
** 43
                                
DIMDLI
                                
** 44
                                
DIMEXE
                                
** 45
                                
DIMRND
                                
** 46
                                
DIMDLE
                                
** 47
                                
DIMTP
                                
** 48
                                
DIMTM
                                
** 140
                                
DIMTXT
                                
** 141
                                
DIMCEN
                                
** 142
                                
DIMTSZ
                                
** 143
                                
DIMALTF
                                
** 144
                                
DIMLFAC
                                
** 145
                                
DIMTVP
                                
** 146
                                
DIMTFAC
                                
** 147
                                
DIMGAP
                                
** 148
                                
DIMALTRND
                                
** 71
                                
DIMTOL
                                
** 72
                                
DIMLIM
                                
** 73
                                
DIMTIH
                                
** 74
                                
DIMTOH
                                
** 75
                                
DIMSE1
                                
** 76
                                
DIMSE2
                                
** 77
                                
DIMTAD
                                
** 78
                                
DIMZIN
                                
** 79
                                
DIMAZIN
                                
** 170
                                
DIMALT
                                
** 171
                                
DIMALTD
                                
** 172
                                
DIMTOFL
                                
** 173
                                
DIMSAH
                                
** 174
                                
DIMTIX
                                
** 175
                                
DIMSOXD
                                
** 176
                                
DIMCLRD
                                
** 177
                                
DIMCLRE
                                
** 178
                                
DIMCLRT
                                
** 179
                                
DIMADEC
                                
** 270
                                
DIMUNIT（已废弃，现在使用 DIMLUNIT 和 DIMFRAC）
                                
** 271
                                
DIMDEC
                                
** 272
                                
DIMTDEC
                                
** 273
                                
DIMALTU
                                
** 274
                                
DIMALTTD
                                
** 275
                                
DIMAUNIT
                                
** 276
                                
DIMFRAC
                                
** 277
                                
DIMLUNIT
                                
** 278
                                
DIMDSEP
                                
** 279
                                
DIMTMOVE
                                
** 280
                                
DIMJUST
                                
** 281
                                
DIMSD1
                                
** 282
                                
DIMSD2
                                
** 283
                                
DIMTOLJ
                                
** 284
                                
DIMTZIN
                                
** 285
                                
DIMALTZ
                                
** 286
                                
DIMALTTZ
                                
** 287
                                
DIMFIT（已废弃，现在使用 DIMATFIT 和 DIMTMOVE)
                                
** 288
                                
DIMUPT
                                
** 289
                                
DIMATFIT
                                
** 340
                                
DIMTXSTY（参照的 STYLE 的句柄）
                                
** 341
                                
DIMLDRBLK（参照的 BLOCK 的句柄）
                                
** 342
                                
DIMBLK（参照的 BLOCK 的句柄）
                                
** 343
                                
DIMBLK1（参照的 BLOCK 的句柄）
                                
** 344
                                
DIMBLK2（参照的 BLOCK 的句柄）
                                
** 371
                                
DIMLWD（线宽枚举值）
                                
** 372
                                
DIMLWE（线宽枚举值）
                                
* layer
                                
** 100
                                
子类标记 (AcDbLayerTableRecord)
                                
** 2
                                
图层名
                                
** 70
                                
标准标记（按位编码值）：
                                
1 = 冻结图层，否则解冻图层
                                
2 = 默认情况下在新视口中冻结图层
                                
4 = 锁定图层
                                
16 = 如果设定了此位，则表条目外部依赖于外部参照
                                
32 = 如果同时设定了此位和位 16，则表明已成功融入了外部依赖的外部参照
                                
64 = 如果设定了此位，则表明在上次编辑图形时，图形中至少有一个图元参照了表条目。
                                （此标志对 AutoCAD 命令很有用。大多数读取 DXF 文件的程序都可以忽略它，并且无需由写入 DXF 文件的程序对其进行设定）
                                
** 62
                                
颜色编号（如果为负值，则表明图层处于关闭状态）
                                
** 6
                                
线型名
                                
** 290
                                
打印标志。
                                如果设定为 0，则不打印此图层
                                
** 370
                                
线宽枚举值
                                
** 390
                                
PlotStyleName 对象的硬指针 ID/句柄
                                
** 347
                                
Material 对象的硬指针 ID/句柄
                                
* ltype
                                
** 100
                                
子类标记 (AcDbLinetypeTableRecord)
                                
** 2
                                
线型名
                                
** 70
                                
标准标记值（按位编码值）：
                                
16 = 如果设定了此位，则表条目外部依赖于外部参照
                                
32 = 如果同时设定了此位和位 16，则表明已成功融入了外部依赖的外部参照
                                
64 = 如果设定了此位，则表明在上次编辑图形时，图形中至少有一个图元参照了表条目。
                                （此标志对 AutoCAD 命令很有用。大多数读取 DXF 文件的程序都可以忽略它，并且无需由写入 DXF 文件的程序对其进行设定）
                                
** 3
                                
线型的说明文字
                                
** 72
                                
对齐代码；
                                值通常为 65，A 的 ASCII 代码
                                
** 73
                                
线型元素的数目
                                
** 40
                                
图案总长度
                                
** 49
                                
虚线、点或空间长度（每个元素一个条目）
                                
** 74
                                
复杂线型元素类型（每个元素一种类型）。
                                默认值为 0（无嵌入的形/文字）
                                
以下代码是位值：
                                
1 = 如果设定了此位，则代码 50 指定绝对旋转；
                                如果未设置此位，则代码 50 指定相对旋转
                                
2 = 嵌入元素是字符串
                                
4 = 嵌入元素是形
                                
** 75
                                
如果代码 74 指定嵌入的形，则表示形编号（每个元素一个编号）
                                
如果代码 74 指定嵌入的字符串，此值将设定为 0
                                
如果代码 74 设定为 0，则省略代码 75
                                
** 340
                                
指向 STYLE 对象的指针（如果代码 74 > 0，则每个元素一个指针）
                                
** 46
                                
S = 比例值（可选）；
                                可存在多个条目
                                
** 50
                                
R = 嵌入的形或文字的相对旋转值（以弧度为单位），A = 嵌入的形或文字的绝对旋转值（以弧度为单位）；
                                如果代码 74 指定了嵌入的形或字符串，则每个元素一个
                                
** 44
                                
X = X 偏移值（可选）；
                                可存在多个条目
                                
** 45
                                
Y = Y 偏移值（可选）；
                                可存在多个条目
                                
** 9
                                
字符串（如果代码 74 = 2，则每个元素一个字符串）
                                
* style
                                
** 100
                                
子类标记 (AcDbTextStyleTableRecord)
                                
** 2
                                
样式名
                                
** 70
                                
标准标记值（按位编码值）：
                                
1 = 如果设定了此位，则此条目用于说明形
                                
4 = 垂直文字
                                
16 = 如果设定了此位，则表条目外部依赖于外部参照
                                
32 = 如果同时设定了此位和位 16，则表明已成功融入了外部依赖的外部参照
                                
64 = 如果设定了此位，则表明在上次编辑图形时，图形中至少有一个图元参照了表条目。
                                （此标志对 AutoCAD 命令很有用。大多数读取 DXF 文件的程序都可以忽略它，并且无需由写入 DXF 文件的程序对其进行设定）
                                
** 40
                                
固定的文字高度；
                                如果文字高度未固定，则为 0
                                
** 41
                                
宽度因子
                                
** 50
                                
倾斜角度
                                
** 71
                                
文字生成标志：
                                
2 = 文字反向（在 X 轴方向镜像）
                                
4 = 文字倒置（在 Y 轴方向镜像）
                                
** 42
                                
上次使用的高度
                                
** 3
                                
主要字体文件名
                                
** 4
                                
大字体文件名；
                                如果无，则为空
                                
** 1071
                                
包含 Truetype 字体的字宽与字族、字符集以及斜体和粗体标志的长值
                                
* ucs
                                
** 100
                                
子类标记 (AcDbUCSTableRecord)
                                
** 2
                                
UCS 名称
                                
** 70
                                
标准标记值（按位编码值）：
                                
16 = 如果设定了此位，则表条目外部依赖于外部参照
                                
32 = 如果同时设定了此位和位 16，则表明已成功融入了外部依赖的外部参照
                                
64 = 如果设定了此位，则表明在上次编辑图形时，图形中至少有一个图元参照了表条目。
                                （此标志对 AutoCAD 命令很有用。大多数读取 DXF 文件的程序都可以忽略它，并且无需由写入 DXF 文件的程序对其进行设定）
                                
** 10
                                
原点（在 WCS 中）
                                
DXF：X 值；
                                APP：三维点
                                
** 20, 30
                                
DXF：原点的 Y 值和 Z 值（在 WCS 中）
                                
** 11
                                
X 轴方向（在 WCS 中）
                                
DXF：X 值；
                                APP：三维矢量
                                
** 21, 31
                                
DXF：X 轴方向的 Y 值和 Z 值（在 WCS 中）
                                
** 12
                                
Y 轴方向（在 WCS 中）
                                
DXF：X 值；
                                APP：三维矢量
                                
** 22, 32
                                
DXF：Y 轴方向的 Y 值和 Z 值（在 WCS 中）
                                
** 79
                                
总是为 0
                                
** 146
                                
标高
                                
** 346
                                
基准 UCS 的 ID/句柄（如果为正交）。
                                如果 79 代码为 0，则不显示此代码。
                                如果未显示此代码，且 79 代码不为零，则假定基准 UCS 为 WORLD
                                
** 71
                                
正交类型（可选；通常与 13、23 和 33 代码成对出现）：
                                
1 = 俯视图；
                                2 = 仰视图
                                
3 = 主视图；
                                4 = 后视图
                                
5 = 左视图；
                                6 = 右视图
                                
** 13
                                
与此 UCS 相关的正交类型的原点
                                
DXF：原点的 X 值；
                                APP：三维点
                                
** 23, 33
                                
DXF：原点的 Y 值和 Y 值
                                
* view
                                
** 100
                                
子类标记 (AcDbViewTableRecord)
                                
** 2
                                
视图名称
                                
** 70
                                
标准标记值（按位编码值）：
                                
1 = 如果设定了此位，则为图纸空间视图
                                
16 = 如果设定了此位，则表条目外部依赖于外部参照
                                
32 = 如果同时设定了此位和位 16，则表明已成功融入了外部依赖的外部参照
                                
64 = 如果设定了此位，则表明在上次编辑图形时，图形中至少有一个图元参照了表条目。
                                （此标志对 AutoCAD 命令很有用。大多数读取 DXF 文件的程序都可以忽略它，并且无需由写入 DXF 文件的程序对其进行设定）
                                
** 40
                                
视图高度（在 DCS 中）
                                
** 10
                                
视口中心点（在 DCS 中）
                                
DXF：X 值；
                                APP：二维点
                                
** 20
                                
DXF：视图中心点的 Y 值（在 DCS 中）
                                
** 41
                                
视图宽度（在 DCS 中）
                                
** 11
                                
来自目标的观察方向（在 WCS 中）
                                
DXF：X 值；
                                APP：三维矢量
                                
** 21, 31
                                
DXF：来自目标的观察方向的 Y 值和 Z 值（在 WCS 中）
                                
** 12
                                
目标点（在 WCS 中）
                                
DXF：X 值；
                                APP：三维点
                                
** 22, 32
                                
DXF：目标点的 Y 值和 Z 值（在 WCS 中）
                                
** 42
                                
焦距
                                
** 43
                                
前向剪裁平面（距目标点的偏移）
                                
** 44
                                
后向剪裁平面（距目标点的偏移）
                                
** 50
                                
扭曲角度
                                
** 71
                                
视图模式（参见 VIEWMODE 系统变量）
                                
** 281
                                
渲染模式：
                                
0 = 二维优化（传统二维）
                                
1 = 线框
                                
2 = 隐藏线
                                
3 = 平面着色
                                
4 = 体着色
                                
5 = 带线框平面着色
                                
6 = 带线框体着色
                                
所有非二维优化渲染模式均使用新三维图形管道。
                                这些值直接与 SHADEMODE 命令和 AcDbAbstractViewTableRecord::RenderMode 枚举相对应
                                
** 72
                                
如果存在与此视图相关联的 UCS，则为 1；
                                否则为 0
                                
** 73
                                
如果相机可打印，则为 1
                                
** 332
                                
背景对象的软指针 ID/句柄（可选）
                                
** 334
                                
活动剖切对象的软指针 ID/句柄（可选）
                                
** 348
                                
视觉样式对象的硬指针 ID/句柄（可选）
                                
** 361
                                
Sun 硬所有权 ID
                                
* vport
                                
** 100
                                
子类标记 (AcDbViewportTableRecord)
                                
** 2
                                
视口名
                                
** 70
                                
标准标记值（按位编码值）：
                                
16 = 如果设定了此位，则表条目外部依赖于外部参照
                                
32 = 如果同时设定了此位和位 16，则表明已成功融入了外部依赖的外部参照
                                
64 = 如果设定了此位，则表明在上次编辑图形时，图形中至少有一个图元参照了表条目。
                                （此标志对 AutoCAD 命令很有用。大多数读取 DXF 文件的程序都可以忽略它，并且无需由写入 DXF 文件的程序对其进行设定）
                                
** 10
                                
视口的左下角
                                
DXF：X 值；
                                APP：二维点
                                
** 20
                                
DXF：视口左下角的 Y 值
                                
** 11
                                
视口右上角
                                
DXF：X 值；
                                APP：二维点
                                
** 21
                                
DXF：视口右上角的 Y 值
                                
** 12
                                
视口中心点（在 DCS 中）
                                
DXF：X 值；
                                APP：二维点
                                
** 22
                                
DXF：视图中心点的 Y 值（在 DCS 中）
                                
** 13
                                
捕捉基点（在 DCS 中）
                                
DXF：X 值；
                                APP：二维点
                                
** 23
                                
DXF：捕捉基点的 Y 值（在 DCS 中）
                                
** 14
                                
捕捉间距 X 和 Y
                                
DXF：X 值；
                                APP：二维点
                                
** 24
                                
DXF：捕捉间距 X 和 Y 的 Y 值
                                
** 15
                                
栅格间距 X 和 Y
                                
DXF：X 值；
                                APP：二维点
                                
** 25
                                
DXF：栅格间距 X 和 Y 的 Y 值
                                
** 16
                                
相对于目标点的观察方向（在 WCS 中）
                                
DXF：X 值；
                                APP：三维点
                                
** 26, 36
                                
DXF：相对于目标点的观察方向的 Y 值和 Z 值
                                
（在 WCS 中）
                                
** 17
                                
观察目标点（在 WCS 中）
                                
DXF：X 值；
                                APP：三维点
                                
** 27, 37
                                
DXF：观察目标点的 Y 值和 Z 值（在 WCS 中）
                                
** 42
                                
焦距
                                
** 43
                                
前向剪裁平面（距目标点的偏移）
                                
** 44
                                
后向剪裁平面（距目标点的偏移）
                                
** 45
                                
视图高度
                                
** 50
                                
捕捉旋转角度
                                
** 51
                                
视图扭转角度
                                
** 72
                                
圆形边
                                
** 331 或 441
                                
冻结图层对象的软指针 ID/句柄或硬指针 ID/句柄；
                                为每个冻结图层重复
                                
** 1
                                
打印样式表
                                
** 281
                                
渲染模式：
                                
0 = 二维优化（传统二维）
                                
1 = 线框
                                
2 = 隐藏线
                                
3 = 平面着色
                                
4 = 体着色
                                
5 = 带线框平面着色
                                
6 = 带线框体着色
                                
所有非二维优化渲染模式均使用新三维图形管道。
                                这些值直接与 SHADEMODE 命令和 AcDbAbstractViewTableRecord::RenderMode 枚举相对应
                                
** 71
                                
视图模式（参见 VIEWMODE 系统变量）
                                
** 74
                                
UCSICON 设置
                                
** 110
                                
UCS 原点
                                
DXF：X 值；
                                APP：三维点
                                
** 120, 130
                                
DXF：UCS 原点的 Y 值和 Z 值
                                
** 111
                                
UCS X 轴
                                
DXF：X 值；
                                APP：三维矢量
                                
** 121, 131
                                
DXF：UCS X 轴的 Y 值和 Z 值
                                
** 112
                                
UCS Y 轴
                                
DXF：X 值；
                                APP：三维矢量
                                
** 122, 132
                                
DXF：UCS Y 轴的 Y 值和 Z 值
                                
** 345
                                
如果 UCS 是命名 UCS，则为 AcDbUCSTableRecord 的 ID/句柄。
                                如果不存在，则为未命名 UCS
                                
** 346
                                
如果 UCS 为正交 UCS，则为基准 UCS 的 AcDbUCSTableRecord 的 ID/句柄（代码 79 非零）。
                                如果不存在，且代码 79 非零，则将基准 UCS 作为 WORLD
                                
** 79
                                
UCS 的正交类型
                                
0 = UCS 为非正交视图
                                
1 = 俯视
                                
2 = 仰视
                                
3 = 前视
                                
4 = 后视
                                
5 = 左视
                                
6 = 右视
                                
** 146
                                
标高
                                
** 170
                                
着色打印设置
                                
** 61
                                
主栅格线
                                
** 332
                                
背景对象的软指针 ID/句柄（可选）
                                
** 333
                                
着色打印对象的软指针 ID/句柄（可选）
                                
** 348
                                
视觉样式对象的硬指针 ID/句柄（可选）
                                
** 292
                                
标志上的默认光源
                                
** 282
                                
默认光源类型
                                
0 = 一条平行光
                                
1 = 两条平行光
                                
** 141
                                
亮度
                                
** 142
                                
对比度
                                
** 63, 421, 431
                                
环境色（仅当不是黑色时输出）
                                
* block
                                
** 0
                                
图元类型 (BLOCK)
                                
** 5
                                
句柄
                                
** 102
                                
应用程序定义的组的开始“{application_name”。例如，“{ACAD_REACTORS”表示 AutoCAD 永久反应器组的开始（可选）
                                
应用程序定义的代码
                                
** 102 组中的代码和值由应用程序定义（可选）
                                
** 102
                                
组的结束“}”（可选）
                                
** 330
                                
所有者对象的软指针 ID/句柄
                                
** 100
                                
子类标记 (AcDbEntity)
                                
** 8
                                
图层名
                                
** 100
                                
子类标记 (AcDbBlockBegin)
                                
** 2
                                
块名
                                
** 70
                                
块类型标志（按位编码值，可以组合使用）：
                                
0 = 表示不应用下列任何标志
                                
1 = 由图案填充、关联标注、其他内部操作或应用程序生成的匿名块
                                
2 = 块具有非固定属性定义（如果块具有任何固定属性定义或根本没有属性定义，则不设定此位）
                                
4 = 块是外部参照 (xref)
                                
8 = 块是外部参照覆盖
                                
16 = 块依赖外部参照
                                
32 = 块是融入的外部参照，或者依赖外部参照（输入时被忽略）
                                
64 = 定义是被引用的外部参照（输入时
                                
被忽略）
                                
** 10
                                
基点
                                
DXF：X 值；
                                APP：三维点
                                
** 20, 30
                                
DXF：基点的 Y 值和 Y 值
                                
** 3
                                
块名
                                
** 1
                                
外部参照路径名
                                
** 4
                                
块说明（可选）
                                
* endblock
                                
** 0
                                
图元类型 (ENDBLK)
                                
** 5
                                
句柄
                                
** 102
                                
应用程序定义的组的开始“{application_name”。例如，“{ACAD_REACTORS”表示 AutoCAD 永久反应器组的开始（可选）
                                
应用程序定义的代码
                                
** 102 组中的代码和值由应用程序定义（可选）
                                
** 102
                                
组的结束“}”（可选）
                                
** 330
                                
所有者对象的软指针 ID/句柄
                                
** 100
                                
子类标记 (AcDbEntity)
                                
** 8
                                
图层名
                                
** 100
                                
子类标记 (AcDbBlockEnd)
                                
