#+prefix: 智能建造技术

* 智能设计
应用新型信息技术模拟人类的思维活动，通过提高计算机的智能化运算水平，更全面地挖掘数据价值，辅助完成各种复杂的设计任务，为建筑工程提供创造性与优化性创新方案，使设计全过程更加高效智能。基于我省建筑业优势特点，推广BIM技术“一模到底”，建立贯穿建筑全生命周期的数字化模型，整合标准化构件库，扩大标准化构件的使用范围，加大装配式建筑设计应用，形成建筑数字化模型正向设计与智能审查模式，实现降本增效，提升本质安全水平。
* BIM技术一模到底
此类技术适用于建筑工程全生命周期的设计。
此类技术基于高效图形引擎、轻量化图形引擎、高效数据库等模块，具备基础数据结构与算法、数学运算、建模元素、建模算法、大体量几何图形的优化存储与显示、几何造型复杂度与扩展性、BIM几何信息与非几何信息的关联等核心功能。依托工程总承包、全过程咨询等组织方式和投建营一体化的经营模式，基于BIM的全过程工程管理软件，在同一个建筑模型的基础上，集成咨询、勘察、设计、造价、施工、运维等多个阶段的数据和报建、审批、验收等流程，实现“一模到底”的建筑工程全生命周期的数字化管理。
* 标准化构件库
此类构件库适用于建筑工程BIM设计，为模型设计提供高效便利的构件资源。
此类构件库通过建立标准化、通用化构件资源库，使构件成为标准化设计、生产、运输和安装的基础单元，实现基于统一系统的跨软件平台、多用户交互操作及数据集成更新。具有符合相关BIM标准及设计需求的构件资源，具备BIM构件的管理、下载、复制、编辑，以及构件属性批量添加、赋值等功能，满足国家、省、地方BIM模型交付要求。
* 装配式建筑设计技术
此类技术适用于装配式建筑工程设计、生产、运输、安装、施工一体化全流程设计。
此类技术是通过在设计阶段充分考虑部品部件、模块制造、构件运输和现场装配的要求，结合人工智能、云计算、参数化设计等技术，实现基于制造和安装的设计。将设计成果应用于工厂生产加工，指导部品部件、模块的高效生产，以及对接现场施工管理，促进部品部件、模块的快速安装，有利于提升装配式建筑工程项目标准化设计和建造水平。
* 人工智能设计技术
此类技术适用于建筑工程方案设计、初步设计或施工图设计等阶段，部分设计工作自动完成。
此类技术主要结合人工智能算法、大数据、云端算力等能力，提供图纸识别建模、既有场地强排、建筑识别建模、建筑户型图智能设计、结构智能配筋、建筑标准层智能生成、电气灯具智能设计、喷淋系统智能设计、暖通风机盘管智能设计、设备选型衍生设计、管线综合智能排布、地下车位智能设计、装饰装修设计等功能，基于数据及算法驱动生成的设计场景方案为设计人员提供参考，提升设计质量和效率。
* 基于BIM的设计协同软件
此类软件适用于建筑工程设计过程中的多主体、多专业BIM设计协同与管理。
此类软件与目前主流的二维设计软件、三维设计软件深度集成，具有设计提资、图模会审、云端管理、轻量化浏览、在线批注等功能。软件可有效整合设计资源，准确表达设计意图，减少设计错误，允许项目团队在工程设计或文档编制过程中，随时随地做出更改或修订，修改结果会在整个项目的各个专业、各个环节中实时显示。通过BIM三维工程模型高效进行多专业协同，替代重复的人工协调与检查环节，提升整体工作质量和效率。
* 建筑产业互联网平台
以新型“互联网+”的管理模式进行精细化管理，打造贯穿项目管理、招标采购、机具租赁、用工管理、装饰装修工程管理的工程建设全链条数字化管理系统，实现政府端、企业端、项目端数据资源的互通共享，构建建筑领域数字化新生态。通过完善顶层规划，统一数据标准，实现不同系统之间的互联互通，逐步打造覆盖全省的建筑产业互联网平台，实现住建领域平台全面信息化赋能。
* 项目管理系统
此类系统适用于建筑工程建造全过程的数字化管理。
此类系统融合产业链上下游资源，通过实时连接和智能匹配，对工程项目的深化设计、采购、生产、交付等各阶段各要素进行数字化整合，实现信息协同共享、工作互联互通、决策精准科学、风险智慧预控。支持多方参与、协同联动的一体化管理，高效赋能建筑工程建造全过程管理。针对工程项目，具有深化设计、招采集采、机械租赁、用工管理、智能生产、智能施工等功能，支撑建筑工程建设项目全过程各阶段业务需求的数字化协同管理，并将产生的相关数据向智慧运维传递。
* 招标采购系统
此类系统适用于建筑工程材料、设备等方面的招采服务。
此类系统依托移动互联网、大数据、GIS、人工智能、物联网等技术，实现工程项目招标采购的一站式线上服务。具有采购计划管理、供应商寻源、招投标管理、合同管理、采购订单协同、物流管理、收验货管理、结算管理、供应商及物资管理、“产业链+金融”服务、在线交易及风控管理等功能。能够支持订单履约各参与方在线协同，实现合同、订单、发货单、验收单在线管理，利用“一物一码”实现标的物的实时监控、生产交付。
* 机具租赁系统
此类系统适用于建筑工程机械、设备、器具的租赁服务。
此类系统利用移动互联网、大数据、GIS、云计算、物联网等技术，以“互联网+租赁”模式，为供需双方搭建对接桥梁，提供全流程线上租赁服务。具有融资租赁、物联智控、健康管理、维护保险、信用评价等功能模块，对线上各方进行审核，保障协作过程的可靠性。采用一站式在线租赁服务模式，实现全程跟踪管理，支持对工程机械、设备、器具的远程定位、实时监控、健康管理、智能维护。
* 用工管理系统
此类系统适用于建筑工程单位招工用工管理服务。
此类系统是利用移动互联网、大数据、人工智能等技术，建立建筑工人与工程项目单位供需平台，实现对建筑工程项目单位工人招工用工的一站式管理。包含建筑公司、劳务公司、建筑工人等信息，涵盖发布招工、工人应聘、劳动合同管理、考勤管理、记工记账、健康管理、退场管理、职业指导培训及用工信用管理等功能。
* 装饰装修工程系统
此类系统适用于建筑工程装饰装修全过程管理。
此类系统基于移动互联网、大数据、GIS、物联网等技术，打通工程建设项目装饰装修建材、设计、生产、施工、运维等产业链上下游，实现装饰装修项目各参与方线上全流程数字化管控。涵盖既有建筑数字图纸、部品部件模型库、装配式装修部件综合信息、装修案例、工程项目全过程协同管理、质量安全控制要点及责任追溯等功能。
* 智能建造设备装备
应用先进的建筑施工机械和设备、无人机、建筑机器人、集成平台、监控设备、智能塔吊、传感器等智能建造装备实现自动化施工、智能化管理，对施工过程进行实时监控和数据分析，逐步实现机器代人、降本增效，不断挖掘智能建造设备装备的应用场景，持续提高建造过程的智能化程度。
* 智能测量设备
此类设备适用于建筑工程测量放线、实测实量、质量检测等场景，具有效率高、精度高、数据可追溯、易维护、无纸化测量等特点。
此类设备主要包含BIM放样机器人、三维激光扫描仪等。将设计模型导入BIM放样机器人，进行多工种、多专业、多工作区域、高精度放线测量，实现快速测量、准确定位，辅助现场完成放线。三维激光扫描仪应用激光测量、点云扫描等技术，完成墙面、地面的平整度、垂直度等数据的实测实量，特别是异形建筑、钢结构等复杂表面。
* 建筑机器人装备
此类装备适用于建筑工程施工现场作业。
此类装备主要基于机器人、物联网、移动互联网、人工智能等技术，通过集成控制系统、感知系统、驱动系统和机械系统等，结合工程施工工艺，以“危繁脏重”的施工作业为重点，逐步实现机器代人。具备数据采集、人机协调、自然交互、自主移动、自主学习等功能。主要包括地面抹光机器人、地面整平机器人、地砖铺贴机器人、墙板安装机器人、喷涂机器人、玻璃幕墙安装机器人、焊接机器人、混凝土打磨机器人、搬运机器人、预制构件生产机器人等。工程设计应当与机器人施工相适应，利于提高机器人工作效率。
* 无人机应用技术
此类技术适用于建筑工程进度管理、土方测量、施工安全管理、施工质量检测、园林养护管理等方面。
此类技术主要是通过在同一飞行平台上搭载多个传感器，同时从垂直、倾斜等多个角度对地物进行拍摄测量，获取完整、全面地物信息，精细建模，辅助施工管理。结合工程建设项目业务需求，实现对工程安全、质量、进度、土方测量等方面的管理应用。主要包括数据采集与数据处理两大功能板块，可直观展示施工现场进度情况，进行施工过程安全行为巡检，实现场地平整、基坑开挖及填筑土方量的快速精确计算。
* 智能施工机械装备
此类装备适用于建筑工程项目现场施工作业场景。
此类装备是传统机械设备与计算机技术、数据处理技术、控制技术、传感器技术、网络通信技术、电力电子技术等技术的融合创新，具有感知、分析、推理、决策和控制功能。具有易操作、省人工、高效率等特征，包括智能塔吊、智能施工升降机、无人推土机、智能盾构机、智能运输车、智能碾压设备等。
* 智能施工装备集成平台
此类平台适用于高层、超高层等工程结构智能施工。
此类平台主要由混凝土浇筑系统、钢平台系统、支撑系统、动力及控制系统、模板系统、挂架系统、安全保障系统、缺陷评估系统等组成，采用标准化设计，可循环周转利用。平台集成多种设施设备，包括系列智能施工装备与建筑机器人、物联感知与通信设备、悬挂式布料机、水平运输设备、隔音降噪装置、设备控制与监测平台等，提供如工厂化的作业环境，实现钢筋绑扎、模架顶升、模板安装、混凝土浇筑及其他辅助工序流水作业。
* 智能生产
利用新一代数字信息技术、自动化工艺和智能化装备等手段，搭建智能工厂数字化管理系统，实现钢结构、混凝土等部品部件的精益化生产。充分发挥我省制造业基础雄厚、信息化程度高的优势，持续创新混凝土模块化生产、装饰装修部品部件集成交互式生产等技术，提高预制产品全产业链智能化融合程度，逐步实现建筑产品生产过程的工业化、数字化、绿色化。
* 智能工厂数字化管理系统
此类系统适用于预制混凝土、钢结构、装饰装修等部品部件及定制化3D打印建筑等工厂生产的数字化管理。
此类系统深度融合5G网络通信、物联网、GIS、云边计算、数字孪生等技术，主要集成BIM设计、生产制造、供应链管理、生产计划与排程、仓储运输、人员用工等应用系统和现场工厂智能设备装配信息，实现生产计划、产品质量、车间库存、运输流程、车辆调度等管理功能，满足生产数据、资料、业务和流程的可视化，利于工厂产品生产制造的全生命周期实现数字化管控、精益化管理。
* 钢筋加工制作智能生产技术
此类技术适用于建筑工程钢筋半成品的加工制作。
此类技术通过对钢筋进行深化设计与数据信息的智能提取，多个系统协同配合，利用算法进行智能化排产，将钢筋半成品加工中的多种规格工具统一整合，根据半成品规格自动切换使用，实现不同规格、不同加工尺寸钢筋的自动化生产，一次性完成钢筋的定尺切断、攻丝、弯曲等作业，减少不合理浪费。具有自动化程度高、加工精度高、钢筋利用率高、作业效率高等特点。
* 钢结构部品部件智能生产技术
此类技术适用于建筑工程钢结构部品部件的生产。
此类技术集成数控激光切割设备、焊接机器人、高精度变位机、组焊矫一体设备等人机交互智能装备，融合机器人控制技术、智能分析感知系统、机器视觉等高新技术，形成钢结构部品部件智能生产线，提高钢结构部品部件的生产效率和质量。在切割下料阶段可实现全无人化和智能监控；组焊矫阶段可实现全自动的翻转和在线矫正；钻锯锁阶段可采用控制软件自动识别不同工件的加工路径；总装焊接可实现围绕主轴线360度全角度翻转变位和参数化、模块化编程焊接。
* 混凝土模块化智能生产技术
此类技术适用于建筑工程混凝土的模块化生产。
此类技术集成模具精准定位、放料精准计量、自动上下料、自动化质检等功能，提高混凝土模块单元的生产效率和质量。配备智能混凝土搅拌站系统，具有集成物料自动入库、后台自动上料等功能。配备智能化混凝土内外关键特征测量检测质检系统，实现成品各项尺寸、性能指标的自动化质检并与智能工厂数字化管理系统对接，实现混凝土生产与检测的自动化和智能化。
* 预制混凝土部品部件智能生产技术
此类技术适用于建筑工程预制混凝土部品部件的生产加工过程。
此类技术通过部品部件数字化模型指导自动化生产。在模具清理、脱模剂喷涂、安放钢筋网笼、混凝土成型等预制混凝土部品部件生产环节中使用智能化装备与系统；对部品部件成品应用智能化倒运系统或技术进行存放及运输；在预制混凝土部品部件中钢筋网笼的加工制作、各类型PC构件的外观尺寸等方面，做出自动化程序控制及数字化设备调整，提高预制混凝土部品部件的生产质量和效率。
* 装饰装修部品部件智能生产技术
此类技术适用于建筑工程装饰装修部品部件生产。
此类技术采用自主参数定义的激光切割机、数控加工中心、3D打印机、高速数码喷印生产线等高端智能装备，采用智能龙门机械手、动力滚筒、智能搬运（AGV）及传送系统，配合PLC控制系统及上位机软件等，实现零部件自动化生产。加强AI算法技术与智能装备的深度集成，提高机器人的轨迹精度和作业效率。通过制造执行系统、仓储管理系统与BIM设计系统高度集成，实现全流程信息和数据驱动。使用云边计算、GIS、物联网、数字孪生等技术，实现产品识别、任务下载、实时数据采集和产线状态监控等功能，达到系统、设备和工件的集成交互，为生产决策提供更为精准的数据支持。
* 智能施工
利用建筑信息模型、物联网、5G网络通信和大数据等技术，实现工程管理与施工现场的有机融合。运用信息化、BIM+等方式进行建筑工程辅助设计和施工模拟，对质量、安全、环境、工期等进行分析，实现工程施工智能管理。充分发挥龙头企业的示范引领作用，通过对数字化建造、装备作业以及数字驱动装备等相关技术的集成应用，提高主要施工场景、关键施工工序的数字化覆盖率和智能化装备率，提升生产效率，提高工程管理智能化水平。
* 智慧工地管理系统
此类系统适用于建筑工程施工现场的数字化管理，并具备数据安全保护机制。
此类系统依托工程施工现场，以物联网技术为核心，综合运用移动互联网、人工智能等信息技术及智能设备，将三维模型与项目管理数据相融合，提升对工程质量、安全、工期、物资、成本的管控能力。通过“赋码落图”为建筑单体设定全生命周期唯一的编码，贯穿审批、施工、验收、运维等各环节，实现项目代码、建筑单体编码“一码串联”。逐步统一数据对接标准，打造智慧工地管理体系，最终实现政府端、企业端、项目端数据互通，通过系统进行监管并发现问题，工程现场实施整改。
* 施工安全监测
此类技术适用于建筑工程施工过程的安全监测。
此类技术通过监测建筑工程项目施工过程中结构、基坑、边坡、高支模等安全控制参数在一定期间内的量值及变化，评估或预判安全状态，为安全风险防控提供参考。对现场人的行为、物的状态等进行可视化连续自动监测，数据对接智慧工地管理系统，进行处理、存储、分析，根据相关规范要求作出量化评价和预警，保障安全生产。
* 施工质量监测
此类技术适用于建筑工程施工过程的质量监测。
此类技术主要基于智能检测设备、物联网、先进检测监测技术等，对关键工序、隐蔽工程可视化追溯管理，支持远程实时查看、录屏、回放。通过实测实量智能设备的远程管理，做到施工过程中数据采集、数据处理和交互以及监测成果评估，及时输出整改报告，提高检测效率、减少人工计算、互通检测数据，对接智慧工地管理系统，进行处理、存储、分析，根据相关规范要求作出量化评价和预警。
* 施工环境监测
此类技术适用于建筑工程施工过程的环境监测。
此类技术主要以传感器为监测基础，以无线数据传输技术为通信手段，以数字化的方式对施工现场风速、风向、温度、湿度、施工噪声、施工扬尘、建筑垃圾、污水排放等环境指标数据进行实时监测、记录、统计、分析、评价和预警的监测技术。智慧工地管理平台对监测数据进行处理、存储、分析，根据相关规范要求作出量化评价和预警，提高施工过程中环境监测的质量和效率。
* BIM+辅助施工组织
此类技术适用于建筑工程布置模拟、虚拟建造、辅助深化设计。
此类技术使用BIM技术对场区内的施工部署、工期、临设、大型设备、临水临电等进行模拟比选，做到入场即施工，工序穿插合理，节约工期。利用BIM技术对模板工程、脚手架工程等进行参数化、模块化建模，优化模板、脚手架等方案，精准统计模板、脚手架等材料用量，降低项目施工措施成本。辅助复杂钢结构节点深化设计、机电与土建配合深化设计，指导项目高效施工。
* BIM+辅助专项工程施工
此类技术适用于建筑工程钢结构、机电、幕墙等专项工程的辅助施工。
此类技术将BIM模型在真实环境中进行精确定位，叠加在项目现场，清晰直观地反映钢结构、混凝土构件、幕墙复杂节点、复杂空间构成，机电安装工程排布走向，不同专业之间进行交叉碰撞检查等，为施工提供可视化的参考和指导。对施工人员进行现场交底、指导，检查验收时对比现场安装与设计模型相符性，提升现场检查验收的质量和效率。
* 智慧运维
通过系统对运维数据进行实时采集，引入算法学习、汇总规则，自主作出决策。利用智慧运维平台，直观了解建筑物使用运行状况，完成对建筑结构的安全监测、能耗评估、管道养护等自主管理，降低人工成本，及时发现隐患、解决问题，提高运维效率，实现运维操作的标准化、自动化、智能化，确保运维系统安全可靠、操作过程可溯源，逐步形成统一、标准的智慧城市运维管理生态。
* 基于数字孪生技术的智慧运维平台
此类平台适用于建筑工程的智慧运维管理。
此类平台基于物理空间的BIM模型底座，融合云边计算、大数据、5G网络通信等技术，采用物联网架构体系进行搭建。平台利用传感器等智能设备对空间中的静态及动态数据进行采集，将数据信息与服务资源进行统一集成管理，实现现实环境与数字空间的场景联动及健康状况预警、运维状态警示等。具备设备故障识别管理、空间孪生数据可视化展现等能力，支持多种运维管理场景搭建，能够实现建筑、市政基础设施全生命周期智慧运维管理。
* 建筑安全监测系统
此类系统适用于建筑工程关键构件及重要结构的安全健康监测。
此类系统通过集成传感器系统、数据采集传输系统、数据处理与分析系统、结构健康性能安全预警系统实现项目设施健康状况的实时评价，利用BIM技术将结构施工—运营全生命周期安全状态进行数字化展现，同时利用人工智能算法，实时评估结构安全。通过应用监测技术，获取建筑变形、振动、裂缝等关键参数，挖掘监测数据与安全运行的映射关系，量化评估安全运维水平，对建筑安全隐患进行预警，及时反映设施安全状态。
* 建筑能耗监控管理系统
此类系统适用于建筑能源系统的在线监测、动态分析与控制优化。
此类系统是利用物联网、大数据、人工智能等技术，实现对建筑楼宇供水、供电、燃气、采暖、可再生能源等能源系统运行状态的实时监测、分析诊断和优化调控，提高建筑能源系统运行效率，实现建筑运行用能精细化管理。支持集成或自定义控制策略，远程优化用能设备控制；支持其他建筑设备能源监控系统的接入，提供一站式能耗集成监控；支持楼宇运行数据的实时采集、校验、解析和储存，实现数据的汇总、整合、分析，依据相关标准和自定义条件，自动计算分类分项分区能耗、各能源系统运行效率，二氧化碳排放量等指标，提供优化建议，辅助管理人员提升建筑楼宇整体能效水平。
* 智能管养设备系统
此类系统适用于建筑工程的智能管养。
此类系统主要基于机器人、物联网、移动互联网、人工智能等技术，通过集成控制系统、感知系统、驱动系统和机械系统等，解决一些难度大、周期长、范围广的管养问题，实现建筑、市政基础设施等智能化检查、保养、维修。具备数据采集、人机协调、自然交互、自主学习等功能，主要包括智能巡检设备、智能检测设备、智能保洁设备、幕墙智能清洁设备、桥梁智能管养设备、隧道智能管养设备、城市智能管养设备等。
