#+TITLE: 如何使用 @lisp
#+AUTHOR: VitalGG

* @lisp 是什么
@lisp 全称 *CAD应用云* ，是一个运行于 AutoCAD、中望CAD、浩辰CAD及类似兼容的CAD系统中的应用管理器。用于管理 AutoLisp 程序的网络下载安装、加载、卸载、查询等。可方便地实现 autolisp 程序的云管理。

* 安装@lisp | 大道至简
将以下代码复制到 CAD 命令行内，回车即可开始安装 @lisp kernel。@lisp kernel（内核）包含 @lisp函数库 及 @lisp应用云 的基本管理功能。

(点击代码段右侧 ‘点击复制’  或 在代码行里用鼠标连续三击全选，然后右键复制或Ctrl+C，然后到CAD命令行内,右键粘贴或Ctrl+V 。)

#+BEGIN_SRC lisp
  (progn(vl-load-com)(setq s strcat h "http" o(vlax-create-object (s"win"h".win"h"request.5.1"))v vlax-invoke e eval r read)(v o'open "get" (s h"://atlisp.""cn/@"):vlax-true)(v o'send)(v o'WaitforResponse 1000)(e(r(vlax-get-property o'ResponseText))))
#+END_SRC

安装完成后会出现 @lisp(A) 菜单。并弹出一个使用提示。

* 安装教程 | 不出户 知天下 不窥牖 见天道


* 使用@lisp | 衍化至繁
** @lisp 基本命令和菜单
  @lisp 基本功能菜单都在 @lisp -> 配置 菜单下。
  以下 标题中 | 前面是在命令行输入的命令 ， | 后面是菜单项。
*** @ | 重新加载或功能提示
重新加载 @lisp , 如果 @lisp 不完整，多次运行可自行修补完整 。

在命令行输入 @ ，有些CAD软件会呈现一系列相关功能命令，可以按上下箭头选择需要的功能命令。
   
*** @@ | 命令面板
显示 *@lisp* 命令面板。面板功能按钮与菜单是一一对应的，操作更快捷一点。

在智能命令框内输入中文短语并回车，可以弹出与这些短语相关的功能按钮。选择相应的功能按钮，就会下载并执行这个功能。
*** @C | 对话
chat, 与@lisp服务对话。有两种对话模式， study 模式用于查询命令、变量、@lisp功能以及开发函数的用法； free 模式可以自由聊天。
*** @F | 修复
修复@lisp，当@lisp无法启动、升级失败时，可以使用 @F 命令修复你的@lisp系统。
*** @H | 关于@lisp
   显示CAD命令及用法。

*** @P | 应用管理
图形界面的应用包管理器，用于管理 '应用包'的安装、加载、卸载。

当 *勾选* 了某个或某些应用后，@lisp 系统会在加载 *@lisp* 时，同时加载这些应用。

如果本地没有这个应用的副本， *@lisp* 会从网站下载一个副本到你的硬盘。 

如果本地的副本版本较低， *@lisp* 会从网站下载一个新版本的副本到你的硬盘，也就是升级。

*** @I 
命令行方式安装应用包。输入 @I 并回车或空格，然后输入应用包名(英文名).就可以完成这个应用包的安装。

*** @S | 配置管理
设置系统变量的值。

*** @L
在命令行显示已安装的应用包列表。

*** @M | 重建菜单
重新生成菜单。如果 @lisp 菜单与现有的环境不匹配，可运行此命令。

*** @R
remove,命令行工具 移除应用包。在应用管理器中，取消 ‘勾选’ 后的功能相同。

*** @U | 升级系统
update，手动更新 @lisp 系统及已安装的包。
*** @W
www，访问 @lisp 网站。查询 @lisp 新动态及新增应用包。
*** @X
@lisp全部功能，对于autocad 2016+以选项板的形式显示，其它cad以命令面板的形式显示。

*** 菜单 @lisp主目录
打开本地@lisp的主目录，所有@lisp应用都存放在这个目录下。

*** 菜单 自毁@lisp
删除@lisp主文件和菜单文件。再次打开CAD后，就不加载@lisp了。

@lisp目录一其它文件可保留，以便于以后再次安装时使用原来的配置。

如果不需要，可以手动删除@lisp目录及以下的所有文件。


** 云端应用、任意调用
安装完成后，可以进行应用包的下载、安装、选择、加载等功能。在 CAD 命令行 输入 @H 查看如何使用 @lisp。

@lisp 提供CAD插件的一站式、保姆式安装加载服务。收录常用的插件功能。用户只需在 CAD 中安装 @lisp ，就可以在CAD界面中完成插件、应用程序的下载、加载等步骤。无须到处找寻、也无须繁杂的配置。

** 云端函数库
@lisp 函数库是一个开源、共享、可云端加载的 autolisp 函数库。由像您一样热爱开源共享的爱好者所构筑并维护。可依据开放许可协议自由使用。

@lisp函数库 提供上千个常用函数，云端加载，一行代码加载函数定义。开放源码，无需手动升级，时刻保持最新。

@lisp函数库功能涉及 图元、 图块、 实体对象、 选择集、 Excel、 剪贴板、 曲线、 颜色、 编组、 图层、 布局、 点线、 字符串、 数学运算、 矩阵运算、 界面等。更多内容持续迭代中。
